### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  id: CantStartSingleInstanceException
  children:
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  type: Class
  summary: "Questa eccezione viene generata quando una seconda istanza di un&quot;applicazione a istanza singola non riesce a connettersi alla prima istanza di applicazione."
  remarks: "Un&quot;applicazione a istanza singola è diverso da un&quot;applicazione normale che è possibile eseguire solo un&quot;istanza dell&quot;applicazione alla volta. Quando viene avviata un&quot;istanza di applicazione successivo, tenta di contattare la prima istanza dell&quot;applicazione per passare gli argomenti della riga di comando. Se la prima istanza non può essere contattata, viene generato il CantStartSingleInstanceException nell&quot;istanza successiva dell&quot;applicazione. Il modello di applicazione Visual Basic non fornisce informazioni di contesto nell&quot;eccezione.       Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class CantStartSingleInstanceException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> classe."
  remarks: "Un&quot;applicazione a istanza singola è diverso da un&quot;applicazione normale che è possibile eseguire solo un&quot;istanza dell&quot;applicazione alla volta. Quando viene avviata un&quot;istanza di applicazione successivo, tenta di contattare la prima istanza dell&quot;applicazione per passare gli argomenti della riga di comando. Se la prima istanza non può essere contattata, il <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>viene generato nell&quot;istanza successiva dell&quot;applicazione.</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md).       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>.</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>      |||   |-|-|   | Proprietà | Valore |   | <xref:System.Exception.InnerException%2A>| Un riferimento null (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore localizzato. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> classe con un messaggio di errore specificato."
  remarks: "Il contenuto del `message` parametro deve essere facilmente comprensibile. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente.       <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>eredita da <xref:System.Exception>.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> Questo costruttore imposta le proprietà del <xref:System.Exception>dell&quot;oggetto come illustrato nella tabella seguente.</xref:System.Exception>      |||   |-|-|   | Proprietà | Valore |   | <xref:System.Exception.InnerException%2A>| Un riferimento null (`Nothing` in Visual Basic) |   | <xref:System.Exception.Message%2A>| Il `message` stringa. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Un messaggio che descrive l&quot;errore."
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso."
  syntax:
    content: protected CantStartSingleInstanceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Il <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> oggetto che contiene i dati oggetto serializzati relativi all&quot;eccezione generata."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Il <xref:System.Runtime.Serialization.StreamingContext>oggetto che contiene le informazioni contestuali sull&quot;origine o destinazione.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> classe con un messaggio di errore specificato e un riferimento all&quot;eccezione interna che è la causa dell&quot;eccezione corrente."
  remarks: "Il contenuto del `message` parametro deve essere facilmente comprensibile. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente.       Un&quot;eccezione generata come risultato diretto di un&quot;eccezione precedente deve includere un riferimento all&quot;eccezione precedente nella <xref:System.Exception.InnerException%2A>proprietà.</xref:System.Exception.InnerException%2A> Il <xref:System.Exception.InnerException%2A>proprietà restituisce lo stesso valore passato al costruttore o un riferimento null se il <xref:System.Exception.InnerException%2A>proprietà non fornisce il valore di eccezione interna al costruttore.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.ApplicationException>.</xref:System.ApplicationException>      |||   |-|-|   | Proprietà | Valore |   | <xref:System.Exception.InnerException%2A>| Il `inner` riferimento. |   | <xref:System.Exception.Message%2A>| Il `message` stringa. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "Oggetto <xref:System.String>oggetto che descrive l&quot;errore.</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "Il <xref:System.Exception>oggetto che è la causa dell&quot;eccezione corrente.</xref:System.Exception> Se il <xref:System.Exception.InnerException*>parametro non è un riferimento null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> in Visual Basic), l&quot;eccezione corrente viene generata in un <xref uid=&quot;langword_csharp_Catch&quot; name=&quot;Catch&quot; href=&quot;&quot;> </xref> blocco che gestisce l&quot;eccezione interna.</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException
