### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  id: BuiltInRole
  children:
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  langs:
  - csharp
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  type: Enum
  summary: "Indica il tipo di ruolo per controllare quando viene chiamato il <xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>metodo.</xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>"
  remarks: "Questa enumerazione fornisce funzionalità simili a quelle di <xref:System.Security.Principal.WindowsBuiltInRole>enumerazione.</xref:System.Security.Principal.WindowsBuiltInRole>       Questi ruoli rappresentano i gruppi locali di Windows comuni per la maggior parte delle installazioni di Windows."
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.ApplicationServices.BuiltInRoleConverter))]

      public enum BuiltInRole
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  id: AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gruppo account operators gestisce gli account utente in un computer o un dominio."
  syntax:
    content: AccountOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  id: Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gli amministratori hanno accesso completo e illimitato al computer o dominio."
  syntax:
    content: Administrator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  id: BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Operatori di backup è possono eseguire l&quot;override di restrizioni di sicurezza al solo scopo di backup e ripristino di file."
  syntax:
    content: BackupOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  id: Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Guest sono più limitati rispetto agli utenti."
  syntax:
    content: Guest
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  id: PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gli utenti esperti dispongono la maggior parte delle autorizzazioni amministrative con alcune restrizioni. Pertanto, gli utenti esperti possono eseguire le applicazioni legacy, oltre alle applicazioni certificate."
  syntax:
    content: PowerUser
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  id: PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gli operatori di stampa possono assumere il controllo di una stampante."
  syntax:
    content: PrintOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  id: Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "I servizi di replica supporta la replica di file in un dominio."
  syntax:
    content: Replicator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  id: SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gestori del sistema di gestiscono un computer specifico."
  syntax:
    content: SystemOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  id: User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Impedisce di apportare modifiche a livello di sistema accidentali o intenzionali. Di conseguenza, gli utenti possono eseguire applicazioni certificate, ma non la maggior parte delle applicazioni legacy."
  syntax:
    content: User
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
