### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser
  id: WebUser
  children:
  - Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  - Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  langs:
  - csharp
  name: WebUser
  nameWithType: WebUser
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser
  type: Class
  summary: "Fornisce l&quot;accesso alle informazioni sull&quot;utente corrente."
  remarks: "Le proprietà e metodi esposti dal `My.User` oggetto fornire accesso alle informazioni sull&quot;utente corrente. Il significato di &quot;utente corrente&quot; differisce leggermente tra le applicazioni di Windows e Web. In un&quot;applicazione Windows, l&quot;utente corrente è l&quot;utente che esegue l&quot;applicazione. In un&quot;applicazione Web, l&quot;utente corrente è l&quot;utente che accede all&quot;applicazione.       Il `My.User` proprietà fornisce inoltre l&quot;accesso per il <xref:System.Security.Principal.IPrincipal>per l&quot;utente corrente.</xref:System.Security.Principal.IPrincipal> Un oggetto entità rappresenta il contesto di sicurezza dell&quot;utente, tra cui identità dell&quot;utente e eventuali ruoli a cui appartiene l&quot;utente.       Per le applicazioni di Windows, questa proprietà fornisce la stessa funzionalità come la <xref:System.Threading.Thread.CurrentPrincipal%2A>proprietà.</xref:System.Threading.Thread.CurrentPrincipal%2A> Per le applicazioni Web, questa proprietà fornisce la stessa funzionalità come la <xref:System.Web.HttpContext.User%2A>proprietà dell&quot;oggetto restituito dal <xref:System.Web.HttpContext.Current%2A>proprietà.</xref:System.Web.HttpContext.Current%2A> </xref:System.Web.HttpContext.User%2A>      > [!NOTE] > Per applicazioni Windows, solo i progetti compilati **applicazione Windows** modello inizializzare il `My.User` oggetto per impostazione predefinita. In tutti gli altri tipi di progetto di Windows, è necessario inizializzare il `My.User` oggetto chiamando il <xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>metodo in modo esplicito o assegnando un valore per <xref:System.Threading.Thread.CurrentPrincipal%2A>.</xref:System.Threading.Thread.CurrentPrincipal%2A> </xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>      > [!NOTE] > Il `My.User` oggetto non è possibile segnalare informazioni relative all&quot;utente di Windows corrente quando viene eseguito in Windows 95 e Windows 98, poiché questi sistemi operativi non supportano il concetto di un utente connesso. È necessario implementare l&quot;autenticazione personalizzata per utilizzare il `My.User` oggetto in questi sistemi operativi..."
  example:
  - "This example checks if the application is using Windows or custom authentication, and uses that information to parse the `My.User.Name` property.  \n  \n [!code-vb[VbVbalrMyUser#3](~/add/codesnippet/visualbasic/VbVbalrMyUser/Class1.vb#3)]"
  syntax:
    content: 'public class WebUser : Microsoft.VisualBasic.ApplicationServices.User'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.User
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal
  - Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser
  - Microsoft.VisualBasic.ApplicationServices.User.IsAuthenticated
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(Microsoft.VisualBasic.ApplicationServices.BuiltInRole)
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(System.String)
  - Microsoft.VisualBasic.ApplicationServices.User.Name
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.WebUser&quot;> </xref> classe."
  remarks: "Le proprietà e metodi esposti dal `My.User` oggetto fornire accesso alle informazioni sull&quot;utente corrente."
  syntax:
    content: public WebUser ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  id: InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Ottiene o imposta l&quot;oggetto principale che rappresenta l&quot;utente corrente."
  remarks: "Nel <xref:Microsoft.VisualBasic.ApplicationServices.WebUser>dell&quot;oggetto, questa proprietà esegue il wrapping di <xref:System.Web.HttpContext.User%2A>proprietà del <xref:System.Web.HttpContext.Current%2A?displayProperty=fullName>proprietà.</xref:System.Web.HttpContext.Current%2A?displayProperty=fullName> </xref:System.Web.HttpContext.User%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WebUser>       Per ulteriori informazioni, vedere il <xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>proprietà.</xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>"
  syntax:
    content: protected override System.Security.Principal.IPrincipal InternalPrincipal { get; set; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Un <xref:System.Security.Principal.IPrincipal>che rappresenta l&quot;utente corrente.</xref:System.Security.Principal.IPrincipal>"
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.VisualBasic.ApplicationServices.User
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.User
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser
  nameWithType: WebUser.WebUser
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
