### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  id: ShutdownMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  langs:
  - csharp
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  type: Enum
  summary: "Indica la condizione che deve provocare l&quot;arresto di un&quot;applicazione Windows Form."
  remarks: "È possibile impostare la modalità di chiusura di un&quot;applicazione tramite il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A>proprietà.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> Per impostazione predefinita, il <xref:System.Windows.Forms.ApplicationContext.OnMainFormClosed%2A>metodo controlla il valore di <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A>proprietà per determinare se l&quot;applicazione deve essere chiuso.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> </xref:System.Windows.Forms.ApplicationContext.OnMainFormClosed%2A>"
  syntax:
    content: public enum ShutdownMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  id: AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Arrestato solo dopo la chiusura dell&quot;ultimo form."
  syntax:
    content: AfterAllFormsClose
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  id: AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Arrestare alla chiusura del form principale."
  syntax:
    content: AfterMainFormCloses
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
