### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  id: StartupNextInstanceEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  langs:
  - csharp
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  type: Class
  summary: "Fornisce dati per la <xref uid=&quot;langword_csharp_My.Application.StartupNextInstance&quot; name=&quot;My.Application.StartupNextInstance&quot; href=&quot;&quot;> </xref> evento."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>evento si verifica quando viene avviata una seconda istanza di un&quot;applicazione a istanza singola mediante il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md).       StartupNextInstanceEventArgs contiene gli argomenti della riga di comando dell&quot;istanza successiva dell&quot;applicazione e indica se la prima istanza di applicazione deve essere portata in primo piano all&quot;uscita dal gestore di eccezioni."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public class StartupNextInstanceEventArgs : EventArgs
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs&quot;> </xref> classe."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>evento si verifica quando viene avviata una seconda istanza di un&quot;applicazione a istanza singola mediante il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>contiene gli argomenti della riga di comando dell&quot;istanza successiva dell&quot;applicazione e indica se la prima istanza di applicazione deve essere portata in primo piano all&quot;uscita dal gestore di eccezioni.</xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>"
  syntax:
    content: public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args, bool bringToForegroundFlag);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "Oggetto &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; oggetto che contiene gli argomenti della riga di comando dell&quot;istanza successiva dell&quot;applicazione."
    - id: bringToForegroundFlag
      type: System.Boolean
      description: "Oggetto <xref:System.Boolean>che indica se la prima istanza di applicazione deve essere portata in primo piano all&quot;uscita dal gestore di eccezioni.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  id: BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Indica se la prima istanza di applicazione deve essere portata in primo piano all&quot;uscita dal gestore di eccezioni."
  remarks: "Il modello di applicazione Visual Basic controlla il valore di questa proprietà dopo l&quot;esecuzione dei gestori del <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>evento.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Se la proprietà BringToForeground `True`, la prima istanza di applicazione viene portata in primo piano. In caso contrario, la prima istanza dell&quot;applicazione rimane invariata. Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool BringToForeground { get; set; }
    return:
      type: System.Boolean
      description: "Oggetto <xref:System.Boolean>che indica se la prima istanza di applicazione deve essere portata in primo piano all&quot;uscita dal gestore di eccezioni.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Ottiene gli argomenti della riga di comando dell&quot;istanza successiva dell&quot;applicazione."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>evento si verifica quando viene avviata una seconda istanza di un&quot;applicazione a istanza singola mediante il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "Oggetto &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; oggetto che contiene gli argomenti della riga di comando dell&quot;istanza successiva dell&quot;applicazione."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
