### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  summary: "Fornisce dati per il <xref uid=&quot;langword_csharp_My.Application.Startup&quot; name=&quot;My.Application.Startup&quot; href=&quot;&quot;> </xref> evento."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>evento si verifica all&quot;avvio dell&quot;applicazione, se l&quot;applicazione implementa il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md).       StartupEventArgs contiene gli argomenti della riga di comando dell&quot;applicazione e indica se l&quot;avvio dell&quot;applicazione deve essere annullata."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupEventArgs&quot;> </xref> classe."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>evento si verifica all&quot;avvio dell&quot;applicazione, se l&quot;applicazione implementa il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>contiene gli argomenti della riga di comando dell&quot;applicazione e indica se l&quot;avvio dell&quot;applicazione deve essere annullata.</xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>"
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "Oggetto &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; oggetto che contiene gli argomenti della riga di comando dell&quot;applicazione."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Ottiene gli argomenti della riga di comando dell&quot;applicazione."
  remarks: "Il <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>evento si verifica all&quot;avvio dell&quot;applicazione, se l&quot;applicazione implementa il modello di applicazione Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Per ulteriori informazioni, vedere [Panoramica del modello di applicazione Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "Oggetto &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; oggetto che contiene gli argomenti della riga di comando dell&quot;applicazione."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs
  nameWithType: StartupEventArgs.StartupEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
