### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  id: FileAssociation
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  langs:
  - csharp
  name: FileAssociation
  nameWithType: FileAssociation
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  type: Class
  summary: "Rappresenta un&quot;estensione di file da associare all&quot;applicazione."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class FileAssociation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Inizializza una nuova istanza di <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation&quot;> </xref> classe."
  syntax:
    content: public FileAssociation ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  id: DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta l&quot;icona da utilizzare per i file che utilizzano un particolare <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>"
  syntax:
    content: public string DefaultIcon { get; set; }
    return:
      type: System.String
      description: "Il nome del file che contiene l&quot;icona."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  id: Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta la descrizione del tipo di file per l&quot;utilizzo dalla shell."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "Descrizione del tipo di file."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  id: Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta l&quot;estensione del nome file da associare all&quot;applicazione."
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "L&quot;estensione del nome file da associare all&quot;applicazione."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  id: ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta il nome che identifica in modo univoco il tipo di file di associazione di file."
  syntax:
    content: public string ProgId { get; set; }
    return:
      type: System.String
      description: "Il nome che identifica in modo univoco il tipo di file."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  id: XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta una proprietà usata per serializzare l&quot;associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*>proprietà in un file XML.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*>"
  syntax:
    content: public string XmlDefaultIcon { get; set; }
    return:
      type: System.String
      description: "Rappresentazione XML di DefaultIcon questa associazione di file."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  id: XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta una proprietà usata per serializzare l&quot;associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>proprietà in un file XML.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>"
  syntax:
    content: public string XmlDescription { get; set; }
    return:
      type: System.String
      description: "Una rappresentazione XML di questa associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>valore.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  id: XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta una proprietà usata per serializzare l&quot;associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>proprietà in un file XML.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>"
  syntax:
    content: public string XmlExtension { get; set; }
    return:
      type: System.String
      description: "Una rappresentazione XML di questa associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>valore.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  id: XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Ottiene o imposta una proprietà usata per serializzare il <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>proprietà in un file XML.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>"
  syntax:
    content: public string XmlProgId { get; set; }
    return:
      type: System.String
      description: "Una rappresentazione XML di questa associazione di file <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>valore.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation
  nameWithType: FileAssociation.FileAssociation
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
