### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Definisce il contratto implementato da un controllo per agire come un controllo di configurazione per una classe transformer in una connessione Web part."
  remarks: "Un controllo di configurazione può essere visualizzato quando un trasformatore richiede all&quot;utente di configurazione. Il controllo di configurazione fornisce un&quot;interfaccia utente (UI) che consente all&quot;utente di selezionare i valori da trasformare. Viene visualizzato in una zona connessioni. Il <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>metodo restituisce un controllo di configurazione.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       È possibile eseguire l&quot;override di <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>metodo quando il trasformatore richiede un&quot;interfaccia utente personalizzata.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> Il controllo di configurazione deve implementare l&quot;interfaccia ITransformerConfigurationControl, che include il <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>e <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>eventi.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> Questi eventi si verificano quando un controllo transformer non stato configurato o configurato correttamente, rispettivamente."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Si verifica quando la configurazione di trasformatore non è stata completata."
  remarks: "Il controllo di Web part che implementa <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>genera questo evento quando la configurazione di un trasformatore non viene completata, l&quot;utente ha annullato la configurazione o perché non è stato possibile eseguire la configurazione.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Si verifica quando la classe transformer configurazione è stata completata."
  remarks: "Il controllo di Web part che implementa <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>genera questo evento quando viene completata la configurazione di un trasformatore.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
