### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyAttribute
  id: ConfigurationPropertyAttribute
  children:
  - System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  - System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  - System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  - System.Configuration.ConfigurationPropertyAttribute.IsKey
  - System.Configuration.ConfigurationPropertyAttribute.IsRequired
  - System.Configuration.ConfigurationPropertyAttribute.Name
  - System.Configuration.ConfigurationPropertyAttribute.Options
  langs:
  - csharp
  name: ConfigurationPropertyAttribute
  nameWithType: ConfigurationPropertyAttribute
  fullName: System.Configuration.ConfigurationPropertyAttribute
  type: Class
  summary: "Indica in modo dichiarativo a .NET Framework per creare un&quot;istanza di una proprietà di configurazione. Questa classe non può essere ereditata."
  remarks: "Utilizzare il ConfigurationPropertyAttribute per decorare una proprietà di configurazione, che indicherà a .NET Framework per creare un&quot;istanza e per inizializzare la proprietà utilizzando il valore del parametro di decorazione.      > [!NOTE] > È il modo più semplice per creare un elemento di configurazione personalizzato per utilizzare il modello (dichiarativo) con attributo. Dichiarare le proprietà pubbliche personalizzate e decorarle con l&quot;attributo ConfigurationPropertyAttribute. Per ogni proprietà contrassegnate con questo attributo, .NET Framework utilizza la reflection per leggere i parametri di decorazione e creare un processo di <xref:System.Configuration.ConfigurationProperty>istanza.</xref:System.Configuration.ConfigurationProperty> È inoltre possibile utilizzare il modello a livello di codice, nel qual caso sarà necessario dichiarare le proprietà pubbliche personalizzate e restituire la raccolta.       Il sistema di configurazione di .NET Framework fornisce i tipi di attributo che è possibile utilizzare durante la creazione di elementi di configurazione personalizzato. Esistono due tipi di attributo: 1.  I tipi .NET Framework per indicare come creare un&quot;istanza di proprietà dell&quot;elemento di configurazione personalizzato. Questi tipi includono:- <xref:System.Configuration.ConfigurationCollectionAttribute>-2 ConfigurationPropertyAttribute.</xref:System.Configuration.ConfigurationCollectionAttribute>  I tipi che indicano a .NET Framework come convalidare le proprietà dell&quot;elemento di configurazione personalizzato. These types include:          -   <xref:System.Configuration.IntegerValidatorAttribute>          -   <xref:System.Configuration.LongValidatorAttribute>          -   <xref:System.Configuration.RegexStringValidatorAttribute>          -   <xref:System.Configuration.StringValidatorAttribute>          -   <xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.StringValidatorAttribute></xref:System.Configuration.RegexStringValidatorAttribute></xref:System.Configuration.LongValidatorAttribute></xref:System.Configuration.IntegerValidatorAttribute>"
  example:
  - "The following example shows how to define the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the ConfigurationPropertyAttribute attribute.  \n  \n The example contains two classes. The `UrlsSection` custom class uses the ConfigurationPropertyAttribute to define its own properties. The `UsingConfigurationPropertyAttribute` class uses the `UrlsSection` to read and write the custom section in the application configuration file.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#1](~/add/codesnippet/csharp/t-system.configuration.c_21_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#1](~/add/codesnippet/visualbasic/t-system.configuration.c_21_1.vb)]  \n  \n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#21](~/add/codesnippet/visualbasic/t-system.configuration.c_21_2.vb)]\n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#21](~/add/codesnippet/csharp/t-system.configuration.c_21_2.cs)]  \n  \n The following is an excerpt of the configuration file containing the custom section as defined in the previous sample.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n    <configSections>  \n        <section name=\"CustomSection\" type=\"UrlsSection, UsingConfigurationPropertyAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" />  \n    </configSections>  \n    <CustomSection name=\"Contoso\" url=\"http://www.contoso.com\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ConfigurationPropertyAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: ConfigurationPropertyAttribute(String)
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  fullName: System.Configuration.ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza della <xref href=&quot;System.Configuration.ConfigurationPropertyAttribute&quot;> </xref> classe."
  syntax:
    content: public ConfigurationPropertyAttribute (string name);
    parameters:
    - id: name
      type: System.String
      description: "Nome di <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> oggetto definito."
  overload: System.Configuration.ConfigurationPropertyAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  id: DefaultValue
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
  fullName: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il valore predefinito per la proprietà decorata."
  remarks: ''
  example:
  - "The following example shows how to use the DefaultValue property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/csharp/p-system.configuration.c_19_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/visualbasic/p-system.configuration.c_19_1.vb)]"
  syntax:
    content: public object DefaultValue { get; set; }
    return:
      type: System.Object
      description: "Oggetto che rappresenta il valore predefinito della proprietà dell&quot;elemento di configurazione decorata."
  overload: System.Configuration.ConfigurationPropertyAttribute.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  id: IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta un valore che indica se questa è la raccolta di proprietà predefinito per la proprietà di configurazione decorato."
  remarks: "Il valore della proprietà IsDefaultCollection viene ignorato se la proprietà decorata non è una raccolta."
  syntax:
    content: public bool IsDefaultCollection { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà rappresenta l&quot;insieme predefinito di un elemento. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey
  id: IsKey
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsKey
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta un valore che indica se questa è una proprietà chiave per la proprietà dell&quot;elemento decorato."
  remarks: "La proprietà IsKey si applica solo se la proprietà decorata è una raccolta. Non ha alcun effetto se la proprietà non è una raccolta. Più elementi possono essere contrassegnati come IsKey."
  example:
  - "The following example shows how to use the IsKey property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#2](~/add/codesnippet/csharp/p-system.configuration.c_4_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#2](~/add/codesnippet/visualbasic/p-system.configuration.c_4_1.vb)]"
  syntax:
    content: public bool IsKey { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà è una proprietà chiave per un elemento della raccolta. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  id: IsRequired
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta un valore che indica se la proprietà dell&quot;elemento decorato è obbligatoria."
  remarks: ''
  example:
  - "The following example shows how to use the <xref:System.Configuration.ConfigurationPropertyAttribute.DefaultValue%2A> property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/csharp/p-system.configuration.c_44_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/visualbasic/p-system.configuration.c_44_1.vb)]"
  syntax:
    content: public bool IsRequired { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà è obbligatoria. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.Name
  id: Name
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
  fullName: System.Configuration.ConfigurationPropertyAttribute.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il nome della proprietà dell&quot;elemento di configurazione decorata."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "Il nome della proprietà dell&quot;elemento di configurazione decorata."
  overload: System.Configuration.ConfigurationPropertyAttribute.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.Options
  id: Options
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
  fullName: System.Configuration.ConfigurationPropertyAttribute.Options
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il <xref href=&quot;System.Configuration.ConfigurationPropertyOptions&quot;> </xref> per la proprietà dell&quot;elemento di configurazione decorata."
  syntax:
    content: public System.Configuration.ConfigurationPropertyOptions Options { get; set; }
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Uno del <xref href=&quot;System.Configuration.ConfigurationPropertyOptions&quot;> </xref> valori di enumerazione associati alla proprietà."
  overload: System.Configuration.ConfigurationPropertyAttribute.Options*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: ConfigurationPropertyAttribute(String)
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  fullName: System.Configuration.ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
  fullName: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsKey
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsRequired
- uid: System.Configuration.ConfigurationPropertyAttribute.Name
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
  fullName: System.Configuration.ConfigurationPropertyAttribute.Name
- uid: System.Configuration.ConfigurationPropertyAttribute.Options
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
  fullName: System.Configuration.ConfigurationPropertyAttribute.Options
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: ConfigurationPropertyAttribute
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
- uid: System.Configuration.ConfigurationPropertyAttribute.Name*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
- uid: System.Configuration.ConfigurationPropertyAttribute.Options*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
