### YamlMime:ManagedReference
items:
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  id: ActiveDirectoryRoleFactoryConfiguration
  children:
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.#ctor
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member
  - System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath
  langs:
  - csharp
  name: ActiveDirectoryRoleFactoryConfiguration
  nameWithType: ActiveDirectoryRoleFactoryConfiguration
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  type: Class
  summary: "Rappresenta la sezione nel file di configurazione che risolve la classe di ruoli. Questa classe non può essere ereditata."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]Questa classe deriva da <xref:System.Configuration.ConfigurationSection>che rappresenta una sezione in un file di configurazione quando viene implementato in una classe derivata.</xref:System.Configuration.ConfigurationSection>  Ulteriori informazioni possono essere ottenute facendo riferimento a questa classe."
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public sealed class ActiveDirectoryRoleFactoryConfiguration : System.Configuration.ConfigurationSection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.#ctor
  id: '#ctor'
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: ActiveDirectoryRoleFactoryConfiguration()
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.ActiveDirectoryRoleFactoryConfiguration()
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.ActiveDirectoryRoleFactoryConfiguration()
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration&quot;> </xref> classe."
  syntax:
    content: public ActiveDirectoryRoleFactoryConfiguration ();
    parameters: []
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports
  id: DirectReports
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: DirectReports
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DirectReports
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta i nomi dei subalterni."
  remarks: "DirectReports è un <xref:System.Configuration.ConfigurationProperty>definita per questo tipo con il valore predefinito &quot;`DirectReports`&quot;.</xref:System.Configuration.ConfigurationProperty> Questo tipo rappresenta un elemento figlio, attributo o proprietà di configurazione contenuti in un elemento di un file di configurazione."
  syntax:
    content: public string DirectReports { get; set; }
    return:
      type: System.String
      description: "I nomi dei subalterni."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  id: DistinguishedName
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: DistinguishedName
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta il nome distinto per questa istanza."
  remarks: "Nome distinto è una <xref:System.Configuration.ConfigurationProperty>definita per questo tipo con il valore predefinito &quot;`DistiguishedName`&quot;.</xref:System.Configuration.ConfigurationProperty> Questo tipo rappresenta un elemento figlio, attributo o proprietà di configurazione contenuti in un elemento di un file di configurazione."
  syntax:
    content: public string DistinguishedName { get; set; }
    return:
      type: System.String
      description: "Il nome distinto per questa istanza."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group
  id: Group
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: Group
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Group
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta il nome del gruppo per questa istanza."
  syntax:
    content: public string Group { get; set; }
    return:
      type: System.String
      description: "Il nome del gruppo per questa istanza."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager
  id: Manager
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: Manager
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Manager
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta il nome del manager associato a questa istanza."
  remarks: "Gestione è un <xref:System.Configuration.ConfigurationProperty>definita per questo tipo con il valore predefinito &quot;`Manager`&quot;.</xref:System.Configuration.ConfigurationProperty> Questo tipo rappresenta un elemento figlio, attributo o proprietà di configurazione contenuti in un elemento di un file di configurazione."
  syntax:
    content: public string Manager { get; set; }
    return:
      type: System.String
      description: "Il nome del manager associato a questa istanza."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member
  id: Member
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: Member
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Member
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta il membro per questa istanza."
  remarks: "Membro è un <xref:System.Configuration.ConfigurationProperty>definita per questo tipo con il valore predefinito &quot;`Member`&quot;.</xref:System.Configuration.ConfigurationProperty> Questo tipo rappresenta un elemento figlio, attributo o proprietà di configurazione contenuti in un elemento di un file di configurazione."
  syntax:
    content: public string Member { get; set; }
    return:
      type: System.String
      description: "Il membro per questa istanza."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath
  id: RootPath
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  langs:
  - csharp
  name: RootPath
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.RootPath
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath
  type: Property
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Configuration
  summary: "Ottiene o imposta il percorso radice per questa istanza."
  remarks: "RootPath è un <xref:System.Configuration.ConfigurationProperty>definita per questo tipo con il valore predefinito &quot;`RootPath` &quot;.</xref:System.Configuration.ConfigurationProperty> Questo tipo rappresenta un elemento figlio, attributo o proprietà di configurazione contenuti in un elemento di un file di configurazione."
  syntax:
    content: public string RootPath { get; set; }
    return:
      type: System.String
      description: "Il percorso radice per questa istanza."
  overload: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.#ctor
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: ActiveDirectoryRoleFactoryConfiguration()
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.ActiveDirectoryRoleFactoryConfiguration()
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.ActiveDirectoryRoleFactoryConfiguration()
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: DirectReports
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DirectReports
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: DistinguishedName
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Group
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Group
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Manager
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Manager
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Member
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Member
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: RootPath
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.RootPath
  fullName: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.#ctor*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: ActiveDirectoryRoleFactoryConfiguration
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.ActiveDirectoryRoleFactoryConfiguration
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DirectReports*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: DirectReports
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DirectReports
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.DistinguishedName*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: DistinguishedName
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.DistinguishedName
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Group*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Group
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Group
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Manager*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Manager
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Manager
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.Member*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: Member
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.Member
- uid: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration.RootPath*
  parent: System.Workflow.Activities.Configuration.ActiveDirectoryRoleFactoryConfiguration
  isExternal: false
  name: RootPath
  nameWithType: ActiveDirectoryRoleFactoryConfiguration.RootPath
