### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventHandler
  id: DeploymentProgressChangedEventHandler
  langs:
  - csharp
  name: DeploymentProgressChangedEventHandler
  nameWithType: DeploymentProgressChangedEventHandler
  fullName: System.Deployment.Application.DeploymentProgressChangedEventHandler
  type: Delegate
  summary: "Rappresenta il metodo che gestirà il <xref href=&quot;System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged&quot;> </xref> evento <xref href=&quot;System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged&quot;> </xref> evento, o <xref href=&quot;System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged&quot;> </xref> evento di un <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'Quando si crea un delegato DeploymentProgressChangedEventHandler, si identifica il metodo che gestirà l&quot;evento. Per associare l&quot;evento al gestore eventi, aggiungere un&quot;istanza del delegato all&quot;evento. Il gestore eventi viene chiamato ogni volta che si verifica l&quot;evento, a meno che non venga rimosso il delegato. Per ulteriori informazioni sui delegati del gestore eventi, vedere [NIB: eventi e delegati](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void DeploymentProgressChangedEventHandler(object sender, DeploymentProgressChangedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
