### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement
  id: TokenReplayDetectionElement
  children:
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  langs:
  - csharp
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement
  type: Class
  summary: "Rappresenta un <xref uid=&quot;langword_csharp_&lt;tokenReplayDetection&gt;&quot; name=&quot;&lt;tokenReplayDetection&gt;&quot; href=&quot;&quot;> </xref> elemento in un file di configurazione. Questa classe non può essere ereditata."
  remarks: "Il `<tokenReplayDetection>` elemento consente di abilitare la logica di rilevamento per le riproduzioni token. Quando abilitata, WIF memorizza nella cache i token di sicurezza che sono stati ricevuti per l&quot;autenticazione e utilizza la cache per il rilevamento riproduzione. Un token rimane nella cache fino a quando il periodo di scadenza specificato da di <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod%2A>proprietà scade.</xref:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod%2A>       La cache di riproduzione token usato da WIF viene specificata per il `<caches>` elemento che è rappresentato dalla classe TokenReplayDetectionElement. La cache di riproduzione token viene configurata tramite la <xref:System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache%2A>proprietà.</xref:System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache%2A>"
  syntax:
    content: 'public sealed class TokenReplayDetectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.IdentityModel.Configuration.TokenReplayDetectionElement&quot;> </xref> classe"
  syntax:
    content: public TokenReplayDetectionElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  id: Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene o imposta un valore che indica se è necessario eseguire il rilevamento riproduzione."
  remarks: "Questa proprietà è facoltativa. Rappresenta il `enabled` attributo del `<tokenReplayDetection>` elemento."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Per eseguire il rilevamento riproduzione; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  id: ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene o imposta la quantità massima di tempo prima che un elemento viene considerato scaduto e rimossi dalla cache."
  remarks: "Questa proprietà è facoltativa. Rappresenta il `expirationPeriod` attributo del `<tokenReplayDetection>` elemento."
  syntax:
    content: public TimeSpan ExpirationPeriod { get; set; }
    return:
      type: System.TimeSpan
      description: "La quantità massima di tempo prima che un elemento viene considerato scaduto e rimossi dalla cache."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
