### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "Specifica i metodi di crittografia possono essere utilizzati."
  remarks: "Utilizzare i valori MachineKeyCompatibilityMode quando si imposta la <xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>proprietà.</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzare i metodi di crittografia che sono stati implementati in versioni di .NET Framework precedenti alla 2.0 Service Pack 2. Per tutte le operazioni di crittografia, ad eccezione di archiviazione delle password crittografata nel database delle appartenenze ASP.NET vengono utilizzati i vettori di inizializzazione (vettori di inizializzazione)."
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzare i metodi di crittografia più avanzati disponibili in .NET Framework versione 2.0 SP2 e versioni successive. Per tutte le operazioni di crittografia vengono utilizzati i vettori di inizializzazione (vettori di inizializzazione)."
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzare i metodi di crittografia sono disponibili in .NET Framework versione 4.5 e versioni successive. Rispetto ai metodi di crittografia utilizzato per Framework20SP1 e Framework20SP2, il testo crittografato che viene generato dalle routine di crittografia predefinito è leggermente più piccolo e più flessibile rispetto a determinate classi di attacchi teorici. Vengono inoltre integrate con [!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)] gestione delle chiavi directory per ottenere le chiavi di crittografia richieste. Questa opzione consente inoltre di specificare le routine di crittografia personalizzate scrivendo una classe che deriva da <xref href=&quot;System.Security.Cryptography.DataProtector&quot;> </xref> e specificando il nome della classe nel &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; proprietà.       I requisiti di configurazione seguenti si applicano a questa opzione: 1. Se il &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; proprietà ha un valore, il &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt; proprietà deve anche avere un valore.       2. Il &lt;xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt; l&quot;attributo deve specificare un algoritmo di convalida definito dal sistema (ad esempio MD5, SHA1, HMACSHA256, HMACSHA384 o HMACSHA512) o un algoritmo di convalida personalizzata in una classe che deriva dal <xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;> </xref> classe. I valori AES e 3DES non sono gli algoritmi di convalida.       Quando si specifica questa opzione, il ticket di autenticazione form viene sempre sia crittografato e firmato, indipendentemente dal valore specificato per il &lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt; proprietà. Visualizzazione dello stato viene inoltre sia crittografato e firmato se una pagina <> </> *> proprietà <code> true </code> o <> </> *> è <xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always>"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
