### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata
  id: ProfilePropertyMetadata
  children:
  - System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  - System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  - System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  - System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  - System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  - System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  - System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  - System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  langs:
  - csharp
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata
  type: Class
  summary: "Fornisce una raccolta di valori che descrivono una proprietà del profilo."
  remarks: "Utilizzare la classe ProfilePropertyMetadata per recuperare informazioni su una proprietà del profilo quando si accede ai profili tramite la <xref:System.Web.ApplicationServices.ProfileService>classe.</xref:System.Web.ApplicationServices.ProfileService> È possibile recuperare il nome e il tipo della proprietà, se si tratta di sola lettura, se è possibile accedere da utenti non autenticati e il valore predefinito. Un&quot;applicazione può intraprendere le azioni appropriate in base a questi valori, ad esempio non si desidera impostare una proprietà di sola lettura.       Per accedere all&quot;oggetto ProfilePropertyMetadata da un&quot;applicazione che è compatibile con Windows Communication Framework (WCF), utilizzare il <xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A>metodo della <xref:System.Web.ApplicationServices.ProfileService>classe.</xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A> L&quot;utente non deve essere connesso per recuperare l&quot;oggetto ProfilePropertyMetadata perché i metadati per le proprietà del profilo non sono specifico di valori di proprietà di profilo dell&quot;utente.       I valori nella classe ProfilePropertyMetadata sono impostati nel file Web. config nell&quot;elemento della sezione quando la proprietà è definita."
  syntax:
    content: >-
      [System.Runtime.Serialization.DataContract]

      public class ProfilePropertyMetadata : System.Runtime.Serialization.IExtensibleDataObject
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.IExtensibleDataObject
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.ApplicationServices.ProfilePropertyMetadata&quot;> </xref> classe."
  syntax:
    content: public ProfilePropertyMetadata ();
    parameters: []
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  id: AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta un valore che indica se la proprietà è disponibile per gli utenti non autenticati."
  remarks: "Quando si abilita l&quot;identificazione anonima con le impostazioni nell&quot;elemento, è possibile impostare le proprietà del profilo sono disponibili agli utenti anonimi. Impostare la proprietà AllowAnonymousAccess nell&quot;elemento della sezione del file Web. config quando la proprietà è definita. Dall&quot;applicazione client, utilizzare la proprietà AllowAnonymousAccess per determinare se è possibile impostare una proprietà di profilo per un utente anonimo."
  syntax:
    content: public bool AllowAnonymousAccess { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà è disponibile agli utenti non autenticati. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  id: DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta il valore predefinito della proprietà."
  remarks: "Il formato serializzato della proprietà DefaultValue è determinato dalla <xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>proprietà di <xref:System.Web.ApplicationServices.ProfilePropertyMetadata>classe.</xref:System.Web.ApplicationServices.ProfilePropertyMetadata> </xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>"
  syntax:
    content: public string DefaultValue { get; set; }
    return:
      type: System.String
      description: "Una rappresentazione serializzata del valore predefinito per la proprietà, se un valore predefinito è definito nel file Web. config. in caso contrario la stringa &quot;(null)&quot;."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  id: ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta un riferimento a un <xref href=&quot;System.Runtime.Serialization.ExtensionDataObject&quot;> </xref> istanza."
  syntax:
    content: public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
    return:
      type: System.Runtime.Serialization.ExtensionDataObject
      description: "Un riferimento a un oggetto che archivia i dati estesi durante le operazioni di deserializzazione."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  id: IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta un valore che indica se una proprietà del profilo è di sola lettura."
  remarks: "Impostare la proprietà IsReadOnly nell&quot;elemento della sezione del file Web. config quando la proprietà è definita."
  syntax:
    content: public bool IsReadOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà di profilo è di sola lettura. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  id: PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta il nome della proprietà del profilo."
  remarks: "Impostare la proprietà PropertyName nell&quot;elemento della sezione del file Web. config quando la proprietà è definita."
  syntax:
    content: public string PropertyName { get; set; }
    return:
      type: System.String
      description: "Il nome della proprietà del profilo, come definito nel file Web. config."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  id: SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta un valore che indica come serializzare il valore della proprietà."
  remarks: "Impostare la proprietà SerializeAs nell&quot;elemento della sezione del file Web. config quando la proprietà è definita."
  syntax:
    content: public int SerializeAs { get; set; }
    return:
      type: System.Int32
      description: "Il valore di enumerazione."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  id: TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta il nome completo dell&quot;assembly del tipo di proprietà di profilo."
  remarks: "Impostare la proprietà TypeName nell&quot;elemento della sezione del file Web. config quando la proprietà è definita."
  syntax:
    content: public string TypeName { get; set; }
    return:
      type: System.String
      description: "Il nome completo dell&quot;assembly del tipo di proprietà di profilo."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
- uid: System.Runtime.Serialization.ExtensionDataObject
  parent: System.Runtime.Serialization
  isExternal: false
  name: ExtensionDataObject
  nameWithType: ExtensionDataObject
  fullName: System.Runtime.Serialization.ExtensionDataObject
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
