### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode
  id: MembershipPasswordCompatibilityMode
  children:
  - System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  - System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  langs:
  - csharp
  name: MembershipPasswordCompatibilityMode
  nameWithType: MembershipPasswordCompatibilityMode
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode
  type: Enum
  summary: "Enumera le modalità di compatibilità di password per l&quot;appartenenza ASP.NET."
  remarks: "Questa enumerazione fornisce compatibilità con le versioni precedenti per i formati di password."
  syntax:
    content: public enum MembershipPasswordCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: MembershipPasswordCompatibilityMode.Framework20
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web.ApplicationServices
  namespace: System.Web.Configuration
  summary: "Le password sono in modalità di ASP.NET 2.0."
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.MembershipPasswordCompatibilityMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: MembershipPasswordCompatibilityMode.Framework40
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web.ApplicationServices
  namespace: System.Web.Configuration
  summary: "Le password sono in modalità di ASP.NET 4."
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.MembershipPasswordCompatibilityMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: MembershipPasswordCompatibilityMode.Framework20
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MembershipPasswordCompatibilityMode
  nameWithType: MembershipPasswordCompatibilityMode
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: MembershipPasswordCompatibilityMode.Framework40
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
