### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute
  id: ManagementConfigurationAttribute
  children:
  - System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  langs:
  - csharp
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute
  type: Class
  summary: "L&quot;attributo ManagementConfiguration indica che una proprietà o un campo rappresenta una proprietà WMI di lettura / scrittura.       Nota: le librerie .NET di WMI sono ormai considerate in stato finale e nessuna ulteriore sviluppo, miglioramenti o gli aggiornamenti saranno disponibili per problemi correlati, non correlato alla sicurezza che interessano queste librerie. Il [API MI](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) deve essere utilizzato per lo sviluppo di nuovo."
  remarks: "La proprietà o campo deve essere pubblico. La classe che contiene la proprietà deve essere contrassegnata con il <xref:System.Management.Instrumentation.ManagementEntityAttribute>attributo.</xref:System.Management.Instrumentation.ManagementEntityAttribute>       Qualsiasi campo o proprietà nella classe che non sono contrassegnate con questo o un altro attributo estensioni Provider WMI non verrà instrumentata."
  example:
  - "The following example shows how to use the ManagementConfiguration attribute to mark a property. This property is exposed to WMI.  \n  \n [C#]  \n  \n```  \n// Use the ManagementConfiguration attribute to specify that a property  \n// is a read/write property in the provider. Consumers will be  \n// able to get and set this property value through WMI.  \n[ManagementConfiguration]  \npublic double ReadableWritableProperty  \n{  \n    get { return this.propertyValue; }  \n    set { this.propertyValue = value; }  \n}  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple=false)]

      public sealed class ManagementConfigurationAttribute : System.Management.Instrumentation.ManagementMemberAttribute
  inheritance:
  - System.Attribute
  - System.Management.Instrumentation.ManagementMemberAttribute
  implements: []
  inheritedMembers:
  - System.Management.Instrumentation.ManagementMemberAttribute.Name
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  id: '#ctor'
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Inizializza una nuova istanza della <xref:System.Management.ManagementConfigurationAttribute>classe.</xref:System.Management.ManagementConfigurationAttribute> Questo è il costruttore predefinito."
  syntax:
    content: public ManagementConfigurationAttribute ();
    parameters: []
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  id: Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Ottiene o imposta la modalità della proprietà, che specifica se le modifiche a esso vengono applicate presto o quando viene chiamato un metodo di commit."
  remarks: "Se è presente un metodo commit definito, è responsabile per l&quot;aggiornamento di tutte le proprietà WMI di lettura / scrittura che utilizzano il <xref:System.Management.Instrumentation.ManagementConfigurationType>modalità.</xref:System.Management.Instrumentation.ManagementConfigurationType> Viene identificata da <xref:System.Management.Instrumentation.ManagementCommitAttribute>.</xref:System.Management.Instrumentation.ManagementCommitAttribute>"
  syntax:
    content: public System.Management.Instrumentation.ManagementConfigurationType Mode { get; set; }
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Restituisce un <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> che indica se la proprietà WMI utilizza <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> o <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> modalità."
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  id: Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Ottiene o imposta un valore che definisce il tipo di output che verrà restituita la proprietà che è contrassegnata con l&quot;attributo ManagementConfiguration."
  remarks: "Se il tipo restituito <xref:System.Object?displayProperty=fullName>, quindi l&quot;output deve essere trattata come un valore di tipo <xref:System.Object?displayProperty=fullName>.</xref:System.Object?displayProperty=fullName> </xref:System.Object?displayProperty=fullName>"
  syntax:
    content: public Type Schema { get; set; }
    return:
      type: System.Type
      description: "Oggetto <xref:System.Type>restituirà valore che rappresenta il tipo di output che la proprietà è contrassegnata con l&quot;attributo ManagementConfiguration.</xref:System.Type>"
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Management.Instrumentation.ManagementMemberAttribute
  isExternal: false
  name: System.Management.Instrumentation.ManagementMemberAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
