### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqTransportSecurity
  id: MsmqTransportSecurity
  children:
  - System.ServiceModel.MsmqTransportSecurity.#ctor
  - System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  - System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  - System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  - System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  - System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  langs:
  - csharp
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
  type: Class
  summary: "La classe MsmqTransportSecurity incapsula le impostazioni di sicurezza del trasporto dei trasporti in coda."
  syntax:
    content: public sealed class MsmqTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  syntax:
    content: public MsmqTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  id: '#ctor(System.ServiceModel.MsmqTransportSecurity)'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe, utilizzando un&quot;istanza esistente."
  syntax:
    content: public MsmqTransportSecurity (System.ServiceModel.MsmqTransportSecurity other);
    parameters:
    - id: other
      type: System.ServiceModel.MsmqTransportSecurity
      description: "L&quot;istanza esistente del <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> (classe), per essere utilizzato per inizializzare la nuova istanza."
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>other</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  id: MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "MSMQ può autenticare i messaggi vengono inviati alle code di messaggi che richiedono l&quot;autenticazione, o i messaggi possono richiedere esplicitamente l&quot;autenticazione. La modalità di autenticazione predefinita è <xref:System.ServiceModel.MsmqAuthenticationMode>.</xref:System.ServiceModel.MsmqAuthenticationMode>"
  syntax:
    content: public System.ServiceModel.MsmqAuthenticationMode MsmqAuthenticationMode { get; set; }
    return:
      type: System.ServiceModel.MsmqAuthenticationMode
      description: "Il <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore non è uno dei <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> valori."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  id: MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "MSMQ è possibile crittografare i messaggi in transito durante il trasferimento di messaggi tra gestori delle code. L&quot;algoritmo di crittografia predefinito è <xref:System.ServiceModel.MsmqEncryptionAlgorithm>.</xref:System.ServiceModel.MsmqEncryptionAlgorithm>"
  syntax:
    content: public System.ServiceModel.MsmqEncryptionAlgorithm MsmqEncryptionAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqEncryptionAlgorithm
      description: "Il <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore non è uno dei <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> valori."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  id: MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene o imposta il <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "Il livello di protezione predefinito è <xref:System.Net.Security.ProtectionLevel>.</xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel MsmqProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "Il <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore non è incluso il <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> valori."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  id: MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "L&quot;algoritmo hash predefinito è <xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>.</xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>"
  syntax:
    content: public System.ServiceModel.MsmqSecureHashAlgorithm MsmqSecureHashAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqSecureHashAlgorithm
      description: "Il <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> associato a questa istanza di <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore non è uno dei <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> valori."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqAuthenticationMode
  parent: System.ServiceModel
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqEncryptionAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqSecureHashAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
