### YamlMime:ManagedReference
items:
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler
  id: DbProviderFactoriesConfigurationHandler
  children:
  - System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  - System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DbProviderFactoriesConfigurationHandler
  nameWithType: DbProviderFactoriesConfigurationHandler
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler
  type: Class
  summary: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
  syntax:
    content: 'public class DbProviderFactoriesConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  langs:
  - csharp
  name: DbProviderFactoriesConfigurationHandler()
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  type: Constructor
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
  syntax:
    content: public DbProviderFactoriesConfigurationHandler ();
    parameters: []
  overload: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
    - id: configContext
      type: System.Object
      description: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
    - id: section
      type: System.Xml.XmlNode
      description: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
    return:
      type: System.Object
      description: "Questo tipo supporta l&quot;infrastruttura .NET Framework e non deve essere utilizzato direttamente dal codice."
  overload: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: DbProviderFactoriesConfigurationHandler()
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor*
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: DbProviderFactoriesConfigurationHandler
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create*
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DbProviderFactoriesConfigurationHandler.Create
