### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Specifica il percorso in cui una variabile di ambiente è archiviata o recuperata in un&quot;operazione set o get."
  remarks: "L&quot;enumerazione EnvironmentVariableTarget viene utilizzata da determinati overload del <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, e <xref:System.Environment.GetEnvironmentVariables%2A>metodi per specificare il percorso, o destinazione, in cui il nome e il valore di una variabile di ambiente viene archiviata o recuperata.</xref:System.Environment.GetEnvironmentVariables%2A> </xref:System.Environment.GetEnvironmentVariable%2A> </xref:System.Environment.SetEnvironmentVariable%2A>       La destinazione può essere una delle tre posizioni: il blocco di ambiente associato al processo corrente, la chiave del Registro di sistema del sistema operativo Windows riservata per le variabili di ambiente associate all&quot;utente corrente o la chiave del Registro di sistema riservata per le variabili di ambiente associate a tutti gli utenti del computer locale."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/cpp/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/visualbasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/csharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "La variabile di ambiente viene archiviata o recuperata dal <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;> </xref> chiave del Registro di sistema operativo di Windows."
  remarks: "Quando un utente crea la variabile di ambiente in un&quot;operazione set, il sistema operativo, la variabile di ambiente vengono archiviati nel Registro di sistema, ma non nel processo corrente. Se qualsiasi utente nel computer locale viene avviato un nuovo processo, la variabile di ambiente del sistema operativo copiata dal Registro di sistema a tale processo.       Al termine del processo, il sistema operativo elimina la variabile di ambiente del processo. Tuttavia, la variabile di ambiente nel Registro di sistema viene mantenuto finché un utente rimuove a livello di codice o tramite uno strumento del sistema operativo."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "La variabile di ambiente viene archiviata o recuperata dal blocco di ambiente associato al processo corrente."
  remarks: "L&quot;utente crea la variabile di ambiente in un&quot;operazione set.       Al termine del processo, il sistema operativo elimina la variabile di ambiente del processo."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "La variabile di ambiente viene archiviata o recuperata dal <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;> </xref> chiave del Registro di sistema operativo di Windows."
  remarks: "Quando l&quot;utente crea la variabile di ambiente in un&quot;operazione set, il sistema operativo archivia la variabile di ambiente nel Registro di sistema, ma non nel processo corrente. Se l&quot;utente inizia un nuovo processo, la variabile di ambiente del sistema operativo copiata dal Registro di sistema a tale processo.       Al termine del processo, il sistema operativo elimina la variabile di ambiente del processo. Tuttavia, la variabile di ambiente nel Registro di sistema viene mantenuto finché l&quot;utente rimuove a livello di codice o tramite uno strumento del sistema operativo."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
