### YamlMime:ManagedReference
items:
- uid: System.Configuration.IgnoreSectionHandler
  id: IgnoreSectionHandler
  children:
  - System.Configuration.IgnoreSectionHandler.#ctor
  - System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler
  fullName: System.Configuration.IgnoreSectionHandler
  type: Class
  summary: "Fornisce una definizione di gestore di sezione legacy per sezioni di configurazione che non sono gestite dal <xref href=&quot;System.Configuration&quot;> </xref> tipi."
  remarks: "Il sistema di configurazione completamente analizza i file di configurazione per raccogliere informazioni di configurazione e genera eccezioni quando viene rilevato sezioni di configurazione che non dispongono di una voce corrispondente nel `configSections` sezione.       Per le sezioni non è gestite dal <xref:System.Configuration>tipi, il nuovo tipo di wrapper <xref:System.Configuration.IgnoreSection>viene fornito.</xref:System.Configuration.IgnoreSection> </xref:System.Configuration> Questo serve a impedire le eccezioni di analisi del file di configurazione.       Per garantire il IgnoreSectionHandler viene inoltre fornita."
  syntax:
    content: 'public class IgnoreSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.IgnoreSectionHandler&quot;> </xref> classe."
  syntax:
    content: public IgnoreSectionHandler ();
    parameters: []
  overload: System.Configuration.IgnoreSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Crea un nuovo gestore di configurazione e aggiunge l&quot;oggetto di configurazione specificato alla raccolta di gestori di sezione."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Le impostazioni di configurazione in una sezione di configurazione padre corrispondente."
    - id: configContext
      type: System.Object
      description: "Il percorso virtuale per cui il gestore della sezione di configurazione calcola i valori di configurazione. In genere questo parametro è riservato e <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
    - id: section
      type: System.Xml.XmlNode
      description: "Un <xref href=&quot;System.Xml.XmlNode&quot;> </xref> che contiene le informazioni di configurazione da gestire. Fornisce accesso diretto al contenuto XML della sezione di configurazione."
    return:
      type: System.Object
      description: "L&quot;oggetto di gestore di configurazione creato."
  overload: System.Configuration.IgnoreSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IgnoreSectionHandler.#ctor*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler
- uid: System.Configuration.IgnoreSectionHandler.Create*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create
  nameWithType: IgnoreSectionHandler.Create
