### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyNotFoundException
  id: SettingsPropertyNotFoundException
  children:
  - System.Configuration.SettingsPropertyNotFoundException.#ctor
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException
  fullName: System.Configuration.SettingsPropertyNotFoundException
  type: Class
  summary: "Fornisce un&quot;eccezione per <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> gli oggetti che non sono stati trovati."
  remarks: "Questa eccezione viene generata dalla <xref:System.Configuration.SettingsBase>classe quando viene effettuato un tentativo di accedere a una proprietà in base al nome, ma la proprietà è stata mai associata con il <xref:System.Configuration.SettingsBase>istanza della classe o il provider configurato per la proprietà non ha restituito un valore quando viene richiesto di caricare i dati della proprietà.</xref:System.Configuration.SettingsBase> </xref:System.Configuration.SettingsBase>"
  syntax:
    content: 'public class SettingsPropertyNotFoundException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> classe."
  syntax:
    content: public SettingsPropertyNotFoundException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> (classe), in base a un parametro specificato."
  syntax:
    content: public SettingsPropertyNotFoundException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Stringa contenente un messaggio di eccezione."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> (classe), in base ai parametri forniti."
  syntax:
    content: protected SettingsPropertyNotFoundException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Il <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> oggetto che contiene i dati oggetto serializzati relativi all&quot;eccezione generata."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Il <xref:System.Runtime.Serialization.StreamingContext>oggetto che contiene le informazioni contestuali sull&quot;origine o destinazione del flusso serializzato.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> (classe), in base ai parametri forniti."
  syntax:
    content: public SettingsPropertyNotFoundException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Stringa contenente un messaggio di eccezione."
    - id: innerException
      type: System.Exception
      description: "Eccezione che è la causa dell&quot;eccezione corrente."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException
