### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement
  id: WebHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  langs:
  - csharp
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement
  type: Class
  summary: "Un elemento XML che configura la sicurezza per un servizio con endpoint che ricevono richieste HTTP. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class WebHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> classe."
  syntax:
    content: public WebHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene un elemento XML che specifica la modalità di sicurezza per un servizio HTTP di base."
  remarks: "Questa proprietà determina se le impostazioni di <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>proprietà diventa effettivo.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "Il valore <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref> che indica se la sicurezza a livello di trasporto o nessuna sicurezza viene utilizzata da un endpoint. Il valore predefinito è <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore non è valido <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene un elemento XML che indica le impostazioni di sicurezza a livello di trasporto per un endpoint del servizio configurato per ricevere richieste HTTP."
  remarks: "Utilizzare il <xref:System.ServiceModel.Configuration.WebHttpSecurityElement>oggetto restituito da questa proprietà per impostare i parametri di sicurezza trasporto.</xref:System.ServiceModel.Configuration.WebHttpSecurityElement> Il <xref:System.ServiceModel.WebHttpSecurityMode>deve essere impostato sul <xref:System.ServiceModel.WebHttpSecurityMode>o <xref:System.ServiceModel.WebHttpSecurityMode>valore per le impostazioni fornite dal <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>proprietà vengano rese effettive per l&quot;endpoint del servizio.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> Questo valore può essere impostato nella configurazione oppure nel <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>costruttore.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>"
  syntax:
    content: public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: "Oggetto <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> che specifica le impostazioni di sicurezza a livello di trasporto. I valori predefiniti impostati sono un <> </> *> di <xref:System.ServiceModel.HttpClientCredentialType>, <> </> *> di <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>, e <xref:System.ServiceModel.HttpTransportSecurity.Realm*>= &quot;&quot;.</xref:System.ServiceModel.HttpTransportSecurity.Realm*> </xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
