### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigClientHost
  id: IInternalConfigClientHost
  children:
  - System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigClientHost
  nameWithType: IInternalConfigClientHost
  fullName: System.Configuration.Internal.IInternalConfigClientHost
  type: Interface
  summary: "Definisce le interfacce che consentono l&quot;infrastruttura .NET Framework interno personalizzare la configurazione."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigClientHost
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  id: GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce il percorso al file di configurazione dell&quot;applicazione."
  syntax:
    content: public string GetExeConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "Stringa che rappresenta il percorso del file di configurazione dell&quot;applicazione."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  id: GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce una stringa che rappresenta il percorso al file di configurazione dell&quot;utente locale noto."
  syntax:
    content: public string GetLocalUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "Stringa che rappresenta il percorso al file di configurazione dell&quot;utente locale noto."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  id: GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce una stringa che rappresenta il percorso al file di configurazione utente roaming noti."
  syntax:
    content: public string GetRoamingUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "Stringa che rappresenta il percorso al file di configurazione utente roaming noti."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  id: IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un valore che indica se un percorso di file di configurazione è lo stesso come un percorso di file di configurazione dell&quot;applicazione attualmente noto."
  syntax:
    content: public bool IsExeConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Stringa che rappresenta il percorso del file di configurazione dell&quot;applicazione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se una stringa che rappresenta un percorso di configurazione corrisponde al percorso file di configurazione dell&quot;applicazione. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se una stringa che rappresenta un percorso di configurazione non è uguale a un percorso al file di configurazione dell&quot;applicazione."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  id: IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un valore che indica se un percorso di file di configurazione è uguale al percorso del file di configurazione per l&quot;utente locale attualmente noto."
  syntax:
    content: public bool IsLocalUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Stringa che rappresenta il percorso del file di configurazione dell&quot;applicazione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se una stringa che rappresenta un percorso di configurazione è uguale a un percorso in un file di configurazione dell&quot;utente locale noto. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  id: IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un valore che indica se un percorso di file di configurazione è uguale al percorso del file di configurazione per l&quot;utente roaming attualmente noto."
  syntax:
    content: public bool IsRoamingUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Stringa che rappresenta il percorso di un file di configurazione dell&quot;applicazione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se una stringa che rappresenta un percorso di configurazione è uguale a un percorso in un file di configurazione utente roaming noti. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath
  nameWithType: IInternalConfigClientHost.GetExeConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig
  nameWithType: IInternalConfigClientHost.IsExeConfig
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig
