### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer
  id: IRemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: IRemoteWebConfigurationHostServer
  nameWithType: IRemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer
  type: Interface
  summary: "Utilizzata internamente per supportare l&quot;accesso remoto ai dati di configurazione."
  remarks: "Classe da cui base <xref:System.Web.Configuration.RemoteWebConfigurationHostServer>estende.</xref:System.Web.Configuration.RemoteWebConfigurationHostServer>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("A99B591A-23C6-4238-8452-C7B0E895063D")]

      public interface IRemoteWebConfigurationHostServer
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Crittografa o decrittografa il valore della stringa a cui fa riferimento in modo condizionale il <code> xmlString </code> parametro."
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] parameterKeys, string[] parameterValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>per crittografare; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> da decrittografare."
    - id: xmlString
      type: System.String
      description: "Il codice XML da crittografare o decrittografare."
    - id: protectionProviderName
      type: System.String
      description: "Il provider utilizzato per proteggere i dati di configurazione."
    - id: protectionProviderType
      type: System.String
      description: "Il <xref:System.Type>del provider di protezione.</xref:System.Type>"
    - id: parameterKeys
      type: System.String[]
      description: "Le chiavi dei parametri facoltativi per il provider di protezione."
    - id: parameterValues
      type: System.String[]
      description: "I valori dei parametri facoltativi per il provider di protezione."
    return:
      type: System.String
      description: "Una stringa contenente il valore crittografato o decrittografato del <code> xmlString </code>."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzata internamente per supportare l&quot;accesso remoto ai dati di configurazione."
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Percorso del file di configurazione remoto a cui accedere."
    - id: getReadTimeOnly
      type: System.Boolean
      description: "Un valore booleano che specifica se solo il `readTime` viene restituito."
    - id: readTime
      type: System.Int64
      description: "Ora che dell&quot;ultimo accesso al file."
    return:
      type: System.Byte[]
      description: "Un <xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref> di interi senza segno a 8 bit (byte) che contiene i dati di configurazione."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene i dettagli del file di configurazione."
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "Il nome del file."
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il file esiste. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: size
      type: System.Int64
      description: "Le dimensioni del file."
    - id: createDate
      type: System.Int64
      description: "La data di creazione del file."
    - id: lastWriteDate
      type: System.Int64
      description: "La data dell&quot;ultima scrittura nel file."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzata internamente per supportare l&quot;accesso remoto ai dati di configurazione."
  syntax:
    content: public string GetFilePaths (int webLevel, string path, string site, string locationSubPath);
    parameters:
    - id: webLevel
      type: System.Int32
      description: "Il livello di file di configurazione."
    - id: path
      type: System.String
      description: "Percorso del file di configurazione remoto a cui accedere."
    - id: site
      type: System.String
      description: "Percorso nel computer remoto."
    - id: locationSubPath
      type: System.String
      description: "Il sottopercorso del percorso del file di configurazione."
    return:
      type: System.String
      description: "Una stringa concatenata che rappresenta il percorso del file del file di configurazione."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Utilizzata internamente per supportare l&quot;accesso remoto ai dati di configurazione."
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Percorso del file di configurazione remoto a cui accedere."
    - id: templateFileName
      type: System.String
      description: "File per gli attributi di file da duplicare."
    - id: data
      type: System.Byte[]
      description: "Dati da scrivere."
    - id: readTime
      type: System.Int64
      description: "Ora che dell&quot;ultimo accesso al file."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: IRemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: IRemoteWebConfigurationHostServer.WriteData
