### YamlMime:ManagedReference
items:
- uid: System.Xml.Schema.XmlSchemaCompilationSettings
  id: XmlSchemaCompilationSettings
  children:
  - System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  - System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  langs:
  - csharp
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings
  type: Class
  summary: "Fornisce opzioni di compilazione dello schema per il <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> classe questa classe non può essere ereditata."
  remarks: "La classe XmlSchemaCompilationSettings fornisce opzioni di compilazione dello schema per la <xref:System.Xml.Schema.XmlSchemaSet>classe.</xref:System.Xml.Schema.XmlSchemaSet> Ad esempio, il <xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>proprietà specifica che il <xref:System.Xml.Schema.XmlSchemaSet>deve ricercare le violazioni di attribuzione di particelle univoche (UPA) quando gli schemi nel <xref:System.Xml.Schema.XmlSchemaSet>vengono compilati.</xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>"
  syntax:
    content: public sealed class XmlSchemaCompilationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xml.Schema.XmlSchemaCompilationSettings&quot;> </xref> classe."
  syntax:
    content: public XmlSchemaCompilationSettings ();
    parameters: []
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  id: EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Ottiene o imposta un valore che indica se il <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> deve ricercare le violazioni di attribuzione di particelle univoche (UPA)."
  remarks: "Quando è impostata la proprietà EnableUpaCheck `false`, la convalida verrà eseguita in base alle regole seguenti.      1.  Se è possibile scegliere tra un tipo sicuro e un carattere jolly, il <xref:System.Xml.Schema.XmlSchemaSet>sceglierà la particella fortemente tipizzata come illustrato di esempi di Xml schema seguente.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:any namespace=&quot;##any&quot;/>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `</xs:sequence>`Il codice XML seguente, il `A` elemento verrà associato `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` nello schema.       `<A>some text</A>`      1.  Se è possibile scegliere tra due elementi fortemente tipizzati, il <xref:System.Xml.Schema.XmlSchemaSet>sceglierà il primo.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot;/>`       `</xs:sequence>`Il codice XML seguente, il `B` elemento verrà associato `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` nello schema.       `<A/>`       `<B/>`"
  syntax:
    content: public bool EnableUpaCheck { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> deve ricercare le violazioni di attribuzione di particelle univoche (UPA); in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
