### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Indica che una proprietà delle impostazioni dell&quot;applicazione ha un significato speciale. Questa classe non può essere ereditata."
  remarks: "Alcune proprietà delle impostazioni dell&quot;applicazione hanno un significato speciale che consente di modificare il modo in cui i provider di impostazioni associato deve elaborarli. Il SpecialSettingAttribute viene utilizzato per identificare tali proprietà. Questa classe viene utilizzata la <xref:System.Configuration.SpecialSetting?displayProperty=fullName>enumerazione per indicare quale categoria speciale appartiene la proprietà.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute può essere applicato solo alla classe di impostazioni o per la proprietà di singole impostazioni.       Per un esempio di come un provider di impostazioni gestisce il SpecialSettingAttribute, vedere il <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>metodo della <xref:System.Configuration.LocalFileSettingsProvider>classe.</xref:System.Configuration.LocalFileSettingsProvider> </xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> classe."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "Oggetto <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> il valore di enumerazione che definisce la categoria della proprietà di impostazione dell&quot;applicazione."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il valore che descrive la categoria speciale di impostazione della proprietà di impostazione dell&quot;applicazione."
  remarks: "La proprietà SpecialSetting è impostata nel <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>costruttore di questa classe.</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "Oggetto <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> il valore di enumerazione che definisce la categoria della proprietà di impostazione dell&quot;applicazione."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
