### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SerializationMode
  id: SerializationMode
  children:
  - System.Web.Configuration.SerializationMode.Binary
  - System.Web.Configuration.SerializationMode.ProviderSpecific
  - System.Web.Configuration.SerializationMode.String
  - System.Web.Configuration.SerializationMode.Xml
  langs:
  - csharp
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
  type: Enum
  summary: "Determina il metodo di serializzazione usato per un <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> oggetto."
  remarks: "Il <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>proprietà del <xref:System.Web.Configuration.ProfilePropertySettings>oggetto controlla la modalità di serializzazione di un&quot;impostazione di proprietà di profilo singolo.</xref:System.Web.Configuration.ProfilePropertySettings> </xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/csharp/t-system.web.configurati_92_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_92_1.vb)]"
  syntax:
    content: public enum SerializationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Binary
  id: Binary
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Il <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> oggetto viene serializzato mediante la serializzazione binaria."
  syntax:
    content: Binary
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  id: ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Il provider ha una conoscenza implicita del tipo ed è responsabile per decidere come serializzare la <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> oggetto nell&quot;archivio dati."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.String
  id: String
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Il <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> oggetto viene serializzato in una stringa semplice."
  syntax:
    content: String
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Xml
  id: Xml
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Il profilo <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> viene serializzato come XML mediante la serializzazione XML."
  syntax:
    content: Xml
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.SerializationMode.Binary
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
- uid: System.Web.Configuration.SerializationMode
  parent: System.Web.Configuration
  isExternal: false
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
- uid: System.Web.Configuration.SerializationMode.String
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
- uid: System.Web.Configuration.SerializationMode.Xml
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
