### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Rappresenta il metodo che gestirà il <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> evento."
  remarks: "Il <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>evento si verifica quando le impostazioni vengono recuperate da un provider.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> Questo evento viene generato una volta per ogni provider."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
