### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  id: ActivityStateQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables
  langs:
  - csharp
  name: ActivityStateQueryElement
  nameWithType: ActivityStateQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  type: Class
  summary: "Un elemento di configurazione che rappresenta un <xref href=&quot;System.Activities.Tracking.ActivityStateQuery&quot;> </xref>."
  syntax:
    content: 'public class ActivityStateQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: ActivityStateQueryElement()
  nameWithType: ActivityStateQueryElement.ActivityStateQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityStateQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement&quot;> </xref> classe."
  syntax:
    content: public ActivityStateQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName
  id: ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: ActivityName
  nameWithType: ActivityStateQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta il nome dell&quot;attività per filtrare <xref href=&quot;System.Activities.Tracking.ActivityStateRecord&quot;> </xref> istanze."
  remarks: "Il valore predefinito è &quot;*&quot; (tutto)."
  syntax:
    content: public string ActivityName { get; set; }
    return:
      type: System.String
      description: "Il nome dell&quot;attività."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments
  id: Arguments
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: Arguments
  nameWithType: ActivityStateQueryElement.Arguments
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene un <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ArgumentElementCollection&quot;> </xref> che contiene le variabili per filtrare <xref href=&quot;System.Activities.Tracking.ActivityStateRecord&quot;> </xref> in."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ArgumentElementCollection Arguments { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElementCollection
      description: "Raccolta di argomenti."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: ActivityStateQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Crea un nuovo <xref href=&quot;System.Activities.Tracking.ActivityStateQuery&quot;> </xref>."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "La query sullo stato dell&quot;attività."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: ActivityStateQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> che contiene le proprietà dell&quot;elemento di configurazione."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Le proprietà dell&quot;elemento di configurazione."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States
  id: States
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: States
  nameWithType: ActivityStateQueryElement.States
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene un <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection&quot;> </xref> che contiene gli stati da filtrare <xref href=&quot;System.Activities.Tracking.ActivityStateRecord&quot;> </xref> in."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection States { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
      description: "Raccolta di stati."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables
  id: Variables
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  langs:
  - csharp
  name: Variables
  nameWithType: ActivityStateQueryElement.Variables
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene un <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.VariableElementCollection&quot;> </xref> che contiene le variabili per filtrare <xref href=&quot;System.Activities.Tracking.ActivityStateRecord&quot;> </xref> in."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.VariableElementCollection Variables { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.VariableElementCollection
      description: "La raccolta di variabili."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: ActivityStateQueryElement()
  nameWithType: ActivityStateQueryElement.ActivityStateQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityStateQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: ActivityStateQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Arguments
  nameWithType: ActivityStateQueryElement.Arguments
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ArgumentElementCollection
  nameWithType: ArgumentElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: ActivityStateQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Properties
  nameWithType: ActivityStateQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: States
  nameWithType: ActivityStateQueryElement.States
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: StateElementCollection
  nameWithType: StateElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Variables
  nameWithType: ActivityStateQueryElement.Variables
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: VariableElementCollection
  nameWithType: VariableElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: ActivityStateQueryElement
  nameWithType: ActivityStateQueryElement.ActivityStateQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.ActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: ActivityStateQueryElement.ActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Arguments*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Arguments
  nameWithType: ActivityStateQueryElement.Arguments
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: ActivityStateQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Properties
  nameWithType: ActivityStateQueryElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.States*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: States
  nameWithType: ActivityStateQueryElement.States
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement.Variables*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement
  isExternal: false
  name: Variables
  nameWithType: ActivityStateQueryElement.Variables
