### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection
  id: CommonBehaviorsSection
  children:
  - System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  - System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  - System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  - System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  langs:
  - csharp
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection
  type: Class
  summary: "Rappresenta la sezione di configurazione che contiene un elenco di comportamenti applicato a tutti [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] servizi del computer prima che i comportamenti nel <xref uid=&quot;langword_csharp_behaviors&quot; name=&quot;behaviors&quot; href=&quot;&quot;> </xref> sezione vengono applicate."
  remarks: "Questa sezione di configurazione è definita nel file Machine. config. Contiene un elenco di comportamenti applicato a tutti i [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] servizi del computer prima che i comportamenti nel `behaviors` sezione vengono applicate. Se un comportamento viene definito in entrambe le sezioni e il comportamento di `behaviors` viene data preferenza."
  syntax:
    content: 'public class CommonBehaviorsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.CommonBehaviorsSection&quot;> </xref> classe."
  syntax:
    content: public CommonBehaviorsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  id: EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene tutte le voci figlio che sono <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;> </xref> elementi identificati da un nome univoco."
  syntax:
    content: public System.ServiceModel.Configuration.CommonEndpointBehaviorElement EndpointBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
      description: "Le voci figlio che sono <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;> </xref> elementi identificati da un nome univoco."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> istanza che contiene una raccolta di <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> gli oggetti che possono essere attributi o <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> gli oggetti di questo elemento di configurazione."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Oggetto <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> istanza che contiene una raccolta di <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> gli oggetti che possono essere attributi o <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> gli oggetti di questo elemento di configurazione."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  id: ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene tutte le voci figlio che sono <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;> </xref> elementi identificati da un nome univoco."
  syntax:
    content: public System.ServiceModel.Configuration.CommonServiceBehaviorElement ServiceBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonServiceBehaviorElement
      description: "Le voci figlio che sono <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;> </xref> elementi identificati da un nome univoco."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonEndpointBehaviorElement
  nameWithType: CommonEndpointBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
- uid: System.ServiceModel.Configuration.CommonServiceBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonServiceBehaviorElement
  nameWithType: CommonServiceBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonServiceBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
