### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlReaderSettings
  id: XamlReaderSettings
  children:
  - System.Xaml.XamlReaderSettings.#ctor
  - System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  langs:
  - csharp
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
  type: Class
  summary: "Specifica le regole di elaborazione o opzioni di configurazione per un <xref href=&quot;System.Xaml.XamlReader&quot;> </xref> implementazione."
  remarks: "Per impostazione predefinita, un oggetto XamlReaderSettings inizializzato utilizza i valori per le proprietà che corrispondono ai valori predefiniti, previsto, ad esempio `false` per proprietà booleane o valori null per le proprietà del tipo di riferimento. Inizializzazione predefinita riporta i valori seguenti: - il <xref:System.Xaml.XamlReaderSettings.BaseUri%2A>e <xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A>sono proprietà `null`.</xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A> </xref:System.Xaml.XamlReaderSettings.BaseUri%2A>      -La <xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>proprietà `false`.</xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>      -La <xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>proprietà `false` nel modello a oggetti; tuttavia, può essere `true` in fase di esecuzione in base alle eseguibili caricate e le relative impostazioni di debug, o dal contesto dello schema XAML.</xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>"
  syntax:
    content: public class XamlReaderSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> classe."
  remarks: "Per ulteriori informazioni sull&quot;inizializzazione di un&quot; <xref:System.Xaml.XamlReaderSettings>istanza predefinita, vedere <xref:System.Xaml.XamlReaderSettings>.</xref:System.Xaml.XamlReaderSettings> </xref:System.Xaml.XamlReaderSettings>"
  syntax:
    content: public XamlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  id: '#ctor(System.Xaml.XamlReaderSettings)'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> classe in base ai valori in un altro <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> oggetto."
  remarks: "Questo costruttore supporta l&quot;unione delle impostazioni per i reader XAML in cui le impostazioni aggiuntive possono provenire anche da altri partecipanti nel processo di lettura."
  syntax:
    content: public XamlReaderSettings (System.Xaml.XamlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlReaderSettings
      description: "Un oggetto esistente <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> oggetto."
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  id: AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che indica se l&quot;oggetto radice può includere i membri che presentano un modello di accesso di codice protetto quando si segnala la rappresentazione del tipo XAML."
  remarks: "Questa impostazione è pertinente per alcune implementazioni XAML, ad esempio WPF in cui l&quot;oggetto radice è spesso una &quot;factory&quot; per la generazione di un&quot;istanza da un tipo di modello, quando tale tipo di modello non è sempre un&quot;istanza di oggetto pratico. Ad esempio, una radice di `UserControl` dispone di un determinato significato per i modelli di applicazione WPF e Silverlight e `UserControl` potrebbe disporre di proprietà protette (`UserControl.Content`) che il parser deve accedere a. Strumenti e aree di progettazione è inoltre necessario accedere a tali proprietà. In questi casi viene in genere devono essere segnalati al sistema di tipi XAML come proprietà accessibile in scrittura anche se essi dispongono di accesso protetto nel sistema di tipi di backup."
  syntax:
    content: public bool AllowProtectedMembersOnRoot { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;oggetto radice può includere i membri che presentano un modello di accesso di codice protetto; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.BaseUri
  id: BaseUri
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta l&quot;URI di base che viene utilizzato per risolvere i percorsi relativi."
  remarks: "Alcune proprietà relative a URI nell&quot;API di servizi XAML di .NET Framework che considera gli URI degli spazi dei nomi XAML come stringhe. Tuttavia, questa proprietà Usa il vero <xref:System.Uri>tipo.</xref:System.Uri>"
  syntax:
    content: public Uri BaseUri { get; set; }
    return:
      type: System.Uri
      description: "L&quot;URI di base da utilizzare. Il valore predefinito è <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.BaseUri*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  id: IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se il reader XAML deve ignorare i valori per <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> attributi presenti negli elementi di proprietà."
  remarks: "Durante la localizzazione, il `x:Uid` attributo viene utilizzato per identificare gli elementi nel markup in modo che gli strumenti di localizzazione possono elaborare gli elementi XAML come entità discrete per la localizzazione. Gli attributi non vengono visualizzati in genere per gli elementi di proprietà in XAML. Tuttavia, `x:Uid` si verifica un&quot;eccezione perché alcuni utilizzi inseriscono testo localizzato in un elemento di proprietà come contenuto, anziché come oggetto separato che può ricevere il proprio `x:Uid`. Impostare un valore IgnoreUidsOnPropertyElements `true` consente una modalità più rigida. Il valore predefinito di `false` continua a elaborare l&quot;elemento proprietà `x:Uid` attributi."
  syntax:
    content: public bool IgnoreUidsOnPropertyElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il lettore deve ignorare i valori per <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> attributi per gli elementi proprietà. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se il lettore deve elaborare <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> attributi per gli elementi proprietà. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  id: LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta l&quot;oggetto che rappresenta l&quot;assembly locale corrente per l&quot;elaborazione. Queste informazioni assembly viene utilizzate per le chiamate alle API di supporto, ad esempio &lt;xref:System.Xaml.XamlType.GetAllMembers%2A?displayProperty=fullName&gt;."
  syntax:
    content: public System.Reflection.Assembly LocalAssembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: "Un riflesso di CLR <xref:System.Reflection.Assembly>oggetto.</xref:System.Reflection.Assembly>"
  overload: System.Xaml.XamlReaderSettings.LocalAssembly*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  id: ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se il lettore può fornire il numero di riga e la posizione."
  remarks: "È ProvideLineInfo `false` nel modello a oggetti; tuttavia, può essere `true` in fase di esecuzione in base a eseguibili caricate e le relative impostazioni di debug."
  syntax:
    content: public bool ProvideLineInfo { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il lettore può fornire informazioni sulla numero e la posizione riga. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  id: ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se il lettore impone che tutti i <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> nodi vengono elaborati come un <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> tipo."
  remarks: "Oltre a <xref:System.String>, una possibile `Value` contenuto in alcune implementazioni XAML è <xref:System.Windows.Markup.XData>.</xref:System.Windows.Markup.XData> </xref:System.String>"
  syntax:
    content: public bool ValuesMustBeString { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il lettore che impone solo <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> è contenuto in <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> nodi; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlReaderSettings.#ctor
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
- uid: System.Xaml.XamlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlReaderSettings.BaseUri
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
- uid: System.Xaml.XamlReaderSettings.#ctor*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Xaml.XamlReaderSettings.BaseUri*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
