### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: "Specifica il provider di impostazioni utilizzato per fornire l&quot;archiviazione per la proprietà o una classe di impostazioni dell&quot;applicazione corrente. Questa classe non può essere ereditata."
  remarks: "Ogni classe di impostazioni dell&quot;applicazione definisce un gruppo di proprietà delle impostazioni dell&quot;applicazione che rappresentano le informazioni che persiste tra le esecuzioni dell&quot;applicazione. Tuttavia, è un provider di impostazioni, ovvero una classe derivata da <xref:System.Configuration.SettingsProvider>, che fornisce effettivamente il meccanismo di archiviazione.</xref:System.Configuration.SettingsProvider>       Il SettingsProviderAttribute specifica il provider di impostazioni utilizzato per fornire l&quot;archiviazione per le proprietà delle impostazioni dell&quot;applicazione. Questo attributo può essere applicato alla classe di impostazioni intera applicazione o proprietà delle impostazioni di singole applicazioni. Un SettingsProviderAttribute impostare a livello di proprietà sostituirà l&quot;attributo a livello di classe. Se un provider di impostazioni non è specificato in modo esplicito, viene utilizzato il provider predefinito. Per le applicazioni client, il provider predefinito è <xref:System.Configuration.LocalFileSettingsProvider>.</xref:System.Configuration.LocalFileSettingsProvider>       Provider di impostazioni non è possibile determinare in fase di esecuzione. Qualsiasi determinazione in fase di esecuzione dei metodi di archiviazione deve essere codificata nella classe delle impostazioni di provider stesso.      > [!CAUTION] > Utilizzando il provider di impostazioni personalizzati di terze parti è intrinsecamente non sicure, poiché questi provider dispongono dell&quot;accesso in lettura/scrittura alle informazioni di configurazione dell&quot;applicazione. Un provider di impostazioni deve essere esaminato attentamente prima per uso generale."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza un&quot;istanza di <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> classe."
  remarks: "Il nome del tipo è il nome della classe, derivata da <xref:System.Configuration.SettingsProvider>, ovvero viene specificato come provider di impostazioni.</xref:System.Configuration.SettingsProvider>      > [!CAUTION] > Utilizzando il provider di impostazioni personalizzati di terze parti è intrinsecamente non sicure, poiché questi provider dispongono dell&quot;accesso in lettura/scrittura alle informazioni di configurazione dell&quot;applicazione. Un provider di impostazioni deve essere esaminato attentamente prima per uso generale."
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: "Oggetto <xref:System.String>contenente il nome del provider di impostazioni.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> classe."
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: "Oggetto <xref:System.Type>contenente il tipo di provider di impostazioni.</xref:System.Type>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il nome del tipo del provider di impostazioni."
  remarks: "La proprietà ProviderTypeName è impostata in <xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>per la classe.</xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>"
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: "Oggetto <xref:System.String>contenente il nome del provider di impostazioni.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
