### YamlMime:ManagedReference
items:
- uid: System.Runtime.Serialization.Configuration.TypeElement
  id: TypeElement
  children:
  - System.Runtime.Serialization.Configuration.TypeElement.#ctor
  - System.Runtime.Serialization.Configuration.TypeElement.#ctor(System.String)
  - System.Runtime.Serialization.Configuration.TypeElement.Index
  - System.Runtime.Serialization.Configuration.TypeElement.Parameters
  - System.Runtime.Serialization.Configuration.TypeElement.Properties
  - System.Runtime.Serialization.Configuration.TypeElement.Reset(System.Configuration.ConfigurationElement)
  - System.Runtime.Serialization.Configuration.TypeElement.Type
  langs:
  - csharp
  name: TypeElement
  nameWithType: TypeElement
  fullName: System.Runtime.Serialization.Configuration.TypeElement
  type: Class
  summary: "Gestisce gli elementi XML utilizzati per configurare la serializzazione da <xref:System.Runtime.Serialization.DataContractSerializer>.</xref:System.Runtime.Serialization.DataContractSerializer>"
  remarks: "Questa classe viene utilizzata per gestire il [ \\&lt; dataContractSerializer\\&gt;](../Topic/%3CdataContractSerializer%3E.md) all&quot;interno di [ \\&lt; dataContractSerializer\\&gt;](../Topic/%3CdataContractSerializer%3E.md) elemento, in particolare per consentire l&quot;aggiunta di tipi alla raccolta di tipi noti."
  syntax:
    content: 'public sealed class TypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: TypeElement()
  nameWithType: TypeElement.TypeElement()
  fullName: System.Runtime.Serialization.Configuration.TypeElement.TypeElement()
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Runtime.Serialization.Configuration.TypeElement&quot;> </xref> classe."
  syntax:
    content: public TypeElement ();
    parameters: []
  overload: System.Runtime.Serialization.Configuration.TypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: TypeElement(String)
  nameWithType: TypeElement.TypeElement(String)
  fullName: System.Runtime.Serialization.Configuration.TypeElement.TypeElement(String)
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Runtime.Serialization.Configuration.TypeElement&quot;> </xref> classe con il nome del tipo specificato."
  syntax:
    content: public TypeElement (string typeName);
    parameters:
    - id: typeName
      type: System.String
      description: "Il nome del tipo che utilizza tipi noti."
  overload: System.Runtime.Serialization.Configuration.TypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.Index
  id: Index
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: Index
  nameWithType: TypeElement.Index
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Index
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Ottiene o imposta la posizione dell&quot;elemento."
  syntax:
    content: public int Index { get; set; }
    return:
      type: System.Int32
      description: "La posizione dell&quot;elemento."
  overload: System.Runtime.Serialization.Configuration.TypeElement.Index*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.Parameters
  id: Parameters
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: Parameters
  nameWithType: TypeElement.Parameters
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Parameters
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Ottiene una raccolta di parametri."
  syntax:
    content: public System.Runtime.Serialization.Configuration.ParameterElementCollection Parameters { get; }
    return:
      type: System.Runtime.Serialization.Configuration.ParameterElementCollection
      description: "Oggetto <xref href=&quot;System.Runtime.Serialization.Configuration.ParameterElementCollection&quot;> </xref> che contiene i parametri per il tipo."
  overload: System.Runtime.Serialization.Configuration.TypeElement.Parameters*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.Properties
  id: Properties
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: TypeElement.Properties
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Properties
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Runtime.Serialization.Configuration.TypeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: TypeElement.Reset(ConfigurationElement)
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Da aggiungere."
  overload: System.Runtime.Serialization.Configuration.TypeElement.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.TypeElement.Type
  id: Type
  parent: System.Runtime.Serialization.Configuration.TypeElement
  langs:
  - csharp
  name: Type
  nameWithType: TypeElement.Type
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Type
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Ottiene o imposta il nome del tipo."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Il nome del tipo."
  overload: System.Runtime.Serialization.Configuration.TypeElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Runtime.Serialization.Configuration.TypeElement.#ctor
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: TypeElement()
  nameWithType: TypeElement.TypeElement()
  fullName: System.Runtime.Serialization.Configuration.TypeElement.TypeElement()
- uid: System.Runtime.Serialization.Configuration.TypeElement.#ctor(System.String)
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: TypeElement(String)
  nameWithType: TypeElement.TypeElement(String)
  fullName: System.Runtime.Serialization.Configuration.TypeElement.TypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Serialization.Configuration.TypeElement.Index
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Index
  nameWithType: TypeElement.Index
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Index
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Runtime.Serialization.Configuration.TypeElement.Parameters
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Parameters
  nameWithType: TypeElement.Parameters
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Parameters
- uid: System.Runtime.Serialization.Configuration.ParameterElementCollection
  parent: System.Runtime.Serialization.Configuration
  isExternal: false
  name: ParameterElementCollection
  nameWithType: ParameterElementCollection
  fullName: System.Runtime.Serialization.Configuration.ParameterElementCollection
- uid: System.Runtime.Serialization.Configuration.TypeElement.Properties
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Properties
  nameWithType: TypeElement.Properties
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Runtime.Serialization.Configuration.TypeElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: TypeElement.Reset(ConfigurationElement)
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Reset(ConfigurationElement)
- uid: System.Runtime.Serialization.Configuration.TypeElement.Type
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Type
  nameWithType: TypeElement.Type
  fullName: System.Runtime.Serialization.Configuration.TypeElement.Type
- uid: System.Runtime.Serialization.Configuration.TypeElement.#ctor*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: TypeElement
  nameWithType: TypeElement.TypeElement
- uid: System.Runtime.Serialization.Configuration.TypeElement.Index*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Index
  nameWithType: TypeElement.Index
- uid: System.Runtime.Serialization.Configuration.TypeElement.Parameters*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Parameters
  nameWithType: TypeElement.Parameters
- uid: System.Runtime.Serialization.Configuration.TypeElement.Properties*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Properties
  nameWithType: TypeElement.Properties
- uid: System.Runtime.Serialization.Configuration.TypeElement.Reset*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Reset
  nameWithType: TypeElement.Reset
- uid: System.Runtime.Serialization.Configuration.TypeElement.Type*
  parent: System.Runtime.Serialization.Configuration.TypeElement
  isExternal: false
  name: Type
  nameWithType: TypeElement.Type
