### YamlMime:ManagedReference
items:
- uid: System.Web.Management.WebApplicationLifetimeEvent
  id: WebApplicationLifetimeEvent
  children:
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  langs:
  - csharp
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent
  fullName: System.Web.Management.WebApplicationLifetimeEvent
  type: Class
  summary: "Rappresenta un evento significativo nella durata di un&quot;applicazione."
  remarks: "Il monitoraggio dello stato ASP.NET consente di produzione e lo staff operativo per la gestione di applicazioni Web distribuite. Il <xref:System.Web.Management>dello spazio dei nomi contiene i tipi di evento di stato responsabili per comprimere i dati di stato di integrità dell&quot;applicazione e i tipi di provider responsabili dell&quot;elaborazione dei dati.</xref:System.Web.Management> Contiene inoltre i tipi di supporto che semplificano la gestione degli eventi di integrità.       Eventi durata applicazione includono gli eventi, ad esempio l&quot;avvio dell&quot;applicazione e gli eventi di arresto. Se un&quot;applicazione viene terminata, è possibile determinare il motivo visualizzando il campo di messaggio di evento correlate.       Quando si verifica un&quot;istanza di WebApplicationLifetimeEvent, il monitoraggio dello stato ASP.NET aggiorna il contatore delle prestazioni eventi durata applicazione. È possibile accedere a questi eventi aggiungendo l&quot;oggetto WebApplicationLifetimeEvent il `rules` sottosezione del `healthMonitoring` sezione del file di configurazione, come illustrato nell&quot;esempio seguente.      ```   <rules>     <add name=&quot;Application Events&quot;       eventName=&quot;Application Lifetime Events&quot;       provider=&quot;EventLogProvider&quot;       profile=&quot;Default&quot;       minInterval=&quot;00:01:00&quot; />   </rules>      ```Il contatore delle prestazioni eventi durata applicazione contiene la somma totale di tutti gli eventi di durata ASP.NET. Per visualizzare questo contatore delle prestazioni in Monitor di sistema (PerfMon), il **Aggiungi contatori** finestra selezionare **ASP.NET** dal **oggetto prestazione** elenco a discesa. Selezionare il **eventi durata applicazione** contatore delle prestazioni e scegliere il **Aggiungi** pulsante. Per ulteriori informazioni, vedere &quot;Utilizzo di Monitor di sistema (PerfMon) con le applicazioni ASP.NET&quot; in [MSDN](http://go.microsoft.com/fwlink/?linkid=37118). Se si consentono la registrazione dallo standard degli eventi <xref:System.Web.Management.EventLogWebEventProvider>, è possibile visualizzarle nel Visualizzatore eventi selezionando le **applicazione** registro</xref:System.Web.Management.EventLogWebEventProvider> Per ulteriori informazioni, vedere [Visualizzatore eventi](http://go.microsoft.com/fwlink/?linkid=24845&clcid=0x409) nella documentazione di Windows Server 2003 su TechNet.      > [!CAUTION] > Perché l&quot;oggetto WebApplicationLifetimeEvent è un evento con volumi elevati, registrazione utilizza molte risorse e potrebbe rallentare il sistema. Può inoltre causare di essere sovrascritto nel caso di altri eventi di <xref:System.Web.Management.EventLogWebEventProvider>classe a causa dell&quot;elevato volume di eventi e la modalità della registrazione eventi.</xref:System.Web.Management.EventLogWebEventProvider>      > [!NOTE] > Nella maggior parte dei casi sarà possibile utilizzare i tipi di monitoraggio dello stato ASP.NET, come implementato e controllare il sistema di monitoraggio dello stato specificando i valori di `healthMonitoring` sezione di configurazione. È anche possibile derivare da tipi di monitoraggio dello stato per creare eventi personalizzati e i provider. Per un esempio di derivazione dalla classe WebApplicationLifetimeEvent, vedere l&quot;esempio fornito in questo argomento."
  example:
  - "The following code example shows how to derive from the WebApplicationLifetimeEvent class to create a custom event.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/visualbasic/t-system.web.management._24_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/csharp/t-system.web.management._24_1.cs)]  \n  \n The following configuration-file excerpt shows how to configure the `healthMonitoring` section of a configuration file to add the `SampleWebApplicationLifetimeEvent` code defined above to the ASP.NET health-monitoring system. To add the event to the system, you must define the event by adding a new entry to the `eventMappings` section and map the event to a provider by adding a new entry to the `rules` section.  \n  \n```  \n<healthMonitoring  \n  enabled=\"true\"  \n  heartBeatInterval=\"0\">  \n  \n    <eventMappings>  \n       <clear />  \n       <!-- Configure the application lifetime event -->  \n       <!-- object to handle the Web application events. -->  \n       <add name=\"SampleApplicationLifetimeEvents\"  \n         type=\"System.Web.Management.SampleWebApplicationLifetimeEvent,  \n         System.Web,Version=2.0.3600.0,  \n         Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a\" />  \n     </eventMappings>  \n  \n    <rules>  \n      <clear/>  \n       // Configure the connection between the   \n       // application lifetime event object   \n       // and the provider that must process it.  \n       <add name=\"Custom Application Events\"  \n         eventName=\"SampleApplicationLifetimeEvents\"  \n         provider=\"EventLogProvider\"  \n         profile=\"Default\"  \n         minInterval=\"00:01:00\" />  \n    </rules>  \n  \n</healthMonitoring>  \n```"
  syntax:
    content: 'public class WebApplicationLifetimeEvent : System.Web.Management.WebManagementEvent'
  inheritance:
  - System.Object
  - System.Web.Management.WebBaseEvent
  - System.Web.Management.WebManagementEvent
  implements: []
  inheritedMembers:
  - System.Web.Management.WebBaseEvent.ApplicationInformation
  - System.Web.Management.WebBaseEvent.EventCode
  - System.Web.Management.WebBaseEvent.EventDetailCode
  - System.Web.Management.WebBaseEvent.EventID
  - System.Web.Management.WebBaseEvent.EventOccurrence
  - System.Web.Management.WebBaseEvent.EventSequence
  - System.Web.Management.WebBaseEvent.EventSource
  - System.Web.Management.WebBaseEvent.EventTime
  - System.Web.Management.WebBaseEvent.EventTimeUtc
  - System.Web.Management.WebBaseEvent.FormatCustomEventDetails(System.Web.Management.WebEventFormatter)
  - System.Web.Management.WebBaseEvent.Message
  - System.Web.Management.WebBaseEvent.Raise
  - System.Web.Management.WebBaseEvent.Raise(System.Web.Management.WebBaseEvent)
  - System.Web.Management.WebBaseEvent.ToString
  - System.Web.Management.WebBaseEvent.ToString(System.Boolean,System.Boolean)
  - System.Web.Management.WebManagementEvent.ProcessInformation
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Inizializza il <xref href=&quot;System.Web.Management.WebApplicationLifetimeEvent&quot;> </xref> classe utilizzando i parametri forniti."
  remarks: "Questo costruttore viene utilizzato internamente dal sistema di monitoraggio dello stato di ASP.NET. Non verrà mai utilizzato per creare un&quot;istanza della <xref:System.Web.Management.WebApplicationLifetimeEvent>classe, ma è possibile chiamare questo costruttore quando si implementa un tipo di evento che eredita da questa classe.</xref:System.Web.Management.WebApplicationLifetimeEvent>      > [!NOTE] > WebApplicationLifetimeEvent il costruttore non è destinato a essere utilizzato direttamente dal codice. Viene chiamato da ASP.NET. È possibile chiamare il costruttore WebApplicationLifetimeEvent quando si deriva dalla <xref:System.Web.Management.WebApplicationLifetimeEvent>classe.</xref:System.Web.Management.WebApplicationLifetimeEvent>"
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/visualbasic/f6897152-ffc5-4ce1-a4ea-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/csharp/f6897152-ffc5-4ce1-a4ea-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio associato all&quot;evento."
    - id: eventSource
      type: System.Object
      description: "Oggetto che rappresenta l&quot;origine dell&quot;evento."
    - id: eventCode
      type: System.Int32
      description: "Il codice associato all&quot;evento. Quando si implementa un evento personalizzato, il codice dell&quot;evento deve essere maggiore di <xref href=&quot;System.Web.Management.WebEventCodes.WebExtendedBase&quot;> </xref>."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Inizializza il <xref href=&quot;System.Web.Management.WebApplicationLifetimeEvent&quot;> </xref> classe utilizzando i parametri forniti."
  remarks: "Questo costruttore viene utilizzato internamente dal sistema di monitoraggio dello stato di ASP.NET. Non verrà mai utilizzato per creare un&quot;istanza della <xref:System.Web.Management.WebApplicationLifetimeEvent>classe, ma è possibile chiamare questo costruttore quando si implementa un tipo di evento che eredita da questa classe.</xref:System.Web.Management.WebApplicationLifetimeEvent>      > [!NOTE] > WebApplicationLifetimeEvent il costruttore non è destinato a essere utilizzato direttamente dal codice. Viene chiamato da ASP.NET. È possibile chiamare il costruttore WebApplicationLifetimeEvent quando si deriva dalla <xref:System.Web.Management.WebApplicationLifetimeEvent>classe.</xref:System.Web.Management.WebApplicationLifetimeEvent>"
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/visualbasic/d658829b-c5f1-4bb1-9080-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/csharp/d658829b-c5f1-4bb1-9080-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode, int eventDetailCode);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio associato all&quot;evento."
    - id: eventSource
      type: System.Object
      description: "Oggetto che rappresenta l&quot;origine dell&quot;evento."
    - id: eventCode
      type: System.Int32
      description: "Il codice associato all&quot;evento. Quando si implementa un evento personalizzato, il codice dell&quot;evento deve essere maggiore di <xref href=&quot;System.Web.Management.WebEventCodes.WebExtendedBase&quot;> </xref>."
    - id: eventDetailCode
      type: System.Int32
      description: "Il <xref href=&quot;System.Web.Management.WebEventCodes&quot;> </xref> valore che specifica l&quot;identificatore dettagliato per l&quot;evento."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  id: IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Utilizzato internamente per incrementare i contatori delle prestazioni."
  syntax:
    content: protected override void IncrementPerfCounters ();
    parameters: []
  overload: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Management.WebManagementEvent
  isExternal: false
  name: System.Web.Management.WebManagementEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters
