### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  id: TransactionsSectionGroup
  children:
  - System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  - System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  - System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  langs:
  - csharp
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
  type: Class
  summary: "Rappresenta una sezione di configurazione che incapsula e consente l&quot;attraversamento di tutte le transazioni elementi XML di configurazione e gli attributi che si trovano all&quot;interno di questa sezione di configurazione. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class TransactionsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;> </xref> classe."
  syntax:
    content: public TransactionsSectionGroup ();
    parameters: []
  overload: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  id: DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Ottiene le impostazioni predefinite utilizzate per inizializzare gli elementi e attributi in una sezione di transazioni."
  syntax:
    content: public System.Transactions.Configuration.DefaultSettingsSection DefaultSettings { get; }
    return:
      type: System.Transactions.Configuration.DefaultSettingsSection
      description: "Oggetto <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> che rappresenta le impostazioni predefinite. Il valore predefinito è una <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> che viene popolata con i valori predefiniti."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Fornisce l&quot;accesso statico per una <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;> </xref>."
  syntax:
    content: public static System.Transactions.Configuration.TransactionsSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "Oggetto <xref href=&quot;System.Configuration.Configuration&quot;> </xref> che rappresenta le impostazioni di configurazione che si applicano a un determinato computer, l&quot;applicazione o risorsa."
    return:
      type: System.Transactions.Configuration.TransactionsSectionGroup
      description: "A <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;></xref> object."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  id: MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Ottiene le impostazioni di configurazione impostate a livello di computer."
  syntax:
    content: public System.Transactions.Configuration.MachineSettingsSection MachineSettings { get; }
    return:
      type: System.Transactions.Configuration.MachineSettingsSection
      description: "Oggetto <xref href=&quot;System.Transactions.Configuration.MachineSettingsSection&quot;> </xref> che rappresenta le impostazioni di configurazione a livello di computer. Il valore predefinito è una <xref href=&quot;System.Transactions.Configuration.MachineSettingsSection&quot;> </xref> che viene popolata con i valori predefiniti."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
- uid: System.Transactions.Configuration.DefaultSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  parent: System.Transactions.Configuration
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
- uid: System.Transactions.Configuration.MachineSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: MachineSettingsSection
  nameWithType: MachineSettingsSection
  fullName: System.Transactions.Configuration.MachineSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: TransactionsSectionGroup.GetSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
