### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "Rappresenta i possibili comportamenti di commit di una proprietà di lettura/scrittura. Viene utilizzato come valore di un parametro del <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationAttribute&quot;> </xref> attributo.       Nota: le librerie .NET di WMI sono ormai considerate in stato finale e nessuna ulteriore sviluppo, miglioramenti o gli aggiornamenti saranno disponibili per problemi correlati, non correlato alla sicurezza che interessano queste librerie. La [API MI](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) deve essere utilizzato per lo sviluppo di nuovo."
  remarks: "Questo attributo viene utilizzato come valore di parametro per il <xref:System.Management.Instrumentation.ManagementConfigurationAttribute>attributo solo se il <xref:System.Management.Instrumentation.ManagementCommitAttribute>attributo viene utilizzato per identificare un metodo da eseguire per i valori di commit.</xref:System.Management.Instrumentation.ManagementCommitAttribute> </xref:System.Management.Instrumentation.ManagementConfigurationAttribute> In caso contrario, i valori delle proprietà di lettura/scrittura vengono applicati automaticamente."
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Impostare i valori hanno effetto solo quando viene chiamato Commit."
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Impostare i valori vengono applicati immediatamente."
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
