### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer
  id: ArgumentValueSerializer
  children:
  - System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  - System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: ArgumentValueSerializer
  nameWithType: ArgumentValueSerializer
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer
  type: Class
  summary: "Converte istanze di <xref href=&quot;System.Activities.Argument&quot;> </xref> alle istanze di <xref:System.String>.</xref:System.String>"
  syntax:
    content: 'public class ArgumentValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: ArgumentValueSerializer()
  nameWithType: ArgumentValueSerializer.ArgumentValueSerializer()
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ArgumentValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Activities.XamlIntegration.ArgumentValueSerializer&quot;> </xref> classe."
  syntax:
    content: public ArgumentValueSerializer ();
    parameters: []
  overload: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Determina se l&quot;oggetto specificato può essere convertito in un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Oggetto da valutare per la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <code> value </code> può essere convertito in un <xref:System.String>; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Converte l&quot;oggetto specificato in un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Oggetto da convertire in un <xref:System.String>.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.String
      description: "Oggetto <xref:System.String>rappresentazione dell&quot;oggetto specificato.</xref:System.String>"
  overload: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ArgumentValueSerializer()
  nameWithType: ArgumentValueSerializer.ArgumentValueSerializer()
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ArgumentValueSerializer()
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor*
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ArgumentValueSerializer
  nameWithType: ArgumentValueSerializer.ArgumentValueSerializer
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString*
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: ArgumentValueSerializer.CanConvertToString
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString*
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: ArgumentValueSerializer.ConvertToString
