### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  summary: "Specifica il tipo di registrazione da eseguire per un <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> o <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> registrazione."
  remarks: "Registrazione di un <xref:System.Net.PeerToPeer.Collaboration.PeerApplication>consente di ricevere <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>le richieste di invito.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> </xref:System.Net.PeerToPeer.Collaboration.PeerApplication> Il servizio o applicazione che esegue la registrazione abbia le autorizzazioni a tale scopo, in quanto richiede l&quot;accesso alla <xref:System.Net.PeerToPeer.Collaboration.ContactManager>e altre risorse quali gli utenti, applicazioni e servizi nel computer remoto.</xref:System.Net.PeerToPeer.Collaboration.ContactManager>"
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> o <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> viene registrato per tutti i peer dell&quot;host applicazione"
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "L&quot;applicazione o un oggetto viene registrato solo per l&quot;utente associato al peer chiamante"
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
