### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TransformerInfo
  id: TransformerInfo
  children:
  - System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  - System.Web.Configuration.TransformerInfo.Equals(System.Object)
  - System.Web.Configuration.TransformerInfo.GetHashCode
  - System.Web.Configuration.TransformerInfo.Name
  - System.Web.Configuration.TransformerInfo.Properties
  - System.Web.Configuration.TransformerInfo.Type
  langs:
  - csharp
  name: TransformerInfo
  nameWithType: TransformerInfo
  fullName: System.Web.Configuration.TransformerInfo
  type: Class
  summary: "Specifica una classe personalizzata che estende il <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe per l&quot;uso da parte delle connessioni Web Part."
  remarks: "Oggetti TransformerInfo specificano le classi personalizzate che estendono la <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>classe.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer> Queste classi di trasformazione personalizzato fungono da ponte tra le Web part, convertendo i dati tra le Web part con punti di connessione incompatibili."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for several properties of the TransformerInfo class.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <transformers>  \n      <add name=\"RowToFieldTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFieldTransformer\" />  \n      <add name=\"RowToFilterTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFilterTransformer\" />  \n      <add name=\"RowToParametersTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToParametersTransformer\" />  \n    </transformers>  \n  </webParts>   \n</system.web>  \n```  \n  \n The following code example shows how to use the TransformerInfo class. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/csharp/t-system.web.configurati_58_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/visualbasic/t-system.web.configurati_58_1.vb)]"
  syntax:
    content: 'public sealed class TransformerInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: TransformerInfo(String,String)
  nameWithType: TransformerInfo.TransformerInfo(String,String)
  fullName: System.Web.Configuration.TransformerInfo.TransformerInfo(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> classe con il nome e il tipo di riferimento specificato."
  remarks: "Il sistema di configurazione non convalida il tipo specificato per garantire che venga utilizzato un nome di tipo valido."
  example:
  - "The following code example shows how to use the TransformerInfo constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#5](~/add/codesnippet/csharp/8552e432-1ac7-4c16-b8d4-_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#5](~/add/codesnippet/visualbasic/8552e432-1ac7-4c16-b8d4-_1.vb)]"
  syntax:
    content: public TransformerInfo (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "Il nome di questo tipo di trasformatore."
    - id: type
      type: System.String
      description: "Un riferimento a un tipo che estende il trasformatore <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe."
  overload: System.Web.Configuration.TransformerInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: TransformerInfo.Equals(Object)
  fullName: System.Web.Configuration.TransformerInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Confronta l&quot;oggetto corrente <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> oggetto a un altro <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> oggetto."
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: "Oggetto da confrontare all&quot;oggetto corrente."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;oggetto passato è uguale all&quot;oggetto corrente. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.TransformerInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: TransformerInfo.GetHashCode()
  fullName: System.Web.Configuration.TransformerInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Genera un codice hash per la raccolta."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Codice hash di tipo integer univoco per l&quot;oggetto corrente."
  overload: System.Web.Configuration.TransformerInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Name
  id: Name
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Name
  nameWithType: TransformerInfo.Name
  fullName: System.Web.Configuration.TransformerInfo.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta un nome descrittivo per un tipo che estende il <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe."
  remarks: ''
  example:
  - "The following code example shows how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Un nome descrittivo per un tipo che estende il <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe."
  overload: System.Web.Configuration.TransformerInfo.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Properties
  id: Properties
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Properties
  nameWithType: TransformerInfo.Properties
  fullName: System.Web.Configuration.TransformerInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.TransformerInfo.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Type
  id: Type
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Type
  nameWithType: TransformerInfo.Type
  fullName: System.Web.Configuration.TransformerInfo.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il riferimento al tipo per una classe che estende il <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe."
  remarks: "Il sistema di configurazione non convalida il tipo specificato per garantire che venga utilizzato un nome di tipo valido. Tuttavia, i tipi non validi generano eccezioni quando vengono caricate le pagine Web."
  example:
  - "The following code example shows how to use the Type property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> type.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Riferimento a un tipo per una classe che estende il <xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> classe."
  overload: System.Web.Configuration.TransformerInfo.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: TransformerInfo(String,String)
  nameWithType: TransformerInfo.TransformerInfo(String,String)
  fullName: System.Web.Configuration.TransformerInfo.TransformerInfo(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TransformerInfo.Equals(System.Object)
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: TransformerInfo.Equals(Object)
  fullName: System.Web.Configuration.TransformerInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.TransformerInfo.GetHashCode
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: TransformerInfo.GetHashCode()
  fullName: System.Web.Configuration.TransformerInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.TransformerInfo.Name
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Name
  nameWithType: TransformerInfo.Name
  fullName: System.Web.Configuration.TransformerInfo.Name
- uid: System.Web.Configuration.TransformerInfo.Properties
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Properties
  nameWithType: TransformerInfo.Properties
  fullName: System.Web.Configuration.TransformerInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TransformerInfo.Type
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Type
  nameWithType: TransformerInfo.Type
  fullName: System.Web.Configuration.TransformerInfo.Type
- uid: System.Web.Configuration.TransformerInfo.#ctor*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: TransformerInfo
  nameWithType: TransformerInfo.TransformerInfo
- uid: System.Web.Configuration.TransformerInfo.Equals*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Equals
  nameWithType: TransformerInfo.Equals
- uid: System.Web.Configuration.TransformerInfo.GetHashCode*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: GetHashCode
  nameWithType: TransformerInfo.GetHashCode
- uid: System.Web.Configuration.TransformerInfo.Name*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Name
  nameWithType: TransformerInfo.Name
- uid: System.Web.Configuration.TransformerInfo.Properties*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Properties
  nameWithType: TransformerInfo.Properties
- uid: System.Web.Configuration.TransformerInfo.Type*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Type
  nameWithType: TransformerInfo.Type
