### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationHost
  id: ApplicationHost
  children:
  - System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  langs:
  - csharp
  name: ApplicationHost
  nameWithType: ApplicationHost
  fullName: System.Web.Hosting.ApplicationHost
  type: Class
  summary: "Abilita l&quot;hosting delle pagine ASP.NET all&quot;esterno dell&quot;applicazione Internet Information Services (IIS). Questa classe consente all&quot;host creare i domini applicazione per l&quot;elaborazione delle richieste ASP.NET."
  remarks: "ApplicationHost è stato introdotto in .NET Framework versione 3.5.  Per ulteriori informazioni, vedere [versioni e dipendenze](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public sealed class ApplicationHost
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  id: CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  langs:
  - csharp
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Crea e configura un dominio applicazione per l&quot;hosting ASP.NET."
  syntax:
    content: public static object CreateApplicationHost (Type hostType, string virtualDir, string physicalDir);
    parameters:
    - id: hostType
      type: System.Type
      description: "Il nome di una classe fornita dall&quot;utente da creare nel nuovo dominio applicazione."
    - id: virtualDir
      type: System.String
      description: "La directory virtuale per il dominio applicazione. ad esempio, /myapp."
    - id: physicalDir
      type: System.String
      description: "La directory fisica per il dominio applicazione in cui le pagine ASP.NET si trovano; ad esempio c:\\mypages.."
    return:
      type: System.Object
      description: "Un&quot;istanza di una classe fornita dall&quot;utente utilizzata per il marshalling delle chiamate nel dominio applicazione appena creato."
  overload: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  exceptions:
  - type: System.PlatformNotSupportedException
    commentId: T:System.PlatformNotSupportedException
    description: "Il computer host Web non è in esecuzione la piattaforma di Windows NT o un ambiente Coriolis."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.PlatformNotSupportedException
  isExternal: true
  name: System.PlatformNotSupportedException
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost
  nameWithType: ApplicationHost.CreateApplicationHost
