### YamlMime:ManagedReference
items:
- uid: System.Configuration.IriParsingElement
  id: IriParsingElement
  children:
  - System.Configuration.IriParsingElement.#ctor
  - System.Configuration.IriParsingElement.Enabled
  - System.Configuration.IriParsingElement.Properties
  langs:
  - csharp
  name: IriParsingElement
  nameWithType: IriParsingElement
  fullName: System.Configuration.IriParsingElement
  type: Class
  summary: "Fornisce l&quot;impostazione di configurazione per identificatore IRI (International Resource) l&quot;elaborazione nel &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) basati su RFC 3987.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       L&quot;impostazione di configurazione per il IriParsingElement verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: 'public sealed class IriParsingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: System.Configuration.IriParsingElement.IriParsingElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> classe."
  remarks: "Questo costruttore crea un <xref:System.Configuration.IriParsingElement>istanza.</xref:System.Configuration.IriParsingElement>"
  syntax:
    content: public IriParsingElement ();
    parameters: []
  overload: System.Configuration.IriParsingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.Enabled
  id: Enabled
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: System.Configuration.IriParsingElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene o imposta il valore di <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> impostazione di configurazione."
  remarks: "L&quot; <xref:System.Configuration.IriParsingElement>elaborazione della configurazione impostazione controlli IRI nella <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Questa impostazione controlla inoltre indirettamente nome IDN (International Domain) l&quot;elaborazione di set con la <xref:System.Configuration.IdnElement?displayProperty=fullName>classe.</xref:System.Configuration.IdnElement?displayProperty=fullName> Elaborazione IRI deve essere abilitato per l&quot;elaborazione possibili IDN. Se l&quot;elaborazione di IRI è disabilitata, elaborazione IDN verrà configurata l&quot;impostazione predefinita, in cui viene utilizzato il comportamento di .NET Framework 2.0 per la compatibilità e non vengono utilizzati i nomi IDN.       L&quot;impostazione di configurazione per il <xref:System.Configuration.IriParsingElement>verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "Valore booleano che indica se è abilitato l&quot;elaborazione di identificatore IRI (International Resource)."
  overload: System.Configuration.IriParsingElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.Properties
  id: Properties
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: System.Configuration.IriParsingElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Configuration.IriParsingElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.IriParsingElement.#ctor
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: System.Configuration.IriParsingElement.IriParsingElement()
- uid: System.Configuration.IriParsingElement.Enabled
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: System.Configuration.IriParsingElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IriParsingElement.Properties
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: System.Configuration.IriParsingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IriParsingElement.#ctor*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement
  nameWithType: IriParsingElement.IriParsingElement
- uid: System.Configuration.IriParsingElement.Enabled*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
- uid: System.Configuration.IriParsingElement.Properties*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
