### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.IApplicationTrustManager
  id: IApplicationTrustManager
  children:
  - System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  langs:
  - csharp
  name: IApplicationTrustManager
  nameWithType: IApplicationTrustManager
  fullName: System.Security.Policy.IApplicationTrustManager
  type: Interface
  summary: "Determina se è necessario eseguire un&quot;applicazione e il set di autorizzazioni deve essere concessa."
  remarks: "Attendibilità Gestioni devono implementare l&quot;interfaccia IApplicationTrustManager. L&quot;host chiama il <xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>metodo per determinare se è necessario eseguire un&quot;applicazione e le autorizzazioni devono essere concesse all&quot;applicazione.</xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>       Nel [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)] e versioni successive, è presente un solo gestore di attendibilità, che può essere un&quot;implementazione personalizzata dell&quot;interfaccia IApplicationTrustManager. L&quot;implementazione predefinita trust manager richiede all&quot;utente l&quot;autorizzazione per installare l&quot;applicazione e di aumentare le autorizzazioni concesse all&quot;applicazione. Altre implementazioni potrebbero fornire esperienze utente diverso. Ad esempio, un&quot;implementazione potrebbe verificare un elenco di enterprise per le applicazioni attendibili anziché chiedere conferma all&quot;utente di quell&quot;informazione."
  example:
  - "The following example shows a simple implementation of IApplicationTrustManager.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/csharp/t-system.security.policy_3_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/visualbasic/t-system.security.policy_3_1.vb)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public interface IApplicationTrustManager : System.Security.ISecurityEncodable
  implements:
  - System.Security.ISecurityEncodable
  platform:
  - net462
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  id: DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  langs:
  - csharp
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Determina se è necessario eseguire un&quot;applicazione e il set di autorizzazioni deve essere concessa."
  remarks: "Il metodo DetermineApplicationTrust viene chiamato dall&quot;host per determinare se un&quot;applicazione deve essere eseguita e deve essere concesso il set di autorizzazioni. DetermineApplicationTrust restituisce un <xref:System.Security.Policy.ApplicationTrust>dell&quot;oggetto con un <xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A>set di proprietà che contiene un&quot;autorizzazione che rappresenta le autorizzazioni da concedere a ogni assembly in esecuzione all&quot;interno del contesto dell&quot;applicazione.</xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A> </xref:System.Security.Policy.ApplicationTrust> Le autorizzazioni concesse non si applicano agli assembly nella global assembly cache. Il <xref:System.Security.Policy.ApplicationTrust>oggetto dispone anche di un <xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A>proprietà che imposta il gestore di attendibilità per indicare se l&quot;applicazione deve essere considerato attendibile.</xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A> </xref:System.Security.Policy.ApplicationTrust> Se il gestore di attendibilità indica che l&quot;applicazione può essere considerato attendibile, l&quot;host è attiva l&quot;applicazione e concede relativi assembly il set di autorizzazioni specificato nel <xref:System.Security.Policy.ApplicationTrust>insieme.</xref:System.Security.Policy.ApplicationTrust>"
  example:
  - "The following example shows an implementation of the DetermineApplicationTrust method for a custom trust manager. This code example is part of a larger example provided for the <xref:System.Security.Policy.IApplicationTrustManager> interface.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/csharp/24b6db65-f82b-47e4-ac93-_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/visualbasic/24b6db65-f82b-47e4-ac93-_1.vb)]"
  syntax:
    content: public System.Security.Policy.ApplicationTrust DetermineApplicationTrust (ActivationContext activationContext, System.Security.Policy.TrustManagerContext context);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Il contesto di attivazione per l&quot;applicazione."
    - id: context
      type: System.Security.Policy.TrustManagerContext
      description: "Il contesto del gestore di attendibilità per l&quot;applicazione."
    return:
      type: System.Security.Policy.ApplicationTrust
      description: "Oggetto che contiene le decisioni di protezione sull&quot;applicazione."
  overload: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
- uid: System.Security.Policy.ApplicationTrust
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationTrust
  nameWithType: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Security.Policy.TrustManagerContext
  parent: System.Security.Policy
  isExternal: false
  name: TrustManagerContext
  nameWithType: TrustManagerContext
  fullName: System.Security.Policy.TrustManagerContext
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust
