### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: "Specifica dei nomi XML e il prefisso dello spazio dei nomi XML da utilizzare per un&quot;estensione di formato di descrizione del servizio all&quot;interno di una descrizione del servizio. Questa classe non può essere ereditata."
  remarks: "Un&quot;estensione di formato di descrizione del servizio estende la modalità di generazione di una descrizione del servizio per un servizio Web XML creato con ASP.NET. In particolare, un&quot;estensione di formato della descrizione di servizio aggiunge elementi XML per la descrizione del servizio. Ciò è utile quando un&quot;estensione SOAP viene compilata per l&quot;esecuzione sul lato client e server di un servizio Web XML, come informazioni sulle estensioni SOAP non viene inserite automaticamente nella descrizione del servizio. Se si aggiungono informazioni sull&quot;estensione SOAP alla descrizione del servizio, può interpretare in questo modo un client deve eseguire l&quot;estensione SOAP specifica. Un esempio di un&quot;estensione SOAP che deve essere eseguito nel client e server è un&quot;estensione SOAP di crittografia. Se un&quot;estensione SOAP di crittografia viene eseguita solo sul server e i valori vengono crittografati prima di inviarli al client, il client deve avere l&quot;estensione SOAP per decrittografare il messaggio SOAP in esecuzione. In caso contrario, il client non è possibile elaborare il valore restituito.       Utilizzare la procedura seguente per compilare un&quot;estensione di formato di descrizione del servizio: 1.  Creare una classe che deriva da <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Applicare un <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>alla classe e specificare i punti di estensione in cui è necessario eseguire l&quot;estensione di formato.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Facoltativamente, applicare un XmlFormatExtensionPointAttribute alla classe e specificare un membro all&quot;interno della classe di agire come un nuovo punto di estensione.      4.  Se si desidera, applicare un <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>alla classe e specificare il prefisso dello spazio dei nomi XML da associare agli elementi XML generati dall&quot;estensione di formato della descrizione del servizio.</xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>      5.  Configurare l&quot;estensione di formato per l&quot;esecuzione all&quot;interno di `serviceDescriptionFormatExtensionTypes` sezione del file di configurazione."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPointAttribute&quot;> </xref> classe."
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: "Il membro della classe che implementa l&quot;estensione di formato che può avere un&quot;estensione di formato della descrizione del servizio associata."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Ottiene o imposta un valore che indica se il membro della classe che implementa l&quot;estensione di formato specificato nella <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>proprietà può accettare elementi XML non elaborati.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>"
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il membro della classe che implementa la descrizione del servizio di estensione specificata formato di <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>proprietà può accettare elementi XML non elaborati; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Specifica che il membro della classe che implementa l&quot;estensione di formato di descrizione del servizio può avere un&quot;estensione di formato della descrizione del servizio associata."
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: "Il membro della classe che implementa l&quot;estensione di formato che può avere un&quot;estensione di formato della descrizione del servizio associata."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
