### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  id: WindowsServiceElement
  children:
  - System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  - System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  - System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  - System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  - System.ServiceModel.Configuration.WindowsServiceElement.Properties
  langs:
  - csharp
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica le impostazioni di una credenziale di servizio Windows. Questa classe non può essere ereditata."
  remarks: ''
  example:
  - <xref:System.ServiceModel.Security.WindowsServiceCredential>
  syntax:
    content: 'public sealed class WindowsServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WindowsServiceElement&quot;> </xref> classe."
  syntax:
    content: public WindowsServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  id: AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore booleano che specifica se utenti anonimi possono accedere."
  remarks: "Quando si utilizza credenziali del servizio Windows in un&quot;associazione, il sistema non consente l&quot;accesso anonimo per impostazione predefinita. Ciò significa che solo dominio o gruppo di lavoro autenticati gli utenti hanno accesso al sistema. È possibile utilizzare questa proprietà per consentire agli utenti anonimi, non autenticati di accedere al servizio. È necessario prestare attenzione quando si utilizza questa impostazione."
  syntax:
    content: public bool AllowAnonymousLogons { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se gli utenti anonimi possono accedere. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  id: Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia il contenuto dell&quot;elemento di configurazione specificato in questo elemento di configurazione."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsServiceElement
      description: "L&quot;elemento di configurazione da copiare."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Il file di configurazione è di sola lettura."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  id: IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che indica se i gruppi di Windows sono inclusi nel contesto di sicurezza."
  remarks: "Impostando questa proprietà su `true` ha un impatto sulle prestazioni poiché comporta un&quot;espansione completa del gruppo. Impostare questa proprietà su `false` se non è necessario stabilire l&quot;elenco di gruppi di un utente appartiene."
  syntax:
    content: public bool IncludeWindowsGroups { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se i gruppi di Windows sono inclusi nel contesto di sicurezza. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement.WindowsServiceElement
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy
  nameWithType: WindowsServiceElement.Copy
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
