### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebApplicationLevel
  id: WebApplicationLevel
  children:
  - System.Web.Configuration.WebApplicationLevel.AboveApplication
  - System.Web.Configuration.WebApplicationLevel.AtApplication
  - System.Web.Configuration.WebApplicationLevel.BelowApplication
  langs:
  - csharp
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
  type: Enum
  summary: "Specifica il livello di percorso di file di configurazione dell&quot;applicazione Web."
  remarks: "La classe WebApplicationLevel fornisce tre livelli che vengono utilizzati per distinguere in un file di configurazione in relazione a livello di radice di un&quot;applicazione Web ASP.NET. I tre tipi di livello di percorso sono AboveApplication AtApplication e BelowApplication."
  syntax:
    content: public enum WebApplicationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  id: AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che il file di configurazione è in una directory globale in relazione all&quot;applicazione Web ASP.NET corrente."
  syntax:
    content: AboveApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  id: AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che il file di configurazione sia nella directory radice dell&quot;applicazione Web ASP.NET corrente."
  syntax:
    content: AtApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  id: BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che il file di configurazione è in una sottodirectory dell&quot;applicazione Web ASP.NET corrente."
  syntax:
    content: BelowApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
