### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidatorAttribute
  id: StringValidatorAttribute
  children:
  - System.Configuration.StringValidatorAttribute.#ctor
  - System.Configuration.StringValidatorAttribute.InvalidCharacters
  - System.Configuration.StringValidatorAttribute.MaxLength
  - System.Configuration.StringValidatorAttribute.MinLength
  - System.Configuration.StringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute
  fullName: System.Configuration.StringValidatorAttribute
  type: Class
  summary: "Indica in modo dichiarativo a .NET Framework per eseguire la convalida delle stringhe in una proprietà di configurazione. Questa classe non può essere ereditata."
  remarks: "Utilizzare il StringValidatorAttribute per decorare una proprietà di configurazione. Viene utilizzata per indicare di .NET Framework per convalidare la proprietà utilizzando il <xref:System.Configuration.StringValidator>e passare il valore dei parametri di decorazione.</xref:System.Configuration.StringValidator>       È possibile applicare oggetti StringValidatorAttribute e solo i tipi di proprietà."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the StringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/t-system.configuration.s_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/t-system.configuration.s_1_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class StringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.StringValidatorAttribute&quot;> </xref> classe."
  remarks: "Utilizzare questo costruttore nel modello con gli attributi per assicurarsi che il valore assegnato alla proprietà dell&quot;elemento di configurazione è di tipo stringa."
  example:
  - "The following example shows how to use the StringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/visualbasic/m-system.configuration.s_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/csharp/m-system.configuration.s_2_1.cs)]"
  syntax:
    content: public StringValidatorAttribute ();
    parameters: []
  overload: System.Configuration.StringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  id: InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta i caratteri non validi per la proprietà."
  remarks: ''
  example:
  - "The following example shows how to use the InvalidCharacters property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_15_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_15_1.cs)]"
  syntax:
    content: public string InvalidCharacters { get; set; }
    return:
      type: System.String
      description: "Stringa che contiene il set di caratteri che non sono consentiti per la proprietà."
  overload: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  id: MaxLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta la lunghezza massima consentita per la stringa da assegnare alla proprietà."
  remarks: ''
  example:
  - "The following example shows how to use the MaxLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_8_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_8_1.cs)]"
  syntax:
    content: public int MaxLength { get; set; }
    return:
      type: System.Int32
      description: "Valore intero che indica la lunghezza massima consentita per la stringa da assegnare alla proprietà."
  overload: System.Configuration.StringValidatorAttribute.MaxLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore selezionato è minore di <xref:System.Configuration.StringValidatorAttribute.MinLength*>.</xref:System.Configuration.StringValidatorAttribute.MinLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MinLength
  id: MinLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il valore minimo consentito per la stringa da assegnare alla proprietà."
  remarks: ''
  example:
  - "The following example shows how to use the MinLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_12_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_12_1.cs)]"
  syntax:
    content: public int MinLength { get; set; }
    return:
      type: System.Int32
      description: "Valore intero che indica la lunghezza minima consentita per la stringa da assegnare alla proprietà."
  overload: System.Configuration.StringValidatorAttribute.MinLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore selezionato è maggiore di <xref:System.Configuration.StringValidatorAttribute.MaxLength*>.</xref:System.Configuration.StringValidatorAttribute.MaxLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un&quot;istanza di <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> classe."
  remarks: "Utilizzare la proprietà ValidatorInstance per eseguire la convalida delle stringhe chiamando il relativo <xref:System.Configuration.StringValidator.Validate%2A>metodo.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/visualbasic/p-system.configuration.s_4_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/csharp/p-system.configuration.s_4_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Una corrente <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> impostazioni in un <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> istanza del validator."
  overload: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.StringValidatorAttribute.#ctor
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidatorAttribute.MinLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidatorAttribute.#ctor*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute.StringValidatorAttribute
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
- uid: System.Configuration.StringValidatorAttribute.MaxLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
- uid: System.Configuration.StringValidatorAttribute.MinLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
