### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "Specifica le regole di elaborazione o opzioni di configurazione per un <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> classe."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che determina se gli autori che usano associato <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> per il contesto devono utilizzare le impostazioni della finestra di progettazione per la scrittura in modo esplicito di contenuto."
  remarks: "Questa impostazione viene eseguita una query internamente. Influisce sul comportamento seguente per il contesto che un <xref:System.Xaml.XamlObjectReader>passa a qualsiasi <xref:System.Xaml.XamlWriter>:-RequireExplicitContentVisibility il comportamento viene applicato solo per le proprietà in cui <xref:System.Xaml.XamlMember.IsWritePublic%2A>è `false`e quando un `ShouldSerialize` modello non è disponibile per il valore della proprietà.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      -Se l&quot;istruzione al primo punto è true e RequireExplicitContentVisibility `true`, le impostazioni della finestra di progettazione per stabilire se la proprietà scrive l&quot;output come contenuto o la proprietà viene considerata implicita. Accesso alle impostazioni della finestra di progettazione tramite le API interne nei servizi XAML di .NET Framework, è basato sulla lettura <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>dagli assembly di supporto.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> In questo caso, il codice interno verifica il valore <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>e scrive l&quot;output alla proprietà.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> In caso contrario, il contenuto viene considerato implicito.      -Se l&quot;istruzione al primo punto è `true`, e RequireExplicitContentVisibility è `false`, la proprietà viene sempre scritto l&quot;output, e <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>dagli assembly di supporto è irrilevante.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Per specificare che i writer che utilizzano questo contesto devono utilizzare le impostazioni della finestra di progettazione per la scrittura qualsiasi output del contenuto nei casi in cui <xref:System.Xaml.XamlMember.IsWritePublic*>segnala <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se le impostazioni della finestra di progettazione devono essere ignorate.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
