### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  id: X509InitiatorCertificateClientElement
  children:
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica un certificato utilizzato da un client per identificarsi. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class X509InitiatorCertificateClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.X509InitiatorCertificateClientElement&quot;> </xref> classe."
  syntax:
    content: public X509InitiatorCertificateClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  id: Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia il contenuto dell&quot;elemento di configurazione specificato in questo elemento di configurazione."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509InitiatorCertificateClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
      description: "L&quot;elemento di configurazione da copiare."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Il file di configurazione è di sola lettura."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta una stringa che specifica il valore da cercare nell&quot;archivio certificati x.&509;."
  remarks: "Il tipo di contenuto in questa proprietà deve soddisfare i requisiti dell&quot;oggetto specificato <xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType%2A>valore.</xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType%2A> Il valore predefinito è una stringa vuota."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Valore da cercare nell&quot;archivio certificati x.&509;."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che specifica che il percorso dell&quot;archivio certificati del client può utilizzare per convalidare il certificato del server."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "Oggetto <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref> che specifica il percorso dell&quot;archivio certificati client è possibile utilizzare per convalidare il certificato del server. Il valore predefinito è <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il nome dell&quot;archivio certificati x.&509; da aprire."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "Oggetto <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> che contiene il nome dell&quot;archivio certificati x.&509; da aprire."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il tipo di ricerca x.&509; da eseguire."
  remarks: "Il tipo contenuto in <xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue%2A>deve soddisfare i requisiti di questa proprietà.</xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "Oggetto <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> che specifica il tipo di ricerca x.&509; da eseguire."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy
  nameWithType: X509InitiatorCertificateClientElement.Copy
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
