### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthorizationSection
  id: AuthorizationSection
  children:
  - System.Web.Configuration.AuthorizationSection.#ctor
  - System.Web.Configuration.AuthorizationSection.PostDeserialize
  - System.Web.Configuration.AuthorizationSection.Properties
  - System.Web.Configuration.AuthorizationSection.Rules
  langs:
  - csharp
  name: AuthorizationSection
  nameWithType: AuthorizationSection
  fullName: System.Web.Configuration.AuthorizationSection
  type: Class
  summary: "Configura un&quot;autorizzazione di applicazione Web. Questa classe non può essere ereditata."
  remarks: "La classe AuthorizationSection fornisce un modo per accedere a livello di codice e di modificare il `authorization` sezione di un file di configurazione.       Questo tipo è parte di un gruppo che include il <xref:System.Web.Configuration.AuthorizationRule>, <xref:System.Web.Configuration.AuthorizationRuleCollection>e <xref:System.Web.Configuration.AuthorizationRuleAction>tipi.</xref:System.Web.Configuration.AuthorizationRuleAction> </xref:System.Web.Configuration.AuthorizationRuleCollection> </xref:System.Web.Configuration.AuthorizationRule>      > [!NOTE] > AuthorizationSection il possibile leggere e scrivere informazioni da e verso la sezione corrispondente del file di configurazione in base alla sezione proprietà <xref:System.Configuration.SectionInformation.AllowDefinition%2A>il cui valore è <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A>"
  example:
  - "The following code example shows how to obtain the AuthorizationSection object from the configuration file of an existing Web application. You can use this object to access its members. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security capability, it is recommended that you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authorization>  \n  <allow users=\"userName\" roles=\"admin\" verbs=\"post\" />  \n  <deny users=\"*\" verbs=\"post\"/>  \n</authorization>  \n```  \n  \n [!code-cs[System.Web.Configuration.Authorization#1](~/add/codesnippet/csharp/t-system.web.configurati_65_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#1](~/add/codesnippet/visualbasic/t-system.web.configurati_65_1.vb)]  \n  \n [!code-cs[System.Web.Configuration.Authorization#2](~/add/codesnippet/csharp/t-system.web.configurati_65_2.cs)]\n [!code-vb[System.Web.Configuration.Authorization#2](~/add/codesnippet/visualbasic/t-system.web.configurati_65_2.vb)]"
  syntax:
    content: 'public sealed class AuthorizationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: System.Web.Configuration.AuthorizationSection.AuthorizationSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;> </xref> classe utilizzando le impostazioni predefinite."
  remarks: "Il costruttore AuthorizationSection non deve essere utilizzato direttamente dal codice. Viene chiamato dal sistema di configurazione ASP.NET. Per ottenere un&quot;istanza di <xref:System.Web.Configuration.AuthorizationSection>classe utilizzando il <xref:System.Configuration.Configuration.GetSection%2A>(metodo).</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.AuthorizationSection>"
  syntax:
    content: public AuthorizationSection ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  id: PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: System.Web.Configuration.AuthorizationSection.PostDeserialize()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.Properties
  id: Properties
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: System.Web.Configuration.AuthorizationSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.AuthorizationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.Rules
  id: Rules
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: System.Web.Configuration.AuthorizationSection.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the <xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.AuthorizationRule&quot;></xref> rules."
  remarks: "La raccolta di regole restituita da questo metodo non fa riferimento ad alcun elemento effettivo nel file di configurazione sottostante. È un costrutto che consente di accedere facilmente alle regole in che esso contenute. Si tratta di un modello comune per la gestione degli elementi di un file di configurazione."
  example:
  - "The following code example shows how to use the Rules.  \n  \n [!code-cs[System.Web.Configuration.Authorization#6](~/add/codesnippet/csharp/p-system.web.configurati_248_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#6](~/add/codesnippet/visualbasic/p-system.web.configurati_248_1.vb)]"
  syntax:
    content: public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: "Ottiene il <xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;> </xref> di <xref href=&quot;System.Web.Configuration.AuthorizationRule&quot;> </xref> regole definite nella raccomandazione di <xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;> </xref>."
  overload: System.Web.Configuration.AuthorizationSection.Rules*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: System.Web.Configuration.AuthorizationSection.AuthorizationSection()
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: System.Web.Configuration.AuthorizationSection.PostDeserialize()
- uid: System.Web.Configuration.AuthorizationSection.Properties
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: System.Web.Configuration.AuthorizationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AuthorizationSection.Rules
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: System.Web.Configuration.AuthorizationSection.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.AuthorizationSection.#ctor*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection
  nameWithType: AuthorizationSection.AuthorizationSection
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize
  nameWithType: AuthorizationSection.PostDeserialize
- uid: System.Web.Configuration.AuthorizationSection.Properties*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
- uid: System.Web.Configuration.AuthorizationSection.Rules*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
