### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  id: ApplicationChangedEventArgs
  children:
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  langs:
  - csharp
  name: ApplicationChangedEventArgs
  nameWithType: ApplicationChangedEventArgs
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  type: Class
  summary: "Fornisce informazioni complete a un metodo di callback quando un <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication.ApplicationChanged&quot;> </xref> si verifica l&quot;evento."
  remarks: "Un <xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged>evento viene generato quando: - un peer avvia un&quot;applicazione all&quot;interno di una collaborazione - termina con un&quot;applicazione all&quot;interno di una collaborazione peer - il <xref:System.Net.PeerToPeer.Collaboration.PeerContact>oggetto che rappresenta un peer che collabora dispone di una modifica nelle relative proprietà, ad esempio il nome alternativo - l&quot;ambito dell&quot;applicazione viene modificato nel computer del contatto che peer - peer consente di spostare a un indirizzo IP diverso nella rete - ogni classe che utilizza la classe ApplicationChangedEventArgs richiede un <xref:System.Security.Permissions.PermissionState>su Unrestricted.</xref:System.Security.Permissions.PermissionState> </xref:System.Net.PeerToPeer.Collaboration.PeerContact> </xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged> Questo stato viene creato quando il <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>oggetto viene costruito.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>"
  syntax:
    content: 'public class ApplicationChangedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Ottiene il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> per cui è stato generato l&quot;evento."
  remarks: "Se non diversamente specificato, il valore predefinito per questa proprietà è `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "Il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> istanza che è stata aggiornata."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  id: PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Ottiene il tipo di modifica per il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> che si è verificato."
  remarks: "Se non diversamente specificato, il valore predefinito per questa proprietà è `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerChangeType PeerChangeType { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerChangeType
      description: "Il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerChangeType&quot;> </xref> valore di enumerazione che specifica il tipo di modifica è stata eseguita su di <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Ottiene il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> associato il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;></xref>associata con il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Ottiene l&quot;endpoint per il quale <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> informazioni sono state modificate."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "Il <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> che contiene l&quot;endpoint per l&quot;applicazione che sono state modificate informazioni. A meno che non venga specificato esplicitamente, il valore predefinito per tutte le proprietà è <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> per i tipi di riferimento e zero (0) per le proprietà di tipo <xref uid=&quot;langword_csharp_int&quot; name=&quot;int&quot; href=&quot;&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerChangeType
  nameWithType: PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
