### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.OutputCacheSettingsSection
  id: OutputCacheSettingsSection
  children:
  - System.Web.Configuration.OutputCacheSettingsSection.#ctor
  - System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  - System.Web.Configuration.OutputCacheSettingsSection.Properties
  langs:
  - csharp
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
  type: Class
  summary: "Configura le impostazioni della cache di output per le pagine dell&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "La classe OutputCacheSettingsSection consente di accedere a livello di codice e di modificare il `outputCacheSettings` elemento del `caching` sezione in un file di configurazione. Le dipendenze di definire le impostazioni della cache di output (le relazioni tra gli elementi memorizzati nella cache e i file, chiavi della cache, o <xref:System.Web.Caching.CacheDependency>oggetti), utilizzate per la memorizzazione nella cache di output, ad esempio, per il [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direttiva o da <xref:System.Web.Configuration.OutputCacheProfile>.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Caching.CacheDependency>      > [!NOTE] > OutputCacheSettingsSection il possibile scrivere informazioni nella relativa sezione del file di configurazione in base alle restrizioni definite dalla sezione proprietà <xref:System.Configuration.SectionInformation.AllowDefinition%2A>il cui valore è <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> Qualsiasi tentativo di scrivere in un file di configurazione a un livello non consentito nella gerarchia comporterà un messaggio di errore generato dal parser. Tuttavia, è possibile utilizzare questa classe per leggere le informazioni di configurazione a qualsiasi livello della gerarchia."
  example:
  - "The following code example shows how to obtain the OutputCacheSettingsSection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_9_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_9_1.vb)]"
  syntax:
    content: 'public sealed class OutputCacheSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> classe."
  remarks: "Il costruttore OutputCacheSettingsSection non deve essere utilizzato direttamente dal codice. Viene chiamato dal sistema di configurazione ASP.NET. Per ottenere un&quot;istanza di <xref:System.Web.Configuration.OutputCacheSettingsSection>classe utilizzando il <xref:System.Configuration.Configuration.GetSection%2A>(metodo).</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  syntax:
    content: public OutputCacheSettingsSection ();
    parameters: []
  overload: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  id: OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref>."
  remarks: "La proprietà OutputCacheProfiles consente di accedere a livello di codice il `outputCacheProfiles` elemento in un file di configurazione. È possibile utilizzare la proprietà OutputCacheProfiles per modificare il `outputCacheProfiles` elemento a livello di codice.       Il `outputCacheProfiles` sezione <xref:System.Web.Configuration.OutputCacheProfile>gli oggetti che rappresentano l&quot;output nella cache le impostazioni che possono essere utilizzate dalle pagine dell&quot;applicazione.</xref:System.Web.Configuration.OutputCacheProfile>  Queste impostazioni possono essere applicate a una pagina impostando la `CacheProfile` attributo del [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direttiva. Applicare il profilo per controllare la memorizzazione nella cache gli attributi, ad esempio le dipendenze, percorso della cache e data di scadenza della cache.       Il [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direttiva può eseguire l&quot;override di tutte le impostazioni incluse in un <xref:System.Web.Configuration.OutputCacheProfile>ad eccezione di <xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A>proprietà.</xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A> </xref:System.Web.Configuration.OutputCacheProfile> In questo modo è possibile abilitare o disabilitare il <xref:System.Web.Configuration.OutputCacheProfile>senza dover modificare le direttive in tutte le pagine che potrebbe essere stato eseguito l&quot;override tale</xref:System.Web.Configuration.OutputCacheProfile> viene"
  example:
  - "The following code example shows how to use the OutputCacheProfiles property.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_105_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_105_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheProfileCollection OutputCacheProfiles { get; }
    return:
      type: System.Web.Configuration.OutputCacheProfileCollection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.OutputCacheProfile&quot;></xref> objects"
  overload: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheProfileCollection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheProfileCollection
  nameWithType: OutputCacheProfileCollection
  fullName: System.Web.Configuration.OutputCacheProfileCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
