### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ExpressionBuilder
  id: ExpressionBuilder
  children:
  - System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  - System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  - System.Web.Configuration.ExpressionBuilder.Properties
  - System.Web.Configuration.ExpressionBuilder.Type
  langs:
  - csharp
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder
  fullName: System.Web.Configuration.ExpressionBuilder
  type: Class
  summary: "Recupera una risorsa dinamica durante la compilazione."
  remarks: "ASP.NET valuta automaticamente le espressioni durante l&quot;analisi delle pagine utilizzando la classe ExpressionBuilder. Il <xref:System.Web.Configuration.ExpressionBuilderCollection>raccolta, è costituito il `expressionBuilders` elementi contenuti nel `compilation` sezione della configurazione.</xref:System.Web.Configuration.ExpressionBuilderCollection> Il ExpressionBuilder contiene valori specifici in coppie chiave/valore.       Un valore viene recuperato includendo un&quot;espressione nel formato `<%$ ExpressionPrefix: ExpressionKey %>` all&quot;interno della pagina. Il `ExpressionPrefix` il tipo dell&quot;espressione devono essere recuperate come tipo comune un generatore di espressioni esegue il mapping (ovvero, <xref:System.Web.Compilation.AppSettingsExpressionBuilder>) o un tipo di generatore di espressioni personalizzate.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> Il `ExpressionKey` specifica la chiave utilizzata per fare riferimento al valore restituito.       Se si sceglie di implementare un tipo di generatore di espressioni comuni, è necessario mappare il generatore di espressioni per il nome di sezione associato nella configurazione. Se si sceglie di implementare un tipo di generatore di espressioni personalizzate, è necessario eseguire il mapping del generatore di espressioni alla classe del generatore di espressioni personalizzate, che deve derivare dalla classe ExpressionBuilder."
  syntax:
    content: 'public sealed class ExpressionBuilder : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionBuilder(String,String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String,String)
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionBuilder(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.ExpressionBuilder&quot;> </xref> classe."
  remarks: ''
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.ExpressionBuilder> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ExpressionBuilderCollection> class.  \n  \n [!code-cs[System.Web.Configuration.ExpressionBuilderCollection#2](~/add/codesnippet/csharp/e711f1b6-36ca-4643-bdf7-_1.cs)]\n [!code-vb[System.Web.Configuration.ExpressionBuilderCollection#2](~/add/codesnippet/visualbasic/e711f1b6-36ca-4643-bdf7-_1.vb)]"
  syntax:
    content: public ExpressionBuilder (string expressionPrefix, string theType);
    parameters:
    - id: expressionPrefix
      type: System.String
      description: "Stringa che identifica il tipo dell&quot;espressione da recuperare."
    - id: theType
      type: System.String
      description: "Stringa che specifica il tipo dell&quot;espressione."
  overload: System.Web.Configuration.ExpressionBuilder.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  id: ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta una stringa che identifica il tipo dell&quot;espressione da recuperare."
  remarks: "Il ExpressionPrefix l&quot;espressione viene eseguito il mapping al nome di sezione associato nella configurazione per i tipi di espressioni comuni o l&quot;espressione viene eseguito il mapping alla classe di espressioni personalizzato."
  syntax:
    content: public string ExpressionPrefix { get; set; }
    return:
      type: System.String
      description: "Stringa che identifica il tipo dell&quot;espressione da recuperare."
  overload: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  id: Properties
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: System.Web.Configuration.ExpressionBuilder.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.ExpressionBuilder.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ExpressionBuilder.Type
  id: Type
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: System.Web.Configuration.ExpressionBuilder.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta una stringa che specifica il tipo dell&quot;espressione."
  remarks: "Il tipo specifica il tipo di oggetto utilizzato per determinare il valore dell&quot;espressione. Il tipo può specificare una sezione all&quot;interno della configurazione o una classe personalizzata."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Stringa che specifica il tipo dell&quot;espressione."
  overload: System.Web.Configuration.ExpressionBuilder.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder(String,String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String,String)
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionBuilder(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: System.Web.Configuration.ExpressionBuilder.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ExpressionBuilder.Type
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: System.Web.Configuration.ExpressionBuilder.Type
- uid: System.Web.Configuration.ExpressionBuilder.#ctor*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder.ExpressionBuilder
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
- uid: System.Web.Configuration.ExpressionBuilder.Properties*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
- uid: System.Web.Configuration.ExpressionBuilder.Type*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
