### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  id: WorkflowInstanceQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States
  langs:
  - csharp
  name: WorkflowInstanceQueryElement
  nameWithType: WorkflowInstanceQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  type: Class
  summary: "Un elemento di configurazione che rappresenta un <xref href=&quot;System.Activities.Tracking.WorkflowInstanceQuery&quot;> </xref>."
  syntax:
    content: 'public class WorkflowInstanceQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  langs:
  - csharp
  name: WorkflowInstanceQueryElement()
  nameWithType: WorkflowInstanceQueryElement.WorkflowInstanceQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.WorkflowInstanceQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement&quot;> </xref> classe."
  syntax:
    content: public WorkflowInstanceQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: WorkflowInstanceQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Crea un nuovo <xref href=&quot;System.Activities.Tracking.WorkflowInstanceQuery&quot;> </xref> istanza."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "Una nuova query di istanza del flusso di lavoro."
  overload: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: WorkflowInstanceQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene la raccolta di proprietà."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "La raccolta di proprietà per l&quot;elemento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States
  id: States
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  langs:
  - csharp
  name: States
  nameWithType: WorkflowInstanceQueryElement.States
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gli stati del flusso di lavoro che la query filtrerà in."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection States { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
      description: "Gli stati da filtrare."
  overload: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: WorkflowInstanceQueryElement()
  nameWithType: WorkflowInstanceQueryElement.WorkflowInstanceQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.WorkflowInstanceQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: WorkflowInstanceQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowInstanceQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: States
  nameWithType: WorkflowInstanceQueryElement.States
  fullName: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: StateElementCollection
  nameWithType: StateElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: WorkflowInstanceQueryElement
  nameWithType: WorkflowInstanceQueryElement.WorkflowInstanceQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: WorkflowInstanceQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowInstanceQueryElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement.States*
  parent: System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement
  isExternal: false
  name: States
  nameWithType: WorkflowInstanceQueryElement.States
