### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  id: ScriptingScriptResourceHandlerSection
  children:
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  langs:
  - csharp
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  type: Class
  summary: "Rappresenta un <xref uid=&quot;langword_csharp_ScriptingScriptResourceHandler&quot; name=&quot;ScriptingScriptResourceHandler&quot; href=&quot;&quot;> </xref> sezione di configurazione di <xref uid=&quot;langword_csharp_&lt;scripting&gt;&quot; name=&quot;&lt;scripting&gt;&quot; href=&quot;&quot;> </xref> elemento del file di configurazione. Questa classe non può essere ereditata."
  remarks: "Questo tipo consente di ottenere o impostare la memorizzazione nella cache o la compressione è abilitata per i file di ECMAScript (JavaScript) che vengono incorporati come risorse in un assembly."
  syntax:
    content: 'public sealed class ScriptingScriptResourceHandlerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: ScriptingScriptResourceHandlerSection()
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;> </xref> classe."
  syntax:
    content: public ScriptingScriptResourceHandlerSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  id: EnableCaching
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta se la memorizzazione nella cache è abilitata per i file di script incorporati come risorse in un assembly."
  remarks: "La proprietà EnableCaching Ottiene o imposta il valore per la memorizzazione nella cache i risultati del file di script incorporati, per la memorizzazione nella cache gli oggetti di localizzazione potenziali e per la memorizzazione nella cache di script."
  syntax:
    content: public bool EnableCaching { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la memorizzazione nella cache è abilitata per i file di script incorporati come risorse in un assembly. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  id: EnableCompression
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta se la compressione è abilitata per i file di script incorporati come risorse in un assembly."
  remarks: "EnableCompression-proprietà ottiene o imposta il valore che indica se verranno compresso, le operazioni seguenti:-file incorporati come risorse in un assembly di Script.      -Oggetti localizzazione, quali le risorse di stringa contenuti in un file di risorse (resx).      -Script che vengono fornito dal gestore di risorse di script.      > [!NOTE] > Se il browser richiedente non supporta la compressione, questa proprietà ha effetto."
  syntax:
    content: public bool EnableCompression { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la compressione è abilitata per i file di script incorporati come risorse in un assembly. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: ScriptingScriptResourceHandlerSection()
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
