### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  id: MsmqIntegrationSecurity
  children:
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  type: Class
  summary: "La classe MsmqIntegrationSecurity incapsula le impostazioni di sicurezza del trasporto per il canale di integrazione di Accodamento messaggi (MSMQ)."
  remarks: "Il canale di integrazione di Accodamento messaggi consente [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] alle applicazioni di comunicare con le applicazioni di Accodamento messaggi esistenti."
  syntax:
    content: public sealed class MsmqIntegrationSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Inizializza una nuova istanza della <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity&quot;> </xref>."
  syntax:
    content: public MsmqIntegrationSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  id: Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> associato al canale di integrazione di Accodamento messaggi (MSMQ)."
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>è un&quot;enumerazione che contiene i seguenti valori: <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>e <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> Il valore predefinito è <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "Il <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> associato al canale di integrazione di Accodamento messaggi."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  id: Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Ottiene il <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> associato al canale di integrazione di Accodamento messaggi (MSMQ)."
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>incapsula le impostazioni di sicurezza per il trasporto di integrazione di Accodamento messaggi.</xref:System.ServiceModel.MsmqTransportSecurity> Le impostazioni sono gli stessi per l&quot;integrazione di Accodamento messaggi e trasporti in coda. <xref:System.ServiceModel.MsmqTransportSecurity>Consente di impostare la modalità di autenticazione, l&quot;algoritmo di crittografia, Secure Hash Algorithm e livello di protezione.</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "Il <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> associato al canale di integrazione di Accodamento messaggi."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
