### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAttribute
  id: EnvironmentPermissionAttribute
  children:
  - System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Security.Permissions.EnvironmentPermissionAttribute.All
  - System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  - System.Security.Permissions.EnvironmentPermissionAttribute.Read
  - System.Security.Permissions.EnvironmentPermissionAttribute.Write
  langs:
  - csharp
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute
  type: Class
  summary: "Consente di azioni di sicurezza per <xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref> da applicare al codice usando la sicurezza dichiarativa. Questa classe non può essere ereditata."
  remarks: "L&quot;ambito della dichiarazione che è consentita dipende il <xref:System.Security.Permissions.SecurityAction>utilizzato.</xref:System.Security.Permissions.SecurityAction>       Le informazioni di sicurezza dichiarate da un attributo di sicurezza viene archiviate nei metadati dell&quot;attributo di destinazione e si accedono dal sistema in fase di esecuzione. Gli attributi di sicurezza vengono utilizzati solo per la sicurezza dichiarativa. Per la sicurezza imperativa, utilizzare la classe dell&quot;autorizzazione corrispondente.       I nomi delle variabili di ambiente sono tra maiuscole e minuscole. Vengono specificati più nomi di variabili di ambiente separando i nomi utilizzando <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Constructor | System.AttributeTargets.Method, AllowMultiple=true, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Security.Permissions.EnvironmentPermissionAttribute&quot;> </xref> classe con l&quot;oggetto specificato <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>."
  syntax:
    content: public EnvironmentPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: "Uno del <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref> valori."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Il <code> action </code> parametro non è un valore valido di <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>."
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  id: All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Imposta l&quot;accesso completo per le variabili di ambiente specificata dal valore di stringa."
  remarks: "I nomi delle variabili di ambiente sono tra maiuscole e minuscole. Vengono specificati più nomi di variabili di ambiente separando i nomi utilizzando <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string All { get; set; }
    return:
      type: System.String
      description: "Un elenco di variabili di ambiente per l&quot;accesso completo."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Il metodo get non è supportato per questa proprietà."
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Crea e restituisce un nuovo <xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref>."
  remarks: "Questo metodo deve essere chiamato solo dal sistema di sicurezza, mai dal codice dell&quot;applicazione.       In fase di compilazione, gli attributi convertono le dichiarazioni di sicurezza in un formato serializzato nei metadati. Dati di sicurezza dichiarativa nei metadati vengono creati dall&quot;autorizzazione restituita dal metodo che corrisponde a questo attributo."
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: "Un <xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref> che corrisponde a questo attributo."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Ottiene o imposta l&quot;accesso in lettura per le variabili di ambiente specificata dal valore di stringa."
  remarks: "I nomi delle variabili di ambiente sono tra maiuscole e minuscole. Vengono specificati più nomi di variabili di ambiente separando i nomi utilizzando <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string Read { get; set; }
    return:
      type: System.String
      description: "Un elenco di variabili di ambiente per l&quot;accesso in lettura."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Ottiene o imposta l&quot;accesso in scrittura per le variabili di ambiente specificata dal valore di stringa."
  remarks: "I nomi delle variabili di ambiente sono tra maiuscole e minuscole. Vengono specificati più nomi di variabili di ambiente separando i nomi utilizzando <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string Write { get; set; }
    return:
      type: System.String
      description: "Un elenco di variabili di ambiente per l&quot;accesso in scrittura."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: EnvironmentPermissionAttribute.CreatePermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
