### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  id: Vector3DCollectionValueSerializer
  children:
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: Vector3DCollectionValueSerializer
  nameWithType: Vector3DCollectionValueSerializer
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  type: Class
  summary: "Converte istanze di <xref:System.String>in e da istanze di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref>.</xref:System.String>"
  remarks: "Questa classe solo deve essere utilizzata dal <xref:System.Windows.Markup.Primitives.MarkupWriter>per scopi di serializzazione.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class Vector3DCollectionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: Vector3DCollectionValueSerializer()
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer&quot;> </xref> classe."
  syntax:
    content: public Vector3DCollectionValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Determina se la conversione da un determinato <xref:System.String>a un&quot;istanza di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> è possibile.</xref:System.String>"
  remarks: "Questo metodo restituisce sempre `true`."
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Stringa da valutare per la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il valore può essere convertito; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Determina se un&quot;istanza di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> può essere convertito in un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Istanza di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> per valutare la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <code> value </code> può essere convertito in un <xref:System.String>; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Converte un <xref:System.String>in un <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>valore da convertire in un <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref>.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Object
      description: "Una nuova istanza della <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> in base al parametro <code> value </code>."
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Converte un&quot;istanza di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> a un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Istanza di <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> per valutare la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.String
      description: "Oggetto <xref:System.String>rappresentazione dell&quot;oggetto specificato <xref href=&quot;System.Windows.Media.Media3D.Vector3DCollection&quot;> </xref> oggetto.</xref:System.String>"
  overload: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: Vector3DCollectionValueSerializer()
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer()
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.#ctor*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: Vector3DCollectionValueSerializer
  nameWithType: Vector3DCollectionValueSerializer.Vector3DCollectionValueSerializer
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: Vector3DCollectionValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: Vector3DCollectionValueSerializer.CanConvertToString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: Vector3DCollectionValueSerializer.ConvertFromString
- uid: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer.ConvertToString*
  parent: System.Windows.Media.Media3D.Converters.Vector3DCollectionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: Vector3DCollectionValueSerializer.ConvertToString
