### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  id: ProfileElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  langs:
  - csharp
  name: ProfileElement
  nameWithType: ProfileElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  type: Class
  summary: "Un elemento di configurazione che rappresenta un <xref href=&quot;System.Activities.Tracking.TrackingProfile&quot;> </xref> e viene utilizzato per l&quot;aggiunta di un profilo tramite l&quot;elemento di comportamento."
  syntax:
    content: 'public class ProfileElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;> </xref> classe."
  syntax:
    content: public ProfileElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene una chiave che identifica in modo univoco il profilo."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "Chiave dell&quot;elemento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  id: ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta la modalità di visibilità del profilo di rilevamento."
  remarks: "I record di rilevamento delle attività che formano l&quot;implementazione delle attività possono essere filtrati utilizzando la modalità di visibilità descritte da <xref:System.Activities.Tracking.ImplementationVisibility>.</xref:System.Activities.Tracking.ImplementationVisibility> Questo flag viene utilizzato per la sottoscrizione di record per tutte le attività o solo per le attività visibili dalla radice del flusso di lavoro di rilevamento.       Quando il flag è impostato su <xref:System.Activities.Tracking.ImplementationVisibility>, vengono rilevate solo l&quot;attività radice e la relativa implementazione.</xref:System.Activities.Tracking.ImplementationVisibility> Se l&quot;implementazione contiene attività che costituiscono attività composte, quindi l&quot;attività composta viene rilevata, ma non la relativa implementazione.       Per ulteriori informazioni, vedere <xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>.</xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>"
  syntax:
    content: public System.Activities.Tracking.ImplementationVisibility ImplementationVisibility { get; set; }
    return:
      type: System.Activities.Tracking.ImplementationVisibility
      description: "La modalità di visibilità del profilo di rilevamento"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta il nome del profilo di rilevamento."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Il nome del profilo di rilevamento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> che contiene le proprietà associate a questo elemento."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Raccolta di proprietà."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  id: Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene la raccolta di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement&quot;> </xref> gli elementi associati a questo <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;> </xref>."
  remarks: "È presente <xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>per ogni flusso di lavoro nel profilo.</xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>"
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection Workflows { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
      description: "Raccolta di elementi della query profilo flusso di lavoro."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
- uid: System.Activities.Tracking.ImplementationVisibility
  parent: System.Activities.Tracking
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ImplementationVisibility
  fullName: System.Activities.Tracking.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileWorkflowElementCollection
  nameWithType: ProfileWorkflowElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement
  nameWithType: ProfileElement.ProfileElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
