### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceSection
  id: XhtmlConformanceSection
  children:
  - System.Web.Configuration.XhtmlConformanceSection.#ctor
  - System.Web.Configuration.XhtmlConformanceSection.Mode
  - System.Web.Configuration.XhtmlConformanceSection.Properties
  langs:
  - csharp
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection
  fullName: System.Web.Configuration.XhtmlConformanceSection
  type: Class
  summary: "Configura il <xref uid=&quot;langword_csharp_xhtmlConformance&quot; name=&quot;xhtmlConformance&quot; href=&quot;&quot;> </xref> sezione. Questa classe non può essere ereditata."
  remarks: "La classe XhtmlConformanceSection fornisce un modo per accedere a livello di codice e di modificare il `xhtmlConformance` sezione di un file di configurazione.      > [!NOTE] > ASP.NET consente di creare pagine Web che sono conformi agli standard XHTML 1.1. Per ulteriori informazioni sugli standard XHTML 1.1, vedere il sito di W3C. Per impostazione predefinita, quando utilizzano i browser che supportano HTML 4.0 o versione successiva, pagine e controlli ASP.NET eseguono il rendering di markup compatibile con lo standard XHTML 1.0 Transitional. Tuttavia, in alcuni casi, può essere opportuno non ASP.NET per il rendering del markup XHTML. Questo vale in genere quando si dispone di pagine esistenti che si basano su tag o attributi che normalmente non consentiti in XHTML."
  syntax:
    content: 'public sealed class XhtmlConformanceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.XhtmlConformanceSection&quot;> </xref> classe utilizzando i parametri predefiniti."
  remarks: "Il costruttore XhtmlConformanceSection non deve essere utilizzato direttamente dal codice. Viene chiamato dal sistema di configurazione ASP.NET. Per ottenere un&quot;istanza di <xref:System.Web.Configuration.XhtmlConformanceSection>classe utilizzando il <xref:System.Configuration.Configuration.GetSection%2A>(metodo).</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.XhtmlConformanceSection>"
  syntax:
    content: public XhtmlConformanceSection ();
    parameters: []
  overload: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  id: Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta la proprietà Mode."
  remarks: "Per impostazione predefinita, quando utilizzano i browser che supportano HTML 4.0 o versione successiva, pagine e controlli ASP.NET eseguono il rendering di markup compatibile con lo standard XHTML 1.0 Transitional. Tuttavia, in alcuni casi, può essere opportuno non ASP.NET per il rendering del markup XHTML. Questo vale in genere quando si dispone di pagine esistenti che si basano su tag o attributi che normalmente non consentiti in XHTML."
  syntax:
    content: public System.Web.Configuration.XhtmlConformanceMode Mode { get; set; }
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Uno del <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref> valori. Il valore predefinito è <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref>."
  overload: System.Web.Configuration.XhtmlConformanceSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  id: Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.XhtmlConformanceSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
