### YamlMime:ManagedReference
items:
- uid: System.Web.Management.WebApplicationInformation
  id: WebApplicationInformation
  children:
  - System.Web.Management.WebApplicationInformation.ApplicationDomain
  - System.Web.Management.WebApplicationInformation.ApplicationPath
  - System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  - System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  - System.Web.Management.WebApplicationInformation.MachineName
  - System.Web.Management.WebApplicationInformation.ToString
  - System.Web.Management.WebApplicationInformation.TrustLevel
  langs:
  - csharp
  name: WebApplicationInformation
  nameWithType: WebApplicationInformation
  fullName: System.Web.Management.WebApplicationInformation
  type: Class
  summary: "Vengono fornite informazioni associate agli eventi."
  remarks: "Il monitoraggio dello stato ASP.NET consente di produzione e lo staff operativo per la gestione di applicazioni Web distribuite. Il <xref:System.Web.Management?displayProperty=fullName>dello spazio dei nomi contiene i tipi di evento di stato responsabili per comprimere i dati di stato di integrità dell&quot;applicazione e i tipi di provider responsabili dell&quot;elaborazione dei dati.</xref:System.Web.Management?displayProperty=fullName> Contiene inoltre i tipi di supporto che semplificano la gestione degli eventi di integrità.       Le istanze della classe WebApplicationInformation contengono informazioni ottenute tramite uno qualsiasi dei tipi derivati dal <xref:System.Web.Management.WebManagementEvent>tipo.</xref:System.Web.Management.WebManagementEvent>       L&quot;applicazione richiede le autorizzazioni appropriate per accedere a informazioni protette fornite da questo tipo.       Di seguito è una porzione di un file di configurazione che è possibile utilizzare per abilitare ASP.NET per registrare gli eventi di errore contenenti informazioni sull&quot;applicazione.      ```   <healthMonitoring      enabled=&quot;true&quot; heartBeatInterval=&quot;0&quot;>          <rules>        <add           name=&quot;All Errors Default&quot;          eventName=&quot;All Errors&quot;          provider=&quot;EventLogProvider&quot;          profile=&quot;Default&quot;          minInterval=&quot;00:01:00&quot; />       </rules>      </healthMonitoring>   ```      > [!NOTE]> Nella maggior parte dei casi sarà possibile utilizzare i tipi di monitoraggio dello stato ASP.NET, come implementato e controllare il sistema di monitoraggio dello stato specificando i valori di `healthMonitoring` sezione di configurazione. È anche possibile derivare da tipi di monitoraggio dello stato per creare eventi personalizzati e i provider. Per un esempio di creazione di una classe di evento personalizzato, vedere l&quot;esempio fornito in questo argomento."
  example:
  - "The following code example has two parts. The first part is an excerpt of the configuration file that enables ASP.NET to use a custom event. The second shows how to create that custom event by using the WebApplicationInformation class.  \n  \n Ensure that your custom event is raised at the proper time, that is, when the equivalent system health event it replaces would be raised.  \n  \n```  \n<healthMonitoring   \n  enabled=\"true\" heartBeatInterval=\"0\">  \n  \n  <eventMappings>   \n    <add name=\"SampleApplicationInformation\"   \n        type=\"SamplesAspNet.SampleWebApplicationInformation, webapplicationinformation, Version=1.0.1585.27289, Culture=neutral, PublicKeyToken=3648e5c763a8239f, processorArchitecture=MSIL\"/>   \n  </eventMappings>  \n  \n  <rules>   \n    <add name=\"Custom Application Information\"  \n      eventName=\"SampleApplicationInformation\"   \n      provider=\"EventLogProvider\"    \n      profile=\"Default\"/>   \n</rules>  \n  \n</healthMonitoring>  \n```  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#1](~/add/codesnippet/visualbasic/t-system.web.management._26_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#1](~/add/codesnippet/csharp/t-system.web.management._26_1.cs)]"
  syntax:
    content: public sealed class WebApplicationInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain
  id: ApplicationDomain
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
  fullName: System.Web.Management.WebApplicationInformation.ApplicationDomain
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Ottiene il nome di dominio applicazione corrente."
  remarks: ''
  example:
  - "The following code example shows how to obtain the application domain name.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#4](~/add/codesnippet/visualbasic/p-system.web.management._46_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#4](~/add/codesnippet/csharp/p-system.web.management._46_1.cs)]"
  syntax:
    content: public string ApplicationDomain { get; }
    return:
      type: System.String
      description: "Ottiene il nome di dominio dell&quot;applicazione."
  overload: System.Web.Management.WebApplicationInformation.ApplicationDomain*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath
  id: ApplicationPath
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Ottiene il percorso fisico dell&quot;applicazione."
  remarks: "Questa proprietà richiede le autorizzazioni appropriate per accedervi. Vedere la sezione autorizzazioni."
  example:
  - "The following code example shows how to obtain the application physical path.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#5](~/add/codesnippet/visualbasic/p-system.web.management._44_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#5](~/add/codesnippet/csharp/p-system.web.management._44_1.cs)]"
  syntax:
    content: public string ApplicationPath { get; }
    return:
      type: System.String
      description: "Il percorso fisico dell&quot;applicazione."
  overload: System.Web.Management.WebApplicationInformation.ApplicationPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  id: ApplicationVirtualPath
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Ottiene il percorso logico dell&quot;applicazione."
  remarks: ''
  example:
  - "The following code example shows how to obtain the application logical path.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#6](~/add/codesnippet/visualbasic/p-system.web.management._36_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#6](~/add/codesnippet/csharp/p-system.web.management._36_1.cs)]"
  syntax:
    content: public string ApplicationVirtualPath { get; }
    return:
      type: System.String
      description: "Il percorso logico dell&quot;applicazione."
  overload: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  id: FormatToString(System.Web.Management.WebEventFormatter)
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: FormatToString(WebEventFormatter)
  nameWithType: WebApplicationInformation.FormatToString(WebEventFormatter)
  fullName: System.Web.Management.WebApplicationInformation.FormatToString(WebEventFormatter)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Formatta le informazioni dell&quot;applicazione."
  remarks: "Il metodo FormatToString fornisce un modello uniforme per informazioni sugli eventi, che risulta utile se i dati dell&quot;evento devono essere registrati e successivamente presentati all&quot;utente. Viene chiamato internamente quando il provider richiama uno del <xref:System.Web.Management.WebBaseEvent.ToString%2A>metodi.</xref:System.Web.Management.WebBaseEvent.ToString%2A>      > [!NOTE] > Quando si formatta le informazioni di evento personalizzato per la visualizzazione, eseguire l&quot;override del metodo FormatToString anziché <xref:System.Web.Management.WebApplicationInformation.ToString%2A>metodo.</xref:System.Web.Management.WebApplicationInformation.ToString%2A> Evitare la sovrascrittura o manomissione delle informazioni di sistema riservati."
  example:
  - "The following code example shows how to format custom information.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#9](~/add/codesnippet/visualbasic/e7244ae1-98b8-46f8-b4c6-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#9](~/add/codesnippet/csharp/e7244ae1-98b8-46f8-b4c6-_1.cs)]"
  syntax:
    content: public void FormatToString (System.Web.Management.WebEventFormatter formatter);
    parameters:
    - id: formatter
      type: System.Web.Management.WebEventFormatter
      description: "Il <xref href=&quot;System.Web.Management.WebEventFormatter&quot;> </xref> che contiene le impostazioni di tabulazione e rientro utilizzate per formattare le informazioni sull&quot;evento di integrità del Web."
  overload: System.Web.Management.WebApplicationInformation.FormatToString*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.MachineName
  id: MachineName
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
  fullName: System.Web.Management.WebApplicationInformation.MachineName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Ottiene il nome del computer dell&quot;applicazione."
  remarks: ''
  example:
  - "The following code example shows how to obtain the machine name.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#7](~/add/codesnippet/visualbasic/p-system.web.management._25_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#7](~/add/codesnippet/csharp/p-system.web.management._25_1.cs)]"
  syntax:
    content: public string MachineName { get; }
    return:
      type: System.String
      description: "Il nome del computer in cui è in esecuzione l&quot;applicazione."
  overload: System.Web.Management.WebApplicationInformation.MachineName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.ToString
  id: ToString
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ToString()
  nameWithType: WebApplicationInformation.ToString()
  fullName: System.Web.Management.WebApplicationInformation.ToString()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Formatta le informazioni di evento per scopi di visualizzazione."
  remarks: "Il <xref:System.Web.Management.WebBaseEvent.ToString%2A>metodo formatta le informazioni sull&quot;evento chiamando il <xref:System.Web.Management.WebApplicationInformation.FormatToString%2A>metodo.</xref:System.Web.Management.WebApplicationInformation.FormatToString%2A> </xref:System.Web.Management.WebBaseEvent.ToString%2A>      > [!NOTE] > Quando si formatta le informazioni di evento personalizzato per la visualizzazione, eseguire l&quot;override di <xref:System.Web.Management.WebApplicationInformation.FormatToString%2A>metodo anziché il metodo ToString.</xref:System.Web.Management.WebApplicationInformation.FormatToString%2A> Evitare la sovrascrittura o manomissione delle informazioni di sistema riservati."
  example:
  - For an example of using the ToString method, see <xref:System.Web.Management.WebEventProvider>.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "Le informazioni sull&quot;evento."
  overload: System.Web.Management.WebApplicationInformation.ToString*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationInformation.TrustLevel
  id: TrustLevel
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
  fullName: System.Web.Management.WebApplicationInformation.TrustLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Ottiene il livello di attendibilità dell&quot;applicazione."
  remarks: "Questa proprietà richiede le autorizzazioni appropriate per accedervi. Vedere la sezione autorizzazioni."
  example:
  - "The following example shows how to obtain the application-trust-level information.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#8](~/add/codesnippet/visualbasic/p-system.web.management._2_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#8](~/add/codesnippet/csharp/p-system.web.management._2_1.cs)]"
  syntax:
    content: public string TrustLevel { get; }
    return:
      type: System.String
      description: "Il livello di attendibilità dell&quot;applicazione."
  overload: System.Web.Management.WebApplicationInformation.TrustLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
  fullName: System.Web.Management.WebApplicationInformation.ApplicationDomain
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationPath
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
- uid: System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: FormatToString(WebEventFormatter)
  nameWithType: WebApplicationInformation.FormatToString(WebEventFormatter)
  fullName: System.Web.Management.WebApplicationInformation.FormatToString(WebEventFormatter)
- uid: System.Web.Management.WebEventFormatter
  parent: System.Web.Management
  isExternal: false
  name: WebEventFormatter
  nameWithType: WebEventFormatter
  fullName: System.Web.Management.WebEventFormatter
- uid: System.Web.Management.WebApplicationInformation.MachineName
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
  fullName: System.Web.Management.WebApplicationInformation.MachineName
- uid: System.Web.Management.WebApplicationInformation.ToString
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ToString()
  nameWithType: WebApplicationInformation.ToString()
  fullName: System.Web.Management.WebApplicationInformation.ToString()
- uid: System.Web.Management.WebApplicationInformation.TrustLevel
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
  fullName: System.Web.Management.WebApplicationInformation.TrustLevel
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
- uid: System.Web.Management.WebApplicationInformation.FormatToString*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: FormatToString
  nameWithType: WebApplicationInformation.FormatToString
- uid: System.Web.Management.WebApplicationInformation.MachineName*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
- uid: System.Web.Management.WebApplicationInformation.ToString*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ToString
  nameWithType: WebApplicationInformation.ToString
- uid: System.Web.Management.WebApplicationInformation.TrustLevel*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
