### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAs
  id: SettingsSerializeAs
  children:
  - System.Configuration.SettingsSerializeAs.Binary
  - System.Configuration.SettingsSerializeAs.ProviderSpecific
  - System.Configuration.SettingsSerializeAs.String
  - System.Configuration.SettingsSerializeAs.Xml
  langs:
  - csharp
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
  type: Enum
  summary: "Determina lo schema di serializzazione utilizzato per archiviare le impostazioni dell&quot;applicazione."
  remarks: "Il SettingsSerializeAsenumeration viene utilizzata per specificare il meccanismo di serializzazione utilizzato dal provider di impostazioni applicazione per rendere persistenti i valori delle proprietà delle impostazioni dell&quot;applicazione. Ad esempio, il ttribute questa enumerazione viene utilizzata nel costruttore per richiedere che una proprietà o un gruppo di proprietà venga reso persistente utilizzando il meccanismo di serializzazione specificato."
  syntax:
    content: public enum SettingsSerializeAs
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Binary
  id: Binary
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "La proprietà delle impostazioni viene serializzata utilizzando la serializzazione di oggetti binari."
  syntax:
    content: Binary
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  id: ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Il provider di impostazioni ha una conoscenza implicita della proprietà o il relativo tipo e rileva un meccanismo di serializzazione appropriato. Spesso utilizzato per la serializzazione personalizzata."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.String
  id: String
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "La proprietà delle impostazioni è serializzata come testo normale."
  syntax:
    content: String
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Xml
  id: Xml
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "La proprietà delle impostazioni è serializzata come XML mediante la serializzazione XML."
  syntax:
    content: Xml
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsSerializeAs.Binary
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
- uid: System.Configuration.SettingsSerializeAs.String
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
- uid: System.Configuration.SettingsSerializeAs.Xml
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
