### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorBase
  id: ConfigurationValidatorBase
  children:
  - System.Configuration.ConfigurationValidatorBase.#ctor
  - System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  - System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  langs:
  - csharp
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
  type: Class
  summary: "Funge da classe base per la derivazione di una classe di convalida in modo che un valore di un oggetto può essere verificato."
  remarks: "La classe ConfigurationValidatorBase viene utilizzata per creare un validator personalizzato. Un validator personalizzato può essere utilizzato per verificare i valori di oggetto."
  syntax:
    content: public abstract class ConfigurationValidatorBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza un&quot;istanza di <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> classe."
  syntax:
    content: protected ConfigurationValidatorBase ();
    parameters: []
  overload: System.Configuration.ConfigurationValidatorBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se un oggetto può essere convalidato in base al tipo."
  syntax:
    content: public virtual bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Il tipo di oggetto."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il <code> type </code> valore del parametro corrisponde al valore previsto <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref>; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationValidatorBase.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se il valore di un oggetto è valido."
  remarks: "Un oggetto derivato dalla <xref:System.Configuration.ConfigurationValidatorBase>classe contiene i criteri necessari per convalidare un oggetto.</xref:System.Configuration.ConfigurationValidatorBase> I criteri vengono stabiliti quando viene creata un&quot;istanza della classe derivata. Oggetto da convalidare viene passato come parametro del metodo di convalida."
  syntax:
    content: public abstract void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Il valore dell&quot;oggetto."
  overload: System.Configuration.ConfigurationValidatorBase.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
- uid: System.Configuration.ConfigurationValidatorBase.#ctor*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate
  nameWithType: ConfigurationValidatorBase.CanValidate
- uid: System.Configuration.ConfigurationValidatorBase.Validate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate
  nameWithType: ConfigurationValidatorBase.Validate
