### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Specifica che una proprietà delle impostazioni dell&quot;applicazione ha un valore comune per tutti gli utenti di un&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "Proprietà delle impostazioni dell&quot;applicazione hanno un ambito che si basa sull&quot;applicazione o a livello di utente. Come implicano le categorie, le proprietà delle impostazioni con ambito di applicazione presentano valori uniformi per tutti gli utenti dell&quot;applicazione, mentre le proprietà con ambito di utente hanno valori dedicati per ogni utente dell&quot;applicazione.       Il ApplicationScopedSettingAttribute indica che una proprietà deve essere considerata come un&quot;impostazione a livello di applicazione e che devono essere rese conseguenza decisioni appropriate sull&quot;archiviazione dal provider di impostazioni.       È necessario per ogni proprietà delle impostazioni di un attributo di ambito. Se una proprietà non viene applicata con entrambi un ApplicationScopedSettingAttribute o <xref:System.Configuration.UserScopedSettingAttribute>, la proprietà non è riconosciuta dal provider di impostazioni, non viene serializzata.</xref:System.Configuration.UserScopedSettingAttribute> Non è possibile, tuttavia, per applicare entrambi gli attributi per la stessa proprietà. Tale operazione genererà un <xref:System.Configuration.ConfigurationErrorsException>generata.</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref> classe."
  remarks: "Ogni proprietà delle impostazioni dell&quot;applicazione deve essere applicato con un solo attributo di ambito in modo che vengano riconosciuti e serializzato dal provider di impostazioni."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
