### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  summary: "Fornisce metodi per convertire espressioni in stringhe."
  remarks: "Gli autori di attività di espressione che desiderano offrire un formato testuale corto delle espressioni delle attività devono implementare questa interfaccia."
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Determina se l&quot;espressione può essere convertito in una stringa."
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;espressione può essere convertito in una stringa. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Converte un&quot;espressione in una stringa."
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.String
      description: "Rappresentazione di stringa dell&quot;espressione."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString
  nameWithType: IValueSerializableExpression.CanConvertToString
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString
  nameWithType: IValueSerializableExpression.ConvertToString
