### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  id: ScriptingWebServicesSectionGroup
  children:
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
  type: Class
  summary: "Rappresenta un gruppo di sezioni correlate in un file di configurazione."
  remarks: "Utilizzare la classe ScriptingWebServicesSectionGroup a livello di codice impostare e recuperare i valori del `webServices` sezione del file di configurazione."
  syntax:
    content: 'public sealed class ScriptingWebServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;> </xref> classe."
  syntax:
    content: public ScriptingWebServicesSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  id: AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene il <xref uid=&quot;langword_csharp_authenticationService&quot; name=&quot;authenticationService&quot; href=&quot;&quot;> </xref> sezione contenuta nel file di configurazione."
  remarks: "Il <xref:System.Web.Configuration.ScriptingAuthenticationServiceSection>oggetto fa riferimento al `authenticationService` sezione del file di configurazione.</xref:System.Web.Configuration.ScriptingAuthenticationServiceSection>"
  syntax:
    content: public System.Web.Configuration.ScriptingAuthenticationServiceSection AuthenticationService { get; }
    return:
      type: System.Web.Configuration.ScriptingAuthenticationServiceSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingAuthenticationServiceSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  id: JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene il <xref uid=&quot;langword_csharp_jsonSerialization&quot; name=&quot;jsonSerialization&quot; href=&quot;&quot;> </xref> sezione contenuta nel file di configurazione."
  remarks: "Il <xref:System.Web.Configuration.ScriptingJsonSerializationSection>oggetto fa riferimento al `jsonSerialization` sezione del file di configurazione.</xref:System.Web.Configuration.ScriptingJsonSerializationSection>"
  syntax:
    content: public System.Web.Configuration.ScriptingJsonSerializationSection JsonSerialization { get; }
    return:
      type: System.Web.Configuration.ScriptingJsonSerializationSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingJsonSerializationSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  id: ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene il <xref uid=&quot;langword_csharp_profileService&quot; name=&quot;profileService&quot; href=&quot;&quot;> </xref> sezione contenuta nel file di configurazione."
  remarks: "Il <xref:System.Web.Configuration.ScriptingProfileServiceSection>oggetto fa riferimento al `profileService` sezione del file di configurazione.</xref:System.Web.Configuration.ScriptingProfileServiceSection>"
  syntax:
    content: public System.Web.Configuration.ScriptingProfileServiceSection ProfileService { get; }
    return:
      type: System.Web.Configuration.ScriptingProfileServiceSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingProfileServiceSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  id: RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene il <xref uid=&quot;langword_csharp_roleService&quot; name=&quot;roleService&quot; href=&quot;&quot;> </xref> sezione contenuta nel file di configurazione."
  remarks: "Il <xref:System.Web.Configuration.ScriptingRoleServiceSection>oggetto fa riferimento al `roleService` sezione del file di configurazione.</xref:System.Web.Configuration.ScriptingRoleServiceSection>"
  syntax:
    content: public System.Web.Configuration.ScriptingRoleServiceSection RoleService { get; }
    return:
      type: System.Web.Configuration.ScriptingRoleServiceSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingRoleServiceSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingAuthenticationServiceSection
  nameWithType: ScriptingAuthenticationServiceSection
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
- uid: System.Web.Configuration.ScriptingRoleServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection
  fullName: System.Web.Configuration.ScriptingRoleServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
