### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  id: PeerCustomResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  langs:
  - csharp
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  type: Class
  summary: "Contiene le impostazioni specifiche per un&quot;istanza di un servizio resolver peer personalizzato."
  remarks: "Questo tipo definisce le impostazioni di base per un servizio resolver peer personalizzato, inclusi l&quot;indirizzo dell&quot;endpoint del peer che ospita il servizio e le impostazioni dell&quot;associazione specifiche. Queste impostazioni vengono in genere fornite per il <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>proprietà.</xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>"
  syntax:
    content: public class PeerCustomResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;> </xref> classe."
  syntax:
    content: public PeerCustomResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  id: Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Ottiene o imposta l&quot;indirizzo dell&quot;endpoint del nodo peer che ospita il servizio resolver peer personalizzato."
  syntax:
    content: public System.ServiceModel.EndpointAddress Address { get; set; }
    return:
      type: System.ServiceModel.EndpointAddress
      description: "<xref:System.ServiceModel.EndpointAddress>che contiene l&quot;indirizzo dell&quot;endpoint del nodo peer che esegue il servizio resolver peer personalizzato.</xref:System.ServiceModel.EndpointAddress>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  id: Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Ottiene o imposta l&quot;associazione di canale utilizzato dal servizio resolver peer personalizzato."
  remarks: "Questo elemento di associazione fornisce la specifica per la creazione di una channel factory nel client e un listener del canale nel servizio. Questa channel factory viene utilizzata per produrre canali per il servizio resolver peer personalizzato."
  syntax:
    content: public System.ServiceModel.Channels.Binding Binding { get; set; }
    return:
      type: System.ServiceModel.Channels.Binding
      description: "<xref:System.ServiceModel.Channels.Binding>che contiene le impostazioni di associazione per questo servizio.</xref:System.ServiceModel.Channels.Binding>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  id: IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Ottiene se la <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>proprietà è impostata.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  syntax:
    content: public bool IsBindingSpecified { get; }
    return:
      type: System.Boolean
      description: "True se il <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>proprietà è impostata; false se non lo è.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  id: Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Ottiene o imposta l&quot;istanza del resolver peer personalizzato per questo servizio."
  syntax:
    content: public System.ServiceModel.PeerResolver Resolver { get; set; }
    return:
      type: System.ServiceModel.PeerResolver
      description: "<xref href=&quot;System.ServiceModel.PeerResolver&quot;></xref>istanza utilizzato dal servizio."
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
- uid: System.ServiceModel.PeerResolver
  parent: System.ServiceModel
  isExternal: false
  name: PeerResolver
  nameWithType: PeerResolver
  fullName: System.ServiceModel.PeerResolver
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
