### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerTransportSecuritySettings
  id: PeerTransportSecuritySettings
  children:
  - System.ServiceModel.PeerTransportSecuritySettings.#ctor
  - System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  langs:
  - csharp
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings
  fullName: System.ServiceModel.PeerTransportSecuritySettings
  type: Class
  summary: "Contiene le impostazioni di sicurezza per un trasporto del canale peer."
  syntax:
    content: public sealed class PeerTransportSecuritySettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerTransportSecuritySettings
  langs:
  - csharp
  name: PeerTransportSecuritySettings()
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  fullName: System.ServiceModel.PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Crea un&quot;istanza di <xref href=&quot;System.ServiceModel.PeerTransportSecuritySettings&quot;> </xref> tipo."
  syntax:
    content: public PeerTransportSecuritySettings ();
    parameters: []
  overload: System.ServiceModel.PeerTransportSecuritySettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  id: CredentialType
  parent: System.ServiceModel.PeerTransportSecuritySettings
  langs:
  - csharp
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
  fullName: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene e imposta il tipo di credenziale utilizzato per autenticare il peer di trasporto del canale."
  syntax:
    content: public System.ServiceModel.PeerTransportCredentialType CredentialType { get; set; }
    return:
      type: System.ServiceModel.PeerTransportCredentialType
      description: "Oggetto <xref href=&quot;System.ServiceModel.PeerTransportCredentialType&quot;> </xref> valore di enumerazione che specifica il tipo di credenziali per fornire l&quot;autenticazione."
  overload: System.ServiceModel.PeerTransportSecuritySettings.CredentialType*
  exceptions:
  - type: System.ComponentModel.InvalidEnumArgumentException
    commentId: T:System.ComponentModel.InvalidEnumArgumentException
    description: "Il tipo di credenziale è un valido <xref href=&quot;System.ServiceModel.PeerTransportCredentialType&quot;> </xref> valore di enumerazione."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ComponentModel.InvalidEnumArgumentException
  parent: System.ComponentModel
  isExternal: false
  name: InvalidEnumArgumentException
  nameWithType: InvalidEnumArgumentException
  fullName: System.ComponentModel.InvalidEnumArgumentException
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: PeerTransportSecuritySettings()
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  fullName: System.ServiceModel.PeerTransportSecuritySettings.PeerTransportSecuritySettings()
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
  fullName: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
- uid: System.ServiceModel.PeerTransportCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportCredentialType
  nameWithType: PeerTransportCredentialType
  fullName: System.ServiceModel.PeerTransportCredentialType
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor*
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType*
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
