### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: "Rappresenta il metodo che gestisce il <xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;> </xref> evento di un <xref href=&quot;System.Drawing.Printing.PrintDocument&quot;> </xref>."
  remarks: "Quando si crea un delegato QueryPageSettingsEventHandler, si identifica il metodo che gestirà l&quot;evento. Per associare l&quot;evento al gestore eventi, aggiungere un&quot;istanza del delegato all&quot;evento. Il gestore eventi viene chiamato ogni volta che si verifica l&quot;evento, a meno che non venga rimosso il delegato. Per ulteriori informazioni sui delegati del gestore eventi, vedere [eventi](~/add/includes/ajax-current-ext-md.md).       Per ulteriori informazioni sulla stampa, vedere il <xref:System.Drawing.Printing>Panoramica dello spazio dei nomi.</xref:System.Drawing.Printing>"
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
