### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlSchemaContextSettings
  id: XamlSchemaContextSettings
  children:
  - System.Xaml.XamlSchemaContextSettings.#ctor
  - System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  - System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  - System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  langs:
  - csharp
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
  type: Class
  summary: "Fornisce le impostazioni facoltative per un <xref href=&quot;System.Xaml.XamlSchemaContext&quot;> </xref>."
  syntax:
    content: public class XamlSchemaContextSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> classe."
  syntax:
    content: public XamlSchemaContextSettings ();
    parameters: []
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  id: '#ctor(System.Xaml.XamlSchemaContextSettings)'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> classe copiando i valori di un oggetto esistente <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> istanza."
  syntax:
    content: public XamlSchemaContextSettings (System.Xaml.XamlSchemaContextSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlSchemaContextSettings
      description: "Un oggetto esistente <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  id: FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se uno schema XAML e il relativo contesto utilizzano nomi di assembly completo nei valori restituiti dall&quot;API di ricerca."
  remarks: "Il valore di questa proprietà influenza le stringhe restituite da <xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A>nel contesto dello schema costruito.</xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A> Se <xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>è `true`, la parte dell&quot;assembly della stringa riporterà l&quot;equivalente di <xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName>.</xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName> </xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>"
  syntax:
    content: public bool FullyQualifyAssemblyNamesInClrNamespaces { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se uno schema XAML e il relativo contesto utilizzano nomi di assembly completo nei valori restituiti dall&quot;API di ricerca; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  id: SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se per le estensioni di markup con grado stesso (numero di parametri di input) di due costruttori consente a un contesto dello schema XAML."
  remarks: "Da un <xref:System.Xaml.XamlSchemaContext>, non è possibile leggere direttamente le impostazioni.</xref:System.Xaml.XamlSchemaContext> Al contrario, si ricevono valori dalle specifiche proprietà di sola lettura, ad esempio <xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>, quale i valori basati sulle impostazioni del report.</xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>"
  syntax:
    content: public bool SupportMarkupExtensionsWithDuplicateArity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il contesto dello schema consente estensioni di markup con grado duplicato; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
- uid: System.Xaml.XamlSchemaContextSettings
  parent: System.Xaml
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
- uid: System.Xaml.XamlSchemaContextSettings.#ctor*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
