### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute
  id: ApplicationAccessControlAttribute
  children:
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  - System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  - System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  langs:
  - csharp
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute
  type: Class
  summary: "Specifica i controlli di accesso a un assembly contenente <xref href=&quot;System.EnterpriseServices.ServicedComponent&quot;> </xref> le classi."
  remarks: "In .NET Framework versione 1.1, se questo attributo non è presente nell&quot;assembly, la configurazione di sicurezza COM+ è abilitata per impostazione predefinita. Si tratta di una modifica nel comportamento di .NET Framework versione 1.0."
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/t-system.enterpriseservi_25_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/t-system.enterpriseservi_25_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/t-system.enterpriseservi_25_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationAccessControlAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;> </xref> (classe), abilitare la configurazione di sicurezza COM+."
  remarks: ''
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/m-system.enterpriseservi_23_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/m-system.enterpriseservi_23_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/m-system.enterpriseservi_23_1.vb)]"
  syntax:
    content: public ApplicationAccessControlAttribute ();
    parameters: []
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;> </xref> classe e imposta il <xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>proprietà che indica se abilitare la configurazione della protezione COM.</xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>"
  syntax:
    content: public ApplicationAccessControlAttribute (bool val);
    parameters:
    - id: val
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>per consentire la configurazione di protezione. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  id: AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Ottiene o imposta il livello a livello di processo o a livello di componente di controllo di accesso."
  remarks: "Questa proprietà è supportata solo in Windows 2000 e versioni successive."
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_33_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_33_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_33_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AccessChecksLevelOption AccessChecksLevel { get; set; }
    return:
      type: System.EnterpriseServices.AccessChecksLevelOption
      description: "Uno del <xref href=&quot;System.EnterpriseServices.AccessChecksLevelOption&quot;> </xref> valori."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  id: Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Ottiene o imposta il livello di autenticazione remote procedure call (RPC)."
  remarks: ''
  example:
  - "The following example illustrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_17_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AuthenticationOption Authentication { get; set; }
    return:
      type: System.EnterpriseServices.AuthenticationOption
      description: "Uno del <xref href=&quot;System.EnterpriseServices.AuthenticationOption&quot;> </xref> valori."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  id: ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Ottiene o imposta il livello di rappresentazione consentito per la chiamata a destinazioni di questa applicazione."
  remarks: "Questa proprietà è supportata solo in Windows 2000 e versioni successive."
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/f57469cf-7d93-405f-ae99-_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/f57469cf-7d93-405f-ae99-_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/f57469cf-7d93-405f-ae99-_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.ImpersonationLevelOption ImpersonationLevel { get; set; }
    return:
      type: System.EnterpriseServices.ImpersonationLevelOption
      description: "Uno del <xref href=&quot;System.EnterpriseServices.ImpersonationLevelOption&quot;> </xref> valori."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Ottiene o imposta un valore che indica se abilitare la configurazione di sicurezza COM+."
  syntax:
    content: public bool Value { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se è abilitata la configurazione di sicurezza COM+. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.AccessChecksLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AccessChecksLevelOption
  nameWithType: AccessChecksLevelOption
  fullName: System.EnterpriseServices.AccessChecksLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.AuthenticationOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AuthenticationOption
  nameWithType: AuthenticationOption
  fullName: System.EnterpriseServices.AuthenticationOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ImpersonationLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: ImpersonationLevelOption
  nameWithType: ImpersonationLevelOption
  fullName: System.EnterpriseServices.ImpersonationLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
