### YamlMime:ManagedReference
items:
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  id: ChartHttpHandlerSettings
  children:
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  langs:
  - csharp
  name: ChartHttpHandlerSettings
  nameWithType: ChartHttpHandlerSettings
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  type: Class
  summary: "Fornisce gli attributi che possono essere usati per scrivere un gestore HTTP personalizzato per l&quot;archiviazione dei file di immagine temporanei."
  syntax:
    content: public class ChartHttpHandlerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  id: CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta il nome del gestore personalizzato."
  syntax:
    content: public string CustomHandlerName { get; set; }
    return:
      type: System.String
      description: "Oggetto <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> valore che rappresenta il nome del gestore personalizzato."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  id: Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta la directory del gestore personalizzato in cui verranno archiviati i file di immagine temporanea."
  syntax:
    content: public string Directory { get; set; }
    return:
      type: System.String
      description: "Oggetto <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> valore che rappresenta la directory."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  id: FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta la cartella che verrà utilizzata per archiviare le immagini nella directory specificata."
  syntax:
    content: public string FolderName { get; set; }
    return:
      type: System.String
      description: "Oggetto <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> che rappresenta il nome della cartella."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  id: HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene il tipo di gestore del gestore personalizzato."
  syntax:
    content: public Type HandlerType { get; }
    return:
      type: System.Type
      description: "Il <xref:System.Type>del gestore personalizzato.</xref:System.Type>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene un parametro delle impostazioni con il nome specificato è registrato nel file Web. config sotto il `ChartHttpHandler` chiave."
  remarks: "Utilizzare questo metodo per accedere a qualsiasi parametro nel file Web. config sotto il `ChartHttpHandler` chiave."
  syntax:
    content: public string this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "Nome del parametro da ottenere."
    return:
      type: System.String
      description: "Valore del parametro."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  id: PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene un flag che indica se il gestore utilizzerà immagini private."
  remarks: "Quando la proprietà PrivateImages è impostata, il gestore non restituirà le immagini dall&quot;ambito di sessione. Inoltre, il client non sarà in grado di scaricare immagini di un altro utente. Questo è il comportamento predefinito."
  syntax:
    content: public bool PrivateImages { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Se il gestore utilizzerà immagini private, in caso contrario <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  id: StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta il tipo di archiviazione di immagine del grafico."
  remarks: "Le immagini dei grafici possono essere archiviate come file o della memoria."
  syntax:
    content: public System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType StorageType { get; set; }
    return:
      type: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
      description: "Oggetto <xref href=&quot;System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType&quot;> </xref> valore di enumerazione che rappresenta il tipo di archiviazione di immagine del grafico."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  id: Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta il timeout del gestore personalizzato."
  remarks: "Quando il timeout è scaduto, l&quot;immagine del grafico archiviata viene sottoposto a override da una nuova immagine del grafico o scartato."
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>valore di enumerazione che rappresenta la durata delle immagini del grafico.</xref:System.TimeSpan>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  id: Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Ottiene o imposta l&quot;URL che corrisponde al percorso HTTP in cui sono archiviati i file di immagine temporanei."
  syntax:
    content: public string Url { get; set; }
    return:
      type: System.String
      description: "Oggetto <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> valore che rappresenta l&quot;URL."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
  parent: System.Web.UI.DataVisualization.Charting
  isExternal: false
  name: ChartHttpHandlerStorageType
  nameWithType: ChartHttpHandlerStorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item
  nameWithType: ChartHttpHandlerSettings.Item
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
