### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  summary: "Fornisce il supporto esteso per l&quot;avvio dell&quot;applicazione."
  remarks: "-Non c&quot;è garanzia dell&quot;ordine in cui vengono chiamati i metodi di avvio dell&quot;applicazione definite dall&quot;assembly. Di conseguenza, ogni metodo registrato di inizio deve essere codificato per l&quot;esecuzione in isolamento e non deve dipendere da effetti collaterali di altri metodi iniziali registrati.       Per ulteriori informazioni sull&quot;utilizzo degli attributi, vedere [attributi](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.PreApplicationStartMethodAttribute&quot;> </xref> classe."
  remarks: "Il metodo a cui fa riferimento il `methodName` parametro deve essere pubblico e può essere un metodo di istanza o un metodo statico."
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: "Un oggetto che descrive il tipo del metodo di avvio..."
    - id: methodName
      type: System.String
      description: "Firma di parametro vuota che non restituisce alcun valore."
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Ottiene il metodo di avvio associato."
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: "Stringa che contiene il nome del metodo di avvio associato."
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Ottiene il tipo restituito dal metodo di avvio associato."
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "Oggetto che descrive il tipo del metodo di avvio."
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
