### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidatorAttribute
  id: TimeSpanValidatorAttribute
  children:
  - System.Configuration.TimeSpanValidatorAttribute.#ctor
  - System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  - System.Configuration.TimeSpanValidatorAttribute.MaxValue
  - System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  - System.Configuration.TimeSpanValidatorAttribute.MinValue
  - System.Configuration.TimeSpanValidatorAttribute.MinValueString
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  - System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute
  fullName: System.Configuration.TimeSpanValidatorAttribute
  type: Class
  summary: "Indica in modo dichiarativo a .NET Framework per eseguire la convalida della fase su una proprietà di configurazione. Questa classe non può essere ereditata."
  remarks: "Utilizzare l&quot;attributo TimeSpanValidatorAttribute per decorare una proprietà di configurazione. Viene utilizzata per indicare di .NET Framework per convalidare la proprietà utilizzando la <xref:System.Configuration.TimeSpanValidator>classe e passare il valore dei parametri di decorazione.</xref:System.Configuration.TimeSpanValidator>       È possibile applicare oggetti TimeSpanValidatorAttribute e solo i tipi di proprietà."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the TimeSpanValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/t-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/t-system.configuration.t_1_1.cs)]  \n  \n The following example is an excerpt of the configuration file that contains the custom section used by the previous sample.  \n  \n```  \n<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">  \n  <configSections>  \n    <section name=\"custom\" type=\"Microsoft.Samples.AspNet.Configuration.SampleSection, ConfigurationValidatorAttribute\" />  \n  </configSections>  \n  <custom fileName=\"NewFile.txt\" maxSize=\"1000\" maxAttempts=\"101\" maxUsers=\"2500\" maxIdleTime=\"00:15:00\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class TimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.TimeSpanValidatorAttribute&quot;> </xref> classe."
  remarks: "Utilizzare questo costruttore nel modello con gli attributi per assicurarsi che il tipo del valore assegnato alla proprietà correlata è una <xref:System.TimeSpan>oggetto.</xref:System.TimeSpan>"
  example:
  - "The following example shows how to use the <xref:System.Configuration.StringValidatorAttribute.%23ctor%2A> constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/visualbasic/m-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/csharp/m-system.configuration.t_0_1.cs)]"
  syntax:
    content: public TimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta un valore che indica se includere o escludere i numeri interi nell&quot;intervallo definito da <> </> *> e <> </> *>."
  remarks: "L&quot;intervallo è comprende il <xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A>e <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A>proprietà.</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A> </xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> Quando la proprietà ExcludeRange è `false`, i valori consentiti sono di fuori dell&quot;intervallo."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il valore deve essere escluso; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene massimo assoluto <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  remarks: "Si tratta del valore massimo assoluto consentito da .NET Framework. Il valore è definito per il <xref:System.TimeSpan>campo.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MaxValue { get; }
    return:
      type: System.TimeSpan
      description: "Il valore massimo consentito <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  id: MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il valore massimo relativo <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  remarks: "Questo è il valore massimo relativo impostato dall&quot;utente."
  example:
  - "The following example shows how to use the MaxValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_1_1.cs)]"
  syntax:
    content: public string MaxValueString { get; set; }
    return:
      type: System.String
      description: "Il valore massimo consentito <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore selezionato è minore di <xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene minimo assoluto <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  remarks: "Questo è il valore minimo assoluto consentito da .NET Framework. Il valore è definito per il <xref:System.TimeSpan>campo.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MinValue { get; }
    return:
      type: System.TimeSpan
      description: "Minimo consentito <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  id: MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il minimo relativo <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  remarks: "Questo è il valore minimo relativo impostato dall&quot;utente."
  example:
  - "The following example shows how to use the MinValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_2_1.cs)]"
  syntax:
    content: public string MinValueString { get; set; }
    return:
      type: System.String
      description: "Il valore minimo consentito <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore selezionato è più <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  id: TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il valore assoluto massimo consentito."
  remarks: "Stringa che contiene il valore massimo consentito per l&quot;intervallo di tempo."
  example:
  - "The following example shows how to use the TimeSpanMaxValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/visualbasic/f-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/csharp/f-system.configuration.t_0_1.cs)]"
  syntax:
    content: public const string TimeSpanMaxValue;
    return:
      type: System.String
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  id: TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il valore minimo assoluto consentito."
  remarks: "Stringa che contiene il valore minimo consentito per l&quot;intervallo di tempo."
  example:
  - "The following example shows how to use the TimeSpanMinValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/visualbasic/f-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/csharp/f-system.configuration.t_1_1.cs)]"
  syntax:
    content: public const string TimeSpanMinValue;
    return:
      type: System.String
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un&quot;istanza di <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> classe."
  remarks: "Utilizzare la proprietà ValidatorInstance per eseguire la convalida delle stringhe chiamando il relativo <xref:System.Configuration.TimeSpanValidator.Validate%2A>metodo.</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Il <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> istanza del validator."
  overload: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
