### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.MouseGestureValueSerializer
  id: MouseGestureValueSerializer
  children:
  - System.Windows.Input.MouseGestureValueSerializer.#ctor
  - System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: MouseGestureValueSerializer
  nameWithType: MouseGestureValueSerializer
  fullName: System.Windows.Input.MouseGestureValueSerializer
  type: Class
  summary: "Converte istanze di <xref:System.String>in e da istanze di <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref>.</xref:System.String>"
  remarks: "Questa classe viene generalmente utilizzata solo per il <xref:System.Windows.Markup.Primitives.MarkupWriter>per scopi di serializzazione.</xref:System.Windows.Markup.Primitives.MarkupWriter>      <a name=&quot;xamlTextUsage_MouseGestureValueSerializer&quot;></a># # Utilizzo di testo XAML"
  syntax:
    content: 'public class MouseGestureValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Input.MouseGestureValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.MouseGestureValueSerializer
  langs:
  - csharp
  name: MouseGestureValueSerializer()
  nameWithType: MouseGestureValueSerializer.MouseGestureValueSerializer()
  fullName: System.Windows.Input.MouseGestureValueSerializer.MouseGestureValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Windows.Input.MouseGestureValueSerializer&quot;> </xref> classe."
  syntax:
    content: public MouseGestureValueSerializer ();
    parameters: []
  overload: System.Windows.Input.MouseGestureValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Determina se l&quot;oggetto specificato <xref:System.String>può essere convertito in un&quot;istanza di <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Stringa da valutare per la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "Restituisce sempre <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Determina se l&quot;oggetto specificato <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref> può essere convertito in un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Tasti di modifica per valutare la conversione."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <code> value </code> può essere convertito in un <xref:System.String>; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Converte un <xref:System.String>in un <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Stringa da convertire in un <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref>."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.Object
      description: "Una nuova istanza della <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref> in base al parametro <code> value </code>."
  overload: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Converte un&quot;istanza di <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref> a un <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Chiave da convertire in una stringa."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informazioni di contesto utilizzate per la conversione."
    return:
      type: System.String
      description: "Una rappresentazione di stringa dell&quot;oggetto specificato <xref href=&quot;System.Windows.Input.ModifierKeys&quot;> </xref>."
  overload: System.Windows.Input.MouseGestureValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.MouseGestureValueSerializer.#ctor
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: MouseGestureValueSerializer()
  nameWithType: MouseGestureValueSerializer.MouseGestureValueSerializer()
  fullName: System.Windows.Input.MouseGestureValueSerializer.MouseGestureValueSerializer()
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Input.MouseGestureValueSerializer.#ctor*
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: MouseGestureValueSerializer
  nameWithType: MouseGestureValueSerializer.MouseGestureValueSerializer
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: MouseGestureValueSerializer.CanConvertFromString
- uid: System.Windows.Input.MouseGestureValueSerializer.CanConvertToString*
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: MouseGestureValueSerializer.CanConvertToString
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertFromString*
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: MouseGestureValueSerializer.ConvertFromString
- uid: System.Windows.Input.MouseGestureValueSerializer.ConvertToString*
  parent: System.Windows.Input.MouseGestureValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: MouseGestureValueSerializer.ConvertToString
