### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationSecurityInfo
  id: ApplicationSecurityInfo
  children:
  - System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  - System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  - System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  - System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  - System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  langs:
  - csharp
  name: ApplicationSecurityInfo
  nameWithType: ApplicationSecurityInfo
  fullName: System.Security.Policy.ApplicationSecurityInfo
  type: Class
  summary: "Contiene l&quot;evidenza di sicurezza per un&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "ApplicationSecurityInfo fornisce informazioni di sicurezza di un&quot;applicazione attivata manifesto utilizzando le informazioni ottenute da manifesti dell&quot;applicazione e il relativo <xref:System.ActivationContext>.</xref:System.ActivationContext>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Security.SecurityCritical]

      public sealed class ApplicationSecurityInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  id: '#ctor(System.ActivationContext)'
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationSecurityInfo(ActivationContext)
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Security.Policy.ApplicationSecurityInfo&quot;> </xref> classe utilizzando il contesto di attivazione fornito."
  remarks: "Il <xref:System.ActivationContext>oggetto contiene un <xref:System.ApplicationIdentity>che identifica un&quot;applicazione in base al relativo nome e percorso completi.</xref:System.ApplicationIdentity> </xref:System.ActivationContext>"
  syntax:
    content: public ApplicationSecurityInfo (ActivationContext activationContext);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Un <xref href=&quot;System.ActivationContext&quot;> </xref> oggetto che identifica in modo univoco l&quot;applicazione di destinazione."
  overload: System.Security.Policy.ApplicationSecurityInfo.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>activationContext</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  id: ApplicationEvidence
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene o imposta l&quot;evidenza per l&quot;applicazione."
  remarks: "Un&quot;evidenza è l&quot;insieme di informazioni che costituiscono l&quot;input per le decisioni relative ai criteri di sicurezza, ad esempio le autorizzazioni che è possono concedere al codice."
  syntax:
    content: public System.Security.Policy.Evidence ApplicationEvidence { get; set; }
    return:
      type: System.Security.Policy.Evidence
      description: "Un <xref href=&quot;System.Security.Policy.Evidence&quot;> </xref> oggetto per l&quot;applicazione."
  overload: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "ApplicationEvidence è impostato su <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  id: ApplicationId
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene o imposta le informazioni sull&quot;identità dell&quot;applicazione."
  remarks: "Identità di un&quot;applicazione costituita dalla chiave pubblica del server di pubblicazione, il nome dell&quot;applicazione, l&quot;architettura del processore di destinazione, le impostazioni cultura e la versione dell&quot;applicazione."
  syntax:
    content: public ApplicationId ApplicationId { get; set; }
    return:
      type: System.ApplicationId
      description: "Un <xref href=&quot;System.ApplicationId&quot;> </xref> oggetto."
  overload: System.Security.Policy.ApplicationSecurityInfo.ApplicationId*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "ID applicazione è impostata su <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  id: DefaultRequestSet
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
  fullName: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene o imposta il set di autorizzazioni predefinito."
  remarks: "Se la proprietà non è stata impostata, la funzione di accesso get restituisce un <xref:System.Security.PermissionSet>con uno stato di autorizzazione <xref:System.Security.Permissions.PermissionState>.</xref:System.Security.Permissions.PermissionState> </xref:System.Security.PermissionSet>"
  syntax:
    content: public System.Security.PermissionSet DefaultRequestSet { get; set; }
    return:
      type: System.Security.PermissionSet
      description: "Oggetto <xref href=&quot;System.Security.PermissionSet&quot;> </xref> oggetto che rappresenta le autorizzazioni predefinite per l&quot;applicazione. Il valore predefinito è una <xref href=&quot;System.Security.PermissionSet&quot;> </xref> con uno stato di autorizzazione<xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref>"
  overload: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "DefaultRequestSet è impostato su <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  id: DeploymentId
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
  fullName: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene o imposta l&quot;elemento principale dell&quot;applicazione, come descritto nell&quot;identità di distribuzione."
  remarks: "Un&quot;identità di distribuzione costituito dalla chiave pubblica del server di pubblicazione, il nome dell&quot;applicazione, l&quot;architettura del processore di destinazione, le impostazioni cultura e la versione dell&quot;applicazione."
  syntax:
    content: public ApplicationId DeploymentId { get; set; }
    return:
      type: System.ApplicationId
      description: "Un <xref href=&quot;System.ApplicationId&quot;> </xref> oggetto che descrive l&quot;elemento principale dell&quot;applicazione."
  overload: System.Security.Policy.ApplicationSecurityInfo.DeploymentId*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "ID distribuzione è impostato su <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationSecurityInfo(ActivationContext)
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
- uid: System.Security.Policy.Evidence
  parent: System.Security.Policy
  isExternal: false
  name: Evidence
  nameWithType: Evidence
  fullName: System.Security.Policy.Evidence
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
- uid: System.ApplicationId
  parent: System
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationId
  fullName: System.ApplicationId
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
  fullName: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: System.Security.PermissionSet
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
  fullName: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationSecurityInfo
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
