### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: "Indica in modo dichiarativo a .NET Framework per eseguire la convalida della fase su una proprietà di configurazione. Questa classe non può essere ereditata."
  remarks: "Utilizzare l&quot;attributo PositiveTimeSpanValidatorAttribute per decorare una proprietà di configurazione. Ciò indica in .NET Framework per convalidare la proprietà utilizzando un <xref:System.Configuration.PositiveTimeSpanValidator>dell&quot;oggetto e passare il valore dei parametri di decorazione.</xref:System.Configuration.PositiveTimeSpanValidator>       È possibile applicare oggetti PositiveTimeSpanValidatorAttribute solo ai tipi di proprietà."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.PositiveTimeSpanValidatorAttribute&quot;> </xref> classe."
  remarks: "Utilizzare questo costruttore nel modello con gli attributi per assicurarsi che il tipo del valore assegnato alla proprietà correlata è un numero positivo <xref:System.TimeSpan>oggetto.</xref:System.TimeSpan>"
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un&quot;istanza di <xref href=&quot;System.Configuration.PositiveTimeSpanValidator&quot;> </xref> classe."
  remarks: "Utilizzare la proprietà ValidatorInstance eseguire positivo <xref:System.TimeSpan>convalida dell&quot;oggetto chiamando il <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName>metodo.</xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName> </xref:System.TimeSpan>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Il <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> istanza del validator."
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
