### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  id: ActivityScheduledQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties
  langs:
  - csharp
  name: ActivityScheduledQueryElement
  nameWithType: ActivityScheduledQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  type: Class
  summary: "Un elemento di configurazione che rappresenta un <xref href=&quot;System.Activities.Tracking.ActivityScheduledQuery&quot;> </xref>."
  syntax:
    content: 'public class ActivityScheduledQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  langs:
  - csharp
  name: ActivityScheduledQueryElement()
  nameWithType: ActivityScheduledQueryElement.ActivityScheduledQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityScheduledQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement&quot;> </xref> classe."
  syntax:
    content: public ActivityScheduledQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName
  id: ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  langs:
  - csharp
  name: ActivityName
  nameWithType: ActivityScheduledQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta il nome dell&quot;attività per filtrare <xref href=&quot;System.Activities.Tracking.ActivityScheduledRecord&quot;> </xref> istanze. Il valore predefinito è &quot;*&quot; (tutto)."
  syntax:
    content: public string ActivityName { get; set; }
    return:
      type: System.String
      description: "Il nome dell&quot;attività."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName
  id: ChildActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  langs:
  - csharp
  name: ChildActivityName
  nameWithType: ActivityScheduledQueryElement.ChildActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta il nome dell&quot;attività figlio per filtrare <xref href=&quot;System.Activities.Tracking.ActivityScheduledRecord&quot;> </xref> istanze. Il valore predefinito è &quot;*&quot; (tutto)."
  syntax:
    content: public string ChildActivityName { get; set; }
    return:
      type: System.String
      description: "Il nome dell&quot;attività figlio."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: ActivityScheduledQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Crea il <xref href=&quot;System.Activities.Tracking.ActivityScheduledQuery&quot;> </xref>."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "La query di attività pianificata."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: ActivityScheduledQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene le proprietà contenute in questo elemento di configurazione."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Le proprietà contenute in questo elemento di configurazione."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ActivityScheduledQueryElement()
  nameWithType: ActivityScheduledQueryElement.ActivityScheduledQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityScheduledQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: ActivityScheduledQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ChildActivityName
  nameWithType: ActivityScheduledQueryElement.ChildActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: ActivityScheduledQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: Properties
  nameWithType: ActivityScheduledQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ActivityScheduledQueryElement
  nameWithType: ActivityScheduledQueryElement.ActivityScheduledQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: ActivityScheduledQueryElement.ActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.ChildActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: ChildActivityName
  nameWithType: ActivityScheduledQueryElement.ChildActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: ActivityScheduledQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ActivityScheduledQueryElement
  isExternal: false
  name: Properties
  nameWithType: ActivityScheduledQueryElement.Properties
