### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.ComponentInstaller
  id: ComponentInstaller
  children:
  - System.Configuration.Install.ComponentInstaller.#ctor
  - System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  - System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  langs:
  - csharp
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
  type: Class
  summary: "Specifica un programma di installazione che copia le proprietà da un componente da utilizzare al momento dell&quot;installazione."
  syntax:
    content: 'public abstract class ComponentInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.Object
  - System.MarshalByRefObject
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  implements: []
  inheritedMembers:
  - System.ComponentModel.Component.CanRaiseEvents
  - System.ComponentModel.Component.Container
  - System.ComponentModel.Component.DesignMode
  - System.ComponentModel.Component.Dispose
  - System.ComponentModel.Component.Dispose(System.Boolean)
  - System.ComponentModel.Component.Disposed
  - System.ComponentModel.Component.Events
  - System.ComponentModel.Component.GetService(System.Type)
  - System.ComponentModel.Component.Site
  - System.ComponentModel.Component.ToString
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.HelpText
  - System.Configuration.Install.Installer.Install(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
  - System.Configuration.Install.Installer.Rollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Uninstall(System.Collections.IDictionary)
  - System.MarshalByRefObject.CreateObjRef(System.Type)
  - System.MarshalByRefObject.GetLifetimeService
  - System.MarshalByRefObject.InitializeLifetimeService
  - System.MarshalByRefObject.MemberwiseClone(System.Boolean)
  platform:
  - net462
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.Install.ComponentInstaller&quot;> </xref> classe."
  syntax:
    content: protected ComponentInstaller ();
    parameters: []
  overload: System.Configuration.Install.ComponentInstaller.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  id: CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Quando sottoposto a override in una classe derivata, copia tutte le proprietà che sono richieste in fase di installazione dal componente specificato."
  remarks: "Il programma di installazione deve richiedere tutte le informazioni che possibili dal componente in tempo reale e archivierà per uso al momento dell&quot;installazione."
  example:
  - "The following example defines a class `MyInstallClass`, which creates the event log and copies the properties of the event log component to the <xref:System.Diagnostics.EventLogInstaller>. It also checks whether the <xref:System.ServiceProcess.ServiceInstaller> can perform the same kind of installation as the <xref:System.Diagnostics.EventLogInstaller>.  \n  \n [!code-cpp[ComponentInstaller_CopyFromComponent#1](~/add/codesnippet/cpp/bbbdd3c8-8c26-472e-ad0c-_1.cpp)]\n [!code-vb[ComponentInstaller_CopyFromComponent#1](~/add/codesnippet/visualbasic/bbbdd3c8-8c26-472e-ad0c-_1.vb)]\n [!code-cs[ComponentInstaller_CopyFromComponent#1](~/add/codesnippet/csharp/bbbdd3c8-8c26-472e-ad0c-_1.cs)]"
  syntax:
    content: public abstract void CopyFromComponent (System.ComponentModel.IComponent component);
    parameters:
    - id: component
      type: System.ComponentModel.IComponent
      description: "Il componente da cui copiare."
  overload: System.Configuration.Install.ComponentInstaller.CopyFromComponent*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  id: IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Determina se il programma di installazione specificato installa l&quot;oggetto stesso come il programma di installazione."
  remarks: "In genere, IsEquivalentInstaller restituisce `true` solo se il programma di installazione e il programma di installazione specificato per il `otherInstaller` parametro installare lo stesso oggetto. In tal caso, la chiamata di <xref:System.Configuration.Install.Installer.Install%2A>o <xref:System.Configuration.Install.Installer.Uninstall%2A>metodo entrambi risultati installazione nello stesso stato del sistema.</xref:System.Configuration.Install.Installer.Uninstall%2A> </xref:System.Configuration.Install.Installer.Install%2A>"
  example:
  - "The following example defines a class `MyInstallClass`, which creates the event log and copies the properties of the event log component to the <xref:System.Diagnostics.EventLogInstaller> object. It also checks whether <xref:System.ServiceProcess.ServiceInstaller> object can handle the same kind of installation as <xref:System.Diagnostics.EventLogInstaller>.  \n  \n [!code-cpp[ComponentInstaller_CopyFromComponent#2](~/add/codesnippet/cpp/9712fa47-8bed-4108-9ebc-_1.cpp)]\n [!code-vb[ComponentInstaller_CopyFromComponent#2](~/add/codesnippet/visualbasic/9712fa47-8bed-4108-9ebc-_1.vb)]\n [!code-cs[ComponentInstaller_CopyFromComponent#2](~/add/codesnippet/csharp/9712fa47-8bed-4108-9ebc-_1.cs)]"
  syntax:
    content: public virtual bool IsEquivalentInstaller (System.Configuration.Install.ComponentInstaller otherInstaller);
    parameters:
    - id: otherInstaller
      type: System.Configuration.Install.ComponentInstaller
      description: "Il programma di installazione da confrontare."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il programma di installazione e il programma di installazione specificato per il <code> otherInstaller </code> parametro installare lo stesso oggetto; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Install.Installer
  isExternal: false
  name: System.Configuration.Install.Installer
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
- uid: System.ComponentModel.IComponent
  parent: System.ComponentModel
  isExternal: false
  name: IComponent
  nameWithType: IComponent
  fullName: System.ComponentModel.IComponent
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Install.ComponentInstaller
  parent: System.Configuration.Install
  isExternal: false
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
- uid: System.Configuration.Install.ComponentInstaller.#ctor*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: ComponentInstaller
  nameWithType: ComponentInstaller.ComponentInstaller
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: CopyFromComponent
  nameWithType: ComponentInstaller.CopyFromComponent
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: IsEquivalentInstaller
  nameWithType: ComponentInstaller.IsEquivalentInstaller
