### YamlMime:ManagedReference
items:
- uid: System.Configuration.IdnElement
  id: IdnElement
  children:
  - System.Configuration.IdnElement.#ctor
  - System.Configuration.IdnElement.Enabled
  - System.Configuration.IdnElement.Properties
  langs:
  - csharp
  name: IdnElement
  nameWithType: IdnElement
  fullName: System.Configuration.IdnElement
  type: Class
  summary: "Fornisce l&quot;impostazione di configurazione per nome IDN (International Domain) l&quot;elaborazione nel &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) basati su RFC 3987.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       L&quot;impostazione di configurazione per il IdnElement indirettamente è controllata dall&quot; <xref:System.Configuration.IriParsingElement>impostazione di configurazione che controlla l&quot;elaborazione IRI nella <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Elaborazione IRI deve essere abilitato per l&quot;elaborazione possibili IDN. Se l&quot;elaborazione di IRI è disabilitata, elaborazione IDN verrà configurata l&quot;impostazione predefinita, in cui viene utilizzato il comportamento di .NET Framework 2.0 per la compatibilità e non vengono utilizzati i nomi IDN.       L&quot;attributo IDN (Internationalized Domain Name) controlla solo l&quot;elaborazione IDN. Per impostazione predefinita, viene eseguita ogni altra elaborazione IRI (la normalizzazione dei caratteri, ad esempio).       L&quot;impostazione di configurazione per il IdnElement verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: 'public sealed class IdnElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.IdnElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> classe."
  remarks: "Questo costruttore crea un&quot; <xref:System.Configuration.IdnElement>istanza</xref:System.Configuration.IdnElement>"
  syntax:
    content: public IdnElement ();
    parameters: []
  overload: System.Configuration.IdnElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Enabled
  id: Enabled
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene o imposta il valore di <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> impostazione di configurazione."
  remarks: "L&quot;attributo nome IDN (International Domain) controlla solo l&quot;elaborazione IDN. Per impostazione predefinita, viene eseguita l&quot;elaborazione di tutti gli altri identificatori IRI (International Resource) (la normalizzazione dei caratteri, ad esempio).       L&quot;impostazione di configurazione per <xref:System.Configuration.IdnElement>indirettamente è controllata dall&quot; <xref:System.Configuration.IriParsingElement?displayProperty=fullName>impostazione di configurazione che controlla l&quot;elaborazione IRI nella <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement?displayProperty=fullName> </xref:System.Configuration.IdnElement> Elaborazione IRI deve essere abilitato per l&quot;elaborazione possibili IDN. Se l&quot;elaborazione di IRI è disabilitata, elaborazione IDN verrà configurata l&quot;impostazione predefinita, in cui viene utilizzato il comportamento di .NET Framework 2.0 per la compatibilità e non vengono utilizzati i nomi IDN.       L&quot;impostazione di configurazione per il <xref:System.Configuration.IdnElement>verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IdnElement> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public UriIdnScope Enabled { get; set; }
    return:
      type: System.UriIdnScope
      description: "Oggetto <xref href=&quot;System.UriIdnScope&quot;> </xref> che contiene l&quot;impostazione di configurazione corrente per l&quot;elaborazione IDN."
  overload: System.Configuration.IdnElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Properties
  id: Properties
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Configuration.IdnElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.IdnElement.#ctor
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
- uid: System.Configuration.IdnElement.Enabled
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
- uid: System.UriIdnScope
  parent: System
  isExternal: false
  name: UriIdnScope
  nameWithType: UriIdnScope
  fullName: System.UriIdnScope
- uid: System.Configuration.IdnElement.Properties
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IdnElement.#ctor*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement
  nameWithType: IdnElement.IdnElement
- uid: System.Configuration.IdnElement.Enabled*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
- uid: System.Configuration.IdnElement.Properties*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
