### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigRoot
  id: IInternalConfigRoot
  children:
  - System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  - System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  - System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  - System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  - System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigRoot
  nameWithType: IInternalConfigRoot
  fullName: System.Configuration.Internal.IInternalConfigRoot
  type: Interface
  summary: "Definisce le interfacce utilizzate dalle strutture .NET interne per supportare un oggetto di primo livello di configurazione."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigRoot
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  id: ConfigChanged
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: ConfigChanged
  nameWithType: IInternalConfigRoot.ConfigChanged
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  type: Event
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Rappresenta il metodo che gestisce l&quot;evento ConfigChanged di un <xref href=&quot;System.Configuration.Internal.IInternalConfigRoot&quot;> </xref> oggetto."
  syntax:
    content: public event System.Configuration.Internal.InternalConfigEventHandler ConfigChanged;
    return:
      type: System.Configuration.Internal.InternalConfigEventHandler
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  id: ConfigRemoved
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: ConfigRemoved
  nameWithType: IInternalConfigRoot.ConfigRemoved
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  type: Event
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Rappresenta il metodo che gestisce l&quot;evento ConfigRemoved di un <xref href=&quot;System.Configuration.Internal.IInternalConfigRoot&quot;> </xref> oggetto."
  syntax:
    content: public event System.Configuration.Internal.InternalConfigEventHandler ConfigRemoved;
    return:
      type: System.Configuration.Internal.InternalConfigEventHandler
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  id: GetConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref> oggetto che rappresenta una configurazione specificata da un percorso di configurazione."
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRecord GetConfigRecord (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Stringa che rappresenta il percorso di un file di configurazione."
    return:
      type: System.Configuration.Internal.IInternalConfigRecord
      description: "Un <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref> oggetto che rappresenta una configurazione specificata da <code> configPath </code>."
  overload: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  id: GetSection(System.String,System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetSection(String,String)
  nameWithType: IInternalConfigRoot.GetSection(String,String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetSection(String,String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un <xref:System.Object>che rappresenta i dati in una sezione di un file di configurazione.</xref:System.Object>"
  syntax:
    content: public object GetSection (string section, string configPath);
    parameters:
    - id: section
      type: System.String
      description: "Stringa che rappresenta una sezione di un file di configurazione."
    - id: configPath
      type: System.String
      description: "Stringa che rappresenta il percorso di un file di configurazione."
    return:
      type: System.Object
      description: "Un <xref:System.Object>che rappresenta i dati in una sezione di un file di configurazione.</xref:System.Object>"
  overload: System.Configuration.Internal.IInternalConfigRoot.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  id: GetUniqueConfigPath(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetUniqueConfigPath(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un valore che rappresenta il percorso del file del predecessore più vicino di configurazione che dispone di dati di configurazione."
  syntax:
    content: public string GetUniqueConfigPath (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Il percorso del file di configurazione."
    return:
      type: System.String
      description: "Restituisce una stringa che rappresenta il percorso del file del predecessore più vicino di configurazione che dispone di dati di configurazione."
  overload: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  id: GetUniqueConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetUniqueConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref> oggetto che rappresenta un record di configurazione univoco per un determinato percorso di configurazione."
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRecord GetUniqueConfigRecord (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Il percorso del file di configurazione."
    return:
      type: System.Configuration.Internal.IInternalConfigRecord
      description: "Un <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref> oggetto che rappresenta un record di configurazione univoco per un determinato percorso di configurazione."
  overload: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  id: Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: Init(IInternalConfigHost,Boolean)
  nameWithType: IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Inizializza un oggetto di configurazione."
  syntax:
    content: public void Init (System.Configuration.Internal.IInternalConfigHost host, bool isDesignTime);
    parameters:
    - id: host
      type: System.Configuration.Internal.IInternalConfigHost
      description: "Un <xref href=&quot;System.Configuration.Internal.IInternalConfigHost&quot;> </xref> oggetto."
    - id: isDesignTime
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se fase di progettazione; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> in fase di esecuzione."
  overload: System.Configuration.Internal.IInternalConfigRoot.Init*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  id: IsDesignTime
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
  fullName: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Restituisce un valore che indica se la configurazione è in fase di progettazione."
  syntax:
    content: public bool IsDesignTime { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la configurazione è una configurazione in fase di progettazione. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se la configurazione non è una configurazione design-time."
  overload: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  id: RemoveConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: RemoveConfig(String)
  nameWithType: IInternalConfigRoot.RemoveConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Individua e rimuove tutti gli elementi figlio per un determinato percorso di configurazione e un record di configurazione."
  syntax:
    content: public void RemoveConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "Il percorso del file di configurazione."
  overload: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: ConfigChanged
  nameWithType: IInternalConfigRoot.ConfigChanged
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
- uid: System.Configuration.Internal.InternalConfigEventHandler
  parent: System.Configuration.Internal
  isExternal: false
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: ConfigRemoved
  nameWithType: IInternalConfigRoot.ConfigRemoved
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(String)
- uid: System.Configuration.Internal.IInternalConfigRecord
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigRecord
  nameWithType: IInternalConfigRecord
  fullName: System.Configuration.Internal.IInternalConfigRecord
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetSection(String,String)
  nameWithType: IInternalConfigRoot.GetSection(String,String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetSection(String,String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigPath(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: Init(IInternalConfigHost,Boolean)
  nameWithType: IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
- uid: System.Configuration.Internal.IInternalConfigHost
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigHost
  nameWithType: IInternalConfigHost
  fullName: System.Configuration.Internal.IInternalConfigHost
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
  fullName: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: RemoveConfig(String)
  nameWithType: IInternalConfigRoot.RemoveConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetConfigRecord
  nameWithType: IInternalConfigRoot.GetConfigRecord
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigRoot.GetSection
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigPath
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigRecord
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord
- uid: System.Configuration.Internal.IInternalConfigRoot.Init*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: Init
  nameWithType: IInternalConfigRoot.Init
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: RemoveConfig
  nameWithType: IInternalConfigRoot.RemoveConfig
