### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocationCollection
  id: ConfigurationLocationCollection
  children:
  - System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  langs:
  - csharp
  name: ConfigurationLocationCollection
  nameWithType: ConfigurationLocationCollection
  fullName: System.Configuration.ConfigurationLocationCollection
  type: Class
  summary: "Contiene una raccolta di oggetti ConfigurationLocationCollection."
  remarks: "Utilizzare la classe ConfigurationLocationCollection per scorrere una raccolta di <xref:System.Configuration.ConfigurationLocation>oggetti che rappresentano le risorse per cui vengono definite le impostazioni di configurazione specifici della posizione.</xref:System.Configuration.ConfigurationLocation> ConfigurationLocationCollection è il tipo restituito per il <xref:System.Configuration.Configuration.Locations%2A>proprietà.</xref:System.Configuration.Configuration.Locations%2A>      > [!NOTE] > ConfigurationLocationCollection la classe non può fare riferimento la raccolta di <xref:System.Configuration.ConfigurationLocation>oggetti nell&quot;ordine in cui sono state specificate nel file di configurazione.</xref:System.Configuration.ConfigurationLocation>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and the locations defined in this configuration are displayed by iterating through the ConfigurationLocationCollection object returned by the <xref:System.Configuration.Configuration.Locations%2A> property.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_1_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_1_1.cs)]"
  syntax:
    content: 'public class ConfigurationLocationCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> oggetto in corrispondenza dell&quot;indice specificato."
  remarks: "Utilizzare la funzione di accesso di elemento per la <xref:System.Configuration.ConfigurationLocationCollection>classe per ottenere un oggetto specifico <xref:System.Configuration.ConfigurationLocation>oggetto dalla raccolta specificando il relativo indice all&quot;interno della raccolta.</xref:System.Configuration.ConfigurationLocation> </xref:System.Configuration.ConfigurationLocationCollection>"
  syntax:
    content: public System.Configuration.ConfigurationLocation this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "La posizione di indice di <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> da restituire."
    return:
      type: System.Configuration.ConfigurationLocation
      description: "Il <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> in corrispondenza dell&quot;indice specificato."
  overload: System.Configuration.ConfigurationLocationCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
- uid: System.Configuration.ConfigurationLocation
  parent: System.Configuration
  isExternal: false
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLocationCollection.Item*
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item
  nameWithType: ConfigurationLocationCollection.Item
