### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelLogLevel
  id: ProcessModelLogLevel
  children:
  - System.Web.Configuration.ProcessModelLogLevel.All
  - System.Web.Configuration.ProcessModelLogLevel.Errors
  - System.Web.Configuration.ProcessModelLogLevel.None
  langs:
  - csharp
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
  type: Enum
  summary: "Specifica i tipi di evento che viene registrato nel registro eventi."
  remarks: "L&quot;enumerazione ProcessModelLogLevel contiene i valori da utilizzare quando si imposta la <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>proprietà.</xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>       Il valore predefinito è errori."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/csharp/t-system.web.configurati_95_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/visualbasic/t-system.web.configurati_95_1.vb)]"
  syntax:
    content: public enum ProcessModelLogLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  id: All
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che vengono registrati tutti gli eventi di processo. Questo campo è costante."
  remarks: "Utilizzare questa opzione quando si desidera esplorare i possibili errori che potrebbe generare un&quot;applicazione, senza eventuali filtri. Questa opzione è utile durante la compilazione e debug di fase."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  id: Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che vengono registrati solo gli arresti imprevisti, limiti di memoria e arresti deadlock. Questo campo è costante."
  remarks: "Questo è il valore predefinito."
  syntax:
    content: Errors
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che viene registrato alcun evento. Questo campo è costante."
  remarks: "È possibile utilizzare questa opzione per le applicazioni testate e distribuite."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
- uid: System.Web.Configuration.ProcessModelLogLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
