### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  id: XmlDictionaryReaderQuotasElement
  children:
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.#ctor
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties
  langs:
  - csharp
  name: XmlDictionaryReaderQuotasElement
  nameWithType: XmlDictionaryReaderQuotasElement
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  type: Class
  summary: "Rappresenta l&quot;elemento di configurazione che definisce i vincoli sulla complessità dei messaggi SOAP che possono essere elaborati dagli endpoint configurati con un&quot;associazione. Questa classe non può essere ereditata."
  remarks: "> [!WARNING]\n>  Properties set on this class must be set on both the client and service sides.  \n  \n [\\&lt;readerQuotas\\&gt;](../Topic/%3CreaderQuotas%3E.md)"
  syntax:
    content: 'public sealed class XmlDictionaryReaderQuotasElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: XmlDictionaryReaderQuotasElement()
  nameWithType: XmlDictionaryReaderQuotasElement.XmlDictionaryReaderQuotasElement()
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.XmlDictionaryReaderQuotasElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement&quot;> </xref> classe."
  syntax:
    content: public XmlDictionaryReaderQuotasElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  id: MaxArrayLength
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene e imposta la lunghezza massima consentita della matrice."
  syntax:
    content: public int MaxArrayLength { get; set; }
    return:
      type: System.Int32
      description: "La lunghezza massima consentita della matrice."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  id: MaxBytesPerRead
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene e imposta i byte massimi consentiti restituiti per ogni lettura."
  syntax:
    content: public int MaxBytesPerRead { get; set; }
    return:
      type: System.Int32
      description: "I byte massimi consentiti restituiti per ogni lettura."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  id: MaxDepth
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene e imposta la profondità massima dei nodi annidati per ogni lettura."
  syntax:
    content: public int MaxDepth { get; set; }
    return:
      type: System.Int32
      description: "La profondità massima dei nodi annidati per ogni lettura."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  id: MaxNameTableCharCount
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene e imposta il numero massimo di caratteri nel nome della tabella."
  syntax:
    content: public int MaxNameTableCharCount { get; set; }
    return:
      type: System.Int32
      description: "Numero massimo di caratteri nel nome della tabella."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  id: MaxStringContentLength
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene e imposta il numero massimo di caratteri consentito nel contenuto dell&quot;elemento XML."
  syntax:
    content: public int MaxStringContentLength { get; set; }
    return:
      type: System.Int32
      description: "Numero massimo di caratteri consentito nel contenuto dell&quot;elemento XML."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  name: Properties
  nameWithType: XmlDictionaryReaderQuotasElement.Properties
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.#ctor
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: XmlDictionaryReaderQuotasElement()
  nameWithType: XmlDictionaryReaderQuotasElement.XmlDictionaryReaderQuotasElement()
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.XmlDictionaryReaderQuotasElement()
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: Properties
  nameWithType: XmlDictionaryReaderQuotasElement.Properties
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.#ctor*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: XmlDictionaryReaderQuotasElement
  nameWithType: XmlDictionaryReaderQuotasElement.XmlDictionaryReaderQuotasElement
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement.Properties*
  parent: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  isExternal: false
  name: Properties
  nameWithType: XmlDictionaryReaderQuotasElement.Properties
