### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocation
  id: ConfigurationLocation
  children:
  - System.Configuration.ConfigurationLocation.OpenConfiguration
  - System.Configuration.ConfigurationLocation.Path
  langs:
  - csharp
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
  type: Class
  summary: "Rappresenta un <xref uid=&quot;langword_csharp_location&quot; name=&quot;location&quot; href=&quot;&quot;> </xref> elemento all&quot;interno di un file di configurazione."
  remarks: "Un&quot;istanza della classe ConfigurationLocation rappresenta un singolo `location` elemento all&quot;interno di un file di configurazione. Percorsi utilizzati per specificare le impostazioni di configurazione che si applicano solo a una risorsa specificata, ad esempio una pagina specifica, un file o sottodirectory, all&quot;interno dell&quot;applicazione Web. Utilizzare la classe ConfigurationLocation per ottenere il percorso e il <xref:System.Configuration.Configuration>oggetto che si applica alla risorsa specificata.</xref:System.Configuration.Configuration>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and then the locations defined in the configuration are displayed.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_22_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_22_1.cs)]"
  syntax:
    content: public class ConfigurationLocation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  id: OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Crea un&quot;istanza di un oggetto di configurazione."
  syntax:
    content: public System.Configuration.Configuration OpenConfiguration ();
    parameters: []
    return:
      type: System.Configuration.Configuration
      description: "Oggetto di configurazione."
  overload: System.Configuration.ConfigurationLocation.OpenConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.Path
  id: Path
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il percorso relativo alla risorsa le cui impostazioni di configurazione sono rappresentate da questo <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref> oggetto."
  remarks: "Il percorso restituito dalla proprietà percorso è relativo alla radice del sito Web.      > [!NOTE] > Proprietà percorso potrebbe contenere un elenco delimitato da virgole di percorsi a cui si applica l&quot;impostazione di configurazione."
  example:
  - "The following code example shows how to access the Path property and display the value returned to the console.  \n  \n [!code-vb[ConfigurationLocationCollection#2](~/add/codesnippet/visualbasic/p-system.configuration.c_38_1.vb)]\n [!code-cs[ConfigurationLocationCollection#2](~/add/codesnippet/csharp/p-system.configuration.c_38_1.cs)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "Il percorso relativo alla risorsa le cui impostazioni di configurazione sono rappresentate da questo <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref>."
  overload: System.Configuration.ConfigurationLocation.Path*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Configuration.ConfigurationLocation.Path
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration
  nameWithType: ConfigurationLocation.OpenConfiguration
- uid: System.Configuration.ConfigurationLocation.Path*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
