### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlWriterSettings
  id: XamlWriterSettings
  children:
  - System.Xaml.XamlWriterSettings.#ctor
  - System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  langs:
  - csharp
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
  type: Class
  summary: "Fornisce le impostazioni di inizializzazione per un <xref href=&quot;System.Xaml.XamlWriter&quot;> </xref> implementazione."
  remarks: "XamlWriterSettings è una classe per le impostazioni utilizzate da un <xref:System.Xaml.XamlWriter>; tuttavia, non contiene impostazioni specifiche XamlWriterSettings.</xref:System.Xaml.XamlWriter> Il <xref:System.Xaml.XamlWriter>costruttore non utilizza questa classe di impostazioni come argomento, neppure da qualsiasi altro <xref:System.Xaml.XamlWriter>membro utilizzarlo.</xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlWriter> Al contrario, il <xref:System.Xaml.XamlXmlWriter>e <xref:System.Xaml.XamlObjectWriter>classi includono classi di impostazioni come argomenti di costruzione, entrambe le classi aggiungono impostazioni effettive e sono basate su XamlWriterSettings.</xref:System.Xaml.XamlObjectWriter> </xref:System.Xaml.XamlXmlWriter>"
  syntax:
    content: public class XamlWriterSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> classe."
  syntax:
    content: public XamlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  id: '#ctor(System.Xaml.XamlWriterSettings)'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> classe utilizza un&quot;altra istanza esistente di impostazioni."
  remarks: "Questo costruttore supporta l&quot;unione delle impostazioni, in cui le impostazioni aggiuntive possono provenire da altri partecipanti nel processo di scrittura o da classi di impostazioni per i writer specializzati che esegue l&quot;override <xref:System.Xaml.XamlWriterSettings>.</xref:System.Xaml.XamlWriterSettings>"
  syntax:
    content: public XamlWriterSettings (System.Xaml.XamlWriterSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlWriterSettings
      description: "Un oggetto esistente <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> oggetto."
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlWriterSettings.#ctor
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
- uid: System.Xaml.XamlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlWriterSettings.#ctor*
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings.XamlWriterSettings
