### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  id: ProcessModelComAuthenticationLevel
  children:
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  langs:
  - csharp
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
  type: Enum
  summary: "Specifica il livello di autenticazione per la sicurezza DCOM."
  remarks: "Il ProcessModelComAuthenticationLevel enumera i valori da utilizzare quando si imposta la <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>proprietà.</xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>       Il valore predefinito è una connessione.      > [!NOTE] > ProcessModelComAuthenticationLevel di impostazioni sono rilevanti solo quando si utilizza il modello di processo ASP.NET (Internet Information Services [IIS 5. n o solo in modalità compatibilità IIS 6)."
  example:
  - "The following code example shows how to get the current <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property value and then set the <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property to a new value of Call.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/csharp/t-system.web.configurati_40_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/visualbasic/t-system.web.configurati_40_1.vb)]"
  syntax:
    content: public enum ProcessModelComAuthenticationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  id: Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM autentica le credenziali del client. Questo campo è costante."
  remarks: "DCOM autentica le credenziali del client quando il server riceve la richiesta all&quot;inizio di ogni chiamata di procedura remota."
  syntax:
    content: Call
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  id: Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM autentica le credenziali del client. Questo campo è costante."
  remarks: "DCOM autentica le credenziali del client solo quando il client stabilisce una relazione con il server.       Questo è il valore predefinito."
  syntax:
    content: Connect
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM determina il livello di autenticazione. Questo campo è costante."
  remarks: "DCOM determina il livello di autenticazione utilizzando l&quot;algoritmo di negoziazione di sicurezza normale."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Non specifica alcuna autenticazione. Questo campo è costante."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  id: Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM verifica che tutti i dati ricevuti dal client previsto. Questo campo è costante."
  remarks: "I trasporti di datagrammi utilizzano sempre l&quot;autenticazione Pkt."
  syntax:
    content: Pkt
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  id: PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM autentica e verifica i dati trasferiti. Questo campo è costante."
  remarks: "DCOM verifica nessuno dei dati trasferiti tra il client e il server è stato modificato."
  syntax:
    content: PktIntegrity
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  id: PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che DCOM autentica tutti i livelli precedenti e applica la crittografia. Questo campo è costante."
  remarks: "DCOM autentica tutti i livelli precedenti e crittografa il valore dell&quot;argomento di ogni chiamata di procedura remota."
  syntax:
    content: PktPrivacy
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
