### YamlMime:ManagedReference
items:
- uid: System.Configuration.UriSection
  id: UriSection
  children:
  - System.Configuration.UriSection.#ctor
  - System.Configuration.UriSection.Idn
  - System.Configuration.UriSection.IriParsing
  - System.Configuration.UriSection.Properties
  - System.Configuration.UriSection.SchemeSettings
  langs:
  - csharp
  name: UriSection
  nameWithType: UriSection
  fullName: System.Configuration.UriSection
  type: Class
  summary: "Rappresenta la sezione Uri all&quot;interno di un file di configurazione."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) e i nomi di dominio internazionali.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI e IDN. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       Le impostazioni di configurazione per IRI e IDN possono essere recuperate utilizzando la classe UriSection."
  syntax:
    content: 'public sealed class UriSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Configuration.UriSection.#ctor
  id: '#ctor'
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: UriSection()
  nameWithType: UriSection.UriSection()
  fullName: System.Configuration.UriSection.UriSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.UriSection&quot;> </xref> classe."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) e i nomi di dominio internazionali.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI e IDN. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       Le impostazioni di configurazione per IRI e IDN possono essere recuperate tramite la <xref:System.Configuration.UriSection>classe.</xref:System.Configuration.UriSection>       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public UriSection ();
    parameters: []
  overload: System.Configuration.UriSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.Idn
  id: Idn
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: Idn
  nameWithType: UriSection.Idn
  fullName: System.Configuration.UriSection.Idn
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> oggetto che contiene l&quot;impostazione di configurazione per nome IDN (International Domain) l&quot;elaborazione nel &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) e i nomi di dominio internazionali.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI e IDN. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       Le impostazioni di configurazione per IRI e IDN possono essere recuperate tramite la <xref:System.Configuration.UriSection>classe.</xref:System.Configuration.UriSection> La proprietà di Idn restituisce l&quot;impostazione di configurazione IDN elaborazione nella <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>       Elaborazione IRI deve essere abilitato per l&quot;elaborazione possibili IDN. Se l&quot;elaborazione di IRI è disabilitata, elaborazione IDN verrà configurata l&quot;impostazione predefinita, in cui viene utilizzato il comportamento di .NET Framework 2.0 per la compatibilità e non vengono utilizzati i nomi IDN.       L&quot;attributo IDN (Internationalized Domain Name) controlla solo l&quot;elaborazione IDN. Per impostazione predefinita, viene eseguita ogni altra elaborazione IRI (la normalizzazione dei caratteri, ad esempio).       L&quot;impostazione di configurazione per il <xref:System.Configuration.IdnElement>verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IdnElement> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public System.Configuration.IdnElement Idn { get; }
    return:
      type: System.Configuration.IdnElement
      description: "L&quot;impostazione di configurazione per nome IDN (International Domain) l&quot;elaborazione nel &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  overload: System.Configuration.UriSection.Idn*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.IriParsing
  id: IriParsing
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: IriParsing
  nameWithType: UriSection.IriParsing
  fullName: System.Configuration.UriSection.IriParsing
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> oggetto che contiene l&quot;impostazione di configurazione per risorse identificatori analisi IRI (International) nei &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "Esistente <xref:System.Uri?displayProperty=fullName>classe è stata estesa per fornire supporto per gli identificatori IRI (International Resource) e i nomi di dominio internazionali.</xref:System.Uri?displayProperty=fullName> Gli utenti non visualizzeranno qualsiasi modifica rispetto al comportamento di .NET Framework 2.0 a meno che non consentono in modo specifico IRI e IDN. Ciò garantisce la compatibilità delle applicazioni con le versioni precedenti di .NET Framework.       Le impostazioni di configurazione per IRI e IDN possono essere recuperate tramite la <xref:System.Configuration.UriSection>classe.</xref:System.Configuration.UriSection> La proprietà IriParsing restituisce l&quot;impostazione di configurazione per l&quot;analisi IRI nella <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>       Elaborazione IRI deve essere abilitato per l&quot;elaborazione possibili IDN. Se l&quot;elaborazione di IRI è disabilitata, elaborazione IDN verrà configurata l&quot;impostazione predefinita, in cui viene utilizzato il comportamento di .NET Framework 2.0 per la compatibilità e non vengono utilizzati i nomi IDN.       L&quot;attributo IDN (Internationalized Domain Name) controlla solo l&quot;elaborazione IDN. Per impostazione predefinita, viene eseguita ogni altra elaborazione IRI (la normalizzazione dei caratteri, ad esempio).       L&quot;impostazione di configurazione per il <xref:System.Configuration.IriParsingElement>verranno letti una volta quando il primo <xref:System.Uri?displayProperty=fullName>classe viene costruita.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Modifiche alle impostazioni di configurazione dopo tale periodo di tempo vengono ignorate.       Per ulteriori informazioni sul supporto IRI, vedere la sezione Osservazioni per la <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public System.Configuration.IriParsingElement IriParsing { get; }
    return:
      type: System.Configuration.IriParsingElement
      description: "L&quot;impostazione di configurazione per risorse identificatori analisi IRI (International) nei &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  overload: System.Configuration.UriSection.IriParsing*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.Properties
  id: Properties
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: Properties
  nameWithType: UriSection.Properties
  fullName: System.Configuration.UriSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Configuration.UriSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.SchemeSettings
  id: SchemeSettings
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
  fullName: System.Configuration.UriSection.SchemeSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene un <xref href=&quot;System.Configuration.SchemeSettingElementCollection&quot;> </xref> oggetto che contiene le impostazioni di analisi dello schema nella configurazione di &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "La proprietà SchemeSettings non è generica. Solo il genericUriParserOptions = &quot;DontUnescapePathDotsAndSlashes&quot; impostazione di configurazione per gli schemi HTTP e HTTPS sono supportati. Tutte le altre impostazioni vengono ignorate."
  syntax:
    content: public System.Configuration.SchemeSettingElementCollection SchemeSettings { get; }
    return:
      type: System.Configuration.SchemeSettingElementCollection
      description: "Le impostazioni di analisi dello schema nella configurazione di &lt;xref:System.Uri?displayProperty=fullName&gt; classe"
  overload: System.Configuration.UriSection.SchemeSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.UriSection.#ctor
  parent: System.Configuration.UriSection
  isExternal: false
  name: UriSection()
  nameWithType: UriSection.UriSection()
  fullName: System.Configuration.UriSection.UriSection()
- uid: System.Configuration.UriSection.Idn
  parent: System.Configuration.UriSection
  isExternal: false
  name: Idn
  nameWithType: UriSection.Idn
  fullName: System.Configuration.UriSection.Idn
- uid: System.Configuration.IdnElement
  parent: System.Configuration
  isExternal: false
  name: IdnElement
  nameWithType: IdnElement
  fullName: System.Configuration.IdnElement
- uid: System.Configuration.UriSection.IriParsing
  parent: System.Configuration.UriSection
  isExternal: false
  name: IriParsing
  nameWithType: UriSection.IriParsing
  fullName: System.Configuration.UriSection.IriParsing
- uid: System.Configuration.IriParsingElement
  parent: System.Configuration
  isExternal: false
  name: IriParsingElement
  nameWithType: IriParsingElement
  fullName: System.Configuration.IriParsingElement
- uid: System.Configuration.UriSection.Properties
  parent: System.Configuration.UriSection
  isExternal: false
  name: Properties
  nameWithType: UriSection.Properties
  fullName: System.Configuration.UriSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.UriSection.SchemeSettings
  parent: System.Configuration.UriSection
  isExternal: false
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
  fullName: System.Configuration.UriSection.SchemeSettings
- uid: System.Configuration.SchemeSettingElementCollection
  parent: System.Configuration
  isExternal: false
  name: SchemeSettingElementCollection
  nameWithType: SchemeSettingElementCollection
  fullName: System.Configuration.SchemeSettingElementCollection
- uid: System.Configuration.UriSection.#ctor*
  parent: System.Configuration.UriSection
  isExternal: false
  name: UriSection
  nameWithType: UriSection.UriSection
- uid: System.Configuration.UriSection.Idn*
  parent: System.Configuration.UriSection
  isExternal: false
  name: Idn
  nameWithType: UriSection.Idn
- uid: System.Configuration.UriSection.IriParsing*
  parent: System.Configuration.UriSection
  isExternal: false
  name: IriParsing
  nameWithType: UriSection.IriParsing
- uid: System.Configuration.UriSection.Properties*
  parent: System.Configuration.UriSection
  isExternal: false
  name: Properties
  nameWithType: UriSection.Properties
- uid: System.Configuration.UriSection.SchemeSettings*
  parent: System.Configuration.UriSection
  isExternal: false
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
