### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.StreamChangeCallback
  id: StreamChangeCallback
  langs:
  - csharp
  name: StreamChangeCallback
  nameWithType: StreamChangeCallback
  fullName: System.Configuration.Internal.StreamChangeCallback
  type: Delegate
  summary: "Rappresenta un metodo per gli host da chiamare quando un flusso monitorato è stato modificato."
  syntax:
    content: public delegate void StreamChangeCallback(string streamName);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
