### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsAttributeDictionary
  id: SettingsAttributeDictionary
  children:
  - System.Configuration.SettingsAttributeDictionary.#ctor
  - System.Configuration.SettingsAttributeDictionary.#ctor(System.Configuration.SettingsAttributeDictionary)
  langs:
  - csharp
  name: SettingsAttributeDictionary
  nameWithType: SettingsAttributeDictionary
  fullName: System.Configuration.SettingsAttributeDictionary
  type: Class
  summary: "Rappresenta una raccolta di coppie chiave/valore utilizzato per descrivere un oggetto di configurazione, nonché un <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> oggetto."
  remarks: "L&quot;oggetto SettingsAttributeDictionary eredita il <xref:System.Collections.Hashtable>oggetto.</xref:System.Collections.Hashtable> L&quot;oggetto SettingsAttributeDictionary viene utilizzato per descrivere un oggetto di configurazione, ad esempio il <xref:System.Configuration.SettingsProperty>oggetto.</xref:System.Configuration.SettingsProperty>"
  syntax:
    content: 'public class SettingsAttributeDictionary : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net462
- uid: System.Configuration.SettingsAttributeDictionary.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsAttributeDictionary
  langs:
  - csharp
  name: SettingsAttributeDictionary()
  nameWithType: SettingsAttributeDictionary.SettingsAttributeDictionary()
  fullName: System.Configuration.SettingsAttributeDictionary.SettingsAttributeDictionary()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsAttributeDictionary&quot;> </xref> classe."
  syntax:
    content: public SettingsAttributeDictionary ();
    parameters: []
  overload: System.Configuration.SettingsAttributeDictionary.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsAttributeDictionary.#ctor(System.Configuration.SettingsAttributeDictionary)
  id: '#ctor(System.Configuration.SettingsAttributeDictionary)'
  parent: System.Configuration.SettingsAttributeDictionary
  langs:
  - csharp
  name: SettingsAttributeDictionary(SettingsAttributeDictionary)
  nameWithType: SettingsAttributeDictionary.SettingsAttributeDictionary(SettingsAttributeDictionary)
  fullName: System.Configuration.SettingsAttributeDictionary.SettingsAttributeDictionary(SettingsAttributeDictionary)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsAttributeDictionary&quot;> </xref> classe."
  syntax:
    content: public SettingsAttributeDictionary (System.Configuration.SettingsAttributeDictionary attributes);
    parameters:
    - id: attributes
      type: System.Configuration.SettingsAttributeDictionary
      description: "Raccolta di coppie chiave/valore correlate alle impostazioni di configurazione."
  overload: System.Configuration.SettingsAttributeDictionary.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsAttributeDictionary.#ctor
  parent: System.Configuration.SettingsAttributeDictionary
  isExternal: false
  name: SettingsAttributeDictionary()
  nameWithType: SettingsAttributeDictionary.SettingsAttributeDictionary()
  fullName: System.Configuration.SettingsAttributeDictionary.SettingsAttributeDictionary()
- uid: System.Configuration.SettingsAttributeDictionary.#ctor(System.Configuration.SettingsAttributeDictionary)
  parent: System.Configuration.SettingsAttributeDictionary
  isExternal: false
  name: SettingsAttributeDictionary(SettingsAttributeDictionary)
  nameWithType: SettingsAttributeDictionary.SettingsAttributeDictionary(SettingsAttributeDictionary)
  fullName: System.Configuration.SettingsAttributeDictionary.SettingsAttributeDictionary(SettingsAttributeDictionary)
- uid: System.Configuration.SettingsAttributeDictionary
  parent: System.Configuration
  isExternal: false
  name: SettingsAttributeDictionary
  nameWithType: SettingsAttributeDictionary
  fullName: System.Configuration.SettingsAttributeDictionary
- uid: System.Configuration.SettingsAttributeDictionary.#ctor*
  parent: System.Configuration.SettingsAttributeDictionary
  isExternal: false
  name: SettingsAttributeDictionary
  nameWithType: SettingsAttributeDictionary.SettingsAttributeDictionary
