### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  id: XmlFormatExtensionPrefixAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  type: Class
  summary: "Specifica dei nomi XML e il prefisso dello spazio dei nomi XML da utilizzare per un&quot;estensione di formato di descrizione del servizio all&quot;interno di una descrizione del servizio. Questa classe non può essere ereditata."
  remarks: "Un&quot;estensione di formato di descrizione del servizio estende la modalità di generazione di una descrizione del servizio per un servizio Web XML creato con ASP.NET. In particolare, un&quot;estensione di formato della descrizione di servizio aggiunge elementi XML per la descrizione del servizio. Ciò è utile quando un&quot;estensione SOAP viene compilata per l&quot;esecuzione sul lato client e server di un servizio Web XML, come informazioni sulle estensioni SOAP non sono state inserite nella descrizione del servizio. Se si aggiungono informazioni sull&quot;estensione SOAP alla descrizione del servizio, un client può interpretare che deve eseguire l&quot;estensione SOAP specifica. Un esempio di un&quot;estensione SOAP che deve essere eseguito nel client e server è un&quot;estensione SOAP di crittografia. Se un&quot;estensione SOAP di crittografia viene eseguita solo sul server e i valori vengono crittografati prima di inviarli al client, il client deve avere l&quot;estensione SOAP per decrittografare il messaggio SOAP in esecuzione. In caso contrario, il client non è possibile elaborare il valore restituito.       Utilizzare la procedura seguente per compilare un&quot;estensione di formato di descrizione del servizio: 1.  Creare una classe che deriva da <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Applicare un <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>alla classe e specificare i punti di estensione in cui è necessario eseguire l&quot;estensione di formato.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Se si desidera, applicare un <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>alla classe e specificare un membro all&quot;interno della classe che agisce come un nuovo punto di estensione.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>      4.  Facoltativamente, applicare un XmlFormatExtensionPrefixAttribute alla classe e specificare il prefisso dello spazio dei nomi XML da associare agli elementi XML generati dall&quot;estensione di formato della descrizione del servizio.      5.  Configurare l&quot;estensione di formato per l&quot;esecuzione all&quot;interno di `serviceDescriptionFormatExtensionTypes` sezione del file di configurazione."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_2_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_2_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]

      public sealed class XmlFormatExtensionPrefixAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> classe."
  syntax:
    content: public XmlFormatExtensionPrefixAttribute ();
    parameters: []
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> classe, impostando lo spazio dei nomi XML e un prefisso dello spazio dei nomi XML per un&quot;estensione di formato di descrizione del servizio."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/31a2fbe2-95e2-473f-8282-_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/31a2fbe2-95e2-473f-8282-_1.vb)]
  syntax:
    content: public XmlFormatExtensionPrefixAttribute (string prefix, string ns);
    parameters:
    - id: prefix
      type: System.String
      description: "Il prefisso dello spazio dei nomi XML associato a un&quot;estensione di formato di descrizione del servizio."
    - id: ns
      type: System.String
      description: "Lo spazio dei nomi XML associata a un&quot;estensione di formato di descrizione del servizio."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  id: Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Ottiene o imposta lo spazio dei nomi XML associata a un&quot;estensione di formato di descrizione del servizio."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_4_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_4_1.vb)]
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "Lo spazio dei nomi XML associata a un&quot;estensione di formato di descrizione del servizio."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  id: Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Ottiene o imposta il prefisso dello spazio dei nomi XML associato a un&quot;estensione di formato di descrizione del servizio."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_0_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_0_1.vb)]
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "Il prefisso dello spazio dei nomi XML associato a un&quot;estensione di formato di descrizione del servizio."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
