### YamlMime:ManagedReference
items:
- uid: System.Configuration.RegexStringValidatorAttribute
  id: RegexStringValidatorAttribute
  children:
  - System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  - System.Configuration.RegexStringValidatorAttribute.Regex
  - System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute
  fullName: System.Configuration.RegexStringValidatorAttribute
  type: Class
  summary: "Indica in modo dichiarativo a .NET Framework per eseguire la convalida delle stringhe in una proprietà di configurazione usando un&quot;espressione regolare. Questa classe non può essere ereditata."
  remarks: "Utilizzare il RegexStringValidatorAttribute per decorare una proprietà di configurazione, che indicherà a .NET Framework per convalidare la proprietà utilizzando il <xref:System.Configuration.RegexStringValidator>e passare il valore dei parametri di decorazione.</xref:System.Configuration.RegexStringValidator>       È possibile applicare gli oggetti RegexStringValidatorAttribute e solo i tipi di proprietà."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the RegexStringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/t-system.configuration.r_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/t-system.configuration.r_2_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class RegexStringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.RegexStringValidatorAttribute&quot;> </xref> oggetto."
  remarks: "Il `regex` parametro contiene il criterio di espressione regolare che deve corrispondere una stringa prima che può essere assegnato alla proprietà dell&quot;elemento di configurazione decorata.       Utilizzare questo costruttore nel modello con gli attributi per garantire che il valore stringa assegnato alla proprietà correlata contenga solo i caratteri consentiti."
  example:
  - "The following example shows how to use the RegexStringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/m-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/m-system.configuration.r_0_1.cs)]"
  syntax:
    content: public RegexStringValidatorAttribute (string regex);
    parameters:
    - id: regex
      type: System.String
      description: "Stringa da usare per la convalida di espressione regolare."
  overload: System.Configuration.RegexStringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  id: Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene la stringa utilizzata per eseguire la convalida di espressione regolare."
  remarks: ''
  example:
  - "The following example shows how to use the Regex property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/visualbasic/p-system.configuration.r_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/csharp/p-system.configuration.r_1_1.cs)]"
  syntax:
    content: public string Regex { get; }
    return:
      type: System.String
      description: "Stringa contenente l&quot;espressione regolare utilizzata per filtrare la stringa assegnata alla proprietà dell&quot;elemento di configurazione decorata."
  overload: System.Configuration.RegexStringValidatorAttribute.Regex*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un&quot;istanza di <xref href=&quot;System.Configuration.RegexStringValidator&quot;> </xref> classe."
  remarks: "Utilizzare la proprietà ValidatorInstance per eseguire la convalida delle stringhe chiamando il relativo <xref:System.Configuration.StringValidator.Validate%2A>metodo.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance method.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/visualbasic/p-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/csharp/p-system.configuration.r_0_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Il <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> istanza del validator."
  overload: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.Regex*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
