### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Agevola la lettura di <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> sezione di un file di configurazione e la creazione di un&quot;istanza del <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> classe che contiene le informazioni sulle funzionalità per il browser client."
  remarks: "La classe HttpCapabilitiesSectionHandler e i corrispondenti `<browserCaps>` sezione di configurazione sono state deprecate in .NET Framework versione 2.0. Il metodo preferito per la gestione delle funzionalità del browser consiste nell&quot;utilizzare Visualizzatore file di definizione che vengono compilati per l&quot;utilizzo da una <xref:System.Web.Configuration.BrowserCapabilitiesFactory>classe.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> L&quot;obiettivo di entrambe le metodologie di configurazione consiste nel generare un&quot;istanza della <xref:System.Web.HttpBrowserCapabilities>classe che è possibile accedere dalla <xref:System.Web.HttpRequest.Browser%2A>proprietà di <xref:System.Web.HttpRequest>classe.</xref:System.Web.HttpRequest> </xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities>       Utilizzando i file di definizione del browser per archiviare le funzionalità del browser offre vantaggi rispetto l&quot;alternativa. E offre prestazioni migliorate in quanto le informazioni sulla definizione del browser viene analizzati dal file di configurazione XML e compilati in una classe anticipatamente. I file di definizione del browser sono inoltre più semplici da gestire:-le definizioni sono gerarchiche e quindi si basano meno su espressioni regolari per determinare le funzionalità del browser.      -Le definizioni possono essere organizzate in più file, rendendole più semplici da gestire.      -Le definizioni possono essere specificate in qualsiasi livello, a livello di un determinato livello di applicazione o Machine. config. In questo modo si elimina la necessità di copiare l&quot;intero set di definizioni per le funzionalità di un browser specifico viene sottoposto a override."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> classe."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Crea un&quot;istanza di <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> classe che contiene le informazioni sulle funzionalità per il browser client."
  remarks: "Questa classe deriva i dati di definizione del browser dal `<browserCaps>` sezione di configurazione. In questa sezione è deprecata in .NET Framework versione 2.0."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Il nodo di configurazione padre."
    - id: configurationContext
      type: System.Object
      description: "Il contesto di configurazione del file di configurazione corrente."
    - id: section
      type: System.Xml.XmlNode
      description: "La sezione del file di configurazione che contiene le informazioni."
    return:
      type: System.Object
      description: "Un&quot;istanza di <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> che contiene le informazioni sulle funzionalità per il browser client."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
