### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement
  id: XPathMessageFilterElement
  children:
  - System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  - System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  - System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  - System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  langs:
  - csharp
  name: XPathMessageFilterElement
  nameWithType: XPathMessageFilterElement
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che viene utilizzato la registrazione dei messaggi. Questa classe non può essere ereditata."
  remarks: "Un filtro XPath è una query su un documento XML definito da un&quot;espressione di XPath 1.0.       È possibile aggiungere filtri XPath per il `messageLogging` sezione per registrare messaggi specifici a livello di trasporto e servizio. Se viene definito nessun filtro, tutti i messaggi vengono registrati. I filtri vengono applicati solo alle intestazioni del messaggio. Il corpo viene ignorato. [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]Ignora il corpo del messaggio per migliorare le prestazioni. Se si desidera filtrare in base al contenuto del corpo, è possibile creare un listener personalizzato con un filtro che esegue questa operazione.       Quando è abilitata la registrazione dei messaggi di trasporto (<xref:System.ServiceModel.Configuration.MessageLoggingElement.LogMessagesAtTransportLevel%2A> è `true`), vengono registrati solo i messaggi corrispondenti ai filtri.</xref:System.ServiceModel.Configuration.MessageLoggingElement.LogMessagesAtTransportLevel%2A>"
  syntax:
    content: 'public sealed class XPathMessageFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: XPathMessageFilterElement()
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.XPathMessageFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> classe."
  syntax:
    content: public XPathMessageFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "Da aggiungere."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  id: Filter
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il filtro XPath definito."
  syntax:
    content: public System.ServiceModel.Dispatcher.XPathMessageFilter Filter { get; set; }
    return:
      type: System.ServiceModel.Dispatcher.XPathMessageFilter
      description: "Il filtro XPath definito."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  langs:
  - csharp
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement (System.Xml.XmlWriter writer, string elementName);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Da aggiungere."
    - id: elementName
      type: System.String
      description: "Da aggiungere."
    return:
      type: System.Boolean
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: XPathMessageFilterElement()
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.XPathMessageFilterElement()
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter
- uid: System.ServiceModel.Dispatcher.XPathMessageFilter
  parent: System.ServiceModel.Dispatcher
  isExternal: false
  name: XPathMessageFilter
  nameWithType: XPathMessageFilter
  fullName: System.ServiceModel.Dispatcher.XPathMessageFilter
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement(XmlWriter,String)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: XPathMessageFilterElement
  nameWithType: XPathMessageFilterElement.XPathMessageFilterElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: DeserializeElement
  nameWithType: XPathMessageFilterElement.DeserializeElement
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Filter*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Filter
  nameWithType: XPathMessageFilterElement.Filter
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.Properties*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: Properties
  nameWithType: XPathMessageFilterElement.Properties
- uid: System.ServiceModel.Configuration.XPathMessageFilterElement.SerializeToXmlElement*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElement
  isExternal: false
  name: SerializeToXmlElement
  nameWithType: XPathMessageFilterElement.SerializeToXmlElement
