### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.SettingsBindableAttribute
  id: SettingsBindableAttribute
  children:
  - System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  - System.ComponentModel.SettingsBindableAttribute.Bindable
  - System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  - System.ComponentModel.SettingsBindableAttribute.GetHashCode
  - System.ComponentModel.SettingsBindableAttribute.No
  - System.ComponentModel.SettingsBindableAttribute.Yes
  langs:
  - csharp
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
  type: Class
  summary: "Specifica quando una proprietà del componente può essere associata a un&quot;impostazione dell&quot;applicazione."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsBindableAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ComponentModel.SettingsBindableAttribute&quot;> </xref> classe."
  syntax:
    content: public SettingsBindableAttribute (bool bindable);
    parameters:
    - id: bindable
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Per specificare che una proprietà è appropriata per associare le impostazioni. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  id: Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
  type: Property
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Ottiene un valore che indica se è appropriata per associare le impostazioni per una proprietà."
  syntax:
    content: public bool Bindable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà è appropriata per associare le impostazioni. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.Bindable*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Restituisce un valore che indica se questa istanza è uguale a un oggetto specificato."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "Un <xref:System.Object>da confrontare con questa istanza o un riferimento null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> in Visual Basic).</xref:System.Object>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <code> obj </code> è uguale al tipo e il valore di questa istanza; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  id: GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Restituisce il codice hash per questa istanza."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Codice hash di un intero con segno a 32 bit."
  overload: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.No
  id: No
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Specifica che una proprietà non è appropriata per l&quot;associazione delle impostazioni."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute No;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  id: Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Specifica che una proprietà è appropriata per l&quot;associazione delle impostazioni."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute Yes;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ComponentModel.SettingsBindableAttribute.No
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
- uid: System.ComponentModel.SettingsBindableAttribute
  parent: System.ComponentModel
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals
  nameWithType: SettingsBindableAttribute.Equals
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode
  nameWithType: SettingsBindableAttribute.GetHashCode
