### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.SupportedRuntimeMissingException
  id: SupportedRuntimeMissingException
  children:
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  langs:
  - csharp
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException
  fullName: System.Deployment.Application.SupportedRuntimeMissingException
  type: Class
  summary: "Questa eccezione viene generata quando non viene trovata una versione runtime compatibile con questa applicazione."
  syntax:
    content: 'public class SupportedRuntimeMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> classe con un messaggio fornito dal sistema che descrive l&quot;errore."
  remarks: "Questo costruttore inizializza la <xref:System.Exception.Message%2A>proprietà della nuova istanza di un messaggio fornito dal sistema che descrive l&quot;errore, ad esempio &quot;Eccezione mancante Runtime&quot;.</xref:System.Exception.Message%2A> Questo messaggio prende in considerazione le impostazioni cultura correnti.       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore localizzato. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException ();
    parameters: []
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> classe con un messaggio specificato che descrive l&quot;errore."
  remarks: "Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Stringa del messaggio di errore specificata `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio che descrive l&quot;eccezione. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso."
  syntax:
    content: protected SupportedRuntimeMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Oggetto che contiene i dati oggetto serializzati."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Informazioni contestuali sull&quot;origine o destinazione."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> classe con un messaggio di errore specificato e un riferimento all&quot;eccezione interna che è la causa dell&quot;eccezione corrente."
  remarks: "Un&quot;eccezione generata come risultato diretto di un&quot;eccezione precedente deve includere un riferimento all&quot;eccezione precedente nella <xref:System.Exception.InnerException%2A>proprietà.</xref:System.Exception.InnerException%2A> Il <xref:System.Exception.InnerException%2A>proprietà restituisce lo stesso valore passato al costruttore o `null` se il <xref:System.Exception.InnerException%2A>proprietà non fornisce il valore di eccezione interna al costruttore.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Stringa del messaggio di errore specificata `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio che descrive l&quot;eccezione. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente."
    - id: innerException
      type: System.Exception
      description: "Eccezione che è la causa dell&quot;eccezione corrente. Se il `innerException` parametro non è <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, l&quot;eccezione corrente viene generata in un <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blocco che gestisce l&quot;eccezione interna."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Oggetto che contiene i dati oggetto serializzati."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Informazioni contestuali sull&quot;origine o destinazione."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  id: SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene la versione del runtime in cui è possibile installare ed eseguire questa applicazione."
  syntax:
    content: public string SupportedRuntimeVersion { get; }
    return:
      type: System.String
      description: "Stringa che contiene il numero di versione del runtime."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: SupportedRuntimeMissingException.GetObjectData
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
