### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.HttpMessageSettings
  id: HttpMessageSettings
  children:
  - System.ServiceModel.Channels.HttpMessageSettings.#ctor
  - System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  - System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  langs:
  - csharp
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
  type: Class
  summary: "Supporta un parametro di associazione che può essere utilizzato con il trasporto HTTP per specificare l&quot;impostazione per HttpMessage."
  syntax:
    content: 'public sealed class HttpMessageSettings : IEquatable<System.ServiceModel.Channels.HttpMessageSettings>'
  inheritance:
  - System.Object
  implements:
  - System.IEquatable<System.ServiceModel.Channels.HttpMessageSettings>
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Channels.HttpMessageSettings&quot;> </xref> classe."
  syntax:
    content: public HttpMessageSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  id: Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Determina se l&quot;oggetto specificato è uguale all&quot;oggetto corrente."
  syntax:
    content: public bool Equals (System.ServiceModel.Channels.HttpMessageSettings other);
    parameters:
    - id: other
      type: System.ServiceModel.Channels.HttpMessageSettings
      description: "Oggetto da confrontare con l&quot;oggetto corrente."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;oggetto specificato è uguale all&quot;oggetto corrente. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  id: HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  langs:
  - csharp
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Ottiene o imposta un valore che indica se il trasporto HTTP deve supportare <xref href=&quot;System.Net.Http.HttpRequestMessage&quot;> </xref> e <xref href=&quot;System.Net.Http.HttpResponseMessage&quot;> </xref> istanze."
  syntax:
    content: public bool HttpMessagesSupported { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il trasporto HTTP supporta <xref href=&quot;System.Net.Http.HttpRequestMessage&quot;> </xref> e <xref href=&quot;System.Net.Http.HttpResponseMessage&quot;> </xref> istanze; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings()
  nameWithType: HttpMessageSettings.HttpMessageSettings()
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessageSettings()
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals(System.ServiceModel.Channels.HttpMessageSettings)
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals(HttpMessageSettings)
  nameWithType: HttpMessageSettings.Equals(HttpMessageSettings)
  fullName: System.ServiceModel.Channels.HttpMessageSettings.Equals(HttpMessageSettings)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.HttpMessageSettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings
  fullName: System.ServiceModel.Channels.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
  fullName: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported
- uid: System.ServiceModel.Channels.HttpMessageSettings.#ctor*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessageSettings
  nameWithType: HttpMessageSettings.HttpMessageSettings
- uid: System.ServiceModel.Channels.HttpMessageSettings.Equals*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: Equals
  nameWithType: HttpMessageSettings.Equals
- uid: System.ServiceModel.Channels.HttpMessageSettings.HttpMessagesSupported*
  parent: System.ServiceModel.Channels.HttpMessageSettings
  isExternal: false
  name: HttpMessagesSupported
  nameWithType: HttpMessageSettings.HttpMessagesSupported
