### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  id: CheckForUpdateCompletedEventArgs
  children:
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  langs:
  - csharp
  name: CheckForUpdateCompletedEventArgs
  nameWithType: CheckForUpdateCompletedEventArgs
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  type: Class
  summary: "Rappresenta informazioni dettagliate sull&quot;aggiornamento ottenute tramite una chiamata a <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*>"
  remarks: "Con CheckForUpdateCompletedEventArgs, è possibile decidere se aggiornare l&quot;applicazione ClickOnce in base alle informazioni relative all&quot;ultima versione. <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A>Restituisce un valore booleano che indica se si tratta di un nuovo aggiornamento.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> Il <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A>proprietà fornisce il numero di versione della nuova versione, mentre <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A>fornisce la versione meno recente che l&quot;utente deve essere installato nel computer.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A> <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A>indica se l&quot;aggiornamento più recente è necessario per l&quot;utente.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> Infine, <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>indica le dimensioni totali dell&quot;aggiornamento.</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>"
  example:
  - "The following code example uses <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/t-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: 'public class CheckForUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene il numero di versione dell&quot;ultima versione installata."
  remarks: "È possibile utilizzare AvailableVersion per decidere se installare l&quot;aggiornamento in base alla gravità dell&quot;aggiornamento. Se, ad esempio, solo il <xref:System.Version.Build%2A>o <xref:System.Version.Revision%2A>sono state modificate le proprietà della versione, l&quot;applicazione potrebbe non essere necessario aggiornare fino a quando non la <xref:System.Version.Minor%2A>o <xref:System.Version.Major%2A>Modifica proprietà.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "Il <xref:System.Version>esprimere la versione principale, secondaria, i numeri di build e revisione della versione più recente.</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene un valore che indica se l&quot;aggiornamento deve essere installato."
  remarks: "Quando si distribuisce un aggiornamento per l&quot;applicazione ClickOnce, è possibile contrassegnarlo come un aggiornamento obbligatorio, la segnalazione per l&quot;applicazione che deve aggiornare immediatamente. È opportuno contrassegnare l&quot;aggiornamento se la versione più recente contiene un aggiornamento critico o se non è compatibile con i formati di file o origini dati back-end utilizzate per la versione precedente."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/2aa4f4df-e487-4c83-87b0-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;aggiornamento è obbligatorio. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene la versione minima che l&quot;utente deve avere installato nel computer."
  remarks: "Le applicazioni possono perdere aggiornamenti necessari quando un utente assume un&quot;assegnazione speciale o non utilizza il computer per settimane o mesi. Utilizzare MinimumRequiredVersion per determinare se l&quot;utente non è stata aggiornata l&quot;applicazione in un po&quot; di tempo e uno o più aggiornamenti necessari."
  example:
  - "The following code example calls <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync%2A>, and forces an application update if MinimumRequiredVersion is greater than <xref:System.Deployment.Application.ApplicationDeployment.CurrentVersion%2A>.  \n  \n [!code-cs[ClickOnceAPI#10](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#10)]\n [!code-vb[ClickOnceAPI#10](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#10)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "Oggetto <xref:System.Version>oggetto che indica la versione meno recente che è necessario installare tutti gli utenti.</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Indica se è disponibile un aggiornamento installato."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether or not there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/847038a4-fd95-4e16-a133-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se è disponibile; nuova versione dell&quot;applicazione in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene la dimensione dell&quot;aggiornamento disponibile."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "Un <xref:System.Int64>che descrive le dimensioni, in byte, dell&quot;aggiornamento disponibile.</xref:System.Int64> Se è disponibile alcun aggiornamento, restituisce 0."
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
