### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: "InstallEventHandler"
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: Represents the method that will handle the <see cref="E:System.Configuration.Install.Installer.BeforeInstall"></see>, <see cref="E:System.Configuration.Install.Installer.AfterInstall"></see>, <see cref="E:System.Configuration.Install.Installer.Committing"></see>, <see cref="E:System.Configuration.Install.Installer.Committed"></see>, <see cref="E:System.Configuration.Install.Installer.BeforeRollback"></see>, <see cref="E:System.Configuration.Install.Installer.AfterRollback"></see>, <see cref="E:System.Configuration.Install.Installer.BeforeUninstall"></see>, or <see cref="E:System.Configuration.Install.Installer.AfterUninstall"></see> event of an <see cref="T:System.Configuration.Install.Installer"></see>.
  remarks: When you create an InstallEventHandler delegate, you identify the method that will handle the event. To associate the event with your event handler, add an instance of the delegate to the event. The event handler is called whenever the event occurs, unless you remove the delegate. For more information about event handler delegates, see [Events](../Topic/Handling%20and%20Raising%20Events.md).
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: "System.Delegate"
