### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement
  id: ServiceThrottlingElement
  children:
  - System.ServiceModel.Configuration.ServiceThrottlingElement.#ctor
  - System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType
  - System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior
  - System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls
  - System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances
  - System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions
  - System.ServiceModel.Configuration.ServiceThrottlingElement.Properties
  langs:
  - csharp
  name: ServiceThrottlingElement
  nameWithType: ServiceThrottlingElement
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica il meccanismo di limitazione delle richieste di [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class ServiceThrottlingElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: ServiceThrottlingElement()
  nameWithType: ServiceThrottlingElement.ServiceThrottlingElement()
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.ServiceThrottlingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.ServiceThrottlingElement&quot;> </xref> classe."
  syntax:
    content: public ServiceThrottlingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: ServiceThrottlingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene il tipo di questo elemento di configurazione del comportamento."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "Il tipo di comportamento."
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceThrottlingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia il contenuto dell&quot;elemento di configurazione specificato in questo elemento di configurazione."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "L&quot;elemento di configurazione da copiare."
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: ServiceThrottlingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls
  id: MaxConcurrentCalls
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: MaxConcurrentCalls
  nameWithType: ServiceThrottlingElement.MaxConcurrentCalls
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che specifica il numero massimo di chiamate simultanee a una singola istanza del servizio."
  remarks: "Le chiamate in eccesso vengono messe in coda. L&quot;impostazione di questo valore su 0 equivale a impostarlo su <xref:System.Int32>.</xref:System.Int32>"
  syntax:
    content: public int MaxConcurrentCalls { get; set; }
    return:
      type: System.Int32
      description: "Il numero massimo di chiamate simultanee a una singola istanza del servizio. Il valore predefinito è <xref:System.Int32>.</xref:System.Int32>"
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances
  id: MaxConcurrentInstances
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: MaxConcurrentInstances
  nameWithType: ServiceThrottlingElement.MaxConcurrentInstances
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che specifica il numero massimo di istanze simultanee del servizio."
  remarks: "Le richieste per creare istanze aggiuntive vengono messe in coda e completate quando diventa disponibile uno slot sotto il limite."
  syntax:
    content: public int MaxConcurrentInstances { get; set; }
    return:
      type: System.Int32
      description: "Il numero massimo di istanze del servizio simultanee. Il valore predefinito è 26."
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions
  id: MaxConcurrentSessions
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: MaxConcurrentSessions
  nameWithType: ServiceThrottlingElement.MaxConcurrentSessions
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che specifica il numero massimo di connessioni simultanee a un singolo servizio."
  remarks: "Il servizio accetta le connessioni che superano il limite. Tuttavia, solo i canali sotto il limite sono attivi e i messaggi vengono letti solo dai canali attivi. L&quot;impostazione di questa proprietà su 0 equivale a impostarlo su <xref:System.Int32>.</xref:System.Int32>"
  syntax:
    content: public int MaxConcurrentSessions { get; set; }
    return:
      type: System.Int32
      description: "Numero massimo di connessioni simultanee a un singolo servizio. Il valore predefinito è <xref:System.Int32>.</xref:System.Int32>"
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceThrottlingElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: ServiceThrottlingElement()
  nameWithType: ServiceThrottlingElement.ServiceThrottlingElement()
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.ServiceThrottlingElement()
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceThrottlingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceThrottlingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: ServiceThrottlingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentCalls
  nameWithType: ServiceThrottlingElement.MaxConcurrentCalls
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentInstances
  nameWithType: ServiceThrottlingElement.MaxConcurrentInstances
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentSessions
  nameWithType: ServiceThrottlingElement.MaxConcurrentSessions
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: Properties
  nameWithType: ServiceThrottlingElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: ServiceThrottlingElement
  nameWithType: ServiceThrottlingElement.ServiceThrottlingElement
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.BehaviorType*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceThrottlingElement.BehaviorType
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CopyFrom*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: CopyFrom
  nameWithType: ServiceThrottlingElement.CopyFrom
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: CreateBehavior
  nameWithType: ServiceThrottlingElement.CreateBehavior
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentCalls*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentCalls
  nameWithType: ServiceThrottlingElement.MaxConcurrentCalls
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentInstances*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentInstances
  nameWithType: ServiceThrottlingElement.MaxConcurrentInstances
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.MaxConcurrentSessions*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: MaxConcurrentSessions
  nameWithType: ServiceThrottlingElement.MaxConcurrentSessions
- uid: System.ServiceModel.Configuration.ServiceThrottlingElement.Properties*
  parent: System.ServiceModel.Configuration.ServiceThrottlingElement
  isExternal: false
  name: Properties
  nameWithType: ServiceThrottlingElement.Properties
