### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMapping
  id: UrlMapping
  children:
  - System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  - System.Web.Configuration.UrlMapping.MappedUrl
  - System.Web.Configuration.UrlMapping.Properties
  - System.Web.Configuration.UrlMapping.Url
  langs:
  - csharp
  name: UrlMapping
  nameWithType: UrlMapping
  fullName: System.Web.Configuration.UrlMapping
  type: Class
  summary: "Esegue il mapping di un URL che verrà visualizzato agli utenti per l&quot;URL di una pagina nell&quot;applicazione Web. Questa classe non può essere ereditata."
  remarks: "La classe UrlMapping consente di eseguire il mapping di un URL che viene visualizzato agli utenti a un URL che è presente nell&quot;applicazione Web. Aggiunta di un oggetto UrlMapping a un <xref:System.Web.Configuration.UrlMappingCollection>è equivalente a livello di codice inclusi un `add` elemento il `urlMappings` sezione di un file di configurazione.</xref:System.Web.Configuration.UrlMappingCollection>       Ogni oggetto UrlMapping contiene due proprietà che identificano un URL. Una proprietà specifica l&quot;URL visualizzato all&quot;utente. l&quot;altro consente di specificare un URL nell&quot;applicazione Web. Finali vengono ignorati gli spazi vuoti in entrambe le <xref:System.Web.Configuration.UrlMapping.Url%2A>e <xref:System.Web.Configuration.UrlMapping.MappedUrl%2A>proprietà.</xref:System.Web.Configuration.UrlMapping.MappedUrl%2A> </xref:System.Web.Configuration.UrlMapping.Url%2A>      > [!NOTE] > UrlMapping la proprietà è possibile scrivere informazioni nella relativa sezione del file di configurazione in base alle restrizioni definite dalla sezione proprietà <xref:System.Configuration.SectionInformation.AllowDefinition%2A>il cui valore è <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> Qualsiasi tentativo di scrivere in un file di configurazione a un livello non consentito nella gerarchia comporterà un messaggio di errore generato dal parser. Tuttavia, è possibile utilizzare questa classe per leggere le informazioni di configurazione a qualsiasi livello della gerarchia."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/t-system.web.configurati_10_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/t-system.web.configurati_10_2.aspx)]"
  syntax:
    content: 'public sealed class UrlMapping : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.UrlMapping&quot;> </xref> classe."
  remarks: "Il costruttore UrlMapping è destinato principalmente per uso interno da ASP.NET. Non è necessario derivare da questa classe e poiché può essere utilizzata per modificare il file Web. config, non sarà probabilmente mai necessario utilizzarla nel codice."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/m-system.web.configurati_60_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/m-system.web.configurati_60_2.aspx)]"
  syntax:
    content: public UrlMapping (string url, string mappedUrl);
    parameters:
    - id: url
      type: System.String
      description: "L&quot;URL da visualizzare all&quot;utente."
    - id: mappedUrl
      type: System.String
      description: "Un URL presente nell&quot;applicazione Web."
  overload: System.Web.Configuration.UrlMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  id: MappedUrl
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "URL dell&quot;applicazione Web."
  remarks: "La proprietà MappedUrl equivale a livello di codice il `mappedUrl` attributo del `add` elemento il `urlMappings` sezione di un file di configurazione.      > [!NOTE] > Quando si utilizza IIS 5.0, se si utilizza la proprietà MappedUrl per eseguire il mapping da un tipo di pagina supportate (ad esempio un file con estensione aspx) a un tipo di pagina non supportate (ad esempio una pagina ASP), si verificherà un errore. Questo tipo di mapping è supportato nella versione 6.0 di IIS."
  example:
  - "The following code example shows how to obtain the MappedUrl property. This example is from a larger example for the <xref:System.Web.Configuration.UrlMapping> class.  \n  \n [!code-cs[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/csharp/p-system.web.configurati_113_1.aspx)]\n [!code-vb[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/visualbasic/p-system.web.configurati_113_1.aspx)]"
  syntax:
    content: public string MappedUrl { get; }
    return:
      type: System.String
      description: "L&quot;URL dell&quot;applicazione Web che è stato eseguito il mapping al valore specificato per il <xref:System.Web.Configuration.UrlMapping.Url*>proprietà.</xref:System.Web.Configuration.UrlMapping.Url*>"
  overload: System.Web.Configuration.UrlMapping.MappedUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.UrlMapping.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Url
  id: Url
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene l&quot;URL che viene visualizzato all&quot;utente."
  remarks: "La proprietà Url equivale a livello di codice il `Url` attributo del `add` elemento il `urlMappings` sezione di un file di configurazione."
  example:
  - For an example, see the <xref:System.Web.Configuration.UrlMapping> class overview.
  syntax:
    content: public string Url { get; }
    return:
      type: System.String
      description: "URL a cui viene visualizzato all&quot;utente."
  overload: System.Web.Configuration.UrlMapping.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMapping.Url
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
- uid: System.Web.Configuration.UrlMapping.#ctor*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping
  nameWithType: UrlMapping.UrlMapping
- uid: System.Web.Configuration.UrlMapping.MappedUrl*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
- uid: System.Web.Configuration.UrlMapping.Url*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
