### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  id: ServiceModelActivitiesSectionGroup
  children:
  - System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.#ctor
  - System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  langs:
  - csharp
  name: ServiceModelActivitiesSectionGroup
  nameWithType: ServiceModelActivitiesSectionGroup
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  type: Class
  summary: "Rappresenta una sezione di configurazione che contiene opzioni di hosting del flusso di lavoro."
  syntax:
    content: 'public sealed class ServiceModelActivitiesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  langs:
  - csharp
  name: ServiceModelActivitiesSectionGroup()
  nameWithType: ServiceModelActivitiesSectionGroup.ServiceModelActivitiesSectionGroup()
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.ServiceModelActivitiesSectionGroup()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup&quot;> </xref> classe."
  syntax:
    content: public ServiceModelActivitiesSectionGroup ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivitiesSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup&quot;> </xref> dalla configurazione specificata."
  syntax:
    content: public static System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "La configurazione da cui ottenere il <xref href=&quot;System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup&quot;> </xref>."
    return:
      type: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
      description: "Il <xref href=&quot;System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup&quot;> </xref> dalla configurazione specificata."
  overload: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  id: WorkflowHostingOptionsSection
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  langs:
  - csharp
  name: WorkflowHostingOptionsSection
  nameWithType: ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Ottiene o imposta il <xref href=&quot;System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection&quot;> </xref>."
  syntax:
    content: public System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection WorkflowHostingOptionsSection { get; }
    return:
      type: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
      description: "La sezione Opzioni hosting del flusso di lavoro."
  overload: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.#ctor
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: ServiceModelActivitiesSectionGroup()
  nameWithType: ServiceModelActivitiesSectionGroup.ServiceModelActivitiesSectionGroup()
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.ServiceModelActivitiesSectionGroup()
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivitiesSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup(Configuration)
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: ServiceModelActivitiesSectionGroup
  nameWithType: ServiceModelActivitiesSectionGroup
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: WorkflowHostingOptionsSection
  nameWithType: ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
  fullName: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: WorkflowHostingOptionsSection
  nameWithType: WorkflowHostingOptionsSection
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.#ctor*
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: ServiceModelActivitiesSectionGroup
  nameWithType: ServiceModelActivitiesSectionGroup.ServiceModelActivitiesSectionGroup
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.GetSectionGroup*
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: ServiceModelActivitiesSectionGroup.GetSectionGroup
- uid: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection*
  parent: System.ServiceModel.Activities.Configuration.ServiceModelActivitiesSectionGroup
  isExternal: false
  name: WorkflowHostingOptionsSection
  nameWithType: ServiceModelActivitiesSectionGroup.WorkflowHostingOptionsSection
