### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Specifica che una proprietà o un gruppo di impostazioni dell&quot;applicazione contiene i valori distinti per ogni utente di un&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "Proprietà delle impostazioni dell&quot;applicazione hanno un ambito che si basa sull&quot;applicazione o a livello di utente. Come implicano le categorie, le proprietà con ambito di applicazione presentano valori uniformi per tutti gli utenti dell&quot;applicazione, mentre le proprietà con ambito di utente hanno valori dedicati per ogni utente dell&quot;applicazione.       Il UserScopedSettingAttribute indica che una proprietà deve essere considerata come un&quot;impostazione a livello utente e che devono essere rese conseguenza decisioni appropriate sull&quot;archiviazione dal provider di impostazioni.       Un attributo di ambito è obbligatorio per ogni proprietà delle impostazioni dell&quot;applicazione. Se non viene applicata una proprietà con un <xref:System.Configuration.ApplicationScopedSettingAttribute>o UserScopedSettingAttribute, la proprietà viene ignorata dal provider di impostazioni, non viene serializzata.</xref:System.Configuration.ApplicationScopedSettingAttribute> Non è possibile, tuttavia, per applicare entrambi gli attributi per la stessa proprietà delle impostazioni. Tale operazione genererà un <xref:System.Configuration.ConfigurationErrorsException>generata.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> classe."
  remarks: "Ogni proprietà delle impostazioni dell&quot;applicazione deve essere applicato con un solo attributo di ambito in modo che vengano riconosciuti e serializzato dal provider di impostazioni."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
