### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesConverter
  id: TimeSpanMinutesConverter
  children:
  - System.Configuration.TimeSpanMinutesConverter.#ctor
  - System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesConverter
  nameWithType: TimeSpanMinutesConverter
  fullName: System.Configuration.TimeSpanMinutesConverter
  type: Class
  summary: "Converte un intervallo di tempo, espresso in minuti."
  remarks: "Questo tipo, come tutti gli altri configurazione convertitore tipi, converte le stringhe trovate nel file di configurazione da e verso le proprietà fortemente tipizzate correlate.       In particolare, consente di convertire il TimeSpanMinutesConverter <xref:System.String>minuti, assegnati a una proprietà di configurazione in <xref:System.TimeSpan>minuti e viceversa.</xref:System.TimeSpan> </xref:System.String>       Il TimeSpanMinutesConverter mantiene i valori di tipo `long` che rappresenta un numero di minuti."
  example:
  - "The following code example shows how to define a custom TimeSpanMinutesConverter type.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.t_3_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#1](~/add/codesnippet/csharp/t-system.configuration.t_3_1.cs)]  \n  \n The following is a configuration excerpt used by the previous example.  \n  \n```  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"  \n      type=\"Samples.AspNet.CustomSection,  \n      ConfigurationConverters,  \n      Version=1.0.0.0, Culture=neutral,  \n      PublicKeyToken=null\"  \n      allowDefinition=\"Everywhere\"  \n      allowExeDefinition=\"MachineToApplication\"  \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\"   \n    timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\"   \n    maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public class TimeSpanMinutesConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: TimeSpanMinutesConverter()
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  fullName: System.Configuration.TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.TimeSpanMinutesConverter&quot;> </xref> classe."
  remarks: "In genere, si usano i tipi di convertitore di tipi forniti dal sistema. L&quot;unica volta che è necessario utilizzare il costruttore TimeSpanMinutesConverter è quando si crea un tipo di conversione."
  syntax:
    content: public TimeSpanMinutesConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.String>a un <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Il sistema utilizza il metodo ConvertFrom durante la lettura da un file di configurazione per convertire un <xref:System.String>valore per <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  example:
  - "The following code example shows how to customize the ConvertFrom method.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#5](~/add/codesnippet/visualbasic/217172fc-63bd-4c91-9301-_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#5](~/add/codesnippet/csharp/217172fc-63bd-4c91-9301-_1.cs)]"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>oggetto utilizzato durante la conversione.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Il <xref:System.String>oggetto da convertire.</xref:System.String>"
    return:
      type: System.Object
      description: "Il <xref:System.TimeSpan>che rappresenta il <code> data </code> parametro in minuti.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanMinutesConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.TimeSpan>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Il sistema utilizza il metodo ConvertTo durante la scrittura di un file di configurazione per convertire un <xref:System.TimeSpan>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  example:
  - "The following code example shows how to customize the ConvertTo method.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#4](~/add/codesnippet/visualbasic/e18c626c-bb93-4990-9d92-_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#4](~/add/codesnippet/csharp/e18c626c-bb93-4990-9d92-_1.cs)]"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>oggetto utilizzato durante la conversione.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Valore da convertire."
    - id: type
      type: System.Type
      description: "Tipo da convertire."
    return:
      type: System.Object
      description: "Il <xref:System.String>che rappresenta il <code> value </code> parametro in minuti.</xref:System.String>"
  overload: System.Configuration.TimeSpanMinutesConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: TimeSpanMinutesConverter()
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  fullName: System.Configuration.TimeSpanMinutesConverter.TimeSpanMinutesConverter()
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: TimeSpanMinutesConverter
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesConverter.ConvertFrom
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesConverter.ConvertTo
