### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  id: TextMetricsPitchAndFamilyValues
  children:
  - System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Device
  - System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.FixedPitch
  - System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.TrueType
  - System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Vector
  langs:
  - csharp
  name: TextMetricsPitchAndFamilyValues
  nameWithType: TextMetricsPitchAndFamilyValues
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  type: Enum
  summary: "Specifica le informazioni su tono, la tecnologia e famiglia del tipo di carattere specificato da uno stile di visualizzazione per un particolare elemento."
  remarks: "L&quot;enumerazione TextMetricsPitchAndFamilyValues specifica i valori possibili del <xref:System.Windows.Forms.VisualStyles.TextMetrics.PitchAndFamily%2A>proprietà del <xref:System.Windows.Forms.VisualStyles.TextMetrics>struttura.</xref:System.Windows.Forms.VisualStyles.TextMetrics> </xref:System.Windows.Forms.VisualStyles.TextMetrics.PitchAndFamily%2A>"
  syntax:
    content: >-
      [System.Flags]

      public enum TextMetricsPitchAndFamilyValues
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Device
  id: Device
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  langs:
  - csharp
  name: Device
  nameWithType: TextMetricsPitchAndFamilyValues.Device
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Device
  type: Field
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.VisualStyles
  summary: "Il tipo di carattere è un dispositivo."
  syntax:
    content: Device
    return:
      type: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.FixedPitch
  id: FixedPitch
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  langs:
  - csharp
  name: FixedPitch
  nameWithType: TextMetricsPitchAndFamilyValues.FixedPitch
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.FixedPitch
  type: Field
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.VisualStyles
  summary: "Se questo valore è impostato, il tipo di carattere è un carattere a passo variabile. In caso contrario, il tipo di carattere è un tipo di carattere a passo fisso."
  syntax:
    content: FixedPitch
    return:
      type: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.TrueType
  id: TrueType
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  langs:
  - csharp
  name: TrueType
  nameWithType: TextMetricsPitchAndFamilyValues.TrueType
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.TrueType
  type: Field
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.VisualStyles
  summary: "Il tipo di carattere è un tipo di carattere TrueType."
  syntax:
    content: TrueType
    return:
      type: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Vector
  id: Vector
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  langs:
  - csharp
  name: Vector
  nameWithType: TextMetricsPitchAndFamilyValues.Vector
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Vector
  type: Field
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.VisualStyles
  summary: "Il tipo di carattere è un tipo di carattere vettoriali."
  syntax:
    content: Vector
    return:
      type: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Device
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  isExternal: false
  name: Device
  nameWithType: TextMetricsPitchAndFamilyValues.Device
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Device
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  parent: System.Windows.Forms.VisualStyles
  isExternal: false
  name: TextMetricsPitchAndFamilyValues
  nameWithType: TextMetricsPitchAndFamilyValues
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.FixedPitch
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  isExternal: false
  name: FixedPitch
  nameWithType: TextMetricsPitchAndFamilyValues.FixedPitch
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.FixedPitch
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.TrueType
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  isExternal: false
  name: TrueType
  nameWithType: TextMetricsPitchAndFamilyValues.TrueType
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.TrueType
- uid: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Vector
  parent: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues
  isExternal: false
  name: Vector
  nameWithType: TextMetricsPitchAndFamilyValues.Vector
  fullName: System.Windows.Forms.VisualStyles.TextMetricsPitchAndFamilyValues.Vector
