### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CallbackDebugElement
  id: CallbackDebugElement
  children:
  - System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  - System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  - System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  - System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  - System.ServiceModel.Configuration.CallbackDebugElement.Properties
  langs:
  - csharp
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement
  fullName: System.ServiceModel.Configuration.CallbackDebugElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica il debug sul lato servizio per un oggetto di callback Windows Communication Foundation (WCF). Questa classe non può essere ereditata."
  remarks: "Se si imposta la <xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>proprietà `true` a livello di codice, è possibile abilitare il flusso di informazioni sulle eccezioni gestite in un oggetto callback client al servizio a scopo di debug.</xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>      > [!CAUTION] > La restituzione ai client informazioni sulle eccezioni gestite può costituire un rischio di sicurezza. Questo avviene perché i dettagli delle eccezioni espongono informazioni sull&quot;implementazione interna del servizio che potrebbe essere usata da client non autorizzati."
  syntax:
    content: 'public sealed class CallbackDebugElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.CallbackDebugElement&quot;> </xref> classe."
  syntax:
    content: public CallbackDebugElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene il tipo di questo elemento di comportamento."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "Il tipo di elemento di comportamento."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia il contenuto dell&quot;elemento di configurazione specificato in questo elemento di configurazione."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "L&quot;elemento di configurazione da copiare."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  id: IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore che specifica se oggetti callback del client restituiscono informazioni sulle eccezioni gestite negli errori SOAP al servizio."
  syntax:
    content: public bool IncludeExceptionDetailInFaults { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se Windows Communication Foundation (WCF) restituisce gestito informazioni sull&quot;eccezione di callback client in SOAP errori per scopi di debug lato servizio nella comunicazione duplex. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement.CallbackDebugElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom
  nameWithType: CallbackDebugElement.CopyFrom
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior
  nameWithType: CallbackDebugElement.CreateBehavior
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
