### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DefaultPortElement
  id: DefaultPortElement
  children:
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  - System.ServiceModel.Configuration.DefaultPortElement.Port
  - System.ServiceModel.Configuration.DefaultPortElement.Properties
  - System.ServiceModel.Configuration.DefaultPortElement.Scheme
  langs:
  - csharp
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che definisce le impostazioni predefinite per un endpoint di comunicazione."
  remarks: "Una porta predefinita è l&quot;endpoint di comunicazione predefinito che l&quot;applicazione client ascolta."
  syntax:
    content: 'public sealed class DefaultPortElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Crea una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref> classe."
  syntax:
    content: public DefaultPortElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  id: '#ctor(System.ServiceModel.Configuration.DefaultPortElement)'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Crea una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref> classe con l&quot;oggetto specificato <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref>."
  syntax:
    content: public DefaultPortElement (System.ServiceModel.Configuration.DefaultPortElement other);
    parameters:
    - id: other
      type: System.ServiceModel.Configuration.DefaultPortElement
      description: "Elemento della porta predefinita che fornisce le impostazioni per l&quot;elemento corrente della porta predefinita."
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  id: Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il numero di porta di comunicazione predefinita."
  syntax:
    content: public int Port { get; set; }
    return:
      type: System.Int32
      description: "La porta di comunicazione."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Port*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  id: Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il gruppo di impostazioni di protocollo associate a una porta di comunicazione."
  syntax:
    content: public string Scheme { get; set; }
    return:
      type: System.String
      description: "Impostazioni del protocollo di comunicazione."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
- uid: System.ServiceModel.Configuration.DefaultPortElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement.DefaultPortElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
