### YamlMime:ManagedReference
items:
- uid: System.Configuration.ClientSettingsSection
  id: ClientSettingsSection
  children:
  - System.Configuration.ClientSettingsSection.#ctor
  - System.Configuration.ClientSettingsSection.Properties
  - System.Configuration.ClientSettingsSection.Settings
  langs:
  - csharp
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection
  fullName: System.Configuration.ClientSettingsSection
  type: Class
  summary: "Rappresenta un gruppo di impostazioni con ambito di utente dell&quot;applicazione in un file di configurazione."
  remarks: "Il [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] contiene un provider di impostazioni predefinito singolo, <xref:System.Configuration.LocalFileSettingsProvider>, che archivia i dati di configurazione per il file system locale in file con estensione `.config`.</xref:System.Configuration.LocalFileSettingsProvider> Il contenuto del file di configurazione è strutturato come documenti XML. Impostazioni con ambito di utente sono persistenti in un file con il nome `username.config`. In questo file, i dati vengono archiviati come elementi all&quot;interno di un `<userSettings>` sezione. Ognuna di queste sezioni è rappresentato da un ClientSettingsSection corrispondente. Ogni oggetto sezione è di proprietà e amministrato mediante un gestore della sezione di configurazione, ovvero un <xref:System.Configuration.IConfigurationSectionHandler>.</xref:System.Configuration.IConfigurationSectionHandler>       La classe ClientSettingsSection rappresenta una semplice estensione della <xref:System.Configuration.ConfigurationSection>classe, che viene utilizzata per la [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] il supporto per i file di configurazione generale.</xref:System.Configuration.ConfigurationSection>       Per ulteriori informazioni sulle impostazioni dell&quot;applicazione, vedere l&quot;argomento [impostazioni applicazione per Windows Form](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public sealed class ClientSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.ClientSettingsSection&quot;> </xref> classe."
  remarks: "Il costruttore ClientSettingsSection predefinito inizializza il <xref:System.Configuration.ClientSettingsSection.Settings%2A>proprietà.</xref:System.Configuration.ClientSettingsSection.Settings%2A>"
  syntax:
    content: public ClientSettingsSection ();
    parameters: []
  overload: System.Configuration.ClientSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.Properties
  id: Properties
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Configuration.ClientSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ClientSettingsSection.Settings
  id: Settings
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene la raccolta di impostazioni client per la sezione."
  remarks: "La proprietà delle impostazioni è una proprietà di configurazione."
  syntax:
    content: public System.Configuration.SettingElementCollection Settings { get; }
    return:
      type: System.Configuration.SettingElementCollection
      description: "Oggetto <xref href=&quot;System.Configuration.SettingElementCollection&quot;> </xref> contenente tutte le impostazioni client, vedere la sezione di configurazione corrente."
  overload: System.Configuration.ClientSettingsSection.Settings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.ClientSettingsSection.#ctor
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
- uid: System.Configuration.ClientSettingsSection.Properties
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ClientSettingsSection.Settings
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
- uid: System.Configuration.SettingElementCollection
  parent: System.Configuration
  isExternal: false
  name: SettingElementCollection
  nameWithType: SettingElementCollection
  fullName: System.Configuration.SettingElementCollection
- uid: System.Configuration.ClientSettingsSection.#ctor*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection.ClientSettingsSection
- uid: System.Configuration.ClientSettingsSection.Properties*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
- uid: System.Configuration.ClientSettingsSection.Settings*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
