### YamlMime:ManagedReference
items:
- uid: System.Configuration.IConfigurationSystem
  id: IConfigurationSystem
  children:
  - System.Configuration.IConfigurationSystem.GetConfig(System.String)
  - System.Configuration.IConfigurationSystem.Init
  langs:
  - csharp
  name: IConfigurationSystem
  nameWithType: IConfigurationSystem
  fullName: System.Configuration.IConfigurationSystem
  type: Interface
  summary: "Fornisce metodi di configurazione standard."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationSystem
  implements: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSystem.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.IConfigurationSystem
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: IConfigurationSystem.GetConfig(String)
  fullName: System.Configuration.IConfigurationSystem.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene la configurazione specificata."
  syntax:
    content: public object GetConfig (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "La chiave di configurazione."
    return:
      type: System.Object
      description: "Oggetto che rappresenta la configurazione."
  overload: System.Configuration.IConfigurationSystem.GetConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSystem.Init
  id: Init
  parent: System.Configuration.IConfigurationSystem
  langs:
  - csharp
  name: Init()
  nameWithType: IConfigurationSystem.Init()
  fullName: System.Configuration.IConfigurationSystem.Init()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Utilizzato per l&quot;inizializzazione."
  syntax:
    content: public void Init ();
    parameters: []
  overload: System.Configuration.IConfigurationSystem.Init*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IConfigurationSystem.GetConfig(System.String)
  parent: System.Configuration.IConfigurationSystem
  isExternal: false
  name: GetConfig(String)
  nameWithType: IConfigurationSystem.GetConfig(String)
  fullName: System.Configuration.IConfigurationSystem.GetConfig(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.IConfigurationSystem.Init
  parent: System.Configuration.IConfigurationSystem
  isExternal: false
  name: Init()
  nameWithType: IConfigurationSystem.Init()
  fullName: System.Configuration.IConfigurationSystem.Init()
- uid: System.Configuration.IConfigurationSystem.GetConfig*
  parent: System.Configuration.IConfigurationSystem
  isExternal: false
  name: GetConfig
  nameWithType: IConfigurationSystem.GetConfig
- uid: System.Configuration.IConfigurationSystem.Init*
  parent: System.Configuration.IConfigurationSystem
  isExternal: false
  name: Init
  nameWithType: IConfigurationSystem.Init
