### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlWriterSettings
  id: XamlXmlWriterSettings
  children:
  - System.Xaml.XamlXmlWriterSettings.#ctor
  - System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  - System.Xaml.XamlXmlWriterSettings.CloseOutput
  - System.Xaml.XamlXmlWriterSettings.Copy
  langs:
  - csharp
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
  type: Class
  summary: "Fornisce le impostazioni di inizializzazione per il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> implementazione del writer XAML."
  remarks: "Le impostazioni predefinite per tutti i valori XamlXmlWriterSettings sono `false`."
  syntax:
    content: 'public class XamlXmlWriterSettings : System.Xaml.XamlWriterSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlWriterSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> classe."
  syntax:
    content: public XamlXmlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  id: AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> deve presupporre sempre l&quot;input XAML valido ai fini di risoluzione duplicata o altri errori."
  syntax:
    content: public bool AssumeValidInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> ignora alcuni controlli di convalida o di errore, ad esempio la generazione di eccezioni per i membri duplicati. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> genera eccezioni quando viene rilevato XAML non valido. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ottiene o imposta un valore che specifica se il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> deve essere chiuso immediatamente in <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> o altre operazioni, o se il writer XAML deve scrivere l&quot;output del buffer prima della chiusura. Utilizzare questa impostazione con cautela. la chiusura immediata può comportare XAML non valido che non può essere caricato di nuovo."
  remarks: "Questa impostazione influisce sulla logica di <xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>, che chiama `Close` sull&quot;oggetto sottostante <xref:System.Xml.XmlWriter>o <xref:System.IO.TextWriter>quando CloseOutput è `true`; o chiama <xref:System.Xaml.XamlXmlWriter.Flush%2A>(nuovamente associato all&quot;oggetto sottostante <xref:System.Xml.XmlWriter>o <xref:System.IO.TextWriter>) se è CloseOutput `false`.</xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Flush%2A> </xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>"
  syntax:
    content: public bool CloseOutput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> si chiude immediatamente su un <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> o operazioni simili. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se viene scritto l&quot;output del buffer rimanente prima il <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> viene rilasciato. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  id: Copy
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
  type: Method
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Restituisce una copia di questo <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> istanza."
  syntax:
    content: public System.Xaml.XamlXmlWriterSettings Copy ();
    parameters: []
    return:
      type: System.Xaml.XamlXmlWriterSettings
      description: "Copia restituita."
  overload: System.Xaml.XamlXmlWriterSettings.Copy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlWriterSettings
  isExternal: false
  name: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
- uid: System.Xaml.XamlXmlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy
  nameWithType: XamlXmlWriterSettings.Copy
