### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.IWebApplication
  id: IWebApplication
  children:
  - System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  - System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  - System.Web.UI.Design.IWebApplication.RootProjectItem
  langs:
  - csharp
  name: IWebApplication
  nameWithType: IWebApplication
  fullName: System.Web.UI.Design.IWebApplication
  type: Interface
  summary: "Fornisce un&quot;interfaccia per l&quot;accesso a un&quot;applicazione Web in un host di progettazione, ad esempio [!INCLUDE[vsprvsext](~/add/includes/ajax-current-ext-md.md)], in fase di progettazione."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("cff39fa8-5607-4b6d-86f3-cc80b3cfe2dd")]

      public interface IWebApplication : IServiceProvider
  implements:
  - System.IServiceProvider
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  id: GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Restituisce un elemento di progetto da un host di progettazione in base all&quot;URL."
  syntax:
    content: public System.Web.UI.Design.IProjectItem GetProjectItemFromUrl (string appRelativeUrl);
    parameters:
    - id: appRelativeUrl
      type: System.String
      description: "Il percorso relativo per l&quot;elemento di progetto da recuperare."
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "Elemento di progetto da un host di progettazione in base all&quot;URL."
  overload: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  id: OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Restituisce un <xref href=&quot;System.Configuration.Configuration&quot;> </xref> oggetto che rappresenta l&quot;applicazione Web corrente nell&quot;host di progettazione."
  syntax:
    content: public System.Configuration.Configuration OpenWebConfiguration (bool isReadOnly);
    parameters:
    - id: isReadOnly
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>per indicare l&quot;oggetto restituito <xref href=&quot;System.Configuration.Configuration&quot;> </xref> è modificabile; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    return:
      type: System.Configuration.Configuration
      description: "Oggetto che rappresenta l&quot;applicazione Web corrente nell&quot;host di progettazione."
  overload: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  id: RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
  type: Property
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Ottiene l&quot;elemento radice del progetto dall&quot;host di progettazione."
  syntax:
    content: public System.Web.UI.Design.IProjectItem RootProjectItem { get; }
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "L&quot;elemento radice del progetto dall&quot;host di progettazione."
  overload: System.Web.UI.Design.IWebApplication.RootProjectItem*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
- uid: System.Web.UI.Design.IProjectItem
  parent: System.Web.UI.Design
  isExternal: false
  name: IProjectItem
  nameWithType: IProjectItem
  fullName: System.Web.UI.Design.IProjectItem
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl
  nameWithType: IWebApplication.GetProjectItemFromUrl
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration
  nameWithType: IWebApplication.OpenWebConfiguration
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
