### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement
  id: IdentityModelCachesElement
  children:
  - System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  - System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  - System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  - System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement
  type: Class
  summary: "Rappresenta un <xref uid=&quot;langword_csharp_&lt;caches&gt;&quot; name=&quot;&lt;caches&gt;&quot; href=&quot;&quot;> </xref> elemento in un file di configurazione. Questa classe non può essere ereditata."
  remarks: "Il `<caches>` elemento consente di configurare i servizi di memorizzazione nella cache per WIF. Registra il tipo di cache dei token di sicurezza della sessione e il tipo di cache di riproduzione token da utilizzare. Può essere specificato a livello di servizio sotto il `<identityConfiguration>` elemento o in una raccolta di gestore del token di sicurezza nel `<securityTokenHandlerConfiguration>` elemento. Il `Caches` proprietà del <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>classe e il <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>classe è un&quot;istanza di IdentityModelCachesElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement> Dopo aver letto il file di configurazione, le cache configurate sono rappresentate dalla <xref:System.IdentityModel.Configuration.IdentityModelCaches>classe.</xref:System.IdentityModel.Configuration.IdentityModelCaches>"
  syntax:
    content: 'public sealed class IdentityModelCachesElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCachesElement&quot;> </xref> classe."
  syntax:
    content: public IdentityModelCachesElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  id: IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene un valore che indica se questo elemento è stato configurato."
  syntax:
    content: public bool IsConfigured { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;elemento è stato configurato. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene o imposta il <xref:System.Type>della cache del token di sessione.</xref:System.Type>"
  remarks: "Questa proprietà è facoltativa. Corrisponde a un `<sessionSecurityTokenCache>` elemento specificato sotto la `<caches>`. Specifica il tipo di cache da utilizzare per archiviare i token di sicurezza della sessione. Tutte le cache token di sessione devono derivare da<xref:System.IdentityModel.Tokens.SessionSecurityTokenCache></xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "Il tipo di cache del token di sessione. Il tipo deve derivare da [System.IdentityModel.Tokens.SessionSecurityTokenCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene o imposta il <xref:System.Type>del token di cache di riproduzione.</xref:System.Type>"
  remarks: "Questa proprietà è facoltativa. Corrisponde a un `<tokenReplayCache>` elemento specificato sotto il `<caches>` elemento. Specifica il tipo della cache da utilizzare per il rilevamento riproduzione token. Tutte le cache di riproduzione devono derivare da <xref:System.IdentityModel.Tokens.TokenReplayCache>è abilitato il rilevamento riproduzione con il `<tokenReplayDetection>` elemento.</xref:System.IdentityModel.Tokens.TokenReplayCache> Questo elemento è rappresentato dalla <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>classe.</xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "Il tipo di cache di riproduzione token. Il tipo deve derivare da [System.IdentityModel.Tokens.TokenReplayCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
