### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventHandler
  id: SettingChangingEventHandler
  langs:
  - csharp
  name: SettingChangingEventHandler
  nameWithType: SettingChangingEventHandler
  fullName: System.Configuration.SettingChangingEventHandler
  type: Delegate
  summary: "Rappresenta il metodo che gestirà il <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> evento."
  remarks: "Il <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>evento si verifica prima che venga modificato il valore di una proprietà delle impostazioni dell&quot;applicazione, in genere tramite una chiamata al <xref:System.Configuration.ApplicationSettingsBase.Item%2A>metodo.</xref:System.Configuration.ApplicationSettingsBase.Item%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingChanging> <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>può essere annullata tramite la <xref:System.Configuration.SettingChangingEventArgs>classe di evento dati.</xref:System.Configuration.SettingChangingEventArgs></xref:System.Configuration.ApplicationSettingsBase.SettingChanging>"
  syntax:
    content: public delegate void SettingChangingEventHandler(object sender, SettingChangingEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
