### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "Viene descritto un processo di stampa."
  remarks: "Il <xref:System.Printing.PrintTicket>oggetto, ovvero il valore del <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>proprietà, contiene tutte le impostazioni dettagliate per un processo di stampa.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> L&quot;elemento padre, PrintJobSettings, aggiunge solo una descrizione.      > [!CAUTION] > Classi all&quot;interno di <xref:System.Printing>dello spazio dei nomi non sono supportati per l&quot;utilizzo all&quot;interno di un servizio Windows o l&quot;applicazione ASP.NET o servizio.</xref:System.Printing> Il tentativo di utilizzare queste classi da all&quot;interno di uno di questi tipi di applicazioni può generare problemi imprevisti, ad esempio diminuita eccezioni prestazioni e in fase di esecuzione del servizio.       Se si desidera stampare da un&quot;applicazione Windows Forms, vedere il <xref:System.Drawing.Printing>spazio dei nomi.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Ottiene o imposta un <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> oggetto che contiene tutte le impostazioni dettagliate per il processo di stampa."
  remarks: "Impostazione di questa proprietà CurrentPrintTicket convalida né modifica specificata <xref:System.Printing.PrintTicket>per un particolare <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Se necessario, utilizzare il <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>metodo per creare un <xref:System.Printing.PrintQueue>-specifico <xref:System.Printing.PrintTicket>valido per una determinata stampante.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "Oggetto <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> dell&quot;oggetto che contiene tutti i dettagli sul processo di stampa, ad esempio il numero di copie da stampare, e l&quot;associazione o la stampa fronte retro."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Ottiene o imposta una descrizione di un processo di stampa."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "Un <xref:System.String>che descrive il processo di stampa, ad esempio, &quot;Report trimestrale&quot;.</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
