### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpCachePolicyElement
  id: HttpCachePolicyElement
  children:
  - System.Net.Configuration.HttpCachePolicyElement.#ctor
  - System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  - System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  - System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  - System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  - System.Net.Configuration.HttpCachePolicyElement.Properties
  - System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement
  fullName: System.Net.Configuration.HttpCachePolicyElement
  type: Class
  summary: "Rappresenta i criteri di cache HTTP predefinito per le risorse di rete. Questa classe non può essere ereditata."
  remarks: "This class corresponds to the [\\&lt;defaultHttpCachePolicy\\&gt; Element (Network Settings)](../Topic/%3CdefaultHttpCachePolicy%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the HTTP caching configuration that applies to network resources obtained by using the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpCachePolicyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Net.Configuration.HttpCachePolicyElement&quot;> </xref> classe."
  remarks: "Questo costruttore aggiunge il <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumAge%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumStale%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MinimumFresh%2A>, e <xref:System.Net.Configuration.HttpCachePolicyElement.PolicyLevel%2A>proprietà alla raccolta.</xref:System.Net.Configuration.HttpCachePolicyElement.PolicyLevel%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MinimumFresh%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MaximumStale%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MaximumAge%2A>"
  syntax:
    content: public HttpCachePolicyElement ();
    parameters: []
  overload: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "Da aggiungere."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Da aggiungere."
  overload: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  id: MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta la durata massima consentita per una risorsa restituita dalla cache."
  remarks: "Se la copia memorizzata nella cache della risorsa è precedente rispetto al valore di tempo specificato, la risorsa deve essere riconvalidata confrontando la risorsa memorizzata nella cache per la risorsa nel server."
  syntax:
    content: public TimeSpan MaximumAge { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>valore che specifica la durata massima per memorizzati nella cache di risorse specificate nel file di configurazione.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  id: MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta il valore di obsolescenza massima consentito per una risorsa restituita dalla cache."
  remarks: "Questa proprietà specifica la quantità di tempo dopo la scadenza del contenuto durante i quali la copia memorizzata nella cache della risorsa è accettabile."
  syntax:
    content: public TimeSpan MaximumStale { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>valore impostato sul valore di obsolescenza massima specificato nel file di configurazione.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  id: MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta la validità minima consentita per una risorsa restituita dalla cache."
  remarks: "Questo valore specifica la quantità di tempo prima della scadenza del contenuto, durante i quali la copia memorizzata nella cache della risorsa è accettabile."
  syntax:
    content: public TimeSpan MinimumFresh { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>valore che specifica la validità minima specificata nel file di configurazione.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  id: PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta HTTP comportamento della cache per il computer locale."
  remarks: "Le applicazioni utilizzano in genere <xref:System.Net.Cache.HttpRequestCacheLevel>come livello di criteri di cache.</xref:System.Net.Cache.HttpRequestCacheLevel> Il <xref:System.Net.WebRequest.CachePolicy%2A>proprietà, se non `null`, determina i criteri della cache attivi per una richiesta.</xref:System.Net.WebRequest.CachePolicy%2A>"
  syntax:
    content: public System.Net.Cache.HttpRequestCacheLevel PolicyLevel { get; set; }
    return:
      type: System.Net.Cache.HttpRequestCacheLevel
      description: "Oggetto <xref href=&quot;System.Net.Cache.HttpRequestCacheLevel&quot;> </xref> valore che specifica il comportamento della cache."
  overload: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Net.Configuration.HttpCachePolicyElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Da aggiungere."
  overload: System.Net.Configuration.HttpCachePolicyElement.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Cache.HttpRequestCacheLevel
  parent: System.Net.Cache
  isExternal: false
  name: HttpRequestCacheLevel
  nameWithType: HttpRequestCacheLevel
  fullName: System.Net.Cache.HttpRequestCacheLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement
  nameWithType: HttpCachePolicyElement.DeserializeElement
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset
  nameWithType: HttpCachePolicyElement.Reset
