### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  id: ArgumentElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  langs:
  - csharp
  name: ArgumentElement
  nameWithType: ArgumentElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  type: Class
  summary: "Un elemento di configurazione che rappresenta un argomento."
  syntax:
    content: 'public class ArgumentElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: ArgumentElement()
  nameWithType: ArgumentElement.ArgumentElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ArgumentElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement&quot;> </xref> classe."
  syntax:
    content: public ArgumentElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene una chiave che identifica in modo univoco l&quot;argomento."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "Chiave dell&quot;elemento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: Name
  nameWithType: ArgumentElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene o imposta il nome dell&quot;argomento."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Il nome dell&quot;argomento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: Properties
  nameWithType: ArgumentElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Ottiene la raccolta di proprietà"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Il <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> delle proprietà per l&quot;elemento."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ArgumentElement()
  nameWithType: ArgumentElement.ArgumentElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ArgumentElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Name
  nameWithType: ArgumentElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Properties
  nameWithType: ArgumentElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ArgumentElement
  nameWithType: ArgumentElement.ArgumentElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Name
  nameWithType: ArgumentElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Properties
  nameWithType: ArgumentElement.Properties
