### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeContext
  id: ExeContext
  children:
  - System.Configuration.ExeContext.ExePath
  - System.Configuration.ExeContext.UserLevel
  langs:
  - csharp
  name: ExeContext
  nameWithType: ExeContext
  fullName: System.Configuration.ExeContext
  type: Class
  summary: "Gestisce il contesto del percorso per l&quot;applicazione corrente. Questa classe non può essere ereditata."
  syntax:
    content: public sealed class ExeContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ExeContext.ExePath
  id: ExePath
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il percorso corrente per l&quot;applicazione."
  syntax:
    content: public string ExePath { get; }
    return:
      type: System.String
      description: "Valore stringa che contiene il percorso corrente."
  overload: System.Configuration.ExeContext.ExePath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeContext.UserLevel
  id: UserLevel
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un oggetto che rappresenta il livello di percorso dell&quot;applicazione corrente."
  syntax:
    content: public System.Configuration.ConfigurationUserLevel UserLevel { get; }
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: "Oggetto <xref href=&quot;System.Configuration.ConfigurationUserLevel&quot;> </xref> oggetto che rappresenta il livello di percorso dell&quot;applicazione corrente."
  overload: System.Configuration.ExeContext.UserLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ExeContext.ExePath
  parent: System.Configuration.ExeContext
  isExternal: false
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeContext.UserLevel
  parent: System.Configuration.ExeContext
  isExternal: false
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
- uid: System.Configuration.ExeContext.ExePath*
  parent: System.Configuration.ExeContext
  isExternal: false
  name: ExePath
  nameWithType: ExeContext.ExePath
- uid: System.Configuration.ExeContext.UserLevel*
  parent: System.Configuration.ExeContext
  isExternal: false
  name: UserLevel
  nameWithType: ExeContext.UserLevel
