### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  id: BaseAddressPrefixFilterElement
  children:
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica un passaggio tramite filtro, che fornisce un meccanismo per scegliere le associazioni di IIS appropriate quando si ospita un [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] applicazione in IIS. Questa classe non può essere ereditata."
  remarks: "Un prefisso filtro provider un meccanismo per un servizio da associare a un URI specifico. Consente di ospitare più applicazioni con indirizzi di base diversi per lo stesso schema sullo stesso sito.       I siti Web IIS sono contenitori di applicazioni virtuali che contengono directory virtuali. L&quot;applicazione in un sito sono accessibili tramite uno o più associazioni IIS. Associazioni IIS forniscono due tipi di informazioni: il protocollo di associazione e informazioni di associazione. Protocollo di associazione (ad esempio, HTTP) definisce lo schema in cui ha luogo la comunicazione e informazioni di associazione (ad esempio, indirizzo IP, porta, intestazione host) contengono i dati utilizzati per accedere al sito.       IIS supporta la definizione di più associazioni IIS per sito, che comporta più indirizzi di base per schema. Poiché un [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] servizio ospitato in un sito consente l&quot;associazione a un solo indirizzo di base per schema, è possibile utilizzare la funzionalità di filtro dei prefissi per scegliere l&quot;indirizzo di base necessario del servizio ospitato.  Gli indirizzi di base in ingresso, forniti da IIS, vengono filtrati in base al filtro elenco prefisso facoltativo.       Ad esempio, il sito può contenere i seguenti indirizzi di base ```   http://testl.fabrikam.com/Service.svc   http://test2.fabrikam.com/Service.svc   ``` è possibile utilizzare il seguente file di configurazione per specificare un filtro dei prefissi a livello di appdomain.      ```   <system.serviceModel>     <serviceHostingEnvironment>        <baseAddressPrefixFilters>           <add prefix=”net.tcp://test1.fabrikam.com:8000”/>           <add prefix=”http://test2.fabrikam.com:9000”/>       </baseAddressPrefixFilters>     </serviceHostingEnvironment>   </system.serviceModel>   ```In questo esempio, `net.tcp://test1.fabrikam.com:8000` e `http://test2.fabrikam.com:9000` sono gli indirizzi di base solo per i rispettivi schemi che possono essere passati tramite.       Per impostazione predefinita, quando non viene specificato un prefisso, tutti gli indirizzi vengono passati. Se si specifica il prefisso, si otterrà solo l&quot;indirizzo di base corrispondente per tale schema deve essere passato tramite.      > [!NOTE] > Il filtro non supporta tutti i caratteri jolly. Di base forniti da IIS possono inoltre disporre di indirizzi associati ad altri schemi non presenti nel `baseAddressPrefixFilters` elenco. Questi indirizzi non vengono filtrati."
  syntax:
    content: 'public sealed class BaseAddressPrefixFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> classe."
  syntax:
    content: public BaseAddressPrefixFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  id: '#ctor(System.Uri)'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> classe con un URI specifico."
  syntax:
    content: public BaseAddressPrefixFilterElement (Uri prefix);
    parameters:
    - id: prefix
      type: System.Uri
      description: "Un filtro che fa sì che il servizio sia in ascolto su tutti gli URI che iniziano con questo prefisso specifico."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un prefisso che viene utilizzato per associare una parte di un indirizzo di base."
  syntax:
    content: public Uri Prefix { get; set; }
    return:
      type: System.Uri
      description: "URI che viene utilizzato per associare una parte di un indirizzo di base."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
