### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsConverter
  id: TimeSpanSecondsConverter
  children:
  - System.Configuration.TimeSpanSecondsConverter.#ctor
  - System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanSecondsConverter
  nameWithType: TimeSpanSecondsConverter
  fullName: System.Configuration.TimeSpanSecondsConverter
  type: Class
  summary: "Converte un intervallo di tempo, espresso in secondi."
  remarks: "Questo tipo, come tutti gli altri configurazione convertitore tipi, converte le stringhe trovate nel file di configurazione da e verso le proprietà fortemente tipizzate correlate.       In particolare, consente di convertire il TimeSpanSecondsConverter <xref:System.String>secondi, assegnati a una proprietà di configurazione in <xref:System.TimeSpan>secondi e viceversa.</xref:System.TimeSpan> </xref:System.String>       Il <xref:System.Configuration.TimeSpanMinutesConverter>mantiene i valori di tipo `long` che rappresentano un numero di secondi.</xref:System.Configuration.TimeSpanMinutesConverter>"
  example:
  - Refer to the code examples in <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter>.
  syntax:
    content: 'public class TimeSpanSecondsConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.TimeSpanSecondsConverter&quot;> </xref> classe."
  remarks: "In genere, si usano i tipi di convertitore di tipi forniti dal sistema. L&quot;unica volta che è necessario utilizzare il costruttore TimeSpanSecondsConverter è quando si crea un tipo di conversione."
  syntax:
    content: public TimeSpanSecondsConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanSecondsConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.String>a un <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Il sistema utilizza il metodo ConvertFrom durante la lettura da un file di configurazione per convertire un <xref:System.String>valore per <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>oggetto utilizzato durante la conversione.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Il <xref:System.String>oggetto da convertire.</xref:System.String>"
    return:
      type: System.Object
      description: "Il <xref:System.TimeSpan>che rappresenta il <code> data </code> parametro in secondi.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanSecondsConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>data</code>Impossibile analizzare come integer."
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.TimeSpan>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Il sistema utilizza il metodo ConvertTo durante la scrittura in un file di configurazione per convertire un <xref:System.TimeSpan>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>oggetto utilizzato durante la conversione.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Valore da convertire."
    - id: type
      type: System.Type
      description: "Tipo da convertire."
    return:
      type: System.Object
      description: "Il <xref:System.String>che rappresenta il <code> value </code> parametro in minuti.</xref:System.String>"
  overload: System.Configuration.TimeSpanSecondsConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: TimeSpanSecondsConverter
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanSecondsConverter.ConvertFrom
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanSecondsConverter.ConvertTo
