### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerSecuritySettings
  id: PeerSecuritySettings
  children:
  - System.ServiceModel.PeerSecuritySettings.#ctor
  - System.ServiceModel.PeerSecuritySettings.Mode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  - System.ServiceModel.PeerSecuritySettings.Transport
  langs:
  - csharp
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings
  fullName: System.ServiceModel.PeerSecuritySettings
  type: Class
  summary: "Contiene le impostazioni di sicurezza associate a un canale peer, compreso il tipo di autenticazione usato e la sicurezza utilizzata per il trasporto dei messaggi."
  syntax:
    content: public sealed class PeerSecuritySettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: System.ServiceModel.PeerSecuritySettings.PeerSecuritySettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inizializza una nuova istanza predefinita di <xref href=&quot;System.ServiceModel.PeerSecuritySettings&quot;> </xref> classe."
  syntax:
    content: public PeerSecuritySettings ();
    parameters: []
  overload: System.ServiceModel.PeerSecuritySettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  id: Mode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: System.ServiceModel.PeerSecuritySettings.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene e imposta il valore che indica la modalità di sicurezza del canale peer."
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: "<xref:System.ServiceModel.SecurityMode>valore di enumerazione che indica la modalità di sicurezza per il canale peer.</xref:System.ServiceModel.SecurityMode>"
  overload: System.ServiceModel.PeerSecuritySettings.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Il valore specificato non è un valore enumerato<xref:System.ServiceModel.SecurityMode></xref:System.ServiceModel.SecurityMode>"
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene un valore che indica se le informazioni sulla modalità di sicurezza deve essere serializzati."
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "Restituisce <xref:System.Boolean>che specifica <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> se le informazioni sulla modalità di sicurezza devono essere serializzate e <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se non deve essere serializzato...</xref:System.Boolean>"
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene un valore che indica se è necessario serializzare le informazioni sul trasporto."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "Restituisce <xref:System.Boolean>che specifica <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> se devono essere serializzate le informazioni sul trasporto e <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se non deve essere serializzato...</xref:System.Boolean>"
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  id: Transport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: System.ServiceModel.PeerSecuritySettings.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene il valore che indica le impostazioni di sicurezza per il trasporto utilizzato per i messaggi trasmessi sul canale peer."
  remarks: "Questa proprietà viene impostata solo se <xref:System.ServiceModel.PeerSecuritySettings.Mode%2A>è impostato su <xref:System.ServiceModel.SecurityMode>o <xref:System.ServiceModel.SecurityMode>.</xref:System.ServiceModel.SecurityMode> </xref:System.ServiceModel.SecurityMode> </xref:System.ServiceModel.PeerSecuritySettings.Mode%2A>"
  syntax:
    content: public System.ServiceModel.PeerTransportSecuritySettings Transport { get; set; }
    return:
      type: System.ServiceModel.PeerTransportSecuritySettings
      description: "<xref href=&quot;System.ServiceModel.PeerTransportSecuritySettings&quot;></xref>che contiene le impostazioni di sicurezza del trasporto del canale peer."
  overload: System.ServiceModel.PeerSecuritySettings.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: System.ServiceModel.PeerSecuritySettings.PeerSecuritySettings()
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: System.ServiceModel.PeerSecuritySettings.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport()
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: System.ServiceModel.PeerSecuritySettings.Transport
- uid: System.ServiceModel.PeerTransportSecuritySettings
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings
  fullName: System.ServiceModel.PeerTransportSecuritySettings
- uid: System.ServiceModel.PeerSecuritySettings.#ctor*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings.PeerSecuritySettings
- uid: System.ServiceModel.PeerSecuritySettings.Mode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: PeerSecuritySettings.ShouldSerializeMode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport
- uid: System.ServiceModel.PeerSecuritySettings.Transport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
