### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowEnvironment
  id: WorkflowEnvironment
  children:
  - System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  - System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  langs:
  - csharp
  name: WorkflowEnvironment
  nameWithType: WorkflowEnvironment
  fullName: System.Workflow.Runtime.WorkflowEnvironment
  type: Class
  summary: "Rappresenta l&quot;ambiente transazionale dell&quot;istanza del flusso di lavoro che è in esecuzione sul thread corrente."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]Il WorkflowEnvironment rappresenta l&quot;ambiente transazionale dell&quot;istanza del flusso di lavoro che è in esecuzione sul thread corrente. WorkflowEnvironment ha due proprietà: la <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>proprietà, che espone il batch di lavoro corrente e consente a un host o un servizio host di partecipare alla transazione corrente aggiungendo <xref:System.Workflow.Runtime.IPendingWork>elementi a questa proprietà; e <xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A>proprietà, che espone il <xref:System.Guid>dell&quot;istanza del flusso di lavoro attualmente in esecuzione su questo thread.</xref:System.Guid> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A> </xref:System.Workflow.Runtime.IPendingWork> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public static class WorkflowEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  id: WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Ottiene il batch di lavoro corrente."
  remarks: "La proprietà WorkBatch consente agli host o i servizi host di partecipare alla transazione corrente aggiungendo elementi di lavoro in sospeso al batch di lavoro corrente. Un host o un servizio host che desideri partecipare alla transazione corrente deve implementare il <xref:System.Workflow.Runtime.IPendingWork>l&quot;interfaccia e utilizzare <xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName>per aggiungere elementi di lavoro in sospeso a WorkBatch.</xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName> </xref:System.Workflow.Runtime.IPendingWork> Servizi durevoli devono aggiungere elementi a WorkBatch per mantenere lo stato degli archivi dati coerenti con lo stato dell&quot;istanza del flusso di lavoro. I servizi durevoli out-of-box, <xref:System.Workflow.Runtime.Tracking.SqlTrackingService>e <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService>, implementano entrambi questa funzionalità.</xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> </xref:System.Workflow.Runtime.Tracking.SqlTrackingService>"
  syntax:
    content: public static System.Workflow.Runtime.IWorkBatch WorkBatch { get; }
    return:
      type: System.Workflow.Runtime.IWorkBatch
      description: "Il <xref href=&quot;System.Workflow.Runtime.IWorkBatch&quot;> </xref> che rappresenta il batch di lavoro corrente."
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  id: WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Ottiene il <xref:System.Guid>dell&quot;istanza del flusso di lavoro associata al thread corrente.</xref:System.Guid>"
  remarks: "WorkflowInstanceId contiene il <xref:System.Guid>dell&quot;istanza del flusso di lavoro attualmente in esecuzione in questo thread.</xref:System.Guid> Ogni volta che viene eseguito codice all&quot;interno di un thread del flusso di lavoro, è possibile ottenere il <xref:System.Guid>dell&quot;istanza del flusso di lavoro tramite la proprietà WorkflowInstanceId.</xref:System.Guid> Ad esempio, se il codice è in un servizio chiamato da un&quot;attività, verranno fornite WorkflowInstanceId <xref:System.Guid>dell&quot;istanza del flusso di lavoro per l&quot;attività chiamante.</xref:System.Guid>"
  syntax:
    content: public static Guid WorkflowInstanceId { get; }
    return:
      type: System.Guid
      description: "Il <xref:System.Guid>che identifica l&quot;istanza del flusso di lavoro corrente.</xref:System.Guid>"
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.IWorkBatch
  parent: System.Workflow.Runtime
  isExternal: false
  name: IWorkBatch
  nameWithType: IWorkBatch
  fullName: System.Workflow.Runtime.IWorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
