### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfiguration
  id: ProtectedConfiguration
  children:
  - System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  - System.Configuration.ProtectedConfiguration.DefaultProvider
  - System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  - System.Configuration.ProtectedConfiguration.Providers
  - System.Configuration.ProtectedConfiguration.RsaProviderName
  langs:
  - csharp
  name: ProtectedConfiguration
  nameWithType: ProtectedConfiguration
  fullName: System.Configuration.ProtectedConfiguration
  type: Class
  summary: "Fornisce l&quot;accesso ai provider di configurazione protetta per il file di configurazione dell&quot;applicazione corrente."
  remarks: "La classe ProtectedConfiguration consente di ottenere informazioni sui provider di proteggere i dati di configurazione sensibili. È in genere utilizzare i provider standard, ma è anche possibile creare provider personalizzati derivandolo dalla <xref:System.Configuration.ProtectedConfigurationProvider>classe.</xref:System.Configuration.ProtectedConfigurationProvider>       Per ulteriori informazioni sulla configurazione protetta, vedere [crittografia configurazione informazioni tramite configurazione protetta](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to use the ProtectedConfiguration class to retrieve a collection of protected-configuration providers and discover their provider name, RSA provider name, and section names.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/csharp/t-system.configuration.p_4_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/visualbasic/t-system.configuration.p_4_1.vb)]"
  syntax:
    content: public static class ProtectedConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  id: DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il nome del provider di protezione dati."
  remarks: "Si tratta di una variabile costante stringa che contiene il nome del provider di protezione dei dati reso disponibile dal sistema per proteggere una sezione di configurazione."
  example:
  - "The following example shows how to use the DataProtectionProviderName property to retrieve the name of the current data-protection provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/csharp/f-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/visualbasic/f-system.configuration.p_2_1.vb)]"
  syntax:
    content: public const string DataProtectionProviderName;
    return:
      type: System.String
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il nome del provider di configurazione protetta predefinito."
  remarks: "Il provider predefinito è identificato dal `defaultProvider` attributo del `<configProtectedData>` elemento del file di configurazione. Il valore deve corrispondere al nome di uno dei provider aggiunti nella `<providers>` sottosezione del `<configProtectedData>` sezione. Il `<configProtectedData>` sezione è possibile accedere tramite un&quot;istanza della <xref:System.Configuration.ProtectedConfigurationSection>classe.</xref:System.Configuration.ProtectedConfigurationSection>"
  syntax:
    content: public static string DefaultProvider { get; }
    return:
      type: System.String
      description: "Il nome del provider di configurazione protetta predefinito."
  overload: System.Configuration.ProtectedConfiguration.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  id: ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il nome della sezione di dati protetti."
  remarks: "Si tratta di una variabile costante stringa che contiene il nome della sezione di dati protetti."
  example:
  - "The following example shows how to use the ProtectedDataSectionName property to retrieve the name of a protected data section.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/csharp/f-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/visualbasic/f-system.configuration.p_0_1.vb)]"
  syntax:
    content: public const string ProtectedDataSectionName;
    return:
      type: System.String
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene una raccolta di provider di configurazione protetta installati."
  remarks: ''
  example:
  - "The following example shows how to use the Providers property to retrieve the collection of installed <xref:System.Configuration.ProtectedConfigurationProvider> objects.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/csharp/p-system.configuration.p_16_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/visualbasic/p-system.configuration.p_16_1.vb)]"
  syntax:
    content: public static System.Configuration.ProtectedConfigurationProviderCollection Providers { get; }
    return:
      type: System.Configuration.ProtectedConfigurationProviderCollection
      description: "Oggetto <xref href=&quot;System.Configuration.ProtectedConfigurationProviderCollection&quot;> </xref> installato insieme di <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> oggetti."
  overload: System.Configuration.ProtectedConfiguration.Providers*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  id: RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il nome del provider RSA."
  remarks: "Si tratta di una variabile costante stringa che contiene il nome del provider RSA reso disponibile dal sistema per proteggere una sezione di configurazione."
  example:
  - "The following example shows how to use the RsaProviderName property to retrieve the name of the current RSA provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/csharp/f-system.configuration.p_1_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/visualbasic/f-system.configuration.p_1_1.vb)]"
  syntax:
    content: public const string RsaProviderName;
    return:
      type: System.String
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
- uid: System.Configuration.ProtectedConfiguration.Providers
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.Providers*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
