### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TagMapInfo
  id: TagMapInfo
  children:
  - System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  - System.Web.Configuration.TagMapInfo.Equals(System.Object)
  - System.Web.Configuration.TagMapInfo.GetHashCode
  - System.Web.Configuration.TagMapInfo.MappedTagType
  - System.Web.Configuration.TagMapInfo.Properties
  - System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Web.Configuration.TagMapInfo.TagType
  langs:
  - csharp
  name: TagMapInfo
  nameWithType: TagMapInfo
  fullName: System.Web.Configuration.TagMapInfo
  type: Class
  summary: "Contiene un tag di configurazione singola istruzione di modifica del mapping. Questa classe non può essere ereditata."
  remarks: "La classe TagMapInfo consente il mapping dei tipi di tag in fase di compilazione. Questo mapping determina il tipo di mapping da utilizzare al posto del tipo di tag originale per tutte le pagine e controlli nell&quot;applicazione ASP.NET nell&quot;ambito del file di configurazione.       La <xref:System.Web.Configuration.TagMapCollection>classe consente di accedere a livello di codice e di modificare il `tagMapping` sottosezione del `pages` sezione di un file di configurazione.</xref:System.Web.Configuration.TagMapCollection> All&quot;interno di `tagMappings` sottosezione, è possibile aggiungere e rimuovere i mapping tra tipi di tag specificando i nomi sicuri completi dei tipi.      > [!NOTE] > A differenza di altri attributi e le raccolte nel `pages` sezione, la modifica del tag non è alcuna direttiva della pagina ASP.NET corrispondente."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for several properties of the TagMapInfo class.  \n  \n```  \n<system.web>  \n  <pages>  \n    <tagMapping>  \n      <add  \n        tagType=  \n          \"System.Web.UI.WebControls.WebParts.WebPartManager\"  \n        mappedTagType=  \n          \"Microsoft.Sharepoint.WebPartPartManager,   \n           MSPS.Web.dll, Version='2.0.0.0'\"   \n      />  \n    </tagMapping>  \n  </pages>  \n</system.web>  \n```  \n  \n The following code example shows how to use the <xref:System.Web.Configuration.TagMapCollection> class to programmatically modify tag-mapping settings. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#17](~/add/codesnippet/csharp/t-system.web.configurati_73_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_73_1.vb)]"
  syntax:
    content: 'public sealed class TagMapInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.TagMapInfo&quot;> </xref> classe in base ai valori di proprietà passati."
  remarks: ''
  example:
  - "The following code example shows how to use the TagMapInfo constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#42](~/add/codesnippet/csharp/m-system.web.configurati_25_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#42](~/add/codesnippet/visualbasic/m-system.web.configurati_25_1.vb)]"
  syntax:
    content: public TagMapInfo (string tagTypeName, string mappedTagTypeName);
    parameters:
    - id: tagTypeName
      type: System.String
      description: "Il nome completo del tipo per il tag di cui modificare il mapping."
    - id: mappedTagTypeName
      type: System.String
      description: "Il nome del tipo a cui il tag viene eseguito il mapping, insieme alle informazioni di supporto."
  overload: System.Web.Configuration.TagMapInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Confronta questa istanza con un altro oggetto."
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: "Oggetto da confrontare."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se gli oggetti sono identici. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.TagMapInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Restituisce un valore hash per l&quot;istanza corrente."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Un valore hash per l&quot;istanza corrente."
  overload: System.Web.Configuration.TagMapInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  id: MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il nome del tipo a cui viene eseguito il mapping di tag."
  remarks: "Modifica del mapping di tag, si verifica in fase di compilazione. Questo mapping determina il tipo di mapping (specificato dalla proprietà MappedTagType) da utilizzare al posto del tipo di tag originale (specificato da di <xref:System.Web.Configuration.TagMapInfo.TagType%2A>proprietà) per tutte le pagine e controlli nell&quot;applicazione ASP.NET nell&quot;ambito del file di configurazione.</xref:System.Web.Configuration.TagMapInfo.TagType%2A>      > [!NOTE] > Un valore di stringa vuota per questa proprietà causerà il sistema di configurazione generare un&quot;eccezione quando viene serializzato l&quot;oggetto."
  example:
  - "The following code example shows how to use the MappedTagType property. It is part of a larger example for the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string MappedTagType { get; set; }
    return:
      type: System.String
      description: "Il nome del tipo a cui viene eseguito il mapping di tag. Il valore predefinito è una stringa vuota."
  overload: System.Web.Configuration.TagMapInfo.MappedTagType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Properties
  id: Properties
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.TagMapInfo.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  id: SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override bool SerializeElement (System.Xml.XmlWriter writer, bool serializeCollectionKey);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Da aggiungere."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Da aggiungere."
    return:
      type: System.Boolean
      description: "Da aggiungere."
  overload: System.Web.Configuration.TagMapInfo.SerializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.TagType
  id: TagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il nome del tipo originale per il tag di cui modificare il mapping."
  remarks: "Modifica del mapping di tag, si verifica in fase di compilazione. Questo mapping determina il tipo di mapping (specificato da di <xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>proprietà) da utilizzare al posto del tipo di tag originale (specificato dalla proprietà TagType) per tutte le pagine e controlli nell&quot;applicazione ASP.NET nell&quot;ambito del file di configurazione.</xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>      > [!NOTE] > Un valore di stringa vuota per questa proprietà causerà il sistema di configurazione generare un&quot;eccezione quando viene serializzato l&quot;oggetto."
  example:
  - "The following code example shows how to use the TagType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string TagType { get; set; }
    return:
      type: System.String
      description: "Il nome del tipo originale per il tag di cui modificare il mapping."
  overload: System.Web.Configuration.TagMapInfo.TagType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.Web.Configuration.TagMapInfo.TagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
- uid: System.Web.Configuration.TagMapInfo.#ctor*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo
  nameWithType: TagMapInfo.TagMapInfo
- uid: System.Web.Configuration.TagMapInfo.Equals*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals
  nameWithType: TagMapInfo.Equals
- uid: System.Web.Configuration.TagMapInfo.GetHashCode*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode
  nameWithType: TagMapInfo.GetHashCode
- uid: System.Web.Configuration.TagMapInfo.MappedTagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
- uid: System.Web.Configuration.TagMapInfo.SerializeElement*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement
  nameWithType: TagMapInfo.SerializeElement
- uid: System.Web.Configuration.TagMapInfo.TagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
