### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Compiler
  id: Compiler
  children:
  - System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  - System.Web.Configuration.Compiler.CompilerOptions
  - System.Web.Configuration.Compiler.Extension
  - System.Web.Configuration.Compiler.Language
  - System.Web.Configuration.Compiler.Properties
  - System.Web.Configuration.Compiler.Type
  - System.Web.Configuration.Compiler.WarningLevel
  langs:
  - csharp
  name: Compiler
  nameWithType: Compiler
  fullName: System.Web.Configuration.Compiler
  type: Class
  summary: "Definisce un compilatore che viene usato per supportare l&quot;infrastruttura di compilazione di applicazioni Web. Questa classe non può essere ereditata."
  remarks: "La classe del compilatore fornisce un modo per accedere a livello di programmazione un elemento di configurazione del compilatore."
  syntax:
    content: 'public sealed class Compiler : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Crea un&quot;istanza di un <xref href=&quot;System.Web.Configuration.Compiler&quot;> </xref> inizializzato in base ai valori specificati."
  syntax:
    content: public Compiler (string compilerOptions, string extension, string language, string type, int warningLevel);
    parameters:
    - id: compilerOptions
      type: System.String
      description: "Elenca le opzioni specifiche del compilatore aggiuntivi da passare durante la compilazione."
    - id: extension
      type: System.String
      description: "Fornisce un elenco delimitato da punto e virgola di estensioni di file utilizzato per i file code-behind dinamici. Ad esempio, &quot;cs&quot;."
    - id: language
      type: System.String
      description: "Fornisce un elenco delimitato da punto e virgola dei linguaggi utilizzati nei file di compilazione dinamica. Ad esempio, &quot;c#; cs; csharp&quot;."
    - id: type
      type: System.String
      description: "Specifica una combinazione di assembly/classe delimitato da virgole che indica la classe di .NET Framework."
    - id: warningLevel
      type: System.Int32
      description: "Specifica i livelli di avviso del compilatore."
  overload: System.Web.Configuration.Compiler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.CompilerOptions
  id: CompilerOptions
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene un elenco di opzioni del compilatore specifiche da utilizzare durante la compilazione."
  syntax:
    content: public string CompilerOptions { get; }
    return:
      type: System.String
      description: "Valore che specifica le opzioni del compilatore specifiche da utilizzare durante la compilazione. Non è un set unito ma invece l&quot;override dei valori definiti in precedenza nelle voci di configurazione precedente."
  overload: System.Web.Configuration.Compiler.CompilerOptions*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Extension
  id: Extension
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene un elenco di estensioni di file utilizzato per i file code-behind dinamici."
  remarks: "Quando l&quot;elenco di estensioni di file include più di un&quot;estensione, l&quot;elenco è separato da punto e virgola."
  syntax:
    content: public string Extension { get; }
    return:
      type: System.String
      description: "Un valore che specifica le estensioni di file utilizzate per i file code-behind dinamici, i file nella directory del codice e altri file di riferimento."
  overload: System.Web.Configuration.Compiler.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Language
  id: Language
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene un elenco di linguaggi di programmazione da utilizzare nei file di compilazione dinamica."
  remarks: "Quando l&quot;elenco dei linguaggi di programmazione include più di una lingua, l&quot;elenco è separato da punto e virgola."
  syntax:
    content: public string Language { get; }
    return:
      type: System.String
      description: "Valore che specifica i linguaggi di programmazione da utilizzare nei file di compilazione dinamica."
  overload: System.Web.Configuration.Compiler.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Properties
  id: Properties
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.Compiler.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Type
  id: Type
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il nome del tipo di provider del linguaggio del compilatore per i file di compilazione dinamica."
  remarks: "Specifica il nome del tipo di provider del linguaggio, inclusi il nome dell&quot;assembly contenente l&quot;implementazione del provider."
  syntax:
    content: public string Type { get; }
    return:
      type: System.String
      description: "Valore che specifica il nome del tipo di compilatore di linguaggio da utilizzare nei file di compilazione dinamica."
  overload: System.Web.Configuration.Compiler.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.WarningLevel
  id: WarningLevel
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il livello di avviso del compilatore."
  remarks: "Specifica il livello di avviso del compilatore predefinito; Determina il livello in corrispondenza del quale il provider del linguaggio considera gli avvisi di compilazione come errori."
  syntax:
    content: public int WarningLevel { get; }
    return:
      type: System.Int32
      description: "Un valore che specifica il livello di avviso del compilatore."
  overload: System.Web.Configuration.Compiler.WarningLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.Compiler.CompilerOptions
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Compiler.Type
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
- uid: System.Web.Configuration.Compiler.#ctor*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler
  nameWithType: Compiler.Compiler
- uid: System.Web.Configuration.Compiler.CompilerOptions*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
- uid: System.Web.Configuration.Compiler.Type*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
