### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsProtectionEnum
  id: FormsProtectionEnum
  children:
  - System.Web.Configuration.FormsProtectionEnum.All
  - System.Web.Configuration.FormsProtectionEnum.Encryption
  - System.Web.Configuration.FormsProtectionEnum.None
  - System.Web.Configuration.FormsProtectionEnum.Validation
  langs:
  - csharp
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
  type: Enum
  summary: "Definisce il tipo di crittografia, se presente, da utilizzare per i cookie."
  remarks: "Se si seleziona tutti i valori, il sistema utilizza l&quot;algoritmo di convalida dei dati configurato, in base il [elemento machineKey (Schema delle impostazioni ASP.NET)](http://msdn.microsoft.com/en-us/4b5699a9-bc21-4c4a-85f1-8b3b8ebd2d46) tag. Questo è l&quot;impostazione predefinita e un valore consigliato.       Se si specifica nessuno, i cookie potrebbero essere soggetti ad attacchi di testo normale.       Se si seleziona la convalida, il cookie viene creato utilizzando la convalida dei cookie concatenando una chiave di convalida con i dati del cookie, calcolando un codice MAC (Message Authentication), e aggiungendolo al cookie in uscita."
  example:
  - "The following code example shows how to use the FormsProtectionEnum enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/visualbasic/t-system.web.configurati_72_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/csharp/t-system.web.configurati_72_1.cs)]"
  syntax:
    content: public enum FormsProtectionEnum
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.All
  id: All
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che l&quot;applicazione utilizza la convalida dei dati sia la crittografia per proteggere i cookie. Questa opzione utilizza l&quot;algoritmo di convalida dei dati configurato (basato sul <xref uid=&quot;langword_csharp_machineKey&quot; name=&quot;machineKey&quot; href=&quot;&quot;> </xref> elemento). Triple DES (3DES) viene utilizzato per la crittografia, se disponibile e se la chiave è lunga almeno 48 byte. <xref uid=&quot;langword_csharp_All&quot; name=&quot;All&quot; href=&quot;&quot;></xref>il valore predefinito è (e consigliabile) valore."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  id: Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che i cookie sono crittografati con Triple DES o DES, ma la convalida dei dati non viene eseguita nel cookie. I cookie usati in questo modo potrebbero essere soggetti ad attacchi di sicurezza non crittografati selezionati."
  syntax:
    content: Encryption
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.None
  id: None
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che la crittografia e convalida sono disabilitate per i siti che usano i cookie solo per la personalizzazione e che hanno requisiti di sicurezza limitati. Si consiglia di non utilizzare i cookie in questo modo; Tuttavia, è il modo meno risorse per abilitare la personalizzazione tramite .NET Framework."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  id: Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che l&quot;applicazione utilizza uno schema di convalida per verificare che il contenuto di un cookie crittografato non sia stato alterato durante la trasmissione. Il cookie viene creato concatenando una chiave di convalida con i dati del cookie, calcolando un codice MAC (Message Authentication), e aggiungendolo al cookie in uscita."
  syntax:
    content: Validation
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsProtectionEnum.All
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
- uid: System.Web.Configuration.FormsProtectionEnum
  parent: System.Web.Configuration
  isExternal: false
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
- uid: System.Web.Configuration.FormsProtectionEnum.None
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
