### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TraceDisplayMode
  id: TraceDisplayMode
  children:
  - System.Web.Configuration.TraceDisplayMode.SortByCategory
  - System.Web.Configuration.TraceDisplayMode.SortByTime
  langs:
  - csharp
  name: TraceDisplayMode
  nameWithType: TraceDisplayMode
  fullName: System.Web.Configuration.TraceDisplayMode
  type: Enum
  summary: "Specifica l&quot;ordine in cui traccia vengono visualizzati i messaggi."
  remarks: "Questa enumerazione definisce i valori che è possibile utilizzare quando si imposta la <xref:System.Web.Configuration.TraceSection.TraceMode%2A>proprietà.</xref:System.Web.Configuration.TraceSection.TraceMode%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.TraceSection.TraceMode%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TraceSection> class.  \n  \n [!code-vb[System.Web.Configuration.TraceSection2#8](~/add/codesnippet/visualbasic/t-system.web.configurati_60_1.vb)]\n [!code-cs[System.Web.Configuration.TraceSection2#8](~/add/codesnippet/csharp/t-system.web.configurati_60_1.cs)]"
  syntax:
    content: public enum TraceDisplayMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TraceDisplayMode.SortByCategory
  id: SortByCategory
  parent: System.Web.Configuration.TraceDisplayMode
  langs:
  - csharp
  name: SortByCategory
  nameWithType: TraceDisplayMode.SortByCategory
  fullName: System.Web.Configuration.TraceDisplayMode.SortByCategory
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creare i messaggi di traccia in ordine alfabetico in base alla categoria."
  syntax:
    content: SortByCategory
    return:
      type: System.Web.Configuration.TraceDisplayMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TraceDisplayMode.SortByTime
  id: SortByTime
  parent: System.Web.Configuration.TraceDisplayMode
  langs:
  - csharp
  name: SortByTime
  nameWithType: TraceDisplayMode.SortByTime
  fullName: System.Web.Configuration.TraceDisplayMode.SortByTime
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creare i messaggi di traccia nell&quot;ordine in che cui sono stati elaborati."
  syntax:
    content: SortByTime
    return:
      type: System.Web.Configuration.TraceDisplayMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TraceDisplayMode.SortByCategory
  parent: System.Web.Configuration.TraceDisplayMode
  isExternal: false
  name: SortByCategory
  nameWithType: TraceDisplayMode.SortByCategory
  fullName: System.Web.Configuration.TraceDisplayMode.SortByCategory
- uid: System.Web.Configuration.TraceDisplayMode
  parent: System.Web.Configuration
  isExternal: false
  name: TraceDisplayMode
  nameWithType: TraceDisplayMode
  fullName: System.Web.Configuration.TraceDisplayMode
- uid: System.Web.Configuration.TraceDisplayMode.SortByTime
  parent: System.Web.Configuration.TraceDisplayMode
  isExternal: false
  name: SortByTime
  nameWithType: TraceDisplayMode.SortByTime
  fullName: System.Web.Configuration.TraceDisplayMode.SortByTime
