### YamlMime:ManagedReference
items:
- uid: System.Configuration.SingleTagSectionHandler
  id: SingleTagSectionHandler
  children:
  - System.Configuration.SingleTagSectionHandler.#ctor
  - System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler
  fullName: System.Configuration.SingleTagSectionHandler
  type: Class
  summary: "Gestisce le sezioni di configurazione che sono rappresentate da un singolo tag XML nel file config."
  syntax:
    content: 'public class SingleTagSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SingleTagSectionHandler&quot;> </xref> classe."
  syntax:
    content: public SingleTagSectionHandler ();
    parameters: []
  overload: System.Configuration.SingleTagSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Utilizzata internamente per creare una nuova istanza di questo oggetto."
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "L&quot;elemento padre di questo oggetto."
    - id: context
      type: System.Object
      description: "Il contesto di questo oggetto."
    - id: section
      type: System.Xml.XmlNode
      description: "Il <xref href=&quot;System.Xml.XmlNode&quot;> </xref> oggetto nella configurazione."
    return:
      type: System.Object
      description: "Il gestore dell&quot;oggetto creato."
  overload: System.Configuration.SingleTagSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.SingleTagSectionHandler.#ctor*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler
- uid: System.Configuration.SingleTagSectionHandler.Create*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create
  nameWithType: SingleTagSectionHandler.Create
