### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "Definisce i metodi che consentono a una classe caricare la configurazione personalizzata."
  remarks: "Le classi che implementano l&quot;interfaccia ICustomIdentityConfiguration possano caricare la configurazione personalizzata da XML.       Molte delle classi Windows Identity Foundation (WIF) implementa l&quot;interfaccia ICustomIdentityConfiguration per fornire la funzionalità che consentono di definire una configurazione personalizzata di classi derivate da un file di configurazione. Molte delle classi di WIF forniscono un&quot;implementazione di base di questo metodo per fornire la configurazione predefinita per gli oggetti che rappresentano."
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Configurazione personalizzata di caricamento da XML. Eseguire l&quot;override di questo metodo per la gestione personalizzata degli elementi di configurazione."
  remarks: "Il metodo LoadCustomConfiguration viene chiamato dall&quot;infrastruttura di configurazione. Quando questo metodo viene chiamato, il `nodelist` parametro contiene gli elementi figlio di livello superiore dell&quot;elemento padre che configura la classe di oggetti dal file di configurazione. Ad esempio, una classe derivata da <xref:System.IdentityModel.Tokens.IssuerNameRegistry>, avrà gli elementi figlio del [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) elemento passato il `nodelist` parametro.</xref:System.IdentityModel.Tokens.IssuerNameRegistry> Il `nodelist` è costituito interamente <xref:System.Xml.XmlElement>oggetti.</xref:System.Xml.XmlElement> Ognuno di questi può avere attributi ed elementi figlio in base allo schema di configurazione definito per la classe che viene configurata."
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "I nodi XML che contengono la configurazione personalizzata. Ogni nodo nell&quot;elenco è di tipo <xref href=&quot;System.Xml.XmlElement&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
