### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HostingEnvironmentSection
  id: HostingEnvironmentSection
  children:
  - System.Web.Configuration.HostingEnvironmentSection.#ctor
  - System.Web.Configuration.HostingEnvironmentSection.IdleTimeout
  - System.Web.Configuration.HostingEnvironmentSection.Properties
  - System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies
  - System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout
  - System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration
  langs:
  - csharp
  name: HostingEnvironmentSection
  nameWithType: HostingEnvironmentSection
  fullName: System.Web.Configuration.HostingEnvironmentSection
  type: Class
  summary: "Definisce le impostazioni di configurazione che controllano il comportamento dell&quot;applicazione ambiente host. Questa classe non può essere ereditata."
  remarks: "La classe HostingEnvironmentSection fornisce un modo per accedere e modificare i valori della sezione HostingEnvironmentSection nel file di configurazione a livello di codice. Quando un&quot;applicazione ASP.NET è inutilizzata per un periodo di tempo specificato, può essere scaricato dalla memoria sulla base di <xref:System.Web.Configuration.HostingEnvironmentSection.IdleTimeout%2A>e <xref:System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout%2A>proprietà.</xref:System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout%2A> </xref:System.Web.Configuration.HostingEnvironmentSection.IdleTimeout%2A>"
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the [hostingEnvironment Element (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/043a75c8-231a-4f8d-9633-501530bd7d40) section, which can also be accessed as members of the HostingEnvironmentSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the [hostingEnvironment Element (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/043a75c8-231a-4f8d-9633-501530bd7d40) section.  \n  \n```  \n<system.web>  \n  <hostingEnvironment  \n    idleTimeout=\"20\"  \n    shutdownTimeout=\"30\"  \n  />  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the HostingEnvironmentSection class.  \n  \n [!code-vb[System.Web.Configuration.HostingEnvironmentSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_2_1.vb)]\n [!code-cs[System.Web.Configuration.HostingEnvironmentSection#1](~/add/codesnippet/csharp/t-system.web.configurati_2_1.cs)]"
  syntax:
    content: 'public sealed class HostingEnvironmentSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: HostingEnvironmentSection()
  nameWithType: HostingEnvironmentSection.HostingEnvironmentSection()
  fullName: System.Web.Configuration.HostingEnvironmentSection.HostingEnvironmentSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.HostingEnvironmentSection&quot;> </xref> classe utilizzando le impostazioni predefinite."
  remarks: "Il costruttore HostingEnvironmentSection non deve essere utilizzato direttamente dal codice. Viene chiamato dal sistema di configurazione ASP.NET. Per ottenere un&quot;istanza di <xref:System.Web.Configuration.HostingEnvironmentSection>classe utilizzando il <xref:System.Configuration.Configuration.GetSection%2A>(metodo).</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HostingEnvironmentSection>"
  syntax:
    content: public HostingEnvironmentSection ();
    parameters: []
  overload: System.Web.Configuration.HostingEnvironmentSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout
  id: IdleTimeout
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: HostingEnvironmentSection.IdleTimeout
  fullName: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta la quantità di tempo, espresso in minuti, prima dello scaricamento di un&quot;applicazione inattiva."
  remarks: "Il valore predefinito per la proprietà IdleTimeout è &quot;Infinito&quot;. Questo può essere impostata a livello di computer o dell&quot;applicazione. Se questa impostazione è definita a qualsiasi altro livello, viene ignorato."
  example:
  - "The following code example shows how to use the IdleTimeout property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.HostingEnvironmentSection> class.  \n  \n [!code-vb[System.Web.Configuration.HostingEnvironmentSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_158_1.vb)]\n [!code-cs[System.Web.Configuration.HostingEnvironmentSection#2](~/add/codesnippet/csharp/p-system.web.configurati_158_1.cs)]"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>che rappresenta il numero specificato di minuti prima dello scaricamento di un&quot;applicazione inattiva.</xref:System.TimeSpan>"
  overload: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.Properties
  id: Properties
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: Properties
  nameWithType: HostingEnvironmentSection.Properties
  fullName: System.Web.Configuration.HostingEnvironmentSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.HostingEnvironmentSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies
  id: ShadowCopyBinAssemblies
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: ShadowCopyBinAssemblies
  nameWithType: HostingEnvironmentSection.ShadowCopyBinAssemblies
  fullName: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta un valore che indica se gli assembly di un&quot;applicazione in Bin vengono replicati nella directory dei file temporanei ASP.NET dell&quot;applicazione."
  syntax:
    content: public bool ShadowCopyBinAssemblies { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se gli assembly di un&quot;applicazione in Bin vengono replicati nella directory dei file temporanei ASP.NET dell&quot;applicazione; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout
  id: ShutdownTimeout
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: ShutdownTimeout
  nameWithType: HostingEnvironmentSection.ShutdownTimeout
  fullName: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta la quantità di tempo, espresso in secondi, per la corretta chiusura dell&quot;applicazione."
  remarks: "Il valore predefinito per la proprietà ShutdownTimeout è 30 secondi. Questo può essere impostata a livello di computer o dell&quot;applicazione. Se questa impostazione è definita a qualsiasi altro livello di configurazione, viene ignorato. Se un debugger è collegato all&quot;applicazione, l&quot;applicazione non essere arrestato."
  example:
  - "The following code example shows how to use the ShutdownTimeout property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.HostingEnvironmentSection> class.  \n  \n [!code-vb[System.Web.Configuration.HostingEnvironmentSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_291_1.vb)]\n [!code-cs[System.Web.Configuration.HostingEnvironmentSection#3](~/add/codesnippet/csharp/p-system.web.configurati_291_1.cs)]"
  syntax:
    content: public TimeSpan ShutdownTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>che rappresenta il numero specificato di secondi per la corretta chiusura dell&quot;applicazione.</xref:System.TimeSpan> Il valore predefinito è 30 secondi."
  overload: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration
  id: UrlMetadataSlidingExpiration
  parent: System.Web.Configuration.HostingEnvironmentSection
  langs:
  - csharp
  name: UrlMetadataSlidingExpiration
  nameWithType: HostingEnvironmentSection.UrlMetadataSlidingExpiration
  fullName: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta un valore che determina la modalità di memorizzazione nella cache dei metadati dell&quot;URL di ASP.NET."
  remarks: "Un esempio di URL metadati è informazioni nel file Web. config sulle restrizioni di sicurezza che si applicano a un particolare URL.       I valori seguenti hanno significati speciali:: &quot;Infinito&quot;. URL metadati viene memorizzato nella cache senza una scadenza. Ciò significa che la memorizzazione nella cache continua fino a quando il server utilizza la massima quantità di memoria assegnata. Questo è il comportamento predefinito in ASP.NET 3.5 e versioni precedenti.      -   &quot;00:00:00&quot;. URL metadati non è memorizzato nella cache. I metadati vengono rigenerati con ogni richiesta. Questo è più efficiente per gli scenari in cui è richiesta raramente lo stesso URL."
  syntax:
    content: public TimeSpan UrlMetadataSlidingExpiration { get; set; }
    return:
      type: System.TimeSpan
      description: "Un valore che determina la modalità di memorizzazione nella cache dei metadati dell&quot;URL di ASP.NET. Il valore predefinito è 1 minuto."
  overload: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HostingEnvironmentSection.#ctor
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: HostingEnvironmentSection()
  nameWithType: HostingEnvironmentSection.HostingEnvironmentSection()
  fullName: System.Web.Configuration.HostingEnvironmentSection.HostingEnvironmentSection()
- uid: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: IdleTimeout
  nameWithType: HostingEnvironmentSection.IdleTimeout
  fullName: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.HostingEnvironmentSection.Properties
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: Properties
  nameWithType: HostingEnvironmentSection.Properties
  fullName: System.Web.Configuration.HostingEnvironmentSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: ShadowCopyBinAssemblies
  nameWithType: HostingEnvironmentSection.ShadowCopyBinAssemblies
  fullName: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: ShutdownTimeout
  nameWithType: HostingEnvironmentSection.ShutdownTimeout
  fullName: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout
- uid: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: UrlMetadataSlidingExpiration
  nameWithType: HostingEnvironmentSection.UrlMetadataSlidingExpiration
  fullName: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration
- uid: System.Web.Configuration.HostingEnvironmentSection.#ctor*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: HostingEnvironmentSection
  nameWithType: HostingEnvironmentSection.HostingEnvironmentSection
- uid: System.Web.Configuration.HostingEnvironmentSection.IdleTimeout*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: IdleTimeout
  nameWithType: HostingEnvironmentSection.IdleTimeout
- uid: System.Web.Configuration.HostingEnvironmentSection.Properties*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: Properties
  nameWithType: HostingEnvironmentSection.Properties
- uid: System.Web.Configuration.HostingEnvironmentSection.ShadowCopyBinAssemblies*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: ShadowCopyBinAssemblies
  nameWithType: HostingEnvironmentSection.ShadowCopyBinAssemblies
- uid: System.Web.Configuration.HostingEnvironmentSection.ShutdownTimeout*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: ShutdownTimeout
  nameWithType: HostingEnvironmentSection.ShutdownTimeout
- uid: System.Web.Configuration.HostingEnvironmentSection.UrlMetadataSlidingExpiration*
  parent: System.Web.Configuration.HostingEnvironmentSection
  isExternal: false
  name: UrlMetadataSlidingExpiration
  nameWithType: HostingEnvironmentSection.UrlMetadataSlidingExpiration
