### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationTrustEnumerator
  id: ApplicationTrustEnumerator
  children:
  - System.Security.Policy.ApplicationTrustEnumerator.Current
  - System.Security.Policy.ApplicationTrustEnumerator.MoveNext
  - System.Security.Policy.ApplicationTrustEnumerator.Reset
  - System.Security.Policy.ApplicationTrustEnumerator.System#Collections#IEnumerator#Current
  langs:
  - csharp
  name: ApplicationTrustEnumerator
  nameWithType: ApplicationTrustEnumerator
  fullName: System.Security.Policy.ApplicationTrustEnumerator
  type: Class
  summary: "Rappresenta l&quot;enumeratore per <xref href=&quot;System.Security.Policy.ApplicationTrust&quot;> </xref> gli oggetti di <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref> insieme."
  remarks: "Gli enumeratori consentono solo la lettura dei dati nella raccolta. Non è possibile utilizzare enumeratori per modificare la raccolta sottostante.       Inizialmente l&quot;enumeratore è posizionato prima del primo elemento nella raccolta. Il <xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A>metodo riporta l&quot;enumeratore in questa posizione.</xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A> In questa posizione, la chiamata di <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>proprietà genera un&quot;eccezione.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> Pertanto, è necessario chiamare il <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>metodo per passare l&quot;enumeratore al primo elemento della raccolta prima di leggere il valore della <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>proprietà.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>       <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>Restituisce lo stesso oggetto finché non <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>o <xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A>viene chiamato.</xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A></xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>imposta <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>all&quot;elemento successivo.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A></xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>       Una volta raggiunta la fine della raccolta, l&quot;enumeratore sarà posizionato dopo l&quot;ultimo elemento nella raccolta e la chiamata <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>restituisce `false`.</xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A> Se l&quot;ultima chiamata a <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>restituito `false`, la chiamata <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>genera un&quot;eccezione.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A> Per reimpostare <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>il primo elemento della raccolta, chiamare il metodo <xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A>seguita da una chiamata a <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>.</xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>       Un enumeratore rimane valido fino a quando la raccolta rimane invariata. Se vengono apportate modifiche alla raccolta, ad esempio aggiungendo, modificando o eliminando elementi, l&quot;enumeratore viene invalidato in modo irreversibile e la successiva chiamata al <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>o <xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A>Genera un <xref:System.InvalidOperationException>eccezione.</xref:System.InvalidOperationException> </xref:System.Security.Policy.ApplicationTrustEnumerator.Reset%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A> Se la raccolta viene modificata tra la chiamata <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>e <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>, <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>restituisce l&quot;elemento a cui è impostata, anche se l&quot;enumeratore risulta già invalidato.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>       L&quot;enumeratore non dispone di accesso esclusivo alla raccolta. Pertanto, l&quot;enumerazione di una raccolta non è quindi una procedura thread-safe. Anche se una raccolta è sincronizzata, altri thread possa comunque modificare la raccolta, che determina l&quot;enumeratore generare un&quot;eccezione. Per garantire la protezione dei thread durante l&quot;enumerazione, bloccare la raccolta per l&quot;intera enumerazione oppure intercettare le eccezioni determinate dalle modifiche apportate da altri thread."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ApplicationTrustEnumerator : System.Collections.IEnumerator
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerator
  inheritedMembers: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationTrustEnumerator.Current
  id: Current
  parent: System.Security.Policy.ApplicationTrustEnumerator
  langs:
  - csharp
  name: Current
  nameWithType: ApplicationTrustEnumerator.Current
  fullName: System.Security.Policy.ApplicationTrustEnumerator.Current
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene l&quot;oggetto corrente <xref href=&quot;System.Security.Policy.ApplicationTrust&quot;> </xref> oggetto di <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref> insieme."
  remarks: "Quando viene creato l&quot;enumeratore, non corrisponde a un oggetto, in modo che la proprietà corrente non è valida e verrà generata un&quot;eccezione se vi si accede. È necessario chiamare prima il <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>metodo per posizionare il cursore in corrispondenza del primo oggetto nella raccolta.</xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>       Più chiamate a corrente senza alcuna chiamata a <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>restituirà lo stesso <xref:System.Security.Policy.ApplicationTrust>oggetto.</xref:System.Security.Policy.ApplicationTrust> </xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>"
  syntax:
    content: public System.Security.Policy.ApplicationTrust Current { get; }
    return:
      type: System.Security.Policy.ApplicationTrust
      description: "The current <xref href=&quot;System.Security.Policy.ApplicationTrust&quot;></xref> in the <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;></xref>."
  overload: System.Security.Policy.ApplicationTrustEnumerator.Current*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationTrustEnumerator.MoveNext
  id: MoveNext
  parent: System.Security.Policy.ApplicationTrustEnumerator
  langs:
  - csharp
  name: MoveNext()
  nameWithType: ApplicationTrustEnumerator.MoveNext()
  fullName: System.Security.Policy.ApplicationTrustEnumerator.MoveNext()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Passa all&quot;elemento successivo nel <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref> insieme."
  remarks: "Il metodo MoveNext restituisce immediatamente `false` se non sono presenti oggetti nella raccolta.       MoveNext restituirà `true` fino a quando non raggiunta la fine della raccolta. Verrà quindi restituito `false` per ogni chiamata successiva. Tuttavia, dopo che ha restituito MoveNext `false`, l&quot;accesso al <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>proprietà genererà un&quot;eccezione.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>       Al momento della creazione, l&quot;enumeratore è posizionato prima del primo <xref:System.Security.Policy.ApplicationTrust>oggetto nella raccolta e la prima chiamata a MoveNext posiziona l&quot;enumeratore al primo oggetto nella raccolta.</xref:System.Security.Policy.ApplicationTrust>"
  syntax:
    content: public bool MoveNext ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;enumeratore è avanzato all&quot;elemento successivo; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se l&quot;enumeratore ha superato la fine della raccolta."
  overload: System.Security.Policy.ApplicationTrustEnumerator.MoveNext*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationTrustEnumerator.Reset
  id: Reset
  parent: System.Security.Policy.ApplicationTrustEnumerator
  langs:
  - csharp
  name: Reset()
  nameWithType: ApplicationTrustEnumerator.Reset()
  fullName: System.Security.Policy.ApplicationTrustEnumerator.Reset()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Reimposta l&quot;enumeratore all&quot;inizio del <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref> insieme."
  remarks: "Un enumeratore viene spostato in una direzione forward-only. Utilizzare questo metodo per restituire l&quot;enumeratore all&quot;inizio dell&quot;insieme di <xref:System.Security.Policy.ApplicationTrust>oggetti.</xref:System.Security.Policy.ApplicationTrust>       Il metodo Reset posiziona il cursore in corrispondenza del primo oggetto nella raccolta. Dopo la chiamata a Reset, non è necessario chiamare il <xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>per spostare in avanti il cursore sul primo oggetto.</xref:System.Security.Policy.ApplicationTrustEnumerator.MoveNext%2A>"
  syntax:
    content: public void Reset ();
    parameters: []
  overload: System.Security.Policy.ApplicationTrustEnumerator.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationTrustEnumerator.System#Collections#IEnumerator#Current
  id: System#Collections#IEnumerator#Current
  isEii: true
  parent: System.Security.Policy.ApplicationTrustEnumerator
  langs:
  - csharp
  name: System.Collections.IEnumerator.Current
  nameWithType: ApplicationTrustEnumerator.System.Collections.IEnumerator.Current
  fullName: System.Security.Policy.ApplicationTrustEnumerator.System.Collections.IEnumerator.Current
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Ottiene l&quot;oggetto corrente <xref:System.Object>nel <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref> insieme.</xref:System.Object>"
  remarks: "Non chiamare questo metodo. Utilizzare il <xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>proprietà invece.</xref:System.Security.Policy.ApplicationTrustEnumerator.Current%2A>"
  syntax:
    content: object System.Collections.IEnumerator.Current { get; }
    return:
      type: System.Object
      description: "Corrente <xref:System.Object>nel <xref href=&quot;System.Security.Policy.ApplicationTrustCollection&quot;> </xref>.</xref:System.Object>"
  overload: System.Security.Policy.ApplicationTrustEnumerator.System#Collections#IEnumerator#Current*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Security.Policy.ApplicationTrustEnumerator.Current
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: Current
  nameWithType: ApplicationTrustEnumerator.Current
  fullName: System.Security.Policy.ApplicationTrustEnumerator.Current
- uid: System.Security.Policy.ApplicationTrust
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationTrust
  nameWithType: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
- uid: System.Security.Policy.ApplicationTrustEnumerator.MoveNext
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: MoveNext()
  nameWithType: ApplicationTrustEnumerator.MoveNext()
  fullName: System.Security.Policy.ApplicationTrustEnumerator.MoveNext()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Policy.ApplicationTrustEnumerator.Reset
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: Reset()
  nameWithType: ApplicationTrustEnumerator.Reset()
  fullName: System.Security.Policy.ApplicationTrustEnumerator.Reset()
- uid: System.Security.Policy.ApplicationTrustEnumerator.System#Collections#IEnumerator#Current
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: System.Collections.IEnumerator.Current
  nameWithType: ApplicationTrustEnumerator.System.Collections.IEnumerator.Current
  fullName: System.Security.Policy.ApplicationTrustEnumerator.System.Collections.IEnumerator.Current
- uid: System.Security.Policy.ApplicationTrustEnumerator.Current*
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: Current
  nameWithType: ApplicationTrustEnumerator.Current
- uid: System.Security.Policy.ApplicationTrustEnumerator.MoveNext*
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: MoveNext
  nameWithType: ApplicationTrustEnumerator.MoveNext
- uid: System.Security.Policy.ApplicationTrustEnumerator.Reset*
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: Reset
  nameWithType: ApplicationTrustEnumerator.Reset
- uid: System.Security.Policy.ApplicationTrustEnumerator.System#Collections#IEnumerator#Current*
  parent: System.Security.Policy.ApplicationTrustEnumerator
  isExternal: false
  name: System.Collections.IEnumerator.Current
  nameWithType: ApplicationTrustEnumerator.System.Collections.IEnumerator.Current
