### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.DiagnosticsConfigurationHandler
  id: DiagnosticsConfigurationHandler
  children:
  - System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  - System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler
  type: Class
  summary: "Gestisce la sezione di diagnostica dei file di configurazione."
  remarks: "Il metodo DiagnosticsConfigurationHandler è un gestore della sezione che partecipa alla risoluzione di impostazioni di configurazione di [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) parte dei file di configurazione."
  syntax:
    content: >-
      [System.Obsolete("This class has been deprecated.  http://go.microsoft.com/fwlink/?linkid=14202")]

      public class DiagnosticsConfigurationHandler : System.Configuration.IConfigurationSectionHandler
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Diagnostics.DiagnosticsConfigurationHandler&quot;> </xref> classe."
  syntax:
    content: public DiagnosticsConfigurationHandler ();
    parameters: []
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Analizza le impostazioni di configurazione per il [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) sezione del file di configurazione."
  remarks: "Il metodo Create popola un <xref:System.Collections.Hashtable>con i valori ottenuti il [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) sezione di un file di configurazione e restituisce la tabella hash.</xref:System.Collections.Hashtable>"
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "L&quot;oggetto ereditato dal percorso padre"
    - id: configContext
      type: System.Object
      description: "riservato. Utilizzati in ASP.NET per fornire il percorso virtuale della configurazione da valutare."
    - id: section
      type: System.Xml.XmlNode
      description: "Il nodo XML radice sezione da gestire."
    return:
      type: System.Object
      description: "Un nuovo oggetto di configurazione, sotto forma di un <xref href=&quot;System.Collections.Hashtable&quot;> </xref>."
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Parametri non è state trovate.       - oppure - asserzione non è stato trovato.       - oppure - traccia non è stata trovata.       - oppure - contatori delle prestazioni non è stati trovati."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DiagnosticsConfigurationHandler.Create
