### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: "Incapsula le informazioni di contesto sono associate un <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> oggetto. Questa classe non può essere ereditata."
  remarks: "L&quot;oggetto ContextInformation fornisce dettagli sull&quot;ambiente correlati a un elemento della configurazione. Ad esempio, è possibile utilizzare il <xref:System.Configuration.ContextInformation.IsMachineLevel%2A>proprietà per determinare se un <xref:System.Configuration.ConfigurationElement>in Machine. config è stata impostata o è possibile determinare quale gerarchia un <xref:System.Configuration.ConfigurationElement>appartiene utilizzando il <xref:System.Configuration.ContextInformation.HostingContext%2A>proprietà.</xref:System.Configuration.ContextInformation.HostingContext%2A> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ContextInformation.IsMachineLevel%2A>"
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!code-vb[System.Configuration.ContextInformation#1](~/add/codesnippet/visualbasic/t-system.configuration.c_0_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#1](~/add/codesnippet/csharp/t-system.configuration.c_0_1.cs)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Fornisce un oggetto contenente le informazioni della sezione di configurazione in base al nome della sezione specificata."
  remarks: "Quando si specifica una sezione all&quot;interno della configurazione, si noti che il nome della sezione di configurazione tra maiuscole e minuscole."
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Il nome della sezione di configurazione."
    return:
      type: System.Object
      description: "Oggetto che contiene la sezione specificata all&quot;interno della configurazione."
  overload: System.Configuration.ContextInformation.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene il contesto dell&quot;ambiente in cui viene valutata la proprietà di configurazione."
  remarks: "Il valore HostingContext è <xref:System.Web.Configuration.WebContext>, <xref:System.Configuration.ExeContext>, o `null`.</xref:System.Configuration.ExeContext> </xref:System.Web.Configuration.WebContext>"
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!code-vb[System.Configuration.ContextInformation#3](~/add/codesnippet/visualbasic/p-system.configuration.c_46_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#3](~/add/codesnippet/csharp/p-system.configuration.c_46_1.cs)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: "Oggetto che specifica l&quot;ambiente in cui viene valutata la proprietà di configurazione."
  overload: System.Configuration.ContextInformation.HostingContext*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene un valore che specifica se la proprietà di configurazione viene valutata a livello di configurazione di computer."
  remarks: "Quando il valore restituito di IsMachineLevel è `false`, utilizzare il <xref:System.Configuration.ContextInformation.HostingContext%2A>proprietà per determinare il livello nella gerarchia di configurazione.</xref:System.Configuration.ContextInformation.HostingContext%2A>"
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!code-vb[System.Configuration.ContextInformation#2](~/add/codesnippet/visualbasic/p-system.configuration.c_7_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#2](~/add/codesnippet/csharp/p-system.configuration.c_7_1.cs)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la proprietà di configurazione viene valutata a livello di configurazione di computer. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ContextInformation.IsMachineLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ContextInformation.GetSection*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection
  nameWithType: ContextInformation.GetSection
- uid: System.Configuration.ContextInformation.HostingContext*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
