### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.SmtpSection
  id: SmtpSection
  children:
  - System.Net.Configuration.SmtpSection.#ctor
  - System.Net.Configuration.SmtpSection.DeliveryFormat
  - System.Net.Configuration.SmtpSection.DeliveryMethod
  - System.Net.Configuration.SmtpSection.From
  - System.Net.Configuration.SmtpSection.Network
  - System.Net.Configuration.SmtpSection.Properties
  - System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  langs:
  - csharp
  name: SmtpSection
  nameWithType: SmtpSection
  fullName: System.Net.Configuration.SmtpSection
  type: Class
  summary: "Rappresenta la sezione SMTP nel <xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;> </xref> file di configurazione."
  remarks: "Questa classe fornisce accesso a livello di codice alle informazioni che possono essere archiviate in file di configurazione che vengono utilizzati dalle classi che supportano SMTP in ingresso il <xref:System.Net.Mail>dello spazio dei nomi.</xref:System.Net.Mail>"
  syntax:
    content: 'public sealed class SmtpSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Net.Configuration.SmtpSection&quot;> </xref> classe."
  syntax:
    content: public SmtpSection ();
    parameters: []
  overload: System.Net.Configuration.SmtpSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  id: DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta il formato di recapito da utilizzare per l&quot;invio di posta elettronica in uscita tramite il trasporto protocollo SMTP (Simple Mail)."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryFormat DeliveryFormat { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryFormat
      description: "Returns <xref href=&quot;System.Net.Mail.SmtpDeliveryFormat&quot;></xref>.       Il formato da utilizzare per l&quot;invio in uscita recapito messaggi di posta elettronica tramite SMTP."
  overload: System.Net.Configuration.SmtpSection.DeliveryFormat*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  id: DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta il metodo di recapito SMTP Simple Mail Transport Protocol (). Il metodo di recapito predefinita è <xref href=&quot;System.Net.Mail.SmtpDeliveryMethod&quot;> </xref>."
  remarks: "I valori validi per questa proprietà sono <xref:System.Net.Mail.SmtpDeliveryMethod>, <xref:System.Net.Mail.SmtpDeliveryMethod>e <xref:System.Net.Mail.SmtpDeliveryMethod>.</xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> Questi valori elementi secondari e di una sezione corrispondente `System.Net` file di configurazione. Tutte le sezioni sono maiuscole/minuscole camel, per consentire agli utenti di corrisponde al metodo di recapito con i relativi nomi di sezione corrispondente."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryMethod DeliveryMethod { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryMethod
      description: "Stringa che rappresenta il metodo di recapito SMTP."
  overload: System.Net.Configuration.SmtpSection.DeliveryMethod*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.From
  id: From
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta il valore predefinito che indica che il messaggio di posta elettronica da."
  syntax:
    content: public string From { get; set; }
    return:
      type: System.String
      description: "Stringa che rappresenta il valore predefinito indica che un messaggio di posta elettronica da."
  overload: System.Net.Configuration.SmtpSection.From*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Network
  id: Network
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene l&quot;elemento di configurazione che controlla le impostazioni di rete utilizzate per il trasporto protocollo SMTP (Simple Mail). file. <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref>."
  syntax:
    content: public System.Net.Configuration.SmtpNetworkElement Network { get; }
    return:
      type: System.Net.Configuration.SmtpNetworkElement
      description: "A <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref> object.       L&quot;elemento di configurazione che controlla le impostazioni di rete utilizzate da SMTP."
  overload: System.Net.Configuration.SmtpSection.Network*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Properties
  id: Properties
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Net.Configuration.SmtpSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  id: SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene la directory di prelievo che verrà utilizzata dal client SMPT."
  remarks: "Indica che la directory specificata da <xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A>verrà utilizzato come directory di prelievo SMTP.</xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A> Se il client SMTP è in grado di scrivere all&quot;eccezione di un / o percorso di directory di prelievo, viene generata da <xref:System.Net.Mail.SmtpClient.Send%2A>.</xref:System.Net.Mail.SmtpClient.Send%2A> La directory non verrà creata se non esiste. Le credenziali del processo o thread attualmente in esecuzione verranno utilizzate per accedere alla directory."
  syntax:
    content: public System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement SpecifiedPickupDirectory { get; }
    return:
      type: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
      description: "Oggetto <xref href=&quot;System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement&quot;> </xref> oggetto che specifica la cartella della directory di prelievo."
  overload: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.SmtpSection.#ctor
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
- uid: System.Net.Mail.SmtpDeliveryFormat
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryFormat
  nameWithType: SmtpDeliveryFormat
  fullName: System.Net.Mail.SmtpDeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
- uid: System.Net.Mail.SmtpDeliveryMethod
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryMethod
  nameWithType: SmtpDeliveryMethod
  fullName: System.Net.Mail.SmtpDeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.SmtpSection.Network
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
- uid: System.Net.Configuration.SmtpNetworkElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpNetworkElement
  nameWithType: SmtpNetworkElement
  fullName: System.Net.Configuration.SmtpNetworkElement
- uid: System.Net.Configuration.SmtpSection.Properties
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpSpecifiedPickupDirectoryElement
  nameWithType: SmtpSpecifiedPickupDirectoryElement
  fullName: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
- uid: System.Net.Configuration.SmtpSection.#ctor*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection
  nameWithType: SmtpSection.SmtpSection
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
- uid: System.Net.Configuration.SmtpSection.Network*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
- uid: System.Net.Configuration.SmtpSection.Properties*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
