### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerCredentialElement
  id: PeerCredentialElement
  children:
  - System.ServiceModel.Configuration.PeerCredentialElement.#ctor
  - System.ServiceModel.Configuration.PeerCredentialElement.Certificate
  - System.ServiceModel.Configuration.PeerCredentialElement.Copy(System.ServiceModel.Configuration.PeerCredentialElement)
  - System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication
  - System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication
  - System.ServiceModel.Configuration.PeerCredentialElement.Properties
  langs:
  - csharp
  name: PeerCredentialElement
  nameWithType: PeerCredentialElement
  fullName: System.ServiceModel.Configuration.PeerCredentialElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che configura una credenziale peer."
  syntax:
    content: 'public sealed class PeerCredentialElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: PeerCredentialElement()
  nameWithType: PeerCredentialElement.PeerCredentialElement()
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.PeerCredentialElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza un nuovo elemento predefinita di <xref href=&quot;System.ServiceModel.Configuration.PeerCredentialElement&quot;> </xref> classe."
  syntax:
    content: public PeerCredentialElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerCredentialElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Certificate
  id: Certificate
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: Certificate
  nameWithType: PeerCredentialElement.Certificate
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Certificate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;elemento per un X509 certificato dall&quot;elemento di configurazione credenziale peer."
  syntax:
    content: public System.ServiceModel.Configuration.X509PeerCertificateElement Certificate { get; }
    return:
      type: System.ServiceModel.Configuration.X509PeerCertificateElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.X509PeerCertificateElement&quot;></xref>che contiene l&quot;elemento di configurazione per X509 certificato associato all&quot;elemento di configurazione credenziale peer corrente."
  overload: System.ServiceModel.Configuration.PeerCredentialElement.Certificate*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Copy(System.ServiceModel.Configuration.PeerCredentialElement)
  id: Copy(System.ServiceModel.Configuration.PeerCredentialElement)
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: Copy(PeerCredentialElement)
  nameWithType: PeerCredentialElement.Copy(PeerCredentialElement)
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Copy(PeerCredentialElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia le impostazioni di configurazione dall&quot;elemento di configurazione credenziale peer fornito."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.PeerCredentialElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.PeerCredentialElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.PeerCredentialElement&quot;></xref>da cui copiare le impostazioni di configurazione."
  overload: System.ServiceModel.Configuration.PeerCredentialElement.Copy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication
  id: MessageSenderAuthentication
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: MessageSenderAuthentication
  nameWithType: PeerCredentialElement.MessageSenderAuthentication
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;elemento che descrive le proprietà di autenticazione mittente di messaggi per la proprietà associata peer X509 certificato dalla configurazione della credenziale peer."
  syntax:
    content: public System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement MessageSenderAuthentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement&quot;></xref>Descrive le proprietà di autenticazione mittente di messaggi per la proprietà associata certificato peer X509."
  overload: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication
  id: PeerAuthentication
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: PeerAuthentication
  nameWithType: PeerCredentialElement.PeerAuthentication
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;elemento che descrive le proprietà di autenticazione per la proprietà associata peer X509 certificato dalla configurazione della credenziale peer."
  syntax:
    content: public System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement PeerAuthentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement&quot;></xref>Descrive le proprietà di autenticazione per la proprietà associata certificato peer X509."
  overload: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerCredentialElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.PeerCredentialElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.PeerCredentialElement.#ctor
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: PeerCredentialElement()
  nameWithType: PeerCredentialElement.PeerCredentialElement()
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.PeerCredentialElement()
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Certificate
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Certificate
  nameWithType: PeerCredentialElement.Certificate
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Certificate
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509PeerCertificateElement
  nameWithType: X509PeerCertificateElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Copy(System.ServiceModel.Configuration.PeerCredentialElement)
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Copy(PeerCredentialElement)
  nameWithType: PeerCredentialElement.Copy(PeerCredentialElement)
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Copy(PeerCredentialElement)
- uid: System.ServiceModel.Configuration.PeerCredentialElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: PeerCredentialElement
  nameWithType: PeerCredentialElement
  fullName: System.ServiceModel.Configuration.PeerCredentialElement
- uid: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: MessageSenderAuthentication
  nameWithType: PeerCredentialElement.MessageSenderAuthentication
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509PeerCertificateAuthenticationElement
  nameWithType: X509PeerCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: PeerAuthentication
  nameWithType: PeerCredentialElement.PeerAuthentication
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Properties
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Properties
  nameWithType: PeerCredentialElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCredentialElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerCredentialElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: PeerCredentialElement
  nameWithType: PeerCredentialElement.PeerCredentialElement
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Certificate*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Certificate
  nameWithType: PeerCredentialElement.Certificate
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Copy*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Copy
  nameWithType: PeerCredentialElement.Copy
- uid: System.ServiceModel.Configuration.PeerCredentialElement.MessageSenderAuthentication*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: MessageSenderAuthentication
  nameWithType: PeerCredentialElement.MessageSenderAuthentication
- uid: System.ServiceModel.Configuration.PeerCredentialElement.PeerAuthentication*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: PeerAuthentication
  nameWithType: PeerCredentialElement.PeerAuthentication
- uid: System.ServiceModel.Configuration.PeerCredentialElement.Properties*
  parent: System.ServiceModel.Configuration.PeerCredentialElement
  isExternal: false
  name: Properties
  nameWithType: PeerCredentialElement.Properties
