### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidatorAttribute
  id: CallbackValidatorAttribute
  children:
  - System.Configuration.CallbackValidatorAttribute.#ctor
  - System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  - System.Configuration.CallbackValidatorAttribute.Type
  - System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute
  fullName: System.Configuration.CallbackValidatorAttribute
  type: Class
  summary: "Specifica un <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref> oggetto da utilizzare per la convalida del codice. Questa classe non può essere ereditata."
  remarks: "La classe di attributo CallbackValidatorAttribute fornisce un&quot;associazione tra un <xref:System.Configuration.CallbackValidator>oggetto e il codice da convalidare.</xref:System.Configuration.CallbackValidator> La classe CallbackValidatorAttribute è derivata dalla <xref:System.Configuration.ConfigurationValidatorAttribute>classe.</xref:System.Configuration.ConfigurationValidatorAttribute>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class CallbackValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.CallbackValidatorAttribute&quot;> </xref> classe."
  syntax:
    content: public CallbackValidatorAttribute ();
    parameters: []
  overload: System.Configuration.CallbackValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  id: CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il nome del metodo di callback."
  syntax:
    content: public string CallbackMethodName { get; set; }
    return:
      type: System.String
      description: "Il nome del metodo da chiamare."
  overload: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.Type
  id: Type
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene o imposta il tipo del validator."
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "Il <xref:System.Type>dell&quot;istanza di attributo di convalida corrente.</xref:System.Type>"
  overload: System.Configuration.CallbackValidatorAttribute.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ottiene l&quot;istanza del validator."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Corrente <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> istanza."
  overload: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Il valore di <xref:System.Configuration.CallbackValidatorAttribute.Type*>proprietà <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>.</xref:System.Configuration.CallbackValidatorAttribute.Type*>"
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Il <xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>proprietà non è impostata su un metodo void statico pubblico con un parametro dell&quot;oggetto.</xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CallbackValidatorAttribute.Type
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidatorAttribute.#ctor*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
- uid: System.Configuration.CallbackValidatorAttribute.Type*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
