### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueFileSectionHandler
  id: NameValueFileSectionHandler
  children:
  - System.Configuration.NameValueFileSectionHandler.#ctor
  - System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler
  fullName: System.Configuration.NameValueFileSectionHandler
  type: Class
  summary: "Fornisce l&quot;accesso a un file di configurazione. Questo tipo supporta l&quot;infrastruttura di configurazione di .NET Framework e non deve essere utilizzato direttamente dal codice."
  remarks: "Il `file` attributo del `<appSettings>` sezione specifica un percorso relativo a un file esterno che contiene le impostazioni di configurazione dell&quot;applicazione personalizzate. I dettagli forniti nel file di agiscono come un `<appSettings>` sezione nel file di configurazione. Il file è accessibile tramite la classe NameValueFileSectionHandler. Elemento radice del file deve corrispondere alla sezione che fa riferimento a esso."
  syntax:
    content: 'public class NameValueFileSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.NameValueFileSectionHandler&quot;> </xref> classe."
  syntax:
    content: public NameValueFileSectionHandler ();
    parameters: []
  overload: System.Configuration.NameValueFileSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Crea un nuovo gestore di configurazione e lo aggiunge alla raccolta del gestore di sezione in base ai parametri specificati."
  remarks: "Il `parent` oggetto parametro funziona come le impostazioni di configurazione nella sezione di configurazione padre corrispondente. Il `configContext` parametro dell&quot;oggetto corrisponde al percorso virtuale per cui il gestore della sezione di configurazione calcola i valori di configurazione. In genere questo parametro è riservato e `null`. Il `section` parametro è il <xref:System.Xml.XmlNode>che contiene le informazioni di configurazione da gestire.</xref:System.Xml.XmlNode> Il `section` parametro fornisce accesso diretto al contenuto XML della sezione di configurazione."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "L&quot;oggetto padre."
    - id: configContext
      type: System.Object
      description: "L&quot;oggetto di contesto di configurazione."
    - id: section
      type: System.Xml.XmlNode
      description: "Nodo XML della sezione."
    return:
      type: System.Object
      description: "Oggetto di configurazione."
  overload: System.Configuration.NameValueFileSectionHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute of <code>section</code> exists but cannot be loaded.  \n  \n \\- or -  \n  \n The <xref uid=\"langword_csharp_name\" name=\"name\" href=\"\"></xref> attribute of <code>section</code> does not match the root element of the file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.NameValueFileSectionHandler.#ctor*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler
- uid: System.Configuration.NameValueFileSectionHandler.Create*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create
  nameWithType: NameValueFileSectionHandler.Create
