### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceActivationElement
  id: ServiceActivationElement
  children:
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.Factory
  - System.ServiceModel.Configuration.ServiceActivationElement.Properties
  - System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  - System.ServiceModel.Configuration.ServiceActivationElement.Service
  langs:
  - csharp
  name: ServiceActivationElement
  nameWithType: ServiceActivationElement
  fullName: System.ServiceModel.Configuration.ServiceActivationElement
  type: Class
  summary: "Gestisce il contenuto dell&quot;elemento di configurazione in relazione all&quot;attivazione di un&quot;applicazione di servizio."
  syntax:
    content: 'public sealed class ServiceActivationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement()
  nameWithType: ServiceActivationElement.ServiceActivationElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Crea una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> classe."
  syntax:
    content: public ServiceActivationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Configura una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> classe che include un percorso di directory file di attivazione del servizio che è relativo a un URL di base."
  syntax:
    content: public ServiceActivationElement (string relativeAddress);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "Un percorso di directory di file che è necessario fare riferimento da un URL di base."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Configura una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> classe che include l&quot;attivazione del servizio specificato e l&quot;indirizzo relativo corrispondente."
  syntax:
    content: public ServiceActivationElement (string relativeAddress, string service);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "Percorso URL a cui è necessario fare riferimento da un indirizzo di base."
    - id: service
      type: System.String
      description: "L&quot;applicazione di servizio che viene attivata."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String,String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Configura una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> classe con il servizio specifico da attivare, l&quot;indirizzo relativo e il nome del percorso di sistema di una factory che genera un elemento di attivazione del servizio."
  syntax:
    content: public ServiceActivationElement (string relativeAddress, string service, string factory);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "Percorso URL a cui è necessario fare riferimento da un indirizzo di base."
    - id: service
      type: System.String
      description: "L&quot;applicazione di servizio in corso l&quot;attivazione."
    - id: factory
      type: System.String
      description: "Il nome del tipo CLR della factory che genera un elemento di attivazione del servizio."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  id: Factory
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Factory
  nameWithType: ServiceActivationElement.Factory
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta una stringa di configurazione che contiene il nome del tipo CLR della factory che genera un elemento di attivazione del servizio."
  syntax:
    content: public string Factory { get; set; }
    return:
      type: System.String
      description: "Stringa di configurazione che contiene il nome del tipo CLR della factory."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Factory*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceActivationElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  id: RelativeAddress
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta l&quot;indirizzo relativo di un file di attivazione del servizio."
  syntax:
    content: public string RelativeAddress { get; set; }
    return:
      type: System.String
      description: "L&quot;indirizzo relativo di un file di attivazione del servizio."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service
  id: Service
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Service
  nameWithType: ServiceActivationElement.Service
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Service
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il nome dell&quot;applicazione di servizio."
  syntax:
    content: public string Service { get; set; }
    return:
      type: System.String
      description: "Il nome di un&quot;applicazione di servizio."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Service*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement()
  nameWithType: ServiceActivationElement.ServiceActivationElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement()
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String)
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String,String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String,String)
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Factory
  nameWithType: ServiceActivationElement.Factory
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Factory
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Properties
  nameWithType: ServiceActivationElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Service
  nameWithType: ServiceActivationElement.Service
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Service
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement
  nameWithType: ServiceActivationElement.ServiceActivationElement
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Factory
  nameWithType: ServiceActivationElement.Factory
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Properties
  nameWithType: ServiceActivationElement.Properties
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Service
  nameWithType: ServiceActivationElement.Service
