### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsClientElement
  id: WindowsClientElement
  children:
  - System.ServiceModel.Configuration.WindowsClientElement.#ctor
  - System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  - System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  - System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  - System.ServiceModel.Configuration.WindowsClientElement.Properties
  langs:
  - csharp
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica le impostazioni per una credenziale Windows da utilizzare per rappresentare il client. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class WindowsClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: System.ServiceModel.Configuration.WindowsClientElement.WindowsClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WindowsClientElement&quot;> </xref> classe."
  syntax:
    content: public WindowsClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  id: AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il livello di rappresentazione consentito."
  remarks: "Vedere <xref:System.Security.Principal.TokenImpersonationLevel>per una descrizione dell&quot;enumerazione.</xref:System.Security.Principal.TokenImpersonationLevel>"
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel AllowedImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: "Un valido <xref:System.Security.Principal.TokenImpersonationLevel>valore che specifica il livello di rappresentazione consentito.</xref:System.Security.Principal.TokenImpersonationLevel> Il valore predefinito è <xref:System.Security.Principal.TokenImpersonationLevel>.</xref:System.Security.Principal.TokenImpersonationLevel>"
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  id: AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta un valore booleano che specifica se l&quot;autenticazione NTLM è consentita."
  remarks: "Quando questa proprietà è impostata su `true`, la sicurezza di Windows è abilitata a livello di gruppo di lavoro. In caso contrario, la sicurezza di Windows è supportata solo a livello di dominio."
  syntax:
    content: public bool AllowNtlm { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se è abilitata la sicurezza di Windows in un gruppo di lavoro; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  id: Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Copy(WindowsClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia il contenuto dell&quot;elemento di configurazione specificato in questo elemento di configurazione."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsClientElement
      description: "L&quot;elemento di configurazione da copiare."
  overload: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Il file di configurazione è di sola lettura."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: System.ServiceModel.Configuration.WindowsClientElement.WindowsClientElement()
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: true
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Copy(WindowsClientElement)
- uid: System.ServiceModel.Configuration.WindowsClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement.WindowsClientElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy
  nameWithType: WindowsClientElement.Copy
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
