### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowDefinition
  id: ConfigurationAllowDefinition
  children:
  - System.Configuration.ConfigurationAllowDefinition.Everywhere
  - System.Configuration.ConfigurationAllowDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  langs:
  - csharp
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
  type: Enum
  summary: "Specifica le posizioni all&quot;interno della gerarchia di file di configurazione che è possibile impostare o eseguire l&quot;override delle proprietà contenute in un <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> oggetto."
  remarks: "I valori di questa enumerazione possono essere utilizzati quando si crea una nuova istanza della <xref:System.Configuration.ConfigurationSection>classe.</xref:System.Configuration.ConfigurationSection>"
  syntax:
    content: public enum ConfigurationAllowDefinition
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  id: Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> possono essere definite in qualsiasi punto."
  syntax:
    content: Everywhere
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> possono essere definite solo nel file Machine. config."
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> può essere definita nel file Machine config, il file Web. config a livello di computer nella stessa directory del file Machine. config, o il file Web. config di primo livello dell&quot;applicazione è stata trovata nella directory virtuale radice, ma non nelle sottodirectory di una radice virtuale."
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  id: MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> può essere definita in Machine config o il file Web. config a livello di computer nella stessa directory del file Machine. config, ma non nel file Web. config dell&quot;applicazione."
  syntax:
    content: MachineToWebRoot
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
