### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  id: CustomErrorsRedirectMode
  children:
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  langs:
  - csharp
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
  type: Enum
  summary: "Specifica i valori per la modalità di gestione l&quot;URL della richiesta originale quando viene visualizzata una pagina di errore personalizzato."
  remarks: "Utilizzare i valori CustomErrorsRedirectMode quando si imposta la <xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>proprietà.</xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>"
  syntax:
    content: public enum CustomErrorsRedirectMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  id: ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Visualizzare la pagina di errore e modificare l&quot;URL della richiesta originale."
  syntax:
    content: ResponseRedirect
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  id: ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Visualizzare la pagina di errore senza modificare l&quot;URL originale."
  syntax:
    content: ResponseRewrite
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
