### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  id: FindCriteriaElement
  children:
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  langs:
  - csharp
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  type: Class
  summary: "Gestisce un elemento di configurazione che contiene un set di criteri utilizzato da un&quot;applicazione client per la ricerca per i servizi del flusso di lavoro tramite una rete o Internet."
  syntax:
    content: 'public sealed class FindCriteriaElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Crea una nuova istanza di <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref> classe."
  syntax:
    content: public FindCriteriaElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  id: ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene una raccolta di elementi di configurazione che contengono i nomi dei tipi di contratto di servizio del flusso di lavoro."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection ContractTypeNames { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
      description: "Una raccolta di elementi."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  id: Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene o imposta il tempo massimo di attesa per le risposte dai servizi in una rete o Internet."
  syntax:
    content: public TimeSpan Duration { get; set; }
    return:
      type: System.TimeSpan
      description: "Un oggetto timespan di definisce il periodo di attesa."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  id: Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene il <xref href=&quot;System.ServiceModel.Configuration.XmlElementElementCollection&quot;> </xref> oggetto che fornisce le estensioni per un <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref>."
  syntax:
    content: public System.ServiceModel.Configuration.XmlElementElementCollection Extensions { get; }
    return:
      type: System.ServiceModel.Configuration.XmlElementElementCollection
      description: "Una raccolta di elementi."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  id: MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene o imposta il numero massimo di risposte da attendere dai servizi in una rete o Internet."
  remarks: "Se vengono ricevute le risposte MaxResults prima <xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration%2A>trascorso, l&quot;operazione di ricerca termina.</xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration%2A>"
  syntax:
    content: public int MaxResults { get; set; }
    return:
      type: System.Int32
      description: "Un numero massimo."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  id: ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene o imposta un URI che definisce il nome e percorso di un servizio che si sta cercando e con i membri del <xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*>raccolta corrispondenti.</xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*>"
  syntax:
    content: public Uri ScopeMatchBy { get; set; }
    return:
      type: System.Uri
      description: "L&quot;URI di un&quot;applicazione di servizio."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  id: Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Ottiene una raccolta di <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref> oggetti contenenti URI assoluti utilizzati durante un&quot;operazione di ricerca per individuare uno o più servizi specifici."
  remarks: "Se il servizio specifico viene trovato, è stata individuata una corrispondenza corretta tra l&quot;URI del servizio e l&quot;URI dell&quot;ambito, talvolta con il supporto delle regole di ambito che gestiscono i problemi di corrispondenza."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ScopeElementCollection Scopes { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
      description: "Una raccolta di elementi che contengono URI."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ContractTypeNameElementCollection
  nameWithType: ContractTypeNameElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
- uid: System.ServiceModel.Configuration.XmlElementElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: XmlElementElementCollection
  nameWithType: XmlElementElementCollection
  fullName: System.ServiceModel.Configuration.XmlElementElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ScopeElementCollection
  nameWithType: ScopeElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement.FindCriteriaElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
