### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement
  id: IBindingConfigurationElement
  children:
  - System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  - System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  langs:
  - csharp
  name: IBindingConfigurationElement
  nameWithType: IBindingConfigurationElement
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement
  type: Interface
  summary: "Fornisce le impostazioni di configurazione di base per un elemento di associazione."
  syntax:
    content: public interface IBindingConfigurationElement
  implements: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: ApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: ApplyConfiguration(Binding)
  nameWithType: IBindingConfigurationElement.ApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Applica il contenuto dell&quot;associazione specificata in questa sezione di configurazione di associazione."
  syntax:
    content: public void ApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "Un&quot;associazione."
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  id: CloseTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;intervallo di tempo fornito per completare un&quot;operazione di chiusura."
  syntax:
    content: public TimeSpan CloseTimeout { get; }
    return:
      type: System.TimeSpan
      description: "Il <xref:System.TimeSpan>che specifica quanto tempo l&quot;operazione di chiusura deve essere completata prima del timeout.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: Name
  nameWithType: IBindingConfigurationElement.Name
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene il nome dell&quot;associazione."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "Il nome dell&quot;associazione."
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  id: OpenTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;intervallo di tempo fornito per completare un&quot;operazione di apertura."
  syntax:
    content: public TimeSpan OpenTimeout { get; }
    return:
      type: System.TimeSpan
      description: "Il <xref:System.TimeSpan>che specifica quanto tempo l&quot;operazione di apertura deve essere completata prima del timeout.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  id: ReceiveTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;intervallo di tempo fornito completare un&quot;operazione di ricezione."
  syntax:
    content: public TimeSpan ReceiveTimeout { get; }
    return:
      type: System.TimeSpan
      description: "Il <xref:System.TimeSpan>che specifica quanto tempo l&quot;operazione di ricezione deve essere completata prima del timeout.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  id: SendTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene l&quot;intervallo di tempo fornito per il completamento di un&quot;operazione di invio."
  syntax:
    content: public TimeSpan SendTimeout { get; }
    return:
      type: System.TimeSpan
      description: "Il <xref:System.TimeSpan>che specifica la durata dell&quot;operazione di invio deve essere completata prima del timeout.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ApplyConfiguration(Binding)
  nameWithType: IBindingConfigurationElement.ApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: Name
  nameWithType: IBindingConfigurationElement.Name
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: IBindingConfigurationElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: Name
  nameWithType: IBindingConfigurationElement.Name
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
