### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyOptions
  id: ConfigurationPropertyOptions
  children:
  - System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  - System.Configuration.ConfigurationPropertyOptions.IsKey
  - System.Configuration.ConfigurationPropertyOptions.IsRequired
  - System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  - System.Configuration.ConfigurationPropertyOptions.None
  langs:
  - csharp
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
  type: Enum
  summary: "Specifica le opzioni da applicare a una proprietà."
  remarks: "Durante la creazione di un elemento di configurazione, utilizzare l&quot;enumeratore ConfigurationPropertyOptions per specificare a livello di codice le opzioni da applicare. Queste opzioni indicano se una proprietà è obbligatoria, è una proprietà chiave della raccolta e così via. Se non è stato specificato un valore, il valore viene considerato nessuno."
  syntax:
    content: >-
      [System.Flags]

      public enum ConfigurationPropertyOptions
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  id: IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica se il nome dell&quot;assembly per la proprietà di configurazione richiede la trasformazione quando viene serializzato per una versione precedente di .NET Framework."
  syntax:
    content: IsAssemblyStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  id: IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica che la proprietà è una raccolta predefinita."
  syntax:
    content: IsDefaultCollection
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  id: IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica che la proprietà è una chiave dell&quot;insieme."
  syntax:
    content: IsKey
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  id: IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica che la proprietà è obbligatoria."
  syntax:
    content: IsRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  id: IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica se il nome del tipo per la proprietà di configurazione richiede la trasformazione quando viene serializzato per una versione precedente di .NET Framework."
  syntax:
    content: IsTypeStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  id: IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica se è necessario eseguire una query di sezione di configurazione padre della proprietà di configurazione in fase di serializzazione per determinare se la proprietà di configurazione deve essere serializzata in XML."
  syntax:
    content: IsVersionCheckRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyOptions.None
  id: None
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Indica che nessuna opzione si applica alla proprietà."
  syntax:
    content: None
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
- uid: System.Configuration.ConfigurationPropertyOptions.None
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
