### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthenticationUser
  id: FormsAuthenticationUser
  children:
  - System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  - System.Web.Configuration.FormsAuthenticationUser.Name
  - System.Web.Configuration.FormsAuthenticationUser.Password
  - System.Web.Configuration.FormsAuthenticationUser.Properties
  langs:
  - csharp
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser
  fullName: System.Web.Configuration.FormsAuthenticationUser
  type: Class
  summary: "Consente di configurare le credenziali dell&quot;utente per applicazioni Web che utilizzano l&quot;autenticazione basata su form."
  remarks: "La classe FormsAuthenticationUser fornisce un modo per accedere a livello di codice e di modificare la sezione di un file di configurazione.       Questo tipo è parte di un gruppo che include il <xref:System.Web.Configuration.FormsAuthenticationCredentials>, <xref:System.Web.Configuration.FormsAuthenticationUserCollection>e <xref:System.Web.Configuration.FormsAuthenticationConfiguration>tipi.</xref:System.Web.Configuration.FormsAuthenticationConfiguration> </xref:System.Web.Configuration.FormsAuthenticationUserCollection> </xref:System.Web.Configuration.FormsAuthenticationCredentials> I tipi di tipo diverso da quello raccolta influisce direttamente sui tag di configurazione sottostanti.      > [!NOTE] > FormsAuthenticationUser il possibile scrivere informazioni nella relativa sezione del file di configurazione al computer, sito o solo a livello di applicazione. Qualsiasi tentativo di scrivere in un file di configurazione a un diverso livello nella gerarchia comporterà un messaggio di errore generato dal parser. Tuttavia, è possibile utilizzare questa classe per leggere le informazioni di configurazione a qualsiasi livello della gerarchia. Per la sicurezza e la scalabilità, è consigliabile utilizzare un repository esterno, ad esempio un database, per mantenere le credenziali degli utenti."
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.FormsAuthenticationUserCollection> to access the FormsAuthenticationUser objects of an existing Web application. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the [credentials Element for forms for authentication (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/e5a001f8-fdbe-4c88-80ca-bfe36df23479) section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security, it is recommended you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authentication mode=\"Forms\">  \n  <forms name=\"MyAppCookieName\" loginUrl=\"/login.aspx\">  \n    defaultUrl=\"formsdefault.aspx\"  \n    protection=\"Encryption\" timeout=\"5\" path=\"aspnet\"  \n    slidingExpiration=\"false\"  \n    cookieless=\"UseCookies\" domain=\"domainName\">  \n    <credentials passwordFormat=\"SHA1\">  \n      <user name=\"aspnetuser1\"  \n        password=\"5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\"/>  \n       <user name=\"aspnetuser2\"  \n         password=\"E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D\"/>  \n    </credentials>            \n  </forms>  \n</authentication>  \n```  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#1](~/add/codesnippet/csharp/t-system.web.configurati_51_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#1](~/add/codesnippet/visualbasic/t-system.web.configurati_51_1.vb)]"
  syntax:
    content: 'public sealed class FormsAuthenticationUser : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: FormsAuthenticationUser(String,String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.FormsAuthenticationUser&quot;> </xref> classe utilizzando i parametri passati."
  remarks: "Questo costruttore crea un <xref:System.Web.Configuration.FormsAuthenticationUser>utilizzando i parametri passati.</xref:System.Web.Configuration.FormsAuthenticationUser>"
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.FormsAuthenticationUser> object.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#3](~/add/codesnippet/csharp/ba248448-bbbd-40de-aba6-_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#3](~/add/codesnippet/visualbasic/ba248448-bbbd-40de-aba6-_1.vb)]"
  syntax:
    content: public FormsAuthenticationUser (string name, string password);
    parameters:
    - id: name
      type: System.String
      description: "Nome dell&quot;utente."
    - id: password
      type: System.String
      description: "Password dell&quot;utente."
  overload: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  id: Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il nome utente di accesso."
  remarks: ''
  example:
  - "The following code example shows how to use the Name property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#5](~/add/codesnippet/csharp/p-system.web.configurati_336_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#5](~/add/codesnippet/visualbasic/p-system.web.configurati_336_1.vb)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Il nome utente di accesso richiesto dall&quot;applicazione."
  overload: System.Web.Configuration.FormsAuthenticationUser.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  id: Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta la password dell&quot;utente."
  remarks: ''
  example:
  - "The following code example shows how to use the Password property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#4](~/add/codesnippet/csharp/p-system.web.configurati_127_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#4](~/add/codesnippet/visualbasic/p-system.web.configurati_127_1.vb)]"
  syntax:
    content: public string Password { get; set; }
    return:
      type: System.String
      description: "La password dell&quot;utente richiesta dall&quot;applicazione."
  overload: System.Web.Configuration.FormsAuthenticationUser.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  id: Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.FormsAuthenticationUser.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser(String,String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser
- uid: System.Web.Configuration.FormsAuthenticationUser.Name*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
- uid: System.Web.Configuration.FormsAuthenticationUser.Password*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
