### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebConfigurationFileMap
  id: WebConfigurationFileMap
  children:
  - System.Web.Configuration.WebConfigurationFileMap.#ctor
  - System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  - System.Web.Configuration.WebConfigurationFileMap.Clone
  - System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  langs:
  - csharp
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap
  fullName: System.Web.Configuration.WebConfigurationFileMap
  type: Class
  summary: "Definisce i mapping dei file di configurazione per un&quot;applicazione Web. Questa classe non può essere ereditata."
  remarks: "La classe WebConfigurationFileMap viene utilizzata per specificare la gerarchia di file di configurazione Web. Per impostazione predefinita, il sistema di configurazione viene utilizzata la metabase IIS per determinare la gerarchia del file Web. Se IIS non è installato o se un&quot;applicazione destinata a una versione di .NET Framework che non è la versione più recente è installata nel server, la classe WebConfigurationFileMap fornisce un mezzo per definire una gerarchia personalizzata.       La classe WebConfigurationFileMap è possibile specificare più percorsi correlati ai file di configurazione o un singolo percorso."
  syntax:
    content: 'public sealed class WebConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Crea una nuova istanza di <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> classe."
  syntax:
    content: public WebConfigurationFileMap ();
    parameters: []
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> classe utilizzando il nome di file di configurazione di computer specificato."
  remarks: "Utilizzare questo costruttore quando si dispone di una versione di [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] precedente a quello più recente installata nel computer. Il metodo consente di specificare il file di configurazione appropriata per la versione di [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] di destinazione.      > [!NOTE] > Anche se il costruttore accetta solo il percorso del file Machine. config, il sistema di configurazione verrà anche leggere il file Web. config radice nella stessa directory in cui è presente il file Machine. config."
  syntax:
    content: public WebConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "Il nome del file di configurazione di computer con il percorso fisico completo (ad esempio, `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  id: Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Crea una nuova istanza di un <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> classe con lo stesso valore dell&quot;istanza esistente."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "Una nuova istanza di un <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> classe."
  overload: System.Web.Configuration.WebConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  id: VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene la raccolta di elencata delle directory virtuali per un&quot;applicazione Web."
  remarks: "Le directory virtuali di un&quot;applicazione Web potrebbero non essere necessariamente mappato a directory fisiche sul server. La <xref:System.Web.Configuration.VirtualDirectoryMapping>classe è indipendente da IIS.</xref:System.Web.Configuration.VirtualDirectoryMapping>"
  syntax:
    content: public System.Web.Configuration.VirtualDirectoryMappingCollection VirtualDirectories { get; }
    return:
      type: System.Web.Configuration.VirtualDirectoryMappingCollection
      description: "Una raccolta di <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> oggetti."
  overload: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
- uid: System.Web.Configuration.VirtualDirectoryMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: VirtualDirectoryMappingCollection
  nameWithType: VirtualDirectoryMappingCollection
  fullName: System.Web.Configuration.VirtualDirectoryMappingCollection
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: WebConfigurationFileMap.Clone
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
