### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Specifica che un provider di impostazioni deve disabilitare qualsiasi logica che viene richiamato quando viene rilevato un aggiornamento dell&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "Per creare un provider di impostazioni dell&quot;applicazione completo che supporta il controllo delle versioni dell&quot;applicazione, il provider deve implementare il <xref:System.Configuration.IApplicationSettingsProvider>interfaccia.</xref:System.Configuration.IApplicationSettingsProvider> Uno dei membri di questa interfaccia, il <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>, viene chiamato per notificare al provider che è stata installata una nuova versione dell&quot;applicazione.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> In risposta, il provider deve eseguire un&quot;azione appropriata, in genere la migrazione delle precedenti impostazioni dell&quot;applicazione.       Il NoSettingsVersionUpgradeAttribute notifica al provider per la logica di aggiornamento associata alla classe corrente delle impostazioni di esclusione. Pertanto, il valore della versione precedente di questo gruppo di proprietà non deve essere migrato nella nuova installazione.      > [!NOTE] > Questo attributo può essere applicato solo alle proprietà delle impostazioni di singole applicazioni."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;> </xref> classe."
  remarks: "Questo è il costruttore predefinito fornito dal compilatore per la <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>classe.</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
