### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WsdlImporterElement
  id: WsdlImporterElement
  children:
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.WsdlImporterElement.Properties
  - System.ServiceModel.Configuration.WsdlImporterElement.Type
  langs:
  - csharp
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement
  fullName: System.ServiceModel.Configuration.WsdlImporterElement
  type: Class
  summary: "Rappresenta l&quot;elemento di configurazione che specifica l&quot;importazione di metadati Web Services Description Language (WSDL) 1.1 con allegati WS-Policy."
  remarks: "Oggetto <xref:System.ServiceModel.Description.WsdlImporter>viene utilizzato per importare i metadati, nonché di convertire tali informazioni in diverse classi che rappresentano informazioni di contratto e l&quot;endpoint.</xref:System.ServiceModel.Description.WsdlImporter>       Può importare selettivamente informazioni di contratto e di endpoint e proprietà che espongono qualsiasi errore di importazione e accettano informazioni sul tipo relative al processo di importazione e di conversione. Supporta inoltre l&quot;importazione di informazioni di associazione e proprietà che forniscono accesso a qualsiasi documento di criteri, documenti WSDL, estensione WSDL e documenti di XML schema."
  syntax:
    content: 'public sealed class WsdlImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> classe."
  syntax:
    content: public WsdlImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> classe con il tipo specificato."
  syntax:
    content: public WsdlImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: "Il tipo specificato."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> classe con il tipo specificato."
  syntax:
    content: public WsdlImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Il tipo specificato."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il tipo di questo elemento di configurazione."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Il tipo di questo elemento di configurazione."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement.WsdlImporterElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
