### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Definisce un valore statico <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>metodo che crea un file di configurazione remota per una libreria dei tipi di client.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "Il <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>metodo viene utilizzato il <xref:System.EnterpriseServices.Internal.Publish>classe durante la generazione di un&quot;interfaccia COM da una libreria dei tipi di client (con estensione tlb).</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> La <xref:System.EnterpriseServices.Internal.Publish>classe pubblica COM (interfacce) in un&quot;applicazione COM+ abilitato per SOAP.</xref:System.EnterpriseServices.Internal.Publish> Uno dei parametri del metodo è il nome di un assembly che contiene i metadati di common language runtime (CLR) che <xref:System.EnterpriseServices.Internal.Publish>è già stato generato per la libreria client.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>non è necessario essere chiamati direttamente.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> In alternativa, chiamare il <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metodo della <xref:System.EnterpriseServices.Internal.Publish>classe.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig viene utilizzata internamente da .NET Framework. Non è necessario utilizzare la classe direttamente nel codice."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> classe."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Crea un file di configurazione remota per una libreria dei tipi di client in un&quot;applicazione COM+ abilitato per SOAP."
  remarks: "Viene chiamato il metodo statico di scrittura la <xref:System.EnterpriseServices.Internal.Publish>classe durante la generazione di un&quot;interfaccia COM da una libreria dei tipi di client (con estensione tlb).</xref:System.EnterpriseServices.Internal.Publish> La <xref:System.EnterpriseServices.Internal.Publish>classe pubblica COM (interfacce) in un&quot;applicazione COM+ abilitato per SOAP.</xref:System.EnterpriseServices.Internal.Publish>       Scrittura non è necessario essere chiamati direttamente. In alternativa, chiamare il <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metodo della <xref:System.EnterpriseServices.Internal.Publish>classe.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       Il `BaseUrl` e `VRoot` vengono concatenati i valori dei parametri (con un separatore di percorso, se necessario) per l&quot;elemento del client del form `URL` valore dell&quot;attributo.       Il `AssemblyName` parametro identifica un assembly contenente metadati CLR che <xref:System.EnterpriseServices.Internal.Publish>, usando la <xref:System.EnterpriseServices.Internal.GenerateMetadata>classe, è già stato generato per la libreria client.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "La cartella in cui creare il file di configurazione."
    - id: VRoot
      type: System.String
      description: "Il nome della radice virtuale."
    - id: BaseUrl
      type: System.String
      description: "URL di base che contiene la radice virtuale."
    - id: AssemblyName
      type: System.String
      description: "Il nome visualizzato dell&quot;assembly che contiene i metadati di common language runtime (CLR) corrispondente alla libreria dei tipi."
    - id: TypeName
      type: System.String
      description: "Il nome completo dell&quot;assembly contenente metadati CLR corrispondente alla libreria dei tipi."
    - id: ProgId
      type: System.String
      description: "L&quot;identificatore a livello di codice della classe."
    - id: Mode
      type: System.String
      description: "La modalità di attivazione."
    - id: Transport
      type: System.String
      description: "Non utilizzato. Specificare <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> per questo parametro."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il file di configurazione remota è stato creato correttamente; in caso contrario <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
