### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "Fornisce una stringa che descrive un gruppo di proprietà di impostazioni dell&quot;applicazione. Questa classe non può essere ereditata."
  remarks: "Una classe di impostazioni dell&quot;applicazione, derivata da <xref:System.Configuration.ApplicationSettingsBase>, definisce uno o più proprietà appartenenti allo stesso gruppo di proprietà dell&quot;applicazione.</xref:System.Configuration.ApplicationSettingsBase> SettingsGroupDescriptionAttribute è un attributo facoltativo che è possibile utilizzare per fornire il testo descrittivo per un gruppo di proprietà delle impostazioni. Questo testo è progettato per gli strumenti design-time sia strumenti di amministrazione in fase di esecuzione nell&quot;identificazione e la descrizione del gruppo di proprietà associato.      > [!NOTE] > Questo attributo può essere applicato solo a livello di classe wrapper."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsGroupDescriptionAttribute&quot;> </xref> classe."
  remarks: "Anche se la lunghezza massima teorica del `description` parametro è vincolato dal limite superiore di un <xref:System.Int32>, limiti pratici, determinati dal livello di usabilità e limiti di quota imposti dal provider di impostazioni, sarà più piccoli.</xref:System.Int32>"
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "Oggetto <xref:System.String>contenente il testo descrittivo per il gruppo di impostazioni dell&quot;applicazione.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Il testo descrittivo per il gruppo di proprietà di impostazioni dell&quot;applicazione."
  remarks: "Il valore della proprietà descrizione è impostato <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>costruttore.</xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "Oggetto <xref:System.String>contenente il testo descrittivo per il gruppo di impostazioni dell&quot;applicazione.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
