### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSFederationHttpSecurity
  id: WSFederationHttpSecurity
  children:
  - System.ServiceModel.WSFederationHttpSecurity.#ctor
  - System.ServiceModel.WSFederationHttpSecurity.Message
  - System.ServiceModel.WSFederationHttpSecurity.Mode
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  langs:
  - csharp
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity
  fullName: System.ServiceModel.WSFederationHttpSecurity
  type: Class
  summary: "Specifica le impostazioni di sicurezza per il <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>. Questa classe non può essere ereditata."
  remarks: "Questa classe specifica il tipo di sicurezza da applicare per il `wsFederationHttpBinding` associazione e le impostazioni di sicurezza specifico."
  syntax:
    content: public sealed class WSFederationHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.WSFederationHttpSecurity&quot;> </xref> classe."
  syntax:
    content: public WSFederationHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Indica le impostazioni di sicurezza del messaggio per il <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>."
  remarks: "L&quot;oggetto restituito specifica le proprietà di sicurezza dettagliate a livello di messaggio per il `wsFederationHttpBinding`."
  example:
  - "The following code shows how to access this property and use it to set properties of the `wsFederationHttpBinding`.  \n  \n [!code-vb[WSFederationHttpSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_6_1.vb)]\n [!code-cs[WSFederationHttpSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ws_6_1.cs)]"
  syntax:
    content: public System.ServiceModel.FederatedMessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.FederatedMessageSecurityOverHttp
      description: "A <xref href=&quot;System.ServiceModel.FederatedMessageSecurityOverHttp&quot;></xref> value."
  overload: System.ServiceModel.WSFederationHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Ottiene o imposta il tipo di sicurezza da applicare."
  remarks: "Il membro di enumerazione restituito specifica il tipo generale di sicurezza da applicare.       I valori consentiti sono <xref:System.ServiceModel.WSFederationHttpSecurityMode>e <xref:System.ServiceModel.WSFederationHttpSecurityMode>.</xref:System.ServiceModel.WSFederationHttpSecurityMode> </xref:System.ServiceModel.WSFederationHttpSecurityMode>       Nel <xref:System.ServiceModel.WSFederationHttpSecurityMode>modalità di sicurezza, il messaggio viene inviato tramite HTTP e sicurezza dei messaggi SOAP viene utilizzata per proteggere il messaggio.</xref:System.ServiceModel.WSFederationHttpSecurityMode> L&quot;autenticazione client viene eseguita in base al token emesso ottenuto dal servizio token di sicurezza. Autenticazione server è basata sul certificato del server.       Nel <xref:System.ServiceModel.WSFederationHttpSecurityMode>modalità di sicurezza, il messaggio viene inviato su HTTPS.</xref:System.ServiceModel.WSFederationHttpSecurityMode> L&quot;autenticazione client viene eseguita includendo il token emesso ottenuto dal servizio token di sicurezza del messaggio SOAP. L&quot;autenticazione server, basata sul certificato del server, viene eseguita come parte dell&quot;installazione connessione HTTPS."
  example:
  - "The following code shows how to set this property.  \n  \n [!code-vb[WSFederationHttpSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_5_1.vb)]\n [!code-cs[WSFederationHttpSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ws_5_1.cs)]"
  syntax:
    content: public System.ServiceModel.WSFederationHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSFederationHttpSecurityMode
      description: "A <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;></xref>. Il valore predefinito è <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.WSFederationHttpSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Restituisce un valore che indica se il <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>proprietà è stato modificato rispetto al valore predefinito e deve essere serializzata.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>valore della proprietà deve essere serializzato; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Restituisce un valore che indica se il <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>proprietà è stato modificato rispetto al valore predefinito e deve essere serializzata.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>valore della proprietà deve essere serializzato; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
- uid: System.ServiceModel.FederatedMessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: FederatedMessageSecurityOverHttp
  nameWithType: FederatedMessageSecurityOverHttp
  fullName: System.ServiceModel.FederatedMessageSecurityOverHttp
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSFederationHttpSecurityMode
  nameWithType: WSFederationHttpSecurityMode
  fullName: System.ServiceModel.WSFederationHttpSecurityMode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity
- uid: System.ServiceModel.WSFederationHttpSecurity.Message*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode
