### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.BasicHttpMessageSecurity
  id: BasicHttpMessageSecurity
  children:
  - System.ServiceModel.BasicHttpMessageSecurity.#ctor
  - System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  - System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  - System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  - System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  langs:
  - csharp
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity
  fullName: System.ServiceModel.BasicHttpMessageSecurity
  type: Class
  summary: "Configura le impostazioni di sicurezza a livello di messaggio per <xref:System.ServiceModel.BasicHttpBinding>.</xref:System.ServiceModel.BasicHttpBinding>"
  remarks: ''
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#5](~/add/codesnippet/csharp/t-system.servicemodel.ba_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#5](~/add/codesnippet/visualbasic/t-system.servicemodel.ba_1.vb)]
  syntax:
    content: public sealed class BasicHttpMessageSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: BasicHttpMessageSecurity()
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.BasicHttpMessageSecurity&quot;> </xref> classe."
  syntax:
    content: public BasicHttpMessageSecurity ();
    parameters: []
  overload: System.ServiceModel.BasicHttpMessageSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Specifica la suite di algoritmi da utilizzare con <xref href=&quot;System.ServiceModel.BasicHttpMessageSecurity&quot;> </xref>."
  remarks: "Il <xref:System.ServiceModel.Security.SecurityAlgorithmSuite>oggetto restituito contiene numerose proprietà che specificano vari algoritmi di sicurezza utilizzabili in condizioni specifiche.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite> Descrive inoltre varie funzionalità di sicurezza del servizio."
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#7](~/add/codesnippet/csharp/p-system.servicemodel.ba_0_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#7](~/add/codesnippet/visualbasic/p-system.servicemodel.ba_0_1.vb)]
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "A <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;></xref>. Il valore predefinito è <xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>"
  overload: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Specifica il tipo di credenziali con cui il client viene autenticato."
  remarks: "Il valore restituito può essere uno dei seguenti membri dell&quot;enumerazione:- <xref:System.ServiceModel.BasicHttpMessageCredentialType>- <xref:System.ServiceModel.BasicHttpMessageCredentialType></xref:System.ServiceModel.BasicHttpMessageCredentialType> </xref:System.ServiceModel.BasicHttpMessageCredentialType>"
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#6](~/add/codesnippet/csharp/p-system.servicemodel.ba_1_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#6](~/add/codesnippet/visualbasic/p-system.servicemodel.ba_1_1.vb)]
  syntax:
    content: public System.ServiceModel.BasicHttpMessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.BasicHttpMessageCredentialType
      description: "Un membro del <xref:System.ServiceModel.BasicHttpMessageCredentialType>enumerazione.</xref:System.ServiceModel.BasicHttpMessageCredentialType> Il valore predefinito è <xref:System.ServiceModel.BasicHttpMessageCredentialType>.</xref:System.ServiceModel.BasicHttpMessageCredentialType>"
  overload: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  id: ShouldSerializeAlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ShouldSerializeAlgorithmSuite()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Indica se la suite di algoritmi da utilizzare per proteggere i messaggi a livello SOAP deve essere serializzata."
  syntax:
    content: public bool ShouldSerializeAlgorithmSuite ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se la suite di algoritmi deve essere serializzata. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  id: ShouldSerializeClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ShouldSerializeClientCredentialType()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Indica se il tipo di credenziale client deve essere serializzato."
  remarks: 'Due esempi di tipi di credenziali client sono: identità e trasporto.'
  syntax:
    content: public bool ShouldSerializeClientCredentialType ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il tipo di credenziale client deve essere serializzato. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: BasicHttpMessageSecurity()
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.BasicHttpMessageSecurity()
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: BasicHttpMessageCredentialType
  nameWithType: BasicHttpMessageCredentialType
  fullName: System.ServiceModel.BasicHttpMessageCredentialType
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeAlgorithmSuite()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeClientCredentialType()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeAlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
