### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: "Specifica il comportamento di override di un elemento di configurazione per gli elementi di configurazione nelle directory figlio."
  remarks: "Utilizzare i valori di enumerazione OverrideMode per impostare la <xref:System.Configuration.SectionInformation.OverrideMode%2A>proprietà di <xref:System.Configuration.SectionInformation>classe.</xref:System.Configuration.SectionInformation> </xref:System.Configuration.SectionInformation.OverrideMode%2A> Impostare questa proprietà per specificare a livello di programmazione il comportamento di override di un elemento di configurazione o un gruppo. Per impostare in modo dichiarativo il comportamento di override per tutti gli elementi di configurazione all&quot;interno di un elemento, utilizzare il `allowOverride` attributo. Il <xref:System.Configuration.SectionInformation.OverrideMode%2A>proprietà fornisce un controllo più granulare elementi all&quot;interno di un `location` elemento.</xref:System.Configuration.SectionInformation.OverrideMode%2A>"
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "L&quot;impostazione di configurazione dell&quot;elemento o del gruppo può essere sottoposto a override dalle impostazioni di configurazione che si trovano in directory figlio."
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "L&quot;impostazione di configurazione dell&quot;elemento o del gruppo non può essere sottoposto a override dalle impostazioni di configurazione che si trovano in directory figlio."
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "L&quot;impostazione di configurazione dell&quot;elemento o del gruppo verrà sovrascritte dalle impostazioni di configurazione che si trovano in directory figlio se esplicitamente consentito da un elemento padre dell&quot;elemento di configurazione corrente o del gruppo. L&quot;autorizzazione per eseguire l&quot;override viene specificata utilizzando il <xref uid=&quot;langword_csharp_OverrideMode&quot; name=&quot;OverrideMode&quot; href=&quot;&quot;> </xref> attributo."
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
