### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingAttribute
  id: SettingAttribute
  children:
  - System.Configuration.SettingAttribute.#ctor
  langs:
  - csharp
  name: SettingAttribute
  nameWithType: SettingAttribute
  fullName: System.Configuration.SettingAttribute
  type: Class
  summary: "Rappresenta un attributo di impostazioni personalizzate consentono di associare le informazioni delle impostazioni a una proprietà."
  remarks: "La classe SettingAttribute associa le informazioni delle impostazioni a una proprietà. La <xref:System.Configuration.ApplicationSettingsBase>classe ignorerà tutte le proprietà non è contrassegnate con questo attributo o un attributo derivato.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class SettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingAttribute
  langs:
  - csharp
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingAttribute&quot;> </xref> classe."
  syntax:
    content: public SettingAttribute ();
    parameters: []
  overload: System.Configuration.SettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingAttribute.#ctor
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
- uid: System.Configuration.SettingAttribute.#ctor*
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute
  nameWithType: SettingAttribute.SettingAttribute
