### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAsAttribute
  id: SettingsSerializeAsAttribute
  children:
  - System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  - System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  langs:
  - csharp
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute
  fullName: System.Configuration.SettingsSerializeAsAttribute
  type: Class
  summary: "Specifica il meccanismo di serializzazione che deve utilizzare il provider di impostazioni. Questa classe non può essere ereditata."
  remarks: "Un provider di impostazioni spesso supporta più di uno degli schemi di serializzazione standard di .NET Framework. Questi schemi vengono definiti per il <xref:System.Configuration.SettingsSerializeAs>, enumerazione e includere testo normale, XML e la serializzazione binaria.</xref:System.Configuration.SettingsSerializeAs> Inoltre, un provider può inoltre supportare uno schema di serializzazione personalizzata.       Con SettingsSerializeAsAttribute, è possibile specificare quale meccanismo di serializzazione da utilizzare per una determinata applicazione impostazioni classe o proprietà. Questo attributo viene considerato una richiesta al provider di impostazioni. Può essere ignorato o causare un errore se il provider o il tipo di proprietà singole non supporta lo schema di serializzazione specificato. Se questo attributo non è presente, il provider in genere fornirà un meccanismo di serializzazione predefinito, in genere testo normale.       Anche se il provider di impostazioni può fornire un modo per modificare dinamicamente il meccanismo di serializzazione in fase di esecuzione, non è una funzionalità tipica."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsSerializeAsAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  id: '#ctor(System.Configuration.SettingsSerializeAs)'
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza un&quot;istanza di <xref href=&quot;System.Configuration.SettingsSerializeAsAttribute&quot;> </xref> classe."
  remarks: "Se il provider di impostazioni o il tipo della proprietà da convertire non supporta lo schema di serializzazione specificato per il `serializeAs` parametro, l&quot;operazione può essere uno dei risultati seguenti:-il provider di impostazioni è possibile ignorare l&quot;attributo e utilizzare il relativo schema di serializzazione predefinito.      -Il processo di serializzazione può non riuscire senza una risposta. La proprietà delle impostazioni dell&quot;applicazione non verrà resi persistenti.      -Un&quot;eccezione può essere generata durante la serializzazione."
  syntax:
    content: public SettingsSerializeAsAttribute (System.Configuration.SettingsSerializeAs serializeAs);
    parameters:
    - id: serializeAs
      type: System.Configuration.SettingsSerializeAs
      description: "Oggetto <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> valore enumerato che specifica lo schema di serializzazione."
  overload: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  id: SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> valore di enumerazione che specifica lo schema di serializzazione."
  remarks: "Questa proprietà è impostata <xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>costruttore.</xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsSerializeAs SerializeAs { get; }
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Oggetto <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> valore enumerato che specifica lo schema di serializzazione."
  overload: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
