### YamlMime:ManagedReference
items:
- uid: System.Configuration.ISettingsProviderService
  id: ISettingsProviderService
  children:
  - System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  langs:
  - csharp
  name: ISettingsProviderService
  nameWithType: ISettingsProviderService
  fullName: System.Configuration.ISettingsProviderService
  type: Interface
  summary: "Fornisce un&quot;interfaccia per la definizione di un provider di impostazioni di applicazioni alternativo."
  remarks: "Il <xref:System.Configuration.IPersistComponentSettings>interfaccia consente ai controlli e componenti ospitati in un&quot;applicazione per rendere persistenti le impostazioni dell&quot;applicazione in modo trasparente all&quot;applicazione.</xref:System.Configuration.IPersistComponentSettings> Tuttavia, in alcuni casi, l&quot;applicazione o un ambiente potrebbe essere necessario eseguire l&quot;override di provider di impostazioni utilizzate in modo nativo da un componente con uno di propria scelta. L&quot;interfaccia ISettingsProviderService consente di creare un semplice servizio che comunica tale provider di impostazioni alternativo, in genere disponibili a cui appartiene <xref:System.ComponentModel.Container>.</xref:System.ComponentModel.Container>       ISettingsProviderService viene comunemente utilizzato dagli strumenti design-time e dai debugger che forniscono un supporto speciale per le impostazioni dell&quot;applicazione. Per creare una funzione di disposizione in modo semplice, la <xref:System.Configuration.ApplicationSettingsBase>classe contiene costruttori che accettano un riferimento al componente proprietario.</xref:System.Configuration.ApplicationSettingsBase> Questi costruttori automaticamente la query per i provider di impostazioni compatibili."
  syntax:
    content: public interface ISettingsProviderService
  implements: []
  platform:
  - net462
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  id: GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  langs:
  - csharp
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Restituisce il provider di impostazioni compatibili con la proprietà delle impostazioni specificate."
  remarks: "Il metodo GetSettingsProvider consente un <xref:System.Configuration.ISettingsProviderService>di offrire i servizi di serializzazione a qualsiasi componente individuato.</xref:System.Configuration.ISettingsProviderService> Questo metodo determina se il provider di impostazioni associato può rendere persistente il tipo di proprietà delle impostazioni dell&quot;applicazione specificato. In caso contrario, questo metodo restituisce un riferimento a tale provider di impostazioni. in caso contrario restituisce `null`."
  syntax:
    content: public System.Configuration.SettingsProvider GetSettingsProvider (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "Il <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> che richiede la serializzazione."
    return:
      type: System.Configuration.SettingsProvider
      description: "Se viene trovato, il <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> che può rendere persistente la proprietà delle impostazioni specificato; in caso contrario, <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider
  nameWithType: ISettingsProviderService.GetSettingsProvider
