### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageability
  id: SettingsManageability
  children:
  - System.Configuration.SettingsManageability.Roaming
  langs:
  - csharp
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
  type: Enum
  summary: "Fornisce i valori per indicare quali servizi devono essere rese disponibili per le impostazioni dell&quot;applicazione."
  remarks: "Il ttribute viene utilizzato per applicare singole proprietà dell&quot;applicazione delle impostazioni e i gruppi di proprietà per indicare che devono fornire servizi speciali e predefiniti. L&quot;enumerazione di SettingsManageability Elenca i servizi disponibili. La maggior parte di questi servizi verrà fornita dal sistema operativo Windows."
  syntax:
    content: public enum SettingsManageability
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsManageability.Roaming
  id: Roaming
  parent: System.Configuration.SettingsManageability
  langs:
  - csharp
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Abilita le impostazioni dell&quot;applicazione da archiviare nei profili utente mobili. Per ulteriori informazioni sui profili utente mobili, vedere [spazio di memorizzazione isolato e Roaming](http://msdn.microsoft.com/en-us/d3cca593-4521-408d-b323-ea398d226de3)."
  syntax:
    content: Roaming
    return:
      type: System.Configuration.SettingsManageability
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsManageability.Roaming
  parent: System.Configuration.SettingsManageability
  isExternal: false
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
