### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection
  id: XmlSerializerSection
  children:
  - System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  - System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  - System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  - System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  - System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  langs:
  - csharp
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection
  type: Class
  summary: "Gestisce gli elementi XML utilizzati per configurare la serializzazione XML."
  remarks: "Questa classe viene utilizzata per gestire il [ \\&lt; xmlSerializer\\&gt; Elemento](../Topic/%3CxmlSerializer%3E%20Element.md)."
  syntax:
    content: 'public sealed class XmlSerializerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.XmlSerializerSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Xml.Serialization.Configuration.XmlSerializerSection&quot;> </xref> classe."
  syntax:
    content: public XmlSerializerSection ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  id: CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Ottiene o imposta un valore che determina se un ulteriore controllo dello stato di avanzamento del <xref:System.Xml.Serialization.XmlSerializer>viene eseguita.</xref:System.Xml.Serialization.XmlSerializer>"
  remarks: "Non utilizzare questo metodo. Al contrario, impostare il `checkDeserializerAdvances` attributo del [ \\&lt; xmlSerializer\\&gt; Elemento](../Topic/%3CxmlSerializer%3E%20Element.md)."
  syntax:
    content: public bool CheckDeserializeAdvances { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il controllo viene effettuato; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  id: TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Restituisce il percorso specificato per la creazione del file temporaneo."
  syntax:
    content: public string TempFilesLocation { get; set; }
    return:
      type: System.String
      description: "Il percorso specificato per la creazione del file temporaneo."
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  id: UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Ottiene o imposta un valore che indica se l&quot;oggetto specificato viene utilizzata la generazione di un serializzatore legacy."
  syntax:
    content: public bool UseLegacySerializerGeneration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;oggetto utilizza la generazione del serializzatore legacy. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.XmlSerializerSection()
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection.XmlSerializerSection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
