### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserSettingsGroup
  id: UserSettingsGroup
  children:
  - System.Configuration.UserSettingsGroup.#ctor
  langs:
  - csharp
  name: UserSettingsGroup
  nameWithType: UserSettingsGroup
  fullName: System.Configuration.UserSettingsGroup
  type: Class
  summary: "Rappresenta un raggruppamento di sezioni all&quot;interno di un file di configurazione delle impostazioni utente correlato. Questa classe non può essere ereditata."
  remarks: "Poiché alcune sezioni di configurazione sono correlate, è spesso utile raggrupparli insieme in un solo gruppo di sezioni."
  syntax:
    content: 'public sealed class UserSettingsGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Configuration.UserSettingsGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.UserSettingsGroup
  langs:
  - csharp
  name: UserSettingsGroup()
  nameWithType: UserSettingsGroup.UserSettingsGroup()
  fullName: System.Configuration.UserSettingsGroup.UserSettingsGroup()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.UserSettingsGroup&quot;> </xref> classe."
  syntax:
    content: public UserSettingsGroup ();
    parameters: []
  overload: System.Configuration.UserSettingsGroup.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Configuration.UserSettingsGroup.#ctor
  parent: System.Configuration.UserSettingsGroup
  isExternal: false
  name: UserSettingsGroup()
  nameWithType: UserSettingsGroup.UserSettingsGroup()
  fullName: System.Configuration.UserSettingsGroup.UserSettingsGroup()
- uid: System.Configuration.UserSettingsGroup.#ctor*
  parent: System.Configuration.UserSettingsGroup
  isExternal: false
  name: UserSettingsGroup
  nameWithType: UserSettingsGroup.UserSettingsGroup
