### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  summary: "Fornisce una stringa che descrive una singola proprietà di configurazione. Questa classe non può essere ereditata."
  remarks: "Il SettingsDescriptionAttribute è progettato per gli strumenti in fase di progettazione sia strumenti di amministrazione runtime identificazione e alla descrizione della proprietà di configurazione associato.       Questo attributo è facoltativo e può essere applicato solo a livello di proprietà di configurazione di singoli."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza un&quot;istanza di <xref href=&quot;System.Configuration.SettingsDescriptionAttribute&quot;> </xref> classe."
  remarks: "Anche se la descrizione presenta una lunghezza massima teorica del <xref:System.String>(classe), la cui lunghezza è rappresentata da un <xref:System.Int32>, le seguenti due considerazioni pratiche limiterà le dimensioni del `description` parametro:-descrizioni di testo di grandi dimensioni sono difficili da visualizzare in un&quot;interfaccia utente (UI) e difficile da leggere.</xref:System.Int32> </xref:System.String>      -I provider di impostazioni possono applicare quote di utilizzo complessivo e sono necessari per imporre le quote di configurazione utente."
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "Il <xref:System.String>utilizzata come testo descrittivo.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il testo descrittivo per la proprietà di configurazione associato."
  remarks: "Impostazione della proprietà Description di <xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>costruttore.</xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "Oggetto <xref:System.String>contenente il testo descrittivo per la proprietà di configurazione associato.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
