### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.CustomTypeElement
  id: CustomTypeElement
  children:
  - System.IdentityModel.Configuration.CustomTypeElement.#ctor
  - System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  - System.IdentityModel.Configuration.CustomTypeElement.Properties
  - System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.Custom``0ypeElement)
  - System.IdentityModel.Configuration.CustomTypeElement.Type
  langs:
  - csharp
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
  type: Class
  summary: "Rappresenta un elemento o attributo che specifica un oggetto personalizzato <xref:System.Type>in un file di configurazione.</xref:System.Type> Questa classe non può essere ereditata."
  remarks: "La classe CustomTypeElement rappresenta un attributo o un elemento che specifica un tipo personalizzato in un file di configurazione. Ad esempio, il [ \\&lt; claimsAuthenticationManager\\&gt;](../Topic/%3CclaimsAuthenticationManager%3E.md) elemento utilizzato per specificare la gestione di identità delle attestazioni contiene `type` attributo che specifica il <xref:System.Type>del gestore di autenticazione delle attestazioni; `<claimsAuthenticationManager type=&quot;MyNamespace.CustomClaimsAuthenticationManager, MyAssembly&quot;/>`.</xref:System.Type> Il <xref:System.IdentityModel.Configuration.IdentityConfigurationElement.ClaimsAuthenticationManager%2A?displayProperty=fullName>proprietà che rappresenta questo elemento come configurato in un [ \\&lt; identityConfiguration\\&gt;](../Topic/%3CidentityConfiguration%3E.md) elemento ottiene e imposta un&quot;istanza di CustomTypeElement.</xref:System.IdentityModel.Configuration.IdentityConfigurationElement.ClaimsAuthenticationManager%2A?displayProperty=fullName>"
  syntax:
    content: 'public sealed class CustomTypeElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: CustomTypeElement()
  nameWithType: CustomTypeElement.CustomTypeElement()
  fullName: System.IdentityModel.Configuration.CustomTypeElement.CustomTypeElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.IdentityModel.Configuration.CustomTypeElement&quot;> </xref> classe."
  syntax:
    content: public CustomTypeElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.CustomTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  id: IsConfigured
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
  fullName: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene un valore che indica se l&quot;elemento è stato configurato con i valori non predefiniti."
  syntax:
    content: public bool IsConfigured { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;elemento è stato configurato con valori non predefiniti. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: CustomTypeElement.Properties
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.IdentityModel.Configuration.CustomTypeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.Custom``0ypeElement)
  id: Resolve``1(System.IdentityModel.Configuration.Custom``0ypeElement)
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Resolve(CustomTypeElement)
  nameWithType: CustomTypeElement.Resolve(CustomTypeElement)
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Resolve(CustomTypeElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: 'public static T Resolve<T> (System.IdentityModel.Configuration.CustomTypeElement customTypeElement) where T : class;'
    parameters:
    - id: customTypeElement
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "Da aggiungere."
    return:
      type: T
      description: "Da aggiungere."
  overload: System.IdentityModel.Configuration.CustomTypeElement.Resolve<T>*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Type
  nameWithType: CustomTypeElement.Type
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Il <xref:System.Type>rappresentato dall&quot;istanza corrente.</xref:System.Type>"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "Il tipo rappresentato da questa istanza."
  overload: System.IdentityModel.Configuration.CustomTypeElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: CustomTypeElement()
  nameWithType: CustomTypeElement.CustomTypeElement()
  fullName: System.IdentityModel.Configuration.CustomTypeElement.CustomTypeElement()
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
  fullName: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Properties
  nameWithType: CustomTypeElement.Properties
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.Custom``0ypeElement)
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Resolve(CustomTypeElement)
  nameWithType: CustomTypeElement.Resolve(CustomTypeElement)
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Resolve(CustomTypeElement)
- uid: T
  isExternal: true
  name: T
  nameWithType: T
  fullName: T
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Type
  nameWithType: CustomTypeElement.Type
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement.CustomTypeElement
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Properties
  nameWithType: CustomTypeElement.Properties
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve<T>*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Resolve<T>
  nameWithType: CustomTypeElement.Resolve<T>
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Type
  nameWithType: CustomTypeElement.Type
