### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  id: PartialTrustVisibleAssembliesSection
  children:
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  type: Class
  summary: "Configura un set di assembly con attendibilità parziale. Questa classe non può essere ereditata."
  remarks: "Per impostazione predefinita, ASP.NET definisce internamente un set noto di assembly contrassegnati con parzialmente attendibili chiamanti attributo (APTCA) per l&quot;utilizzo in applicazioni ASP.NET con attendibilità parziale. Il PartialTrustVisibleAssembliesSection consente di aggiungere all&quot;elenco degli assembly APTCA.       Per configurare un assembly, è necessario la rappresentazione di stringa esadecimale della chiave pubblica. Questa chiave si ottiene utilizzando lo strumento nome sicuro (Sn.exe). Questo strumento genera la rappresentazione di stringa esadecimale a chiave pubblica utilizzato per la configurazione e anche il token di chiave pubblica.       Per ulteriori informazioni sullo strumento nome sicuro, vedere [Sn.exe (strumento nome sicuro)](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to configure a partial trust assembly by using the `partialTrustVisibleAssemblies` section in a configuration file.  \n  \n```  \n<partialTrustVisibleAssemblies>  \n  <add assemblyName=\"MyAssembly\"   \n    publicKey=\"hex_key_representation\"/>  \n</partialTrustVisibleAssemblies>  \n```"
  syntax:
    content: 'public sealed class PartialTrustVisibleAssembliesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> classe."
  syntax:
    content: public PartialTrustVisibleAssembliesSection ();
    parameters: []
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  id: PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> raccolta di assembly APTCA da utilizzare in applicazioni ASP.NET con attendibilità parziale."
  syntax:
    content: public System.Web.Configuration.PartialTrustVisibleAssemblyCollection PartialTrustVisibleAssemblies { get; }
    return:
      type: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
      description: "Raccolta degli assembly contrassegnati con APTCA da utilizzare in applicazioni ASP.NET con attendibilità parziale."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  id: Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
  parent: System.Web.Configuration
  isExternal: false
  name: PartialTrustVisibleAssemblyCollection
  nameWithType: PartialTrustVisibleAssemblyCollection
  fullName: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
