### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventArgs
  id: SettingsLoadedEventArgs
  children:
  - System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  - System.Configuration.SettingsLoadedEventArgs.Provider
  langs:
  - csharp
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs
  fullName: System.Configuration.SettingsLoadedEventArgs
  type: Class
  summary: "Fornisce dati per il <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> evento."
  remarks: "La classe SettingsLoadedEventArgs fornisce dati per il <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>evento che si verifica quando le impostazioni vengono recuperate da un provider.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>"
  syntax:
    content: 'public class SettingsLoadedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  id: '#ctor(System.Configuration.SettingsProvider)'
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsLoadedEventArgs&quot;> </xref> classe."
  syntax:
    content: public SettingsLoadedEventArgs (System.Configuration.SettingsProvider provider);
    parameters:
    - id: provider
      type: System.Configuration.SettingsProvider
      description: "Oggetto <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> oggetto da cui vengono caricate le impostazioni."
  overload: System.Configuration.SettingsLoadedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  id: Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il provider di impostazioni utilizzato per archiviare le impostazioni di configurazione."
  syntax:
    content: public System.Configuration.SettingsProvider Provider { get; }
    return:
      type: System.Configuration.SettingsProvider
      description: "Un provider di impostazioni."
  overload: System.Configuration.SettingsLoadedEventArgs.Provider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.Provider*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
