### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyValidation
  id: MachineKeyValidation
  children:
  - System.Web.Configuration.MachineKeyValidation.AES
  - System.Web.Configuration.MachineKeyValidation.Custom
  - System.Web.Configuration.MachineKeyValidation.HMACSHA256
  - System.Web.Configuration.MachineKeyValidation.HMACSHA384
  - System.Web.Configuration.MachineKeyValidation.HMACSHA512
  - System.Web.Configuration.MachineKeyValidation.MD5
  - System.Web.Configuration.MachineKeyValidation.SHA1
  - System.Web.Configuration.MachineKeyValidation.TripleDES
  langs:
  - csharp
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
  type: Enum
  summary: "Specifica l&quot;algoritmo hash usato da ASP.NET per l&quot;autenticazione basata su form e per la convalida dei dati dello stato di visualizzazione e per l&quot;identificazione dello stato di sessione out-of-process."
  remarks: "ASP.NET utilizza un basati su hash message authentication code (HMAC) per rilevare se i dati utilizzati per lo stato di autenticazione o visualizzazione di form sono stato manomesso. Il valore HMAC viene generato quando viene creato il contenuto dello stato di visualizzazione e il valore HMAC è selezionato nelle richieste successive. Il valore HMAC consente ASP.NET di determinare se qualcuno ha modificato i dati inviati tra il server e client, ma i dati possono essere letti da qualsiasi utente nel tragitto tramite Internet, a meno che non viene inoltre crittografato. Per impostazione predefinita, lo stato di visualizzazione viene convalidato, ma non crittografato. Per ulteriori informazioni, vedere <xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>e <xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A>.</xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A> </xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>       L&quot;enumerazione MachineKeyValidation consente di specificare l&quot;algoritmo usato da ASP.NET per creare il valore HMAC. Il valore predefinito è HMACSHA256. In ASP.NET viene utilizzato il valore di <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>proprietà con l&quot;algoritmo selezionato per generare il valore HMAC.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>"
  example:
  - "The following code example shows how to use the MachineKeyValidation enumeration. In the example, `configSection` is an instance of <xref:System.Web.Configuration.MachineKeySection>.This code example is part of a larger example provided for the <xref:System.Web.Configuration.MachineKeySection> class.  \n  \n [!code-vb[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/visualbasic/t-system.web.configurati_93_1.vb)]\n [!code-cs[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/csharp/t-system.web.configurati_93_1.cs)]"
  syntax:
    content: public enum MachineKeyValidation
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.AES
  id: AES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzata la <xref uid=&quot;langword_csharp_AES&quot; name=&quot;AES&quot; href=&quot;&quot;> </xref> algoritmo di crittografia (Rijndael)."
  remarks: "Scegliere questa opzione se si desidera crittografare lo stato di visualizzazione nell&quot;applicazione Web. Se si sceglie questa opzione, il <xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>verrà utilizzata per la crittografia e decrittografia, proprietà e `HMACSHA1` verrà utilizzato l&quot;algoritmo hash con la <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>proprietà per la convalida.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A> </xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>"
  syntax:
    content: AES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  id: Custom
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che ASP.NET utilizza un algoritmo hash personalizzato."
  remarks: "L&quot;algoritmo hash personalizzato può essere implementato in qualsiasi classe che deriva da <xref:System.Security.Cryptography.KeyedHashAlgorithm>.</xref:System.Security.Cryptography.KeyedHashAlgorithm>       L&quot;algoritmo personalizzato viene in genere specificato in modo dichiarativo nell&quot;attributo di convalida dell&quot;elemento, nel formato `alg:` *nome_algoritmo*. Per informazioni su come specificare un algoritmo personalizzato nel codice, vedere il <xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>proprietà.</xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>"
  syntax:
    content: Custom
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  id: HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzata la <xref uid=&quot;langword_csharp_HMACSHA256&quot; name=&quot;HMACSHA256&quot; href=&quot;&quot;> </xref> algoritmo hash.  Questo è il valore predefinito."
  remarks: '`HMACSHA256`è un algoritmo hash SHA2 che genera un codice hash a 256 bit.'
  syntax:
    content: HMACSHA256
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  id: HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzata la <xref uid=&quot;langword_csharp_HMACSHA384&quot; name=&quot;HMACSHA384&quot; href=&quot;&quot;> </xref> algoritmo hash."
  remarks: '`HMACSHA384`è un algoritmo hash SHA2 che genera un codice hash di 384 bit. Questa opzione è disponibile per le applicazioni che richiedono una maggiore sicurezza rispetto a quella fornita dal `HMACSHA256`algoritmo.'
  syntax:
    content: HMACSHA384
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  id: HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzata la <xref uid=&quot;langword_csharp_HMACSHA512&quot; name=&quot;HMACSHA512&quot; href=&quot;&quot;> </xref> algoritmo hash."
  remarks: '`HMACSHA512`è un algoritmo hash SHA2 che genera un codice hash di 512 bit. Questa opzione è disponibile per le applicazioni che richiedono una maggiore sicurezza rispetto a quella fornita dal `HMACSHA384` algoritmo.'
  syntax:
    content: HMACSHA512
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  id: MD5
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che ASP.NET utilizza Message Digest 5 (<xref uid=&quot;langword_csharp_MD5&quot; name=&quot;MD5&quot; href=&quot;&quot;></xref>) algoritmo hash."
  remarks: '`MD5`è un algoritmo hash che genera un valore hash a 128 bit. Questa opzione è inclusa per scopi legacy e deve essere selezionata solo se è richiesta la compatibilità con le versioni precedenti di ASP.NET.'
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  id: SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzata la <xref uid=&quot;langword_csharp_HMACSHA1&quot; name=&quot;HMACSHA1&quot; href=&quot;&quot;> </xref> algoritmo hash."
  remarks: '`HMACSHA1`è un algoritmo hash che genera un valore hash a 160 bit. Questa opzione è inclusa per scopi legacy e deve essere selezionata solo se è richiesta la compatibilità con le versioni precedenti di ASP.NET.'
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  id: TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifica che verrà utilizzato il TripleDES (<xref uid=&quot;langword_csharp_3DES&quot; name=&quot;3DES&quot; href=&quot;&quot;></xref>) algoritmo di crittografia."
  remarks: "TripleDES è un algoritmo di crittografia che viene utilizzato solo se si specifica che lo stato di visualizzazione è crittografato. Questa opzione è inclusa per scopi legacy e deve essere selezionata solo se è richiesta la compatibilità con le versioni precedenti di ASP.NET."
  syntax:
    content: TripleDES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyValidation.AES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
- uid: System.Web.Configuration.MachineKeyValidation
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
