### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs
  id: CreatingCookieEventArgs
  children:
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  - System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  - System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  - System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  langs:
  - csharp
  name: CreatingCookieEventArgs
  nameWithType: CreatingCookieEventArgs
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs
  type: Class
  summary: "Fornisce dati per il <xref href=&quot;System.Web.ApplicationServices.AuthenticationService.CreatingCookie&quot;> </xref> evento."
  remarks: "La classe CreatingCookieEventArgs fornisce i valori per qualsiasi <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>gestore dell&quot;evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Utilizzando le proprietà di questa classe, è possibile recuperare le credenziali dell&quot;utente quando si crea un cookie di autenticazione personalizzato.       La <xref:System.Web.ApplicationServices.AuthenticationService>classe genera il <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento quando imposta il cookie di autenticazione, dopo aver autenticate le credenziali dell&quot;utente.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService> Il <xref:System.Web.ApplicationServices.AuthenticationService>costruisce un oggetto CreatingCookieEventArgs e la passa a qualsiasi classe <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>gestore dell&quot;evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>       Recuperare le credenziali utente tramite il <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A>, e <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>proprietà.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A></xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> Il <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>proprietà può contenere qualsiasi valore personalizzato che è necessario per eseguire l&quot;autenticazione, ad esempio un numero di identificazione.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> Il <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A>proprietà indica se il cookie di autenticazione deve essere mantenuto oltre la sessione corrente.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A> Impostare il <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>proprietà `true` se si crea il cookie di autenticazione, in modo che il <xref:System.Web.ApplicationServices.AuthenticationService>il cookie verrà creato dalla classe.</xref:System.Web.ApplicationServices.AuthenticationService> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the CreatingCookieEventArgs object to customize the authentication cookie. The handler saves the value from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> property in the authentication ticket and sets the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A> property to `true` to indicate that the authentication cookie has been created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/t-system.web.application_1_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/t-system.web.application_1_1.asax)]"
  syntax:
    content: 'public class CreatingCookieEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  id: CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene o imposta un valore che indica se il cookie di autenticazione è stato creato."
  remarks: "La <xref:System.Web.ApplicationServices.AuthenticationService>classe controlla la proprietà CookieIsSet per determinare se è stato creato il cookie di autenticazione.</xref:System.Web.ApplicationServices.AuthenticationService> Impostare questo valore su `true` se si crea un cookie di autenticazione in un gestore eventi per il <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Se CookieIsSet è impostata su `false` (valore predefinito), la <xref:System.Web.ApplicationServices.AuthenticationService>classe crea un cookie di autenticazione, questo sovrascrive qualsiasi cookie creato nel gestore per il <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The CookieIsSet property is set to `true` after the authentication ticket is created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_11_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_11_1.asax)]"
  syntax:
    content: public bool CookieIsSet { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il cookie di autenticazione è stato creato; in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  id: CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene i valori di autenticazione aggiuntivi forniti dall&quot;utente."
  remarks: "La proprietà CustomCredential per recuperare i valori personalizzati nel ticket di autenticazione. La proprietà CustomCredential contiene il valore passato al <xref:System.Web.ApplicationServices.AuthenticationService.Login%2A>metodo.</xref:System.Web.ApplicationServices.AuthenticationService.Login%2A> In genere, questa proprietà viene utilizzata per passare valori personalizzati che devono essere convalidati con il nome utente e password, ad esempio un numero di identificazione. Se più di un valore viene archiviato nella proprietà, è necessario analizzare la proprietà CustomCredential per recuperare i valori."
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The value passed in the CustomCredential property is stored in the <xref:System.Web.Security.FormsAuthenticationTicket.UserData%2A> property of the forms authentication ticket.  \n  \n> [!NOTE]\n>  Store the CustomCredential property in a cookie only when you know that the data in the property is not sensitive. Malicious users can access the values in the cookie.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_2_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_2_1.asax)]"
  syntax:
    content: public string CustomCredential { get; }
    return:
      type: System.String
      description: "I valori personalizzati necessari per l&quot;autenticazione, diverso dal nome utente e password."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  id: IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene un valore che indica se il cookie di autenticazione deve essere conservato nella sessione corrente."
  remarks: "Quando si crea un <xref:System.Web.Security.FormsAuthenticationTicket>dell&quot;oggetto, è possibile utilizzare la proprietà IsPersistent per specificare se il cookie di autenticazione viene mantenuto oltre la sessione corrente.</xref:System.Web.Security.FormsAuthenticationTicket>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.IsPersistent%2A> property of the <xref:System.Web.Security.FormsAuthenticationTicket> object is set to the value in the IsPersistent property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_0_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_0_1.asax)]"
  syntax:
    content: public bool IsPersistent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il cookie deve essere mantenuto oltre la sessione corrente. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  id: Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene la password per l&quot;utente."
  remarks: "Utilizzare la proprietà della Password per recuperare la password quando si impostano i valori personalizzati nel ticket di autenticazione.      > [!NOTE] > Non salvare il valore della proprietà Password nel ticket di autenticazione. Un utente malintenzionato può accedere al cookie e recuperare la password, anche se il cookie viene crittografato."
  syntax:
    content: public string Password { get; }
    return:
      type: System.String
      description: "La password fornita dall&quot;utente per l&quot;autenticazione."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  id: UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Ottiene il nome dell&quot;utente."
  remarks: "La proprietà nome utente per recuperare il nome di autenticazione quando si impostano i valori personalizzati nel ticket di autenticazione. In genere, si imposta la <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>proprietà del <xref:System.Web.Security.FormsAuthenticationTicket>oggetto con il valore di nome utente.</xref:System.Web.Security.FormsAuthenticationTicket> </xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A> property is set to the values of the UserName property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_6_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_6_1.asax)]"
  syntax:
    content: public string UserName { get; }
    return:
      type: System.String
      description: "Il nome fornito dall&quot;utente per l&quot;autenticazione."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
