### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebRequestModuleElement
  id: WebRequestModuleElement
  children:
  - System.Net.Configuration.WebRequestModuleElement.#ctor
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  - System.Net.Configuration.WebRequestModuleElement.Prefix
  - System.Net.Configuration.WebRequestModuleElement.Properties
  - System.Net.Configuration.WebRequestModuleElement.Type
  langs:
  - csharp
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement
  fullName: System.Net.Configuration.WebRequestModuleElement
  type: Class
  summary: "Rappresenta un prefisso URI e la classe associata che gestisce la creazione di richieste Web per il prefisso. Questa classe non può essere ereditata."
  remarks: "Using the <xref:System.Net.WebRequest> and <xref:System.Net.WebResponse> classes, applications can request resources for any valid <xref:System.Uri>. Use this configuration element to specify a module that is registered to work with the <xref:System.Net.WebRequest.Create%2A> overloads to create new requests.  \n  \n This class corresponds to the [\\&lt;add\\&gt; Element for webRequestModules (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20webRequestModules%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify modules registered to authenticate requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files.  \n  \n The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:  \n  \n-   HTTP  \n  \n-   HTTPS  \n  \n-   FTP  \n  \n-   FILE"
  syntax:
    content: 'public sealed class WebRequestModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> classe."
  syntax:
    content: public WebRequestModuleElement ();
    parameters: []
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> classe utilizzando le informazioni di tipo e del prefisso URI specificate."
  remarks: "Il `type` parametro contiene il nome completo del tipo seguito da una virgola (,) e le informazioni sull&quot;assembly. Gli elementi di informazioni sull&quot;assembly sono separati da virgole, ad esempio, &quot;`System.Net.DigestClient, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;`.       Il <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>è impostata su `prefix` e <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>è impostata su `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, string type);
    parameters:
    - id: prefix
      type: System.String
      description: "Stringa contenente un prefisso URI."
    - id: type
      type: System.String
      description: "Una stringa che contiene le informazioni di tipo e l&quot;assembly per la classe che gestisce la creazione di richieste di risorse che utilizzano il `prefix` prefisso URI. Per ulteriori informazioni, vedere la sezione Osservazioni."
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  id: '#ctor(System.String,System.Type)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> classe usando il prefisso URI specificato e l&quot;identificatore di tipo."
  remarks: "Il <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>è impostata su `prefix` e <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>è impostata su `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, Type type);
    parameters:
    - id: prefix
      type: System.String
      description: "Stringa contenente un prefisso URI."
    - id: type
      type: System.Type
      description: "Oggetto <xref:System.Type>che identifica la classe che gestisce le richieste di creazione per le risorse che utilizzano il `prefix` prefisso URI.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  id: Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta il prefisso URI per il modulo di richiesta Web corrente."
  remarks: ".NET Framework versione 2.0 fornisce i moduli di richiesta Web che creano le richieste di risorse con i prefissi seguenti: - HTTP - HTTPS - FTP - FILE"
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "Stringa che contiene un prefisso URI."
  overload: System.Net.Configuration.WebRequestModuleElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Net.Configuration.WebRequestModuleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  id: Type
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Ottiene o imposta una classe che crea le richieste Web."
  remarks: "Utilizzo <xref:System.Net.WebRequest>e <xref:System.Net.WebResponse>le classi, le applicazioni possono richiedere risorse per qualsiasi <xref:System.Uri>.</xref:System.Uri> valido</xref:System.Net.WebResponse> </xref:System.Net.WebRequest> Utilizzare questa proprietà per specificare un tipo registrato per l&quot;utilizzo con il <xref:System.Net.WebRequest.Create%2A>metodo per creare nuove richieste.</xref:System.Net.WebRequest.Create%2A>       .NET Framework versione 2.0 fornisce i moduli di richiesta Web che creano le richieste di risorse con i prefissi seguenti: - HTTP - HTTPS - FTP - FILE"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "Oggetto <xref:System.Type>istanza che identifica un modulo di richiesta Web.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement.WebRequestModuleElement
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
- uid: System.Net.Configuration.WebRequestModuleElement.Type*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
