### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsContext
  id: SettingsContext
  children:
  - System.Configuration.SettingsContext.#ctor
  langs:
  - csharp
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
  type: Class
  summary: "Fornisce informazioni contestuali che il provider può utilizzare durante il salvataggio delle impostazioni."
  remarks: "La classe SettingsContext è la classe base utilizzata dalle applicazioni per fornire informazioni contestuali al provider di impostazioni. Sebbene la classe non astratta, è possibile creare una classe specializzata che eredita dalla classe SettingsContext e fornisce informazioni aggiuntive a tipi specifici di provider di un&quot;applicazione. Il provider può quindi esaminare le impostazioni contestuali durante la scrittura di proprietà.       Lo scopo principale della classe SettingsContext consiste nel fornire funzionalità che utilizzano il <xref:System.Configuration.SettingsBase>classe e l&quot;infrastruttura correlata.</xref:System.Configuration.SettingsBase> La classe SettingsContext fornisce informazioni contestuali aggiuntive specifiche funzionalità relative ai dati di proprietà archiviati dal <xref:System.Configuration.SettingsBase>istanza.</xref:System.Configuration.SettingsBase> Pertanto, è molto semplice archiviare informazioni aggiuntive in una classe SettingsContext senza derivare da esso (o da altre classi Impostazioni *) per supportare ulteriori funzionalità specifiche informazioni sul contesto.       Ad esempio, ASP.NET utilizza la classe SettingsContext per passare il nome utente associato ai dati gestiti da un <xref:System.Configuration.SettingsBase>istanza, nonché una proprietà che indica se l&quot;utente viene considerato autenticato.</xref:System.Configuration.SettingsBase> In questo modo, ASP.NET utilizza la classe SettingsContext per identificare autenticati rispetto a dati di profilo anonimi."
  syntax:
    content: 'public class SettingsContext : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net462
- uid: System.Configuration.SettingsContext.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsContext
  langs:
  - csharp
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> classe."
  syntax:
    content: public SettingsContext ();
    parameters: []
  overload: System.Configuration.SettingsContext.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsContext.#ctor
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
- uid: System.Configuration.SettingsContext.#ctor*
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext.SettingsContext
