### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Controlla la modalità di interpretazione dei caratteri Unicode dal <xref:System.Net.WebUtility.HtmlDecode*>metodi.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "Per ulteriori informazioni su presunto caratteri Unicode da codificare in formato HTML, vedere [usando caratteri di escape nel markup e CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Utilizzare il comportamento automatico. Il comportamento di decodifica è determinato dal Framework di destinazione dell&quot;applicazione corrente. Per [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] e versioni successive, la codifica di Unicode decodifica è strict."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Utilizzare un comportamento compatibile. Specifica che i dati in ingresso non viene verificati la validità prima da decodificare. Ad esempio, una stringa di input &quot;&amp;amp; #xD84C;&quot; sarebbe decodificare come U + D84C, ovvero un carattere sostitutivo. Inoltre, il decodificatore non riconosce i punti di codice nella migrazione a meno che non sono rappresentati in surrogati codificata in formato HTML, pertanto il parametro inputstring &quot;&amp;#144308;&quot; avrebbe come risultato la stringa di output &quot;&amp;#144308;&quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Utilizzare il comportamento separato. È simile alla compatibilità, in quanto non vengono eseguiti controlli di validità, ma il decodificatore comprende anche i punti di codice. La stringa di input &quot;&amp;#144308;&quot; sarebbe decodifica nel carattere U +&233;B4 correttamente. Questo parametro è progettato per fornire la massima interoperabilità, quando il decodificatore non riconosce il formato di provider di utilizzo per generare la stringa codificata."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Utilizzare il comportamento di tipo strict. Specifica che i dati codificati in ingresso viene verificati la validità prima da decodificare. Ad esempio, una stringa di input &quot;&amp;#144308;&quot; sarebbe decodificare di U +&233;B4, ma con una stringa di input &quot;&amp;#xD84C;&amp; #xDFB4;&quot;in grado di decodificare correttamente. Dati già decodificati nella stringa non viene verificati la validità. Ad esempio, una stringa di input di &quot;\\ud800&quot; comporterà una stringa di output di &quot;\\ud800&quot;, come il surrogato già decodificato viene ignorato durante la decodifica, anche se è non abbinato."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
