### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingRoleServiceSection
  id: ScriptingRoleServiceSection
  children:
  - System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  - System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  - System.Web.Configuration.ScriptingRoleServiceSection.Properties
  langs:
  - csharp
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection
  fullName: System.Web.Configuration.ScriptingRoleServiceSection
  type: Class
  summary: "Rappresenta una sezione di configurazione per le impostazioni del servizio di ruolo."
  remarks: "La classe ScriptingRoleServiceSection consente di accedere a livello di codice e di modificare il `roleService` elemento della sezione di configurazione per l&quot;utilizzo della funzionalità AJAX in [!INCLUDE[vstecasp](~/add/includes/vstecasp-md.md)].       Il servizio ruolo è in genere utilizzato per recuperare le informazioni sui ruoli per l&quot;utente connesso tramite una chiamata asincrona di servizio Web."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for the <xref:System.Web.Configuration.ScriptingRoleServiceSection.Enabled%2A> property of the ScriptingRoleServiceSection class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <roleService enabled=\"true\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example shows how to access the ScriptingRoleServiceSection element programmatically.  \n  \n [!code-cs[System.Web.Configuration#4](~/add/codesnippet/csharp/t-system.web.configurati_42_1.cs)]\n [!code-vb[System.Web.Configuration#4](~/add/codesnippet/visualbasic/t-system.web.configurati_42_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingRoleServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: ScriptingRoleServiceSection()
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.ScriptingRoleServiceSection&quot;> </xref> classe."
  syntax:
    content: public ScriptingRoleServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingRoleServiceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta un valore che indica se il servizio ruolo è abilitato per un [!INCLUDE[vstecasp](~/add/includes/vstecasp-md.md)] applicazione che utilizza le funzionalità AJAX."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se il servizio ruolo è abilitato. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Il valore predefinito è <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingRoleServiceSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.ScriptingRoleServiceSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: ScriptingRoleServiceSection()
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.ScriptingRoleServiceSection()
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingRoleServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
