### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  id: ConfigurationElementInterceptor
  children:
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  type: Class
  summary: "Vi sono componenti di schema di configurazione di Windows Identity Foundation (WIF) in cui gli utenti possono specificare elementi arbitrari e gli attributi. ad esempio, quando si specifica un gestore di token personalizzato. La classe ConfigurationElementInterceptor è implementata per gestire questi casi."
  syntax:
    content: 'public class ConfigurationElementInterceptor : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;> </xref> classe."
  syntax:
    content: public ConfigurationElementInterceptor ();
    parameters: []
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  id: ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene i nodi figlio di questo elemento."
  syntax:
    content: public System.Xml.XmlNodeList ChildNodes { get; }
    return:
      type: System.Xml.XmlNodeList
      description: "Raccolta di nodi figlio. <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>Se questo elemento non dispone di alcun nodo figlio."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Legge il XML dal file di configurazione."
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "Il <xref:System.Xml.XmlReader>che legge dal file di configurazione.</xref:System.Xml.XmlReader>"
    - id: serializeCollectionKey
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>per serializzare solo le proprietà della chiave dell&quot;insieme: in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  id: ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene l&quot;elemento XML rappresentato da questa istanza."
  syntax:
    content: public System.Xml.XmlElement ElementAsXml { get; }
    return:
      type: System.Xml.XmlElement
      description: "L&quot;elemento XML."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene un valore che indica se durante la deserializzazione viene rilevato un attributo sconosciuto. Restituisce sempre <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  remarks: "La <xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>classe è implementata in modo specifico per gestire elementi e attributi arbitrari, definiti dall&quot;utente.</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> Per questo motivo, questo metodo restituisce `true` quando .NET Framework viene rilevato un elemento non riconosciuto o un attributo per mantenere il parser in esecuzione."
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "Il nome dell&quot;attributo non riconosciuto."
    - id: value
      type: System.String
      description: "Il valore dell&quot;attributo non riconosciuto."
    return:
      type: System.Boolean
      description: "Restituisce sempre <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, che indica che è stato rilevato un attributo non riconosciuto."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  id: OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Ottiene un valore che indica se durante la deserializzazione viene rilevato un elemento sconosciuto. Restituisce sempre <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  remarks: "La <xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>classe è implementata in modo specifico per gestire elementi e attributi arbitrari, definiti dall&quot;utente.</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> Per questo motivo, questo metodo restituisce `true` quando .NET Framework viene rilevato un elemento non riconosciuto o un attributo per mantenere il parser in esecuzione."
  syntax:
    content: protected override bool OnDeserializeUnrecognizedElement (string elementName, System.Xml.XmlReader reader);
    parameters:
    - id: elementName
      type: System.String
      description: "Il nome del sottoelemento sconosciuto."
    - id: reader
      type: System.Xml.XmlReader
      description: "Il lettore XML utilizzato per la deserializzazione."
    return:
      type: System.Boolean
      description: "Restituisce sempre <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, che indica che è stato rilevato un elemento non riconosciuto."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Reimposta lo stato interno del <xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;> </xref> oggetto, inclusi i blocchi e raccolte di proprietà."
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Il nodo padre dell&quot;elemento di configurazione."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
- uid: System.Xml.XmlElement
  parent: System.Xml
  isExternal: false
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement
  nameWithType: ConfigurationElementInterceptor.DeserializeElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset
  nameWithType: ConfigurationElementInterceptor.Reset
