### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection
  id: NetPipeSection
  children:
  - System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  - System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  - System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  - System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  - System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  - System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  - System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  langs:
  - csharp
  name: NetPipeSection
  nameWithType: NetPipeSection
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection
  type: Class
  summary: "Contiene gli elementi di configurazione per il servizio di condivisione NetPipeActivator. Questa classe non può essere ereditata."
  remarks: "Named Pipe Activation Service gestisce la durata della connessione named pipe e gestisce le richieste di attivazione che arrivano sulle named pipe. Questa classe contiene proprietà che configurano il servizio."
  syntax:
    content: 'public sealed class NetPipeSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: NetPipeSection()
  nameWithType: NetPipeSection.NetPipeSection()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.NetPipeSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Activation.Configuration.NetPipeSection&quot;> </xref> classe."
  syntax:
    content: public NetPipeSection ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  id: AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Ottiene gli account utente per processi che ospitano [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] servizi e viene concesso l&quot;accesso al servizio di condivisione."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection AllowAccounts { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
      description: "Oggetto <xref href=&quot;System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection&quot;> </xref> che contiene l&quot;account utente per processi che ospitano [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] servizi e viene concesso l&quot;accesso al servizio di condivisione. I valori predefiniti restituiti sono LocalSystem, Admin, NS, LS e IIS_USRS."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: NetPipeSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  id: MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Ottiene o imposta numero massimo thread di accettazione in sospeso contemporaneamente sull&quot;endpoint di ascolto per il servizio di condivisione."
  syntax:
    content: public int MaxPendingAccepts { get; set; }
    return:
      type: System.Int32
      description: "Il massimo in attesa thread di accettazione contemporaneamente sull&quot;endpoint di ascolto per il servizio di condivisione. Il valore predefinito è 2."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  id: MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Ottiene o imposta il numero massimo di connessioni in attesa per questo servizio di condivisione."
  syntax:
    content: public int MaxPendingConnections { get; set; }
    return:
      type: System.Int32
      description: "Il numero massimo di connessioni in attesa per questo servizio di condivisione."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: Properties
  nameWithType: NetPipeSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  id: ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Ottiene o imposta il timeout per il servizio di condivisione NetPipeActivator."
  remarks: "Questa proprietà specifica il timeout per la lettura dei dati sui frame e l&quot;esecuzione dell&quot;invio della connessione dalle connessioni sottostanti."
  syntax:
    content: public TimeSpan ReceiveTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Il valore predefinito è 10 secondi."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: NetPipeSection()
  nameWithType: NetPipeSection.NetPipeSection()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.NetPipeSection()
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: SecurityIdentifierElementCollection
  nameWithType: SecurityIdentifierElementCollection
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: NetPipeSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault()
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: Properties
  nameWithType: NetPipeSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: NetPipeSection
  nameWithType: NetPipeSection.NetPipeSection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: InitializeDefault
  nameWithType: NetPipeSection.InitializeDefault
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: Properties
  nameWithType: NetPipeSection.Properties
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
