### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSaveMode
  id: ConfigurationSaveMode
  children:
  - System.Configuration.ConfigurationSaveMode.Full
  - System.Configuration.ConfigurationSaveMode.Minimal
  - System.Configuration.ConfigurationSaveMode.Modified
  langs:
  - csharp
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
  type: Enum
  summary: "Determina le proprietà che vengono scritte in un file di configurazione."
  remarks: "I valori di enumerazione ConfigurationSaveMode identificano quali proprietà vengono scritte in un file di configurazione quando si chiama il <xref:System.Configuration.Configuration.Save%2A>e <xref:System.Configuration.Configuration.SaveAs%2A>metodi.</xref:System.Configuration.Configuration.SaveAs%2A> </xref:System.Configuration.Configuration.Save%2A>"
  syntax:
    content: public enum ConfigurationSaveMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Full
  id: Full
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Fa sì che tutte le proprietà da scrivere nel file di configurazione. Ciò è utile principalmente per la creazione di file di configurazione di informazioni o lo spostamento di valori di configurazione da un computer a un altro."
  syntax:
    content: Full
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  id: Minimal
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Fa sì che solo le proprietà che differiscono dai valori ereditati da scrivere nel file di configurazione."
  syntax:
    content: Minimal
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Modified
  id: Modified
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Cause modificate solo le proprietà da scrivere nel file di configurazione, anche quando il valore corrisponde al valore ereditato."
  syntax:
    content: Modified
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Da aggiungere."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationSaveMode.Full
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
- uid: System.Configuration.ConfigurationSaveMode.Modified
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
