### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  summary: "Rappresenta un elemento di configurazione che specifica le impostazioni del pool aggiuntivi per la connessione per un trasporto TCP. Questa classe non può essere ereditata."
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement&quot;> </xref> classe."
  syntax:
    content: public TcpConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta una stringa che definisce il nome del pool di connessioni utilizzato per canali in uscita."
  remarks: "In modalità flusso, le connessioni non sono condivise, vale a dire che il pool di connessioni è disabilitato. Il valore predefinito è una stringa &quot;default&quot;. È possibile modificare questo valore per isolare le connessioni per un particolare client in gruppi separati."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "Il nome del pool di connessioni utilizzato per canali in uscita."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il tempo massimo, che la connessione può rimanere inattiva prima che venga interrotta."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Un valore positivo <xref:System.TimeSpan>che specifica il tempo massimo, la connessione può rimanere inattiva prima che venga interrotta.</xref:System.TimeSpan> Il valore predefinito è 00:02:00."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta l&quot;intervallo di tempo dopo il quale una connessione attiva viene chiusa."
  remarks: "Una connessione viene chiusa dopo la restituzione alla cache di connessione e non durante la trasmissione attiva. La cache di connessione utilizzata dal trasporto TCP crea nuove connessioni in base alle esigenze per ogni endpoint, fino al limite della cache impostato da <xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>.</xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Oggetto <xref:System.TimeSpan>struttura che indica la durata dopo il quale viene chiusa la connessione TCP.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ottiene o imposta il numero massimo di connessioni a un endpoint remoto iniziato dal servizio."
  remarks: "Le connessioni che superano il limite vengono messe in coda fino a quando non è disponibile uno spazio inferiore al limite. Questa proprietà limita il periodo di tempo in cui le connessioni rimangono in coda prima che venga generata un&quot;eccezione.       Questa proprietà limita il numero di connessioni attive simultanee dal client a un particolare endpoint del servizio. Se questo valore viene superato dal numero di connessioni client attive, è possibile che il servizio potrebbe non rispondere al client. In questo caso, il valore deve essere regolato per superare il numero massimo di connessioni client simultanee previste a un endpoint specifico.       Questa impostazione può essere definita anche sul lato del servizio, nel quale caso il valore utilizzato per impostare <xref:System.ServiceModel.Channels.MaxPooledConnections%2A>in <xref:System.ServiceModel.Channels.TcpChannelListener>.</xref:System.ServiceModel.Channels.TcpChannelListener> </xref:System.ServiceModel.Channels.MaxPooledConnections%2A>"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Il numero massimo di connessioni a un endpoint remoto iniziate dal servizio. Il valore predefinito è 10."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
