### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteTimeSpanConverter
  id: InfiniteTimeSpanConverter
  children:
  - System.Configuration.InfiniteTimeSpanConverter.#ctor
  - System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter
  fullName: System.Configuration.InfiniteTimeSpanConverter
  type: Class
  summary: "Esegue la conversione tra una stringa e lo standard infinito <xref:System.TimeSpan>valore.</xref:System.TimeSpan>"
  remarks: "Questo tipo, come tutti gli altri configurazione convertitore tipi, converte le stringhe trovate nel file di configurazione da e verso le proprietà fortemente tipizzate correlate.       In particolare il InfiniteTimeSpanConverter converte il <xref:System.String>valore &quot;infinito&quot; assegnato a una proprietà di configurazione infinito standard <xref:System.TimeSpan>e viceversa.</xref:System.TimeSpan> </xref:System.String> Il infinite <xref:System.TimeSpan>valore è rappresentato dal <xref:System.TimeSpan>valore di enumerazione.</xref:System.TimeSpan> </xref:System.TimeSpan>       Questo convertitore viene utilizzato con <xref:System.TimeSpan>proprietà.</xref:System.TimeSpan> Un valore infinito viene mantenuto come la stringa &quot;infinita&quot;."
  example:
  - "The following code example shows how to define a custom section property that uses the InfiniteTimeSpanConverter class.  \n  \n For the complete example code that implements the custom section, refer to the <xref:System.Configuration.ConfigurationConverterBase> class.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/csharp/t-system.configuration.i_6_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/visualbasic/t-system.configuration.i_6_1.vb)]  \n  \n The following example code shows how to access the previous custom section property.  \n  \n [!code-cs[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/csharp/t-system.configuration.i_6_2.cs)]\n [!code-vb[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.i_6_2.vb)]  \n  \n The following is a configuration excerpt as used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n    </configSections>  \n    <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\"/>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class InfiniteTimeSpanConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.InfiniteTimeSpanConverter&quot;> </xref> classe."
  remarks: "In genere, si usano i tipi di convertitore di tipi forniti dal sistema. L&quot;unica volta che è necessario utilizzare il costruttore InfiniteTimeSpanConverter è quando si crea un tipo di conversione."
  syntax:
    content: public InfiniteTimeSpanConverter ();
    parameters: []
  overload: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.String>a un <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Il sistema utilizza il metodo ConvertFrom durante la lettura da un file di configurazione per convertire un <xref:System.String>valore di <xref:System.TimeSpan> <xref:System.String>&quot;infinito&quot; per <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>oggetto utilizzato durante la conversione.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Il <xref:System.String>oggetto da convertire.</xref:System.String>"
    return:
      type: System.Object
      description: "Il <xref:System.TimeSpan.MaxValue>, se il <code> data </code> parametro è il <xref:System.String>infinito in caso contrario, il <xref:System.TimeSpan>che rappresenta il <code> data </code> parametro in minuti.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte un <xref:System.TimeSpan>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Il sistema utilizza il metodo ConvertTo durante la scrittura di un attributo in un file di configurazione per convertire un <xref:System.TimeSpan>l&quot;oggetto in un <xref:System.String>oggetto.</xref:System.String> </xref:System.TimeSpan>       Il sistema utilizza il metodo ConvertTo durante la scrittura di un file di configurazione per convertire un <xref:System.TimeSpan>valore o <xref:System.TimeSpan.MaxValue>a un <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Il <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> oggetto utilizzato per le conversioni di tipo."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Il <xref:System.Globalization.CultureInfo>utilizzato durante la conversione degli oggetti.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Valore da convertire."
    - id: type
      type: System.Type
      description: "Il tipo di conversione."
    return:
      type: System.Object
      description: "Il <xref:System.String>&quot;infinito&quot;, se il <code> value </code> parametro <xref:System.TimeSpan.MaxValue>; in caso contrario, il <xref:System.String>che rappresenta il <code> value </code> parametro in minuti.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteTimeSpanConverter.ConvertTo
