### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FolderLevelBuildProvider
  id: FolderLevelBuildProvider
  children:
  - System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  - System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  - System.Web.Configuration.FolderLevelBuildProvider.Name
  - System.Web.Configuration.FolderLevelBuildProvider.Properties
  - System.Web.Configuration.FolderLevelBuildProvider.Type
  langs:
  - csharp
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider
  fullName: System.Web.Configuration.FolderLevelBuildProvider
  type: Class
  summary: "Rappresenta le impostazioni di configurazione che consentono l&quot;utilizzo del <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> classe per le cartelle specifiche."
  remarks: "L&quot;ambiente di compilazione ASP.NET utilizza oggetti FolderLevelBuildProvider per generare codice sorgente per diversi tipi di file e le sottocartelle in un&quot;applicazione. Le classi che derivano dalla classe FolderLevelBuildProvider generano codice sorgente per le cartelle, ad esempio Bin, App_GlobalResources, App_LocalResources, App_WebReferences, App_Browsers, tema e per altre cartelle personalizzate. In genere, non creare direttamente un&quot;istanza della classe FolderLevelBuildProvider. È invece necessario implementare una classe che deriva da <xref:System.Web.Compilation.BuildProvider>e applicare la <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>classe ad esso e quindi configurare la classe derivata per l&quot;utilizzo nell&quot;ambiente di compilazione ASP.NET.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute> </xref:System.Web.Compilation.BuildProvider> La <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>classe destinata a cartelle anziché file.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>       Utilizzare le istanze della classe FolderLevelBuildProvider assieme <xref:System.Web.Compilation.AssemblyBuilder>oggetti per compilare uno o più file in un assembly compilato.</xref:System.Web.Compilation.AssemblyBuilder> L&quot;istanza FolderLevelBuildProvider genera codice sorgente nella lingua appropriata per i singoli file e <xref:System.Web.Compilation.AssemblyBuilder>oggetto compila il codice sorgente fornito da ogni istanza FolderLevelBuildProvider in un unico assembly.</xref:System.Web.Compilation.AssemblyBuilder>       La classe FolderLevelBuildProvider è incluso il `configuration` sezione del file Web. config."
  example:
  - "The following example shows how to add a build provider named `BuildProvider1` to the Web.config file.  \n  \n```  \n<compilation>  \n  <folderLevelBuildProviders>  \n    <add type=\"BuildProvider1, Assembly1,Version=1.0.0.0,    \n        PublicKeyToken=xxxxx\"/>  \n  </folderLevelBuildProviders>  \n</compilation>  \n```"
  syntax:
    content: 'public sealed class FolderLevelBuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> classe utilizzando un identificatore e il nome completo."
  syntax:
    content: public FolderLevelBuildProvider (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "L&quot;identificatore per il <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> da utilizzare."
    - id: type
      type: System.String
      description: "Il nome completo del <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> da utilizzare."
  overload: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Restituisce un valore che indica se un oggetto specificato è uguale all&quot;oggetto corrente <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> oggetto."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Oggetto provider di compilazione da confrontare."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se l&quot;oggetto provider di compilazione il livello di cartella specificato è uguale all&quot;oggetto corrente. in caso contrario, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Genera un codice hash per il <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> oggetto."
  remarks: "Questo metodo genera un numero intero che può essere utilizzato per identificare l&quot;oggetto di provider di compilazione a livello di cartella. Questo metodo eredita il <xref:System.Object.GetHashCode%2A>metodo.</xref:System.Object.GetHashCode%2A> Il <xref:System.Object.GetHashCode%2A>metodo è adatto per algoritmi hash e dati strutture, ad esempio una tabella hash.</xref:System.Object.GetHashCode%2A>"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Il codice hash per il <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> oggetto."
  overload: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  id: Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il nome del <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> oggetto."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Il nome dell&quot;oggetto provider di compilazione."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  id: Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene o imposta il nome completo della classe di provider di compilazione."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Il nome completo della classe di provider di compilazione."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals
  nameWithType: FolderLevelBuildProvider.Equals
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: FolderLevelBuildProvider.GetHashCode
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
