### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Fornisce il supporto delle versioni 1.0 e 1.1 di runtime per la lettura delle sezioni di configurazione e impostazioni di configurazione comuni."
  remarks: "Utilizzando i metodi statici e le proprietà del tipo ConfigurationSettings è il metodo consigliato per la lettura delle informazioni di configurazione in fase di esecuzione per le applicazioni di versioni 1.0 e 1.1.      > [!NOTE] > ConfigurationSettings la classe fornisce solo la compatibilità con le versioni precedenti. Per le nuove applicazioni è necessario utilizzare la <xref:System.Configuration.ConfigurationManager>classe o <xref:System.Web.Configuration.WebConfigurationManager>classe invece.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> Per utilizzare queste due classi, è necessario aggiungere un riferimento nel progetto o nell&quot;applicazione allo spazio dei nomi System. Configuration."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene una proprietà di sola lettura <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> della sezione di impostazioni dell&quot;applicazione del file di configurazione."
  remarks: "Il `appSettings` elemento della sezione del file di configurazione contiene una serie di coppie nome/valore che l&quot;applicazione può utilizzare per qualsiasi scopo.       Questo metodo è obsoleto e viene mantenuto per compatibilità con le versioni precedenti. Utilizzare il metodo GetSection.      > [!NOTE] > La <xref:System.Configuration.ConfigurationSettings>classe fornisce solo la compatibilità con le versioni precedenti.</xref:System.Configuration.ConfigurationSettings> È consigliabile utilizzare la <xref:System.Configuration.ConfigurationManager>classe o <xref:System.Web.Configuration.WebConfigurationManager>classe invece.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "Sola lettura <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> della sezione di impostazioni dell&quot;applicazione dal file di configurazione."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Restituisce il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> oggetto per il percorso e il nome della sezione di configurazione passata."
  remarks: "Questo metodo è obsoleto e viene mantenuto per compatibilità con le versioni precedenti. Utilizzare il metodo GetSection."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Specifica un nome di configurazione e il percorso, ad esempio &quot;System.NET /Settings&quot;."
    return:
      type: System.Object
      description: "Il <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> oggetto per il percorso e il nome della sezione di configurazione passata.       <div class=&quot;alert NOTE&quot;>    Il <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> classe fornisce solo la compatibilità con le versioni precedenti. È consigliabile utilizzare il <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> classe o <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> classe.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Impossibile recuperare la sezione richiesta."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
