### YamlMime:ManagedReference
items:
- uid: System.Configuration.DictionarySectionHandler
  id: DictionarySectionHandler
  children:
  - System.Configuration.DictionarySectionHandler.#ctor
  - System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  - System.Configuration.DictionarySectionHandler.KeyAttributeName
  - System.Configuration.DictionarySectionHandler.ValueAttributeName
  langs:
  - csharp
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler
  type: Class
  summary: "Fornisce informazioni di configurazione di una sezione di configurazione di coppia chiave/valore."
  remarks: "Questa classe implementa il `IConfigSectionHandler` interfaccia. Il DictionarySectionHandler definisce le regole per la modifica delle sezioni di configurazione XML."
  syntax:
    content: 'public class DictionarySectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.DictionarySectionHandler&quot;> </xref> classe."
  syntax:
    content: public DictionarySectionHandler ();
    parameters: []
  overload: System.Configuration.DictionarySectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Crea un nuovo gestore di configurazione e lo aggiunge alla raccolta del gestore di sezione in base ai parametri specificati."
  remarks: "Il `parent` oggetto parametro funziona come le impostazioni di configurazione nella sezione di configurazione padre corrispondente. Il `context` parametro dell&quot;oggetto corrisponde al percorso virtuale per cui il gestore della sezione di configurazione calcola i valori di configurazione. In genere questo parametro è riservato e `null`.  Il `section` parametro è il <xref:System.Xml.XmlNode>che contiene le informazioni di configurazione da gestire.</xref:System.Xml.XmlNode> Il `section` parametro fornisce accesso diretto al contenuto XML della sezione di configurazione."
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Oggetto padre."
    - id: context
      type: System.Object
      description: "Oggetto di contesto di configurazione."
    - id: section
      type: System.Xml.XmlNode
      description: "Nodo XML della sezione."
    return:
      type: System.Object
      description: "Oggetto di configurazione."
  overload: System.Configuration.DictionarySectionHandler.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  id: KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il nome di attributo XML da utilizzare come chiave nella coppia chiave/valore."
  syntax:
    content: protected virtual string KeyAttributeName { get; }
    return:
      type: System.String
      description: "Valore stringa che contiene il nome dell&quot;attributo chiave."
  overload: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  id: ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ottiene il nome di attributo XML da utilizzare come valore nella coppia chiave/valore."
  syntax:
    content: protected virtual string ValueAttributeName { get; }
    return:
      type: System.String
      description: "Valore stringa che contiene il nome dell&quot;attributo value."
  overload: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.DictionarySectionHandler.#ctor
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
- uid: System.Configuration.DictionarySectionHandler.#ctor*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler.DictionarySectionHandler
- uid: System.Configuration.DictionarySectionHandler.Create*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create
  nameWithType: DictionarySectionHandler.Create
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
