### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ClientTarget
  id: ClientTarget
  children:
  - System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  - System.Web.Configuration.ClientTarget.Alias
  - System.Web.Configuration.ClientTarget.Properties
  - System.Web.Configuration.ClientTarget.UserAgent
  langs:
  - csharp
  name: ClientTarget
  nameWithType: ClientTarget
  fullName: System.Web.Configuration.ClientTarget
  type: Class
  summary: "Definisce l&quot;alias associato all&quot;agente utente di destinazione per cui i controlli server ASP.NET devono eseguire il rendering di contenuto. Questa classe non può essere ereditata."
  remarks: "La classe ClientTarget fa riferimento a elementi che vengono aggiunti i `clientTarget` sezione del file di configurazione.       La classe ClientTarget appartiene a un gruppo che include la <xref:System.Web.Configuration.ClientTargetCollection>classe e la <xref:System.Web.Configuration.ClientTargetSection>classe.</xref:System.Web.Configuration.ClientTargetSection> </xref:System.Web.Configuration.ClientTargetCollection>       La classe ClientTarget contiene due proprietà che identificano un browser client, denominato anche agente utente. Una proprietà è l&quot;alias associato al browser client identificato dalla seconda proprietà. ASP.NET utilizza queste informazioni per il rendering dei controlli server in una pagina.       Per informazioni sulle modalità di utilizzo dell&quot;agente utente o il relativo alias a livello di codice, vedere il <xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>proprietà.</xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName> Per informazioni sulle modalità di utilizzo dell&quot;agente utente o il relativo alias in modo dichiarativo, vedere [@ Page](http://msdn.microsoft.com/en-us/f06cf9e5-22bb-461d-8b8f-549e53ff40a4).       Se il <xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>non è impostata, il <xref:System.Web.HttpBrowserCapabilities>oggetto a cui è associato il <xref:System.Web.UI.Page.Request%2A?displayProperty=fullName>proprietà rifletterà le funzionalità del browser del client.</xref:System.Web.UI.Page.Request%2A?displayProperty=fullName> </xref:System.Web.HttpBrowserCapabilities> </xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName> (Riflette le funzionalità del tipo di browser, ma non necessariamente le impostazioni in un&quot;istanza specifica di tale browser). Se la proprietà è impostata, il rilevamento del browser client è disabilitato e la pagina utilizza le funzionalità del browser associati con la stringa agente utente definiti. È possibile impostare questa proprietà su una stringa agente utente valido."
  example:
  - "This section provides two code examples. The first demonstrates how to declaratively specify values for several properties of the ClientTarget class. The second shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file. You use this object to access the ClientTarget objects it contains.  \n  \n The following code example shows how to declaratively specify values for several properties of the ClientTarget class.  \n  \n```  \n<clientTarget>  \n  <add alias=  \n    \"uplevel\"   \n    userAgent=\"Mozilla/5.0 (compatible;MSIE 6.0;Windows NT 5.1)\"/>  \n  <add alias=\"downlevel\" userAgent=\"Generic Downlevel\"/>  \n</clientTarget>  \n```  \n  \n The following code example shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/visualbasic/t-system.web.configurati_29_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/csharp/t-system.web.configurati_29_1.cs)]"
  syntax:
    content: 'public sealed class ClientTarget : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.ClientTarget&quot;> </xref> classe."
  syntax:
    content: public ClientTarget (string alias, string userAgent);
    parameters:
    - id: alias
      type: System.String
      description: "Il nome utilizzato per fare riferimento a un agente utente specifico."
    - id: userAgent
      type: System.String
      description: "Nome di identificazione dell&quot;agente utente."
  overload: System.Web.Configuration.ClientTarget.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Alias
  id: Alias
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene l&quot;alias dell&quot;agente utente."
  remarks: "La proprietà Alias fa riferimento al `alias` attributo del `add` elemento il `clientTarget` sezione del file di configurazione.       Le impostazioni di configurazione ASP.NET predefinite includono gli alias seguenti:- `uplevel`, che indica ad ASP.NET di inviare HTML ed ECMAScript supportato da Internet Explorer 6.0 e versioni successive.      - `downlevel`, che indica ad ASP.NET per limitare il codice HTML e script per le versioni sono supportati nei browser precedenti a Internet Explorer 6.0."
  example:
  - "The following code example shows how to get the Alias from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/visualbasic/p-system.web.configurati_91_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/csharp/p-system.web.configurati_91_1.cs)]"
  syntax:
    content: public string Alias { get; }
    return:
      type: System.String
      description: "Il nome utilizzato per fare riferimento a un agente utente specifico."
  overload: System.Web.Configuration.ClientTarget.Alias*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Properties
  id: Properties
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Da aggiungere."
  overload: System.Web.Configuration.ClientTarget.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.UserAgent
  id: UserAgent
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il nome di identificazione dell&quot;agente utente."
  remarks: "La proprietà UserAgent fa riferimento al `userAgent` attributo del `add` elemento il `clientTarget` sezione del file di configurazione.       Le impostazioni di configurazione ASP.NET predefinite consentono la personalizzazione delle pagine per le diverse versioni di Microsoft Internet Explorer. Fra questi si trova l&quot;alias `uplevel`, che indica ad ASP.NET di inviare HTML ed ECMAScript supportato da Internet Explorer 4.0 e versioni successive, il client e `downlevel`, che indica ad ASP.NET per limitare il codice HTML e script a quelli supportati dai browser precedenti a Internet Explorer 4.0."
  example:
  - "The following code example shows how to get the UserAgent from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/visualbasic/p-system.web.configurati_190_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/csharp/p-system.web.configurati_190_1.cs)]"
  syntax:
    content: public string UserAgent { get; }
    return:
      type: System.String
      description: "Nome di identificazione dell&quot;agente utente."
  overload: System.Web.Configuration.ClientTarget.UserAgent*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ClientTarget.Alias
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ClientTarget.UserAgent
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
- uid: System.Web.Configuration.ClientTarget.#ctor*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget
  nameWithType: ClientTarget.ClientTarget
- uid: System.Web.Configuration.ClientTarget.Alias*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
- uid: System.Web.Configuration.ClientTarget.UserAgent*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
