### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworkMissingException
  id: CompatibleFrameworkMissingException
  children:
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  - System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException
  type: Class
  summary: "Questa eccezione viene generata quando non viene trovata una versione di .NET Framework compatibile con questa applicazione."
  syntax:
    content: 'public class CompatibleFrameworkMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> classe con un messaggio fornito dal sistema che descrive l&quot;errore."
  remarks: "Questo costruttore inizializza la <xref:System.Exception.Message%2A>proprietà della nuova istanza di un messaggio fornito dal sistema che descrive l&quot;errore, ad esempio &quot;Non è stato trovato alcun framework compatibile&quot;.</xref:System.Exception.Message%2A> Questo messaggio prende in considerazione le impostazioni cultura correnti.       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore localizzato. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException ();
    parameters: []
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> classe con un messaggio specificato che descrive l&quot;errore."
  remarks: "Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Stringa del messaggio di errore specificata `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio che descrive l&quot;eccezione. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso."
  syntax:
    content: protected CompatibleFrameworkMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Oggetto che contiene i dati oggetto serializzati."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Informazioni contestuali sull&quot;origine o destinazione."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> classe con un messaggio di errore specificato e un riferimento all&quot;eccezione interna che è la causa dell&quot;eccezione corrente."
  remarks: "Un&quot;eccezione generata come risultato diretto di un&quot;eccezione precedente deve includere un riferimento all&quot;eccezione precedente nella <xref:System.Exception.InnerException%2A>proprietà.</xref:System.Exception.InnerException%2A> Il <xref:System.Exception.InnerException%2A>proprietà restituisce lo stesso valore passato al costruttore o `null` se il <xref:System.Exception.InnerException%2A>proprietà non fornisce il valore di eccezione interna al costruttore.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Stringa del messaggio di errore specificata `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio che descrive l&quot;eccezione. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente."
    - id: innerException
      type: System.Exception
      description: "Eccezione che è la causa dell&quot;eccezione corrente. Se il `innerException` parametro non è <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, l&quot;eccezione corrente viene generata in un <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blocco che gestisce l&quot;eccezione interna."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  id: CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Ottiene un elenco delle versioni di .NET Framework in cui è possibile installare ed eseguire questa applicazione."
  syntax:
    content: public System.Deployment.Application.CompatibleFrameworks CompatibleFrameworks { get; }
    return:
      type: System.Deployment.Application.CompatibleFrameworks
      description: "Un elenco delle versioni di .NET Framework in cui è possibile installare ed eseguire questa applicazione."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Oggetto che contiene i dati oggetto serializzati."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Informazioni contestuali sull&quot;origine o destinazione."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworks
  parent: System.Deployment.Application
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: CompatibleFrameworkMissingException.GetObjectData
